package org.exoplatform.selenium.platform.social.sniff;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.ManageAccount.userType;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.UserGroupManagement;
import org.exoplatform.selenium.platform.social.Notification;
import org.exoplatform.selenium.platform.social.PeopleConnection;
import org.openqa.selenium.By;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
/**
 * 
 * @author thuntn
 * @date 04/06/2014
 *
 */
public class Social_EmailNotifications_Settings extends Notification {
	//Platform
	ManageAccount magAcc;
	NavigationToolbar navToolBar;
	UserGroupManagement userGroup;
	PeopleConnection peo;

	String user = "John Smith";
	String user1="Mary Williams";
	String user2="Jack Miller";
	String user3="James Davis";

	@BeforeMethod
	public void beforeMethods() {
		initSeleniumTest();
		driver.get(baseUrl);
		magAcc = new ManageAccount(driver,this.plfVersion);
		navToolBar = new NavigationToolbar(driver,this.plfVersion);
		magAcc.signIn(DATA_USER1, DATA_PASS);
		userGroup = new UserGroupManagement(driver);
		peo = new PeopleConnection(driver);
	}

	@AfterMethod
	public void afterMethods() {
		info("Logout portal");
		driver.manage().deleteAllCookies();
		driver.quit();
	}

	/**
	 * Case ID:109847.
	 * Test Case Name: Notification Settings.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by thuntn at 2014/06/04 17:17:09
	 */
	@Test(priority = 1)
	public void test01_NotificationSetings(){
		
		info("Test 1: Notification Settings");
		/*
		- Login
		- Click full name of user and select [Notifications] on the menu
		 *Expected Outcome: Notification setting page is shown with 2 main parts1. Never notify me, by default is unchecked2. A table contains all notification settings for the user.The columns are :
		- Notify me when: contains title of the notifications and categories
		- Send me an email right away : contains a checkbox to indicate that the user wants to receive the email notification Instantly 
		- Include in a digest email : contains a combo boxwith one of the following values :+ Never : to not include this notification in any digest 
		+ Daily : to include notifications of this type in the daily digestemail 
		+ Weekly : to include the notifications of this type in the weekly digest email		*/
		navToolBar.goToNotificationSettings();
		waitForAndGetElement(ELEMENT_NEVER_NOTIFY_ME,DEFAULT_TIMEOUT,1,2);
		waitForAndGetElement(ELEMENT_NOTIFY_COLUMN.replace("${column}", MSG_SETTINGS_COLUMN_INCLUDE_DIGEST));
		waitForAndGetElement(ELEMENT_NOTIFY_COLUMN.replace("${column}", MSG_SETTINGS_COLUMN_NOFITY_WHEN));
		waitForAndGetElement(ELEMENT_NOTIFY_COLUMN.replace("${column}", MSG_SETTINGS_COLUMN_SEND_RIGHT));
		waitForAndGetElement(ELEMENT_NOTIFY_RIGHT_INPUT.replace("${activity}", MSG_ACTIVITY_COMMENT),DEFAULT_TIMEOUT,1,2);
		waitForAndGetElement(ELEMENT_NOTIFY_RIGHT_INPUT.replace("${activity}", MSG_ACTIVITY_JOIN_INTRANET),DEFAULT_TIMEOUT,1,2);
		waitForAndGetElement(ELEMENT_NOTIFY_RIGHT_INPUT.replace("${activity}", MSG_ACTIVITY_JOIN_SPACE),DEFAULT_TIMEOUT,1,2);
		waitForAndGetElement(ELEMENT_NOTIFY_RIGHT_INPUT.replace("${activity}", MSG_ACTIVITY_MENTION),DEFAULT_TIMEOUT,1,2);
		waitForAndGetElement(ELEMENT_NOTIFY_RIGHT_INPUT.replace("${activity}", MSG_ACTIVITY_LIKE_MY_ACTIVITY),DEFAULT_TIMEOUT,1,2);
		waitForAndGetElement(ELEMENT_NOTIFY_RIGHT_INPUT.replace("${activity}", MSG_ACTIVITY_POST_MY_SPACE),DEFAULT_TIMEOUT,1,2);
		waitForAndGetElement(ELEMENT_NOTIFY_RIGHT_INPUT.replace("${activity}", MSG_ACTIVITY_POST_MY_STREAM),DEFAULT_TIMEOUT,1,2);
		waitForAndGetElement(ELEMENT_NOTIFY_RIGHT_INPUT.replace("${activity}", MSG_ACTIVITY_RECEIVE_SPACE_INVITATION),DEFAULT_TIMEOUT,1,2);
		waitForAndGetElement(ELEMENT_NOTIFY_RIGHT_INPUT.replace("${activity}", MSG_ACTIVITY_SEND_CONNECTION_REQUEST),DEFAULT_TIMEOUT,1,2);
		waitForAndGetElement(ELEMENT_NOTIFY_DIGEST_EMAIL.replace("${activity}",MSG_ACTIVITY_COMMENT));
		waitForAndGetElement(ELEMENT_NOTIFY_DIGEST_EMAIL.replace("${activity}",MSG_ACTIVITY_JOIN_INTRANET));
		waitForAndGetElement(ELEMENT_NOTIFY_DIGEST_EMAIL.replace("${activity}",MSG_ACTIVITY_JOIN_SPACE));
		waitForAndGetElement(ELEMENT_NOTIFY_DIGEST_EMAIL.replace("${activity}",MSG_ACTIVITY_MENTION));
		waitForAndGetElement(ELEMENT_NOTIFY_DIGEST_EMAIL.replace("${activity}",MSG_ACTIVITY_LIKE_MY_ACTIVITY));
		waitForAndGetElement(ELEMENT_NOTIFY_DIGEST_EMAIL.replace("${activity}",MSG_ACTIVITY_POST_MY_SPACE));
		waitForAndGetElement(ELEMENT_NOTIFY_DIGEST_EMAIL.replace("${activity}",MSG_ACTIVITY_POST_MY_STREAM));
		waitForAndGetElement(ELEMENT_NOTIFY_DIGEST_EMAIL.replace("${activity}",MSG_ACTIVITY_RECEIVE_SPACE_INVITATION));
		waitForAndGetElement(ELEMENT_NOTIFY_DIGEST_EMAIL.replace("${activity}",MSG_ACTIVITY_SEND_CONNECTION_REQUEST));
	}

	/**
	 * Case ID:109844.
	 * Test Case Name: Update a notification option.
	 * Pre-Condition: PLF server has mail configured
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by thuntn at 2014/06/04 17:17:09
	 */
	@Test
	public  void test02_UpdateANotificationOption() {
		info("Test 2: Update a notification option");

		String username = getRandomString();
		String password = "gtngtn";
		String fullName = username + " "+username;
		String email = username + "@gmail.com";
		By eEmail = By.xpath(ELEMENT_GMAIL_TITLE.replace("${title}", fullName+" has joined eXo"));
		String username2 = getRandomString();
		String fullName2 = username2 + " "+ username2;
		String email2 = username2 + "@gmail.com";
		By eEmail2 = By.xpath(ELEMENT_GMAIL_TITLE.replace("${title}", fullName2+" has joined eXo"));
		/*
		- Click username on the right of top navigation
		- Click Notification
		- In column [Send me an email right away], select 1 option then tick it, eg "Someone joins the social intranet"
		- As admin, Create new user successfully
		 *Expected Outcome: An notification email is sent.		*/
		navToolBar.goToMyProfile();
		magAcc.updateUserProfile(null, null, null, EMAIL_ADDRESS1);

		navToolBar.goToNotificationSettings();
		enableSendNotificationRight(MSG_ACTIVITY_JOIN_INTRANET, true);

		navToolBar.goToNewStaff();
		magAcc.addNewUserAccount(username, password, password, username, username, null, email, "", null,true);

		goToMail(EMAIL_ADDRESS1, EMAIL_PASS);
		String handle1 = driver.getWindowHandle();
		checkAndDeleteMail(eEmail, MSG_CONTENT_EMAIL_NEW_USER.replace("${user}", fullName));
		switchToParentWindow();

		/*- Go to Notification Setting screen again
		- Untick option in step 1
		- As admin create another new user
		 *Input Data: 
		 *Expected Outcome: No notification email is sent.	*/	 
		navToolBar.goToNotificationSettings();
		enableSendNotificationRight(MSG_ACTIVITY_JOIN_INTRANET, false);

		navToolBar.goToNewStaff();
		magAcc.addNewUserAccount(username2, password, password, username2, username2, null, email2, "", null,true);

		driver.switchTo().window(handle1);
		assert waitForAndGetElement(eEmail2,60000,0) == null : "Still receive email";
		switchToParentWindow();

		//Restore data
		navToolBar.goToUsersAndGroupsManagement();
		userGroup.deleteUser(username2);
		userGroup.deleteUser(username);
	}

	/**
	 * Case ID:109846.
	 * Test Case Name: Check the box "Never Notify me".
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by thuntn at 2014/06/04 17:17:09
	 */
	@Test
	public  void test03_CheckTheBoxNeverNotifyMe() {
		info("Test 3: Check the box Never Notify me");
		By eEmail = By.xpath(ELEMENT_GMAIL_TITLE.replace("${title}", "Mary Williams wants to connect with you on eXo')]"));
		navToolBar.goToMyProfile();
		magAcc.updateUserProfile(null, null, null, EMAIL_ADDRESS1);
		navToolBar.goToNotificationSettings();
		check(ELEMENT_NEVER_NOTIFY_ME,2);
		waitForElementNotPresent(ELEMENT_NOTIFY_COLUMN.replace("${column}", MSG_SETTINGS_COLUMN_NOFITY_WHEN));

		magAcc.userSignIn(userType.PUBLISHER);
		/*
		- Login
		- Click full name of user and select [Notifications] on the menu
		 *Expected Outcome: 
		- Notification Settings page is appeared		*/

		navToolBar.goToNotificationSettings();

		/*
		- Check the check box[Never notify me]
		 *Input Data: 
		 *Expected Outcome: 
		- The notification settings table is hidden. The user will not receive any email notification.		*/ 

		navToolBar.goToConnectionPage();
		peo.connectPeople(user);

		goToMail(EMAIL_ADDRESS1, EMAIL_PASS);
		assert waitForAndGetElement(eEmail,60000,0) == null : "Still receive email";
		
		//Restore data
		switchToParentWindow();
		peo.cancelRequest(user);

		navToolBar.goToNotificationSettings();
		uncheck(ELEMENT_NEVER_NOTIFY_ME,2);
	}
}
