package org.exoplatform.selenium.platform.plf.functional.genericuserpopup;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.Utils;
import org.exoplatform.selenium.platform.HomePageActivity;
import org.exoplatform.selenium.platform.HomePageGadget;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.ManageAccount.userType;
import org.exoplatform.selenium.platform.ecms.EcmsBase;
import org.exoplatform.selenium.platform.ecms.contentexplorer.ActionBar;
import org.exoplatform.selenium.platform.ecms.contentexplorer.ContextMenu.actionType;
import org.exoplatform.selenium.platform.social.Activity;
import org.exoplatform.selenium.platform.social.PeopleConnection;
import org.openqa.selenium.By;
import org.testng.annotations.*;

/**
 * @author chinhdtt
 * @date 17 Jun 2014
 */
public class PLF_GenericUserPopup_ConnectionApplication extends Activity{
	NavigationToolbar nav; 
	ManageAccount acc; 
	PeopleConnection pConnect;
	HomePageGadget hg;
	HomePageActivity home; 
	ActionBar act; 
	EcmsBase ecms; 
	String user1 = "John Smith";
	String user2 = "Mary Williams";
	String user3 = "Jack Miller"; 
	String user4 = "James Davis";

	@BeforeMethod
	public void setUpBeforeTest(){
		getDriverAutoSave();
		acc = new ManageAccount(driver, this.plfVersion);
		hg = new HomePageGadget(driver, this.plfVersion);
		pConnect = new PeopleConnection(driver, this.plfVersion);
		nav = new NavigationToolbar(driver, this.plfVersion);
		home = new HomePageActivity(driver, this.plfVersion);
		acc.signIn(DATA_USER1, DATA_PASS);
		act = new ActionBar(driver, this.plfVersion);
		ecms = new EcmsBase(driver, this.plfVersion);
	}

	@AfterMethod
	public void afterTest(){
		driver.manage().deleteAllCookies();
		driver.quit();
	}

	/**
	 * Case ID:108030.
	 * Test Case Name: Generic popup should be displayed on hover of the Connections on "Everyone" Tab.
	 * Pre-Condition: users are member of Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test01_GenericPopupShouldBeDisplayedOnHoverOfTheConnectionsOnEveryoneTab() {
		info("Test 1: Generic popup should be displayed on hover of the Connections on Everyone Tab");
		/*
		- Connect to Intranet
		- Open Connections application, choose "Everyone" tab
		 *Expected Outcome: 
		- The list of users, member ins the Intranet, is displayed		*/
		nav.goToConnectionPage();
		waitForAndGetElement(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user2));
		waitForAndGetElement(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user3));
		waitForAndGetElement(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user4));

		/*
		- Hover on the username link
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed		*/ 
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user2), true);
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER2), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2), DEFAULT_TIMEOUT,1,2);

	}

	/**
	 * Case ID:108031.
	 * Test Case Name: Generic popup should be displayed on hover of the Connections on "My Connections" Tab.
	 * Pre-Condition: User A is connected to User B
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test02_GenericPopupShouldBeDisplayedOnHoverOfTheConnectionsOnMyConnectionsTab() {
		info("Test 2: Generic popup should be displayed on hover of the Connections on My Connections Tab");
		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);		

		/*
		- Connect to Intranet
		- Open Connections application, choose "My Connectionstab
		 *Expected Outcome: 
		- The list of users, connected with the user is displayed		*/
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user1), true);	

		/*
		- Hover on the username link
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed		*/ 
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1), DEFAULT_TIMEOUT,1,2);

		//Delete data test 
		waitForAndGetElement(pConnect.ELEMENT_REMOVE_CONNECTION_BUTTON.replace("${peopleName}", user1));
		click(pConnect.ELEMENT_REMOVE_CONNECTION_BUTTON.replace("${peopleName}", user1));
		Utils.pause(3000);
		waitForElementNotPresent(pConnect.ELEMENT_REMOVE_CONNECTION_BUTTON.replace("${peopleName}", user1));
		Utils.pause(1000);
	}

	/**
	 * Case ID:108032.
	 * Test Case Name: Generic popup should be displayed on hover of the Connections on "Requests Received" Tab.
	 * Pre-Condition: User A receive a request to connect from User B
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test03_GenericPopupShouldBeDisplayedOnHoverOfTheConnectionsOnRequestsReceivedTab() {
		info("Test 3: Generic popup should be displayed on hover of the Connections on Requests Received Tab");
		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);		

		/*
		- Connect to Intranet with User A
		- Open Connections application, choose "Requests Received" tab
		 *Expected Outcome: 
		- The list of users is displayed, waiting to accept their requesting connection		*/
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		click(pConnect.ELEMENT_REQUESTS_RECEIVED_TAB);
		waitForAndGetElement(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user1));

		/*
		- Hover on the username link
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed		*/ 
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user1), true);
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1), DEFAULT_TIMEOUT,1,2);

		//Delete data test 
		waitForAndGetElement(pConnect.ELEMENT_IGNORE_BUTTON.replace("${peopleName}", user1));
		info("---Ignore the invitation from user '"+user1+"'-----");
		click(pConnect.ELEMENT_IGNORE_BUTTON.replace("${peopleName}", user1));
		waitForElementNotPresent(pConnect.ELEMENT_IGNORE_BUTTON.replace("${peopleName}", user1));
		info("---Go to Everyone tab----");
		click(pConnect.ELEMENT_EVERYONE_TAB);
		waitForAndGetElement(pConnect.ELEMENT_CONNECTION_BUTTON.replace("${peopleName}", user1));			
	}

	/**
	 * Case ID:108033.
	 * Test Case Name: Generic popup should be displayed on hover of the Connections on "Requests Pending" Tab.
	 * Pre-Condition: User A invite User B to connect
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test04_GenericPopupShouldBeDisplayedOnHoverOfTheConnectionsOnRequestsPendingTab() {
		info("Test 4: Generic popup should be displayed on hover of the Connections on Requests Pending Tab");
		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);		

		/*
		- Connect to Intranet with User A
		- Open Connections application, choose "Requests Pending" tab
		 *Expected Outcome: 
		- The list of users is displayed		*/
		click(pConnect.ELEMENT_REQUEST_PENDING_TAB);
		waitForAndGetElement(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user2));

		/*
		- Hover on the username link
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed		*/ 
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user2), true);
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER2), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2), DEFAULT_TIMEOUT,1,2);

		//Delete data test
		waitForAndGetElement(pConnect.ELEMENT_CANCEL_REQUEST_BUTTON.replace("${peopleName}", user2));
		info("---Cancel the invitation to user '"+user2+"'-----");
		click(pConnect.ELEMENT_CANCEL_REQUEST_BUTTON.replace("${peopleName}", user2));
		waitForElementNotPresent(pConnect.ELEMENT_CANCEL_REQUEST_BUTTON.replace("${peopleName}", user2));
		info("---Go to Everyone tab----");
		click(pConnect.ELEMENT_EVERYONE_TAB);
		waitForAndGetElement(pConnect.ELEMENT_CONNECTION_BUTTON.replace("${peopleName}", user2));
	}

	/**
	 * Case ID:108038.
	 * Test Case Name: User's informations should be displayed on generic pop up of connection "Everyone" tab.
	 * Pre-Condition: other users are member in Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test05_UsersInformationsShouldBeDisplayedOnGenericPopUpOfConnectionEveryoneTab() {
		info("Test 5: User's informations should be displayed on generic pop up of connection Everyone tab");
		String post = "Case 108038";

		info("User Mary update profile");
		acc.userSignIn(userType.PUBLISHER);
		acc.updateUserProfile(post,null, null, null);

		/*
		- Connect to Intranet with the User A
		- From Connections application, choose "Everyone" tab
		- Move the mouse over the username link
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/ 
		acc.userSignIn(userType.ADMIN);
		nav.goToConnectionPage();
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user2), true);
		info("Position of user displays true");
		assert getText(hg.ELEMENT_USER_POPUP_POSITION).equalsIgnoreCase(post);		
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER2), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2), DEFAULT_TIMEOUT,1,2);	

		//Delete date test 
		acc.userSignIn(userType.PUBLISHER);
		acc.updateUserProfile("mary",null, null, null);
	}

	/**
	 * Case ID:108039.
	 * Test Case Name: User's informations should be displayed on generic pop up of connection "My connections" tab.
	 * Pre-Condition: User A is connected with the user B
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test06_UsersInformationsShouldBeDisplayedOnGenericPopUpOfConnectionMyConnectionsTab() {
		info("Test 6: User's informations should be displayed on generic pop up of connection My connections tab");
		String post = "Case 108039";

		//Pre-Condition
		info("User update profile");
		acc.updateUserProfile(post,null, null, null);
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);	

		/*
		- Connect to Intranet with the User A
		- From Connections application, choose "My connections" tab
		- Move the mouse over the username link
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/ 
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user1), true);
		info("Position of user displays true");
		assert getText(hg.ELEMENT_USER_POPUP_POSITION).equalsIgnoreCase(post);	
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1), DEFAULT_TIMEOUT,1,2);

		//Delete data test 
		waitForAndGetElement(pConnect.ELEMENT_REMOVE_CONNECTION_BUTTON.replace("${peopleName}", user1));
		click(pConnect.ELEMENT_REMOVE_CONNECTION_BUTTON.replace("${peopleName}", user1));
		Utils.pause(3000);
		waitForElementNotPresent(pConnect.ELEMENT_REMOVE_CONNECTION_BUTTON.replace("${peopleName}", user1));
		Utils.pause(1000);

		//Delete date test 
		acc.userSignIn(userType.ADMIN);
		acc.updateUserProfile("john",null, null, null);
	}

	/**
	 * Case ID:108040.
	 * Test Case Name: User's informations should be displayed on generic pop up of connection "Requests Pending" tab.
	 * Pre-Condition: User A invite User B to connect
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test07_UsersInformationsShouldBeDisplayedOnGenericPopUpOfConnectionRequestsPendingTab() {
		info("Test 7: User's informations should be displayed on generic pop up of connection Requests Pending tab");
		String post = "Case 108040";

		//Pre-Condition
		info("User Mary update profile");
		acc.userSignIn(userType.PUBLISHER);
		acc.updateUserProfile(post,null, null, null);

		info("UserA connect userB");
		acc.userSignIn(userType.ADMIN);
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);		

		/*
		- Connect to Intranet with the User A
		- From Connections application, choose "Requests Pending" tab
		- Move the mouse over the username link
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/ 
		click(pConnect.ELEMENT_REQUEST_PENDING_TAB);
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user2), true);
		info("Position of user displays true");
		assert getText(hg.ELEMENT_USER_POPUP_POSITION).equalsIgnoreCase(post);
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER2), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2), DEFAULT_TIMEOUT,1,2);

		//Delete data test
		waitForAndGetElement(pConnect.ELEMENT_CANCEL_REQUEST_BUTTON.replace("${peopleName}", user2));
		info("---Cancel the invitation to user '"+user2+"'-----");
		click(pConnect.ELEMENT_CANCEL_REQUEST_BUTTON.replace("${peopleName}", user2));
		waitForElementNotPresent(pConnect.ELEMENT_CANCEL_REQUEST_BUTTON.replace("${peopleName}", user2));
		info("---Go to Everyone tab----");
		click(pConnect.ELEMENT_EVERYONE_TAB);
		waitForAndGetElement(pConnect.ELEMENT_CONNECTION_BUTTON.replace("${peopleName}", user2));

		acc.userSignIn(userType.PUBLISHER);
		acc.updateUserProfile("mary",null, null, null);		
	}

	/**
	 * Case ID:108041.
	 * Test Case Name: User's informations should be displayed on generic pop up of connection "Requests Received" tab.
	 * Pre-Condition: User A receive an invitation from the User B
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test08_UsersInformationsShouldBeDisplayedOnGenericPopUpOfConnectionRequestsReceivedTab() {
		info("Test 8: User's informations should be displayed on generic pop up of connection Requests Received tab");
		String post = "Case 108041";

		//Pre-Condition
		info("User update profile");
		acc.updateUserProfile(post,null, null, null);
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);		
		/*
		- Connect to Intranet with the User A
		- From Connections application, choose "Requests Received" tab
		- Move the mouse over the username link
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/ 
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		click(pConnect.ELEMENT_REQUESTS_RECEIVED_TAB);
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user1), true);
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1), DEFAULT_TIMEOUT,1,2);

		//Delete data test 
		waitForAndGetElement(pConnect.ELEMENT_IGNORE_BUTTON.replace("${peopleName}", user1));
		info("---Ignore the invitation from user '"+user1+"'-----");
		click(pConnect.ELEMENT_IGNORE_BUTTON.replace("${peopleName}", user1));
		waitForElementNotPresent(pConnect.ELEMENT_IGNORE_BUTTON.replace("${peopleName}", user1));
		info("---Go to Everyone tab----");
		click(pConnect.ELEMENT_EVERYONE_TAB);
		waitForAndGetElement(pConnect.ELEMENT_CONNECTION_BUTTON.replace("${peopleName}", user1));	

		acc.userSignIn(userType.ADMIN);
		acc.updateUserProfile("john",null, null, null);
	}

	/**
	 * Case ID:108046.
	 * Test Case Name: Generic popup should be displayed as status type in connections app.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test09_GenericPopupShouldBeDisplayedAsStatusTypeInConnectionsApp() {
		info("Test 9: Generic popup should be displayed as status type in connections app");
		String activity = "Activity 108046";

		/*
		- Connect to Intranet
		- Share an activity
		 *Expected Outcome: 
		- Activity with status is shared		*/
		info("Share activity");
		addActivity(true, activity, false, "");		

		/*
		- Go to Connections application
		- Hover on the current user's avatar
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: Status		*/ 
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		Utils.pause(1000);
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user1), true);
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user activity");
		assert getText(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY).equalsIgnoreCase(activity);

		//Delete data test 
		acc.userSignIn(userType.ADMIN);
		home.deleteActivity(activity, true);
	}

	/**
	 * Case ID:108056.
	 * Test Case Name: Generic popup should be displayed as File Sharing type in connections app.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 * Bug: https://jira.exoplatform.org/browse/COMMONS-278
	 */
	@Test (groups = "errors")
	public  void test10_GenericPopupShouldBeDisplayedAsFileSharingTypeInConnectionsApp() {
		info("Test 10 Generic popup should be displayed as File Sharing type in connections app");
		String uploadFileName = "French.docx";
		String folder = "folder108056";
		String driverName = "Personal Drives";
		String folderPath = "Personal Documents";

		/*
		- Connect to Intranet
		- Share a file
		 *Expected Outcome: 
		- Activity with File is shared		*/
		selectFile(driverName,true,folderPath,"",uploadFileName,folder);

		/*
		- Go to Connections application
		- Hover on the current user's avatar
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: File		*/ 
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		Utils.pause(1000);
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user1), true);
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user activity");
		assert getText(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY).equalsIgnoreCase(uploadFileName);

		//Delete data test 
		acc.userSignIn(userType.ADMIN);
		home.deleteActivity(uploadFileName, true);
		nav.goToSiteExplorer();
		act.chooseDrive(ecms.ELEMENT_PERSONAL_DRIVE);
		act.actionsOnElement(folder, actionType.DELETE,true,true);
	}

	/**
	 * Case ID:108057.
	 * Test Case Name: Generic popup should be displayed as Link Sharing type in connections app.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test11_GenericPopupShouldBeDisplayedAsLinkSharingTypeInConnectionsApp() {
		info("Test 11 Generic popup should be displayed as Link Sharing type in connections app");
		String text = "";
		String link = "http://yahoo.com";

		/*
		- Connect to Intranet
		- Share a Link
		 *Expected Outcome: 
		- Activity with Link is shared		*/
		info("Share link");
		addActivity(false, text, true, link);

		/*
		- Go to Connections application
		- Hover on the current user's avatar
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: Link		*/ 
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();		
		Utils.pause(1000);
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user1), true);
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user activity");
		assert getText(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY).equalsIgnoreCase("Yahoo");

		//Delete data test 
		acc.userSignIn(userType.ADMIN);
		home.deleteActivity(link, true);
	}

	/**
	 * Case ID:108064.
	 * Test Case Name: Generic pop up should be display with "Connect" button in the Connection app.
	 * Pre-Condition: User A and User B are not a connectionUser B is connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test12_GenericPopUpShouldBeDisplayWithConnectButtonInTheConnectionApp() {
		info("Test 12 Generic pop up should be display with Connect button in the Connection app");
		String activity = "Activity 108064";
		String post = "Case 108064";

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/
		addActivity(true, activity, false, "");
		Utils.pause(1000);
		info("User update profile");
		acc.updateUserProfile(post,null, null, null);

		/*
		- Connect to Intranet with the User B
		- Go to the connection application
		- Move the mouse over the avatar of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Connect" is displayed		*/
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		Utils.pause(1000);
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user1), true);
		info("Position of user displays true");
		assert getText(hg.ELEMENT_USER_POPUP_POSITION).equalsIgnoreCase(post);				
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user activity");
		assert getText(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY).equalsIgnoreCase(activity);
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Connect"));

		/*
		- Click on the button "Connect"
		 *Input Data: 
		 *Expected Outcome: 
		- The State of the button changes to show a connection request was sent.		*/ 
		click(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Connect"));
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user1), true);
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Cancel Request"));

		//Delete data test 
		click(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Cancel Request"));
		acc.userSignIn(userType.ADMIN);
		home.deleteActivity(activity, true);
		acc.updateUserProfile("john",null, null, null);
	}

	/**
	 * Case ID:108070.
	 * Test Case Name: Generic pop up should be display with "Confirm" button in the Connection app.
	 * Pre-Condition: User B has received an invitation from the User AUser B is connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test13_GenericPopUpShouldBeDisplayWithConfirmButtonInTheConnectionApp() {
		info("Test 13 Generic pop up should be display with Confirm button in the Connection app");
		String activity = "Activity 108070";
		String post = "Case 108070";

		//Pre-Condition
		info("User update profile");
		acc.updateUserProfile(post,null, null, null);
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);	

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/
		nav.goToHomePage();
		addActivity(true, activity, false, "");

		/*
		- Connect to Intranet with the User B
		- Go to the connection application
		- Move the mouse over the avatar of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Confirm" is displayed		*/ 
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		Utils.pause(1000);
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user1), true);
		info("Position of user displays true");
		assert getText(hg.ELEMENT_USER_POPUP_POSITION).equalsIgnoreCase(post);	
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user activity");
		assert getText(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY).equalsIgnoreCase(activity);
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Confirm"));

		//Delete data test
		waitForAndGetElement(pConnect.ELEMENT_IGNORE_BUTTON.replace("${peopleName}", user1));
		info("---Ignore the invitation from user '"+user1+"'-----");
		click(pConnect.ELEMENT_IGNORE_BUTTON.replace("${peopleName}", user1));
		waitForElementNotPresent(pConnect.ELEMENT_IGNORE_BUTTON.replace("${peopleName}", user1));

		acc.userSignIn(userType.ADMIN);
		home.deleteActivity(activity, true);
		acc.updateUserProfile("john",null, null, null);
	}

	/**
	 * Case ID:108076.
	 * Test Case Name: Generic pop up should be display with "Cancel Request" button in the Connection app.
	 * Pre-Condition: User A has received an invitation from the User BUser B is connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test14_GenericPopUpShouldBeDisplayWithCancelRequestButtonInTheConnectionApp() {
		info("Test 14 Generic pop up should be display with Cancel Request button in the Connection app");
		String activity = "Activity 108076";
		String post = "Case 108076";

		//Pre-Condition
		info("User A send request");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/
		acc.userSignIn(userType.PUBLISHER);
		nav.goToHomePage();
		addActivity(true, activity, false, "");
		info("User Mary update profile");
		acc.updateUserProfile(post,null, null, null);

		/*
		- Connect to Intranet with the User B
		- Go to the connection application
		- Move the mouse over the avatar of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Cancel Request" is displayed		*/ 
		acc.userSignIn(userType.ADMIN);
		nav.goToConnectionPage();
		Utils.pause(1000);
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user2), true);
		info("Position of user displays true");
		assert getText(hg.ELEMENT_USER_POPUP_POSITION).equalsIgnoreCase(post);	
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER2), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2), DEFAULT_TIMEOUT,1,2);
		info("Confirm user activity");
		assert getText(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY).equalsIgnoreCase(activity);
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Cancel Request"));

		//Delete data test
		waitForAndGetElement(pConnect.ELEMENT_CANCEL_REQUEST_BUTTON.replace("${peopleName}", user2));
		info("---Cancel the invitation to user '"+user2+"'-----");
		click(pConnect.ELEMENT_CANCEL_REQUEST_BUTTON.replace("${peopleName}", user2));
		waitForElementNotPresent(pConnect.ELEMENT_CANCEL_REQUEST_BUTTON.replace("${peopleName}", user2));

		acc.userSignIn(userType.PUBLISHER);
		home.deleteActivity(activity, true);	
		acc.updateUserProfile("mary",null, null, null);
	}

	/**
	 * Case ID:108082.
	 * Test Case Name: Generic pop up should be display with "Remove Connection" button in the Connection app.
	 * Pre-Condition: User A and User B are already a connectionUser A and User B are connected to Intranet User B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test15_GenericPopUpShouldBeDisplayWithRemoveConnectionButtonInTheConnectionApp() {
		info("Test 15 Generic pop up should be display with Remove Connection button in the Connection app");
		String activity = "Activity 108082";
		String post = "Case 108082";

		//Pre-Condition
		info("User update profile");
		acc.updateUserProfile(post,null, null, null);
		info("User A send request");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/
		nav.goToHomePage();
		addActivity(true, activity, false, "");

		/*
		- Connect to Intranet with the User B
		- Go to the connection application
		- Move the mouse over the avatar of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Remove Connection" is displayed		*/ 
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);
		Utils.pause(1000);
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user1), true);
		info("Position of user displays true");
		assert getText(hg.ELEMENT_USER_POPUP_POSITION).equalsIgnoreCase(post);	
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user activity");
		assert getText(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY).equalsIgnoreCase(activity);
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Remove Connection"));

		//Delete data test
		waitForAndGetElement(pConnect.ELEMENT_REMOVE_CONNECTION_BUTTON.replace("${peopleName}", user1));
		info("---Remove connection to user '"+user1+"'-----");
		click(pConnect.ELEMENT_REMOVE_CONNECTION_BUTTON.replace("${peopleName}", user1));
		waitForElementNotPresent(pConnect.ELEMENT_REMOVE_CONNECTION_BUTTON.replace("${peopleName}", user1));

		acc.userSignIn(userType.ADMIN);
		home.deleteActivity(activity, true);		
		acc.updateUserProfile("john",null, null, null);
	}

	/**
	 * Case ID:108088.
	 * Test Case Name: User's activity should be displayed after click on the username on generic pop up of connection "Everyone" tab.
	 * Pre-Condition: other users are member in Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test16_UsersActivityShouldBeDisplayedAfterClickOnTheUsernameOnGenericPopUpOfConnectionEveryoneTab() {
		info("Test 16 User's activity should be displayed after click on the username on generic pop up of connection Everyone tab");
		String post = "Case 108088";

		info("User Mary update profile");
		acc.userSignIn(userType.PUBLISHER);
		acc.updateUserProfile(post,null, null, null);

		/*
		- Connect to Intranet with the User A
		- From Connections application, choose "Everyone" tab
		- Move the mouse over the username link
		 *Expected Outcome: 
		- A generic pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/
		acc.userSignIn(userType.ADMIN);
		nav.goToConnectionPage();
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user2), true);
		info("Position of user displays true");
		assert getText(hg.ELEMENT_USER_POPUP_POSITION).equalsIgnoreCase(post);	
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER2), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2), DEFAULT_TIMEOUT,1,2);

		/*
		- From the Generic pop up, click on the username
		 *Input Data: 
		 *Expected Outcome: 
		- The User A is rediercted to the activity stream of the User 		*/ 
		info("click on userName");
		click(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2));
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER2)));
		Utils.pause(1000);

		//Delete data test
		acc.userSignIn(userType.PUBLISHER);
		acc.updateUserProfile("mary",null, null, null);
	}

	/**
	 * Case ID:108089.
	 * Test Case Name: User's activity should be displayed after click on the username on generic pop up of connection "My Connections" tab.
	 * Pre-Condition: User A and User B are a connection
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test17_UsersActivityShouldBeDisplayedAfterClickOnTheUsernameOnGenericPopUpOfConnectionMyConnectionsTab() {
		info("Test 17 User's activity should be displayed after click on the username on generic pop up of connection My Connections tab");
		String post = "Case 108089";

		//Pre-Condition
		info("User update profile");
		acc.updateUserProfile(post,null, null, null);
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);	

		/*
		- Connect to Intranet with the User A
		- From Connections application, choose "My Connections" tab
		- Move the mouse over the username link of the User B
		 *Expected Outcome: 
		- A generic pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user1), true);
		info("Position of user displays true");
		assert getText(hg.ELEMENT_USER_POPUP_POSITION).equalsIgnoreCase(post);	
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1), DEFAULT_TIMEOUT,1,2);

		/*
		- From the Generic pop up, click on the username
		 *Input Data: 
		 *Expected Outcome: 
		- The User A is rediercted to the activity stream of the User B		*/ 
		info("click on userName goto activity stream");
		click(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1));
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER1)));

		//Delete data test
		nav.goToConnectionPage();
		pConnect.removeConnection(user1);

		acc.userSignIn(userType.ADMIN);
		acc.updateUserProfile("john",null, null, null);
	}

	/**
	 * Case ID:108090.
	 * Test Case Name: User's activity should be displayed after click on the username on generic pop up of connection "Request Pending" tab.
	 * Pre-Condition: User A invite User B to connect
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test18_UsersActivityShouldBeDisplayedAfterClickOnTheUsernameOnGenericPopUpOfConnectionRequestPendingTab() {
		info("Test 18 User's activity should be displayed after click on the username on generic pop up of connection Request Pending tab");
		String post = "Case 108090";

		info("User Mary update profile");
		acc.userSignIn(userType.PUBLISHER);
		acc.updateUserProfile(post,null, null, null);

		//Pre-Condition
		acc.userSignIn(userType.ADMIN);
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);	

		/*
		- Connect to Intranet with the User A
		- From Connections application, choose "Request Pending" tab
		- Move the mouse over the username link of the User B
		 *Expected Outcome: 
		- A generic pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/
		click(pConnect.ELEMENT_REQUEST_PENDING_TAB);
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user2), true);
		info("Position of user displays true");
		assert getText(hg.ELEMENT_USER_POPUP_POSITION).equalsIgnoreCase(post);	
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER2), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2), DEFAULT_TIMEOUT,1,2);

		/*
		- From the Generic pop up, click on the username
		 *Input Data: 
		 *Expected Outcome: 
		- The User A is rediercted to the activity stream of the User B		*/ 
		click(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2));
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER2)));

		//Delete data test
		nav.goToConnectionPage();
		pConnect.cancelRequest(user2);		

		acc.userSignIn(userType.PUBLISHER);
		acc.updateUserProfile("mary",null, null, null);
	}

	/**
	 * Case ID:108091.
	 * Test Case Name: User's activity should be displayed after click on the username on generic pop up of connection "Requests Received" tab.
	 * Pre-Condition: User A receive an invitation from the User B
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test19_UsersActivityShouldBeDisplayedAfterClickOnTheUsernameOnGenericPopUpOfConnectionRequestsReceivedTab() {
		info("Test 19 User's activity should be displayed after click on the username on generic pop up of connection Requests Received tab");
		String post = "Case 108091";

		//Pre-Condition
		info("User update profile");
		acc.updateUserProfile(post,null, null, null);
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		/*
		- Connect to Intranet with the User A
		- From Connections application, choose "Received Requests" tab
		- Move the mouse over the username link of the User B
		 *Expected Outcome: 
		- A generic pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		click(pConnect.ELEMENT_REQUESTS_RECEIVED_TAB);
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user1), true);
		info("Position of user displays true");
		assert getText(hg.ELEMENT_USER_POPUP_POSITION).equalsIgnoreCase(post);	
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1), DEFAULT_TIMEOUT,1,2);

		/*
		- From the Generic pop up, click on the username
		 *Input Data: 
		 *Expected Outcome: 
		- The User A is rediercted to the activity stream of the User B		*/ 		
		click(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1));
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER1)));

		//Delete data test
		nav.goToConnectionPage();
		pConnect.ignoreInvitation(user1);	

		acc.userSignIn(userType.ADMIN);
		acc.updateUserProfile("john",null, null, null);
	}

	/**
	 * Case ID:108096.
	 * Test Case Name: User's activity should be displayed after click on User's avatar on generic pop up of connection "Everyone" tab.
	 * Pre-Condition: other users are member in Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test20_UsersActivityShouldBeDisplayedAfterClickOnUsersAvatarOnGenericPopUpOfConnectionEveryoneTab() {
		info("Test 20 User's activity should be displayed after click on User's avatar on generic pop up of connection Everyone tab");
		String post = "Case 108096";

		info("User Mary update profile");
		acc.userSignIn(userType.PUBLISHER);
		acc.updateUserProfile(post,null, null, null);

		/*
		- Connect to Intranet with the User A
		- From Connections application, choose "Everyone" tab
		- Move the mouse over the username link
		 *Expected Outcome: 
		- A generic pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/
		acc.userSignIn(userType.ADMIN);
		nav.goToConnectionPage();
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user2), true);
		info("Position of user displays true");
		assert getText(hg.ELEMENT_USER_POPUP_POSITION).equalsIgnoreCase(post);	
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER2), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2), DEFAULT_TIMEOUT,1,2);

		/*
		- From the Generic pop up, click on the user's avatar
		 *Input Data: 
		 *Expected Outcome: 
		- The User A is rediercted to the activity stream of the User 		*/ 
		click(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER2));
		Utils.pause(1000);		
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER2)));	

		//Delete data test
		acc.userSignIn(userType.PUBLISHER);
		acc.updateUserProfile("mary",null, null, null);
	}

	/**
	 * Case ID:108097.
	 * Test Case Name: User's activity should be displayed after click on User's avatar on generic pop up of connection "My Connections" tab.
	 * Pre-Condition: User A and User B are a connection
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test21_UsersActivityShouldBeDisplayedAfterClickOnUsersAvatarOnGenericPopUpOfConnectionMyConnectionsTab() {
		info("Test 21 User's activity should be displayed after click on User's avatar on generic pop up of connection My Connections tab");
		String post = "Case 108097";

		//Pre-Condition
		info("User update profile");
		acc.updateUserProfile(post,null, null, null);
		info("UserA connetion to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		/*
		- Connect to Intranet with the User A
		- From Connections application, choose "My Connections" tab
		- Move the mouse over the username link of the User B
		 *Expected Outcome: 
		- A generic pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/
		acc.userSignIn(userType.PUBLISHER);
		nav.goToHomePage();
		pConnect.acceptInvitation(user1);
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user1), true);
		info("Position of user displays true");
		assert getText(hg.ELEMENT_USER_POPUP_POSITION).equalsIgnoreCase(post);	
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1), DEFAULT_TIMEOUT,1,2);

		/*
		- From the Generic pop up, click on the user's avatar
		 *Input Data: 
		 *Expected Outcome: 
		- The User A is rediercted to the activity stream of the User B		*/ 
		click(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER1));
		Utils.pause(1000);		
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER1)));		

		//Delete date test
		acc.userSignIn(userType.ADMIN);
		acc.updateUserProfile("john",null, null, null);
	}

	/**
	 * Case ID:108098.
	 * Test Case Name: User's activity should be displayed after click on User's avatar on generic pop up of connection "Request Pending" tab.
	 * Pre-Condition: User A invite User B to connect
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test22_UsersActivityShouldBeDisplayedAfterClickOnUsersAvatarOnGenericPopUpOfConnectionRequestPendingTab() {
		info("Test 22 User's activity should be displayed after click on User's avatar on generic pop up of connection Request Pending tab");
		String post = "Case 108098";

		//Pre-Condition
		info("User Mary update profile");
		acc.userSignIn(userType.PUBLISHER);
		acc.updateUserProfile(post,null, null, null);

		info("UserA connetion to userB");
		acc.userSignIn(userType.ADMIN);
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		/*
		- Connect to Intranet with the User A
		- From Connections application, choose "Request Pending" tab
		- Move the mouse over the username link of the User B
		 *Expected Outcome: 
		- A generic pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/
		click(pConnect.ELEMENT_REQUEST_PENDING_TAB);
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user2), true);
		info("Position of user displays true");
		assert getText(hg.ELEMENT_USER_POPUP_POSITION).equalsIgnoreCase(post);	
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER2), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2), DEFAULT_TIMEOUT,1,2);

		/*
		- From the Generic pop up, click on the avatar of the User B
		 *Input Data: 
		 *Expected Outcome: 
		- The User A is rediercted to the activity stream of the User B		*/ 
		click(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2));
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER2)));

		//Delete data test
		nav.goToConnectionPage();
		pConnect.cancelRequest(user2);	

		acc.userSignIn(userType.PUBLISHER);
		acc.updateUserProfile("mary",null, null, null);
	}

	/**
	 * Case ID:108099.
	 * Test Case Name: User's activity should be displayed after click on User's avatar generic pop up of connection "Requests Received" tab.
	 * Pre-Condition: User A receive an invitation from the User B
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/17 16:17:41
	 */
	@Test
	public  void test23_UsersActivityShouldBeDisplayedAfterClickOnUsersAvatarGenericPopUpOfConnectionRequestsReceivedTab() {
		info("Test 23 User's activity should be displayed after click on User's avatar generic pop up of connection Requests Received tab");
		String post = "Case 108099";

		//Pre-Condition
		info("User update profile");
		acc.updateUserProfile(post,null, null, null);
		info("UserA connetion to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		/*
		- Connect to Intranet with the User A
		- From Connections application, choose "Received Requests" tab
		- Move the mouse over the username link of the User B
		 *Expected Outcome: 
		- A generic pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		click(pConnect.ELEMENT_REQUESTS_RECEIVED_TAB);
		mouseOver(pConnect.ELEMENT_CONNECTION_MEMBER.replace("${peopleName}", user1), true);
		info("Position of user displays true");
		assert getText(hg.ELEMENT_USER_POPUP_POSITION).equalsIgnoreCase(post);	
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}", DATA_USER1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1), DEFAULT_TIMEOUT,1,2);

		/*
		- From the Generic pop up, click on the avatar of the User B
		 *Input Data: 
		 *Expected Outcome: 
		- The User A is rediercted to the activity stream of the User B		*/ 
		click(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1));
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER1)));

		//Delete data test
		nav.goToConnectionPage();
		pConnect.ignoreInvitation(user1);	

		acc.userSignIn(userType.ADMIN);
		acc.updateUserProfile("john",null, null, null);
	}
}