package org.exoplatform.selenium.platform.plf.functional.genericuserpopup;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.Utils;
import org.exoplatform.selenium.platform.HomePageActivity;
import org.exoplatform.selenium.platform.HomePageGadget;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.ManageAccount.userType;
import org.exoplatform.selenium.platform.ecms.EcmsBase;
import org.exoplatform.selenium.platform.ecms.contentexplorer.ActionBar;
import org.exoplatform.selenium.platform.ecms.contentexplorer.ContextMenu.actionType;
import org.exoplatform.selenium.platform.social.Activity;
import org.exoplatform.selenium.platform.social.PeopleConnection;
import org.exoplatform.selenium.platform.social.PeopleSearch;
import org.openqa.selenium.By;
import org.testng.annotations.*;

/**
 * @author chinhdtt
 * @date 09 Jun 2014
 */
public class PLF_GenericUserPopup_WhoIsOnlineGadget extends Activity{
	ManageAccount acc;
	HomePageGadget hg;
	NavigationToolbar nav;
	PeopleConnection pConnect;
	PeopleSearch pSearch;
	HomePageActivity home; 
	ActionBar act; 
	EcmsBase ecms; 
	String user1 = "John Smith";
	String user2 = "Mary Williams";

	@BeforeMethod
	public void setUpBeforeTest(){
		getDriverAutoSave();
		acc = new ManageAccount(driver, this.plfVersion);
		hg = new HomePageGadget(driver, this.plfVersion);
		pConnect = new PeopleConnection(driver, this.plfVersion);
		pSearch = new PeopleSearch(driver);
		nav = new NavigationToolbar(driver, this.plfVersion);
		home = new HomePageActivity(driver, this.plfVersion);
		act = new ActionBar(driver, this.plfVersion);
		ecms = new EcmsBase(driver, this.plfVersion);
		acc.signIn(DATA_USER1, DATA_PASS);
	}

	@AfterMethod
	public void afterTest(){
		driver.manage().deleteAllCookies();
		driver.quit();
	}

	/**
	 * Case ID:108025.
	 * Test Case Name: Generic popup should be displayed on hover of Who's online.
	 * Pre-Condition: A second User is connected to Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/09 10:05:22
	 */
	@Test
	public  void test01_GenericPopupShouldBeDisplayedOnHoverOfWhosOnline() {
		info("Test 1: Generic popup should be displayed on hover of Who's online");
		/*
		- Connect to Intranet
		- From "Who's online" application, hover on the avatar of the user
		 *Expected Outcome: 
		- The Generic popup is displayed		*/ 
		loginWithAnotherAccOnThesameBrowser(DATA_USER2, DATA_PASS);
		hg=new HomePageGadget(newDriver);
		newDriver.navigate().refresh();

		info("Check pop-up information of online user");
		hg.checkUserInfoOnWhoisOnlineGadget(DATA_USER1, false, "", false, false);

		Utils.pause(1000);
		newDriver.manage().deleteAllCookies();
		newDriver.quit();
	}

	/**
	 * Case ID:108047.
	 * Test Case Name: Generic popup should be displayed as status type in Who's online application.
	 * Pre-Condition: User A and User B are connect to the Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/09 10:05:22
	 */
	@Test
	public  void test02_GenericPopupShouldBeDisplayedAsStatusTypeInWhosOnlineApplication() {
		info("Test 2: Generic popup should be displayed as status type in Who's online application");
		String activity = "Activity 108047";

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);

		/*
		- Connect to Intranet with User A
		- Share an activity
		 *Expected Outcome: 
		- Activity with status is shared		*/
		nav.goToHomePage();
		addActivity(true, activity, false, "");

		/*
		- Connect to Intranet with User B in other browser
		- Go to the Who's online application
		- Hover on the user A's avatar 
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: Status		*/ 
		info("User2 check");
		loginWithAnotherAccOnThesameBrowser(DATA_USER1, DATA_PASS);
		hg=new HomePageGadget(newDriver);
		newDriver.navigate().refresh();
		hg.checkUserInfoOnWhoisOnlineGadget(DATA_USER2, user2, null, false, activity, 4);

		//Delete data test
		pConnect = new PeopleConnection(newDriver);
		nav = new NavigationToolbar(newDriver);
		nav.goToConnectionPage();
		pConnect.removeConnection(user2);
		newDriver.manage().deleteAllCookies();
		newDriver.quit();

		driver.navigate().refresh();
		home.deleteActivity(activity, true);		
	}

	/**
	 * Case ID:108058.
	 * Test Case Name: Generic popup should be displayed as File Sharing type in Who's online application.
	 * Pre-Condition: User A and User B are connect to the Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/09 10:05:22
	 * Bug: https://jira.exoplatform.org/browse/COMMONS-278
	 */
	@Test (groups = "errors")
	public  void test03_GenericPopupShouldBeDisplayedAsFileSharingTypeInWhosOnlineApplication() {
		info("Test 3: Generic popup should be displayed as File Sharing type in Who's online application");
		String uploadFileName = "French.docx";
		String folder = "folder108058";
		String driverName = "Personal Drives";
		String folderPath = "Personal Documents";

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);

		/*
		- Connect to Intranet with User A
		- Share a File
		 *Expected Outcome: 
		- Activity with File is shared		*/
		nav.goToHomePage();
		selectFile(driverName,true,folderPath,"",uploadFileName,folder);

		/*
		- Connect to Intranet with User B in other browser
		- Go to the Who's online application
		- Hover on the user A's avatar 
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: File		*/ 
		loginWithAnotherAccOnThesameBrowser(DATA_USER1, DATA_PASS);
		hg=new HomePageGadget(newDriver);
		newDriver.navigate().refresh();
		hg.checkUserInfoOnWhoisOnlineGadget(DATA_USER2, user2, null, false, uploadFileName, 4);


		//Delete data test
		info("Remove connection");
		pConnect = new PeopleConnection(newDriver);
		nav = new NavigationToolbar(newDriver);
		nav.goToConnectionPage();
		pConnect.removeConnection(user2);
		newDriver.manage().deleteAllCookies();
		newDriver.quit();

		info("Delete file activity");
		driver.navigate().refresh();
		home.deleteActivity(uploadFileName, true);
		nav.goToSiteExplorer();
		act.chooseDrive(ecms.ELEMENT_PERSONAL_DRIVE);
		act.actionsOnElement(folder, actionType.DELETE,true,true);
	}

	/**
	 * Case ID:108059.
	 * Test Case Name: Generic popup should be displayed as Link Sharing type in Who's online application.
	 * Pre-Condition: User A and User B are connect to the Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/09 10:05:22
	 */
	@Test
	public  void test04_GenericPopupShouldBeDisplayedAsLinkSharingTypeInWhosOnlineApplication() {
		info("Test 4: Generic popup should be displayed as Link Sharing type in Who's online application");
		String text = "";
		String link = "http://apple.com"; 

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);

		/*
		- Connect to Intranet with User A
		- Share a Link
		 *Expected Outcome: 
		- Activity with Link is shared		*/
		info("Share activity");
		nav.goToHomePage();
		addActivity(false, text, true, link);

		/*
		- Connect to Intranet with User B in other browser
		- Go to the Who's online application
		- Hover on the user A's avatar 
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: Link		*/ 
		loginWithAnotherAccOnThesameBrowser(DATA_USER1, DATA_PASS);
		hg=new HomePageGadget(newDriver);
		newDriver.navigate().refresh();
		hg.checkUserInfoOnWhoisOnlineGadget(DATA_USER2, user2, null, false, "Apple", 4);

		//Delete data test
		info("Remove connection");
		pConnect = new PeopleConnection(newDriver);
		nav = new NavigationToolbar(newDriver);
		nav.goToConnectionPage();
		pConnect.removeConnection(user2);
		newDriver.manage().deleteAllCookies();
		newDriver.quit();

		info("Delete link activity");
		driver.navigate().refresh();		
		home.deleteActivity(link, true);
	}

	/**
	 * Case ID:108065.
	 * Test Case Name: Generic pop up should be display with "Connect" button in the Who's online app.
	 * Pre-Condition: User A and User B are not a connectionUser B is connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/09 10:05:22
	 */
	@Test
	public  void test05_GenericPopUpShouldBeDisplayWithConnectButtonInTheWhosOnlineApp() {
		info("Test 5: Generic pop up should be display with Connect button in the Who's online app");
		String activity = "Activity 108065";

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/
		addActivity(true, activity, false, "");

		/*
		- Connect to Intranet with the User B in other browser
		- In the gadget Who's online, move the mouse over the avatar of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Connect" is displayed		*/
		loginWithAnotherAccOnThesameBrowser(DATA_USER2, DATA_PASS);
		hg=new HomePageGadget(newDriver);
		newDriver.navigate().refresh();
		hg.checkUserInfoOnWhoisOnlineGadget(DATA_USER1, user1, null, false, activity, 1);

		/*
		- Click on the button "Connect"
		- Mouse over avatar of user in who's online gadget again
		 *Input Data: 
		 *Expected Outcome: 
		- 2 users are friends
		- The button connect is changed to [Cancel Request]		*/ 
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Connect"), DEFAULT_TIMEOUT,1,2, newDriver).click();
		Utils.pause(1000);
		newDriver.navigate().refresh();		
		hg.checkUserInfoOnWhoisOnlineGadget(DATA_USER1, user1, null, false, activity, 2);

		//Delete data test
		info("Remove connection");
		pConnect = new PeopleConnection(newDriver);
		nav = new NavigationToolbar(newDriver);
		nav.goToConnectionPage();
		pConnect.cancelRequest(user1);
		newDriver.manage().deleteAllCookies();
		newDriver.quit();

		info("Delete activity");
		driver.navigate().refresh();
		home.deleteActivity(activity, true);		
	}

	/**
	 * Case ID:108071.
	 * Test Case Name: Generic pop up should be display with "Confirm" button in the Who's online app.
	 * Pre-Condition: User B has received an invitation from the User A
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/09 10:05:22
	 */
	@Test
	public  void test06_GenericPopUpShouldBeDisplayWithConfirmButtonInTheWhosOnlineApp() {
		info("Test 6: Generic pop up should be display with Confirm button in the Who's online app");
		String activity = "Activity 108071";

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/
		nav.goToHomePage();
		addActivity(true, activity, false, "");

		/*
		- Connect to Intranet with the User B in other browser
		- In the gadget Who's online, move the mouse over the avatar of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Confirm" is displayed		*/
		loginWithAnotherAccOnThesameBrowser(DATA_USER2, DATA_PASS);
		hg=new HomePageGadget(newDriver);
		newDriver.navigate().refresh();
		hg.checkUserInfoOnWhoisOnlineGadget(DATA_USER1, user1, null, false, activity, 3);

		/*
		- Click button [Confirm]
		- Mouse over user A avatar on who's online gadget again
		 *Input Data: 
		 *Expected Outcome: 
		- User A & B are friends
		- Button [Confirm] is changed to [Remove connection]		*/ 		
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Confirm"), DEFAULT_TIMEOUT,1,2, newDriver).click();
		Utils.pause(1000);
		newDriver.navigate().refresh();
		hg.checkUserInfoOnWhoisOnlineGadget(DATA_USER1, user1, null, false, activity, 4);

		//Delete data test
		newDriver.manage().deleteAllCookies();
		newDriver.quit();

		info("Delete activity");
		driver.navigate().refresh();
		home.deleteActivity(activity, true);		
	}

	/**
	 * Case ID:108077.
	 * Test Case Name: Generic pop up should be display with "Cancel Request" button in the Who's online app.
	 * Pre-Condition: User A has received an invitation from the User BUser B is connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/09 10:05:22
	 */
	@Test
	public  void test07_GenericPopUpShouldBeDisplayWithCancelRequestButtonInTheWhosOnlineApp() {
		info("Test 7: Generic pop up should be display with Cancel Request button in the Who's online app");
		String activity = "Activity 108077";

		//Pre-Condition
		info("UserA connect userB");
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.connectPeople(user1);
		driver.quit();

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/		
		getDriverAutoSave();
		setUpBeforeTest();
		nav.goToHomePage();
		addActivity(true, activity, false, "");

		/*
		- Connect to Intranet with the User B in other browser
		- In the gadget Who's online, move the mouse over the avatar of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Cancel Request" is displayed		*/
		loginWithAnotherAccOnThesameBrowser(DATA_USER2, DATA_PASS);
		hg=new HomePageGadget(newDriver);
		newDriver.navigate().refresh();
		hg.checkUserInfoOnWhoisOnlineGadget(DATA_USER1, user1, null, false, activity, 2);

		/*
		- Click button [cancel request]
		- Mouse over user avatar on who's online gadget again
		 *Input Data: 
		 *Expected Outcome: 
		- 2 users are not friends
		- Button [Cancel request] is changed to [Connect]		*/ 
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Cancel Request"), DEFAULT_TIMEOUT,1,2, newDriver).click();
		Utils.pause(1000);
		newDriver.navigate().refresh();
		hg.checkUserInfoOnWhoisOnlineGadget(DATA_USER1, user1, null, false, activity, 1);

		//Delete data test
		newDriver.manage().deleteAllCookies();
		newDriver.quit();

		info("Delete activity");
		driver.navigate().refresh();
		home.deleteActivity(activity, true);		
	}

	/**
	 * Case ID:108083.
	 * Test Case Name: Generic pop up should be display with "Remove Connection" button in the Who's online app.
	 * Pre-Condition: User A and User B are already a connectionUser A and User B are connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/09 10:05:22
	 */
	@Test
	public  void test08_GenericPopUpShouldBeDisplayWithRemoveConnectionButtonInTheWhosOnlineApp() {
		info("Test 8: Generic pop up should be display with Remove Connection button in the Who's online app");
		String activity = "Activity 108083";

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/		
		info("Share activity");
		nav.goToHomePage();
		addActivity(true, activity, false, "");

		/*
		- Connect to Intranet with the User B in other browser
		- In the gadget Who's online, move the mouse over the avatar of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Remove Connection" is displayed		*/
		loginWithAnotherAccOnThesameBrowser(DATA_USER1, DATA_PASS);
		hg=new HomePageGadget(newDriver);
		newDriver.navigate().refresh();
		Utils.pause(1000);
		hg.checkUserInfoOnWhoisOnlineGadget(DATA_USER2, user2, null, false, activity, 4);

		/*
		- Click button [Remove connection]
		- Mouse over user avatar on who's online gadget again
		 *Input Data: 
		 *Expected Outcome: 
		- 2 users are not friends
		- Button [Remove Connection] is changed to [Connect]		*/ 		
		info("Click button Remove");
		waitForAndGetElement(By.xpath(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Remove Connection")), DEFAULT_TIMEOUT,1,2, newDriver).click();
		Utils.pause(1000);		
		newDriver.navigate().refresh();
		info("Button Connect is displayed");
		hg.checkUserInfoOnWhoisOnlineGadget(DATA_USER2, user2, null, false, activity, 1);

		//Delete data test
		newDriver.manage().deleteAllCookies();
		newDriver.quit();

		info("Delete activity");
		driver.navigate().refresh();
		home.deleteActivity(activity, true);		
	}

	/**
	 * Case ID:108100.
	 * Test Case Name: User's activity should be displayed after click on User's avatar generic pop up of who's online app.
	 * Pre-Condition: User A and User B are a connectionUser A and User B are connected to Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/09 10:05:22
	 */
	@Test
	public  void test09_UsersActivityShouldBeDisplayedAfterClickOnUsersAvatarGenericPopUpOfWhosOnlineApp() {
		info("Test 9: User's activity should be displayed after click on User's avatar generic pop up of who's online app");
		String activity = "Activity 108100";

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);

		/*
		- Connect to Intranet with the User A
		- Share an activity
		 *Expected Outcome: 
		- activity of the User A is shared		*/
		info("Share activity");
		nav.goToHomePage();
		addActivity(true, activity, false, "");

		/*
		- Connect to Intranet with the User B
		- From Who's online gadget, move the mouse over the User A's avatar
		 *Input Data: 
		 *Expected Outcome: 
		- A generic pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/
		loginWithAnotherAccOnThesameBrowser(DATA_USER1, DATA_PASS);
		hg=new HomePageGadget(newDriver);
		newDriver.navigate().refresh();
		hg.checkUserInfoOnWhoisOnlineGadget(DATA_USER2, user2, null, false, activity, 4);

		/*
		- From the Generic pop up, click on the avatar of the User B
		 *Input Data: 
		 *Expected Outcome: 
		- The User A is rediercted to the activity stream of the User B		*/ 
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}",DATA_USER2), DEFAULT_TIMEOUT,1,2, newDriver).click();
		Utils.pause(1000);
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER2)), DEFAULT_TIMEOUT,1,2, newDriver);

		//Delete data test
		info("Remove connection");
		pConnect = new PeopleConnection(newDriver);
		nav = new NavigationToolbar(newDriver);
		nav.goToConnectionPage();
		pConnect.removeConnection(user2);
		newDriver.manage().deleteAllCookies();
		newDriver.quit();

		driver.navigate().refresh();
		home.deleteActivity(activity, true);
	}

	/**
	 * Case ID:108101.
	 * Test Case Name: User's activity should be displayed after click on the username on generic pop up of who's online app.
	 * Pre-Condition: User A and User B are a connectionUser A and User B are connected to Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/09 10:05:22
	 */
	@Test
	public  void test10_UsersActivityShouldBeDisplayedAfterClickOnTheUsernameOnGenericPopUpOfWhosOnlineApp() {
		info("Test 10 User's activity should be displayed after click on the username on generic pop up of who's online app");
		String activity = "Activity 108101";

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);

		/*
		- Connect to Intranet with the User A
		- Share an activity
		 *Expected Outcome: 
		- activity of the User A is shared		*/
		info("Share activity");
		nav.goToHomePage();
		addActivity(true, activity, false, "");

		/*
		- Connect to Intranet with the User B
		- From Who's online gadget, move the mouse over the User A's avatar
		 *Input Data: 
		 *Expected Outcome: 
		- A generic pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/
		loginWithAnotherAccOnThesameBrowser(DATA_USER1, DATA_PASS);
		hg=new HomePageGadget(newDriver);
		newDriver.navigate().refresh();
		hg.checkUserInfoOnWhoisOnlineGadget(DATA_USER2, user2, null, false, activity, 4);

		/*
		- From the Generic pop up, click on the username of the User B
		 *Input Data: 
		 *Expected Outcome: 
		- The User A is rediercted to the activity stream of the User B		*/ 
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2), DEFAULT_TIMEOUT,1,2, newDriver).click();
		Utils.pause(1000);
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER2)), DEFAULT_TIMEOUT,1,2, newDriver);

		//Delete data test
		info("Remove connection");
		pConnect = new PeopleConnection(newDriver);
		nav = new NavigationToolbar(newDriver);
		nav.goToConnectionPage();
		pConnect.removeConnection(user2);
		newDriver.manage().deleteAllCookies();
		newDriver.quit();

		driver.navigate().refresh();
		home.deleteActivity(activity, true);
	}
}