package org.exoplatform.selenium.platform.plf.functional.genericuserpopup;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.Button;
import org.exoplatform.selenium.Utils;
import org.exoplatform.selenium.platform.HomePageActivity;
import org.exoplatform.selenium.platform.HomePageGadget;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.ManageAccount.userType;
import org.exoplatform.selenium.platform.ecms.EcmsBase;
import org.exoplatform.selenium.platform.ecms.contentexplorer.ActionBar;
import org.exoplatform.selenium.platform.ecms.contentexplorer.ContextMenu.actionType;
import org.exoplatform.selenium.platform.social.Activity;
import org.exoplatform.selenium.platform.social.ManageMember;
import org.exoplatform.selenium.platform.social.PeopleConnection;
import org.exoplatform.selenium.platform.social.PeopleProfile;
import org.exoplatform.selenium.platform.social.PeopleSearch;
import org.exoplatform.selenium.platform.social.SpaceManagement;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebElement;
import org.testng.annotations.*;

/**
 * @author chinhdtt
 * @date 19 Jun 2014
 */
public class PLF_GenericUserPopup_ActivityStream extends Activity{
	ManageAccount acc;
	HomePageGadget hg;
	NavigationToolbar nav;
	PeopleConnection pConnect;
	PeopleSearch pSearch;
	HomePageActivity home; 
	SpaceManagement mSpace; 
	ManageMember mMember; 
	ActionBar act; 
	EcmsBase ecms; 
	String user1 = "John Smith";
	String user2 = "Mary Williams";
	PeopleProfile pepPro;
	Button but;

	@BeforeMethod
	public void setUpBeforeTest(){
		initSeleniumTest();
		but = new Button(driver, this.plfVersion);
		pepPro = new PeopleProfile(driver);
		acc = new ManageAccount(driver, this.plfVersion);
		hg = new HomePageGadget(driver, this.plfVersion);
		pConnect = new PeopleConnection(driver, this.plfVersion);
		pSearch = new PeopleSearch(driver);
		nav = new NavigationToolbar(driver, this.plfVersion);
		home = new HomePageActivity(driver, this.plfVersion);
		act = new ActionBar(driver, this.plfVersion);
		ecms = new EcmsBase(driver, this.plfVersion);
		mSpace = new SpaceManagement(driver, this.plfVersion);
		mMember = new ManageMember(driver, this.plfVersion);
		acc.signIn(DATA_USER1, DATA_PASS);
	}

	@AfterMethod
	public void afterTest(){
		driver.manage().deleteAllCookies();
		driver.quit();
	}

	/**
	 * Case ID:108026.
	 * Test Case Name: Generic popup should be displayed on hover of activity stream's likes.
	 * Pre-Condition: A second User is connected to Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test01_GenericPopupShouldBeDisplayedOnHoverOfActivityStreamsLikes() {
		info("Test 1: Generic popup should be displayed on hover of activity stream's likes");
		String activity = "Activity 108026";

		/*
		- Connect to Intranet
		- From an activity, click on Like action
		 *Expected Outcome: 
		- The avatar of user is displayed		*/
		addActivity(true, activity, false, "");
		Utils.pause(1000);
		home.likeOrUnlikeActivity(activity);
		String avatarName = waitForAndGetElement(ELEMENT_AVATAR_LIST_LIKER_INDEX.replace("${activityText}", activity).replace("${index}", "1")).getAttribute("alt");
		assert(avatarName.contains(user1));
		mouseOver(ELEMENT_AVATAR_LIST_LIKER_INDEX.replace("${activityText}", activity).replace("${index}", "1"),true);
		/*
		- Hover on the avatar of the user
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed		*/ 
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", user1));

		//Detele data test
		home.deleteActivity(activity, true);
	}

	/**
	 * Case ID:108027.
	 * Test Case Name: Generic popup should be displayed on hover of activity stream's mentions.
	 * Pre-Condition: A second User is connected to Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test02_GenericPopupShouldBeDisplayedOnHoverOfActivityStreamsMentions() {
		info("Test 2: Generic popup should be displayed on hover of activity stream's mentions");
		/*
		- Connect to Intranet
		- Share an activity with a mention
		 *Expected Outcome: 
		- The name of the user is displayed in the shared activity		*/
		mentionActivity(true,"",user2);

		/*
		- Hover on the user's name
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed		*/ 
		mouseOver(home.ELEMENT_ACTIVITY.replace("${activityText}",user2), true);		
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", user2));

		//Detele data test
		home.deleteActivity(user2, true);
	}

	/**
	 * Case ID:108028.
	 * Test Case Name: Generic popup should be displayed on hover of activity stream's avatar.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test03_GenericPopupShouldBeDisplayedOnHoverOfActivityStreamsAvatar() {
		info("Test 3: Generic popup should be displayed on hover of activity stream's avatar");
		String activity = "Activity 108028";
		/*
		- Connect to Intranet
		- Share an activity
		 *Expected Outcome: 
		- Activity is shared
		- The avatar of user is displayed on the timeline		*/
		addActivity(true, activity, false, "");

		/*
		- Hover on the user's avatar
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed		*/ 
		Utils.pause(1000);
		info("mouse Over on Avatar");
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_AVATAR.replace("${index}","1").replace("${author}", user1), true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", user1));

		//Delete date test
		nav.goToHomePage();
		home.deleteActivity(activity, true);
	}

	/**
	 * Case ID:108029.
	 * Test Case Name: Generic popup should be displayed on hover of activity stream's username.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test04_GenericPopupShouldBeDisplayedOnHoverOfActivityStreamsUsername() {
		info("Test 4: Generic popup should be displayed on hover of activity stream's username");
		String activity = "Activity 108029";

		/*
		- Connect to Intranet
		- Share an activity
		 *Expected Outcome: 
		- Activity is shared
		- The username is displayed in the activity box		*/
		addActivity(true, activity, false, "");

		/*
		- Hover on the username link
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed		*/ 
		Utils.pause(1000);
		waitForAndGetElement(home.ELEMENT_ACTIVITY_AUTHOR_NAME.replace("${index}","1").replace("${author}", user1));
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_NAME.replace("${index}","1").replace("${author}", user1), true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", user1));

		//Delete data test
		nav.goToHomePage();
		home.deleteActivity(activity);
	}

	/**
	 * Case ID:108034.
	 * Test Case Name: User's informations should be displayed on generic pop up of activity stream's likes.
	 * Pre-Condition: User A has received a request to connect from the user B User B is connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test05_UsersInformationsShouldBeDisplayedOnGenericPopUpOfActivityStreamsLikes() {
		info("Test 5: User's informations should be displayed on generic pop up of activity stream's likes");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String activity = "Activity 108034";
		String name = getRandomString();
		String usertest = name+" "+name;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);
		nav.goToMyProfile();
		info("edit profile");
		click(pepPro.ELEMENT_EDIT_MY_PROFILE_LINK);
		info("edit info");
		pepPro.updateBasicInformation(name, name, null);
		pepPro.saveCancelUpdateInfo(true);

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);

		/*
		- Connect to Intranet with the User A
		- User A like an activity shared by the User B
		 *Expected Outcome: 
		- The avatar of the User A is displayed in the likers list		*/
		nav.goToHomePage();
		addActivity(true, activity, false, "");
		acc.signIn(username1, password1);
		home.likeOrUnlikeActivity(activity);
		acc.userSignIn(userType.PUBLISHER);
		Utils.pause(1000);
		String avatarName = waitForAndGetElement(ELEMENT_AVATAR_LIST_LIKER_INDEX.replace("${activityText}", activity).replace("${index}", "1")).getAttribute("alt");
		assert(avatarName.contains(usertest));
		mouseOver(ELEMENT_AVATAR_LIST_LIKER_INDEX.replace("${activityText}", activity).replace("${index}", "1"),true);

		/*
		- Move the mouse over the user's avatar
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/ 
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", usertest));
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}",username1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",username1), DEFAULT_TIMEOUT,1,2);

		//Detele data test
		home.deleteActivity(activity, true);
	}

	/**
	 * Case ID:108035.
	 * Test Case Name: User's informations should be displayed on generic pop up of activity stream's mentions.
	 * Pre-Condition: User A has received a request to connect from the user BUser B is connected to Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test06_UsersInformationsShouldBeDisplayedOnGenericPopUpOfActivityStreamsMentions() {
		info("Test 6: User's informations should be displayed on generic pop up of activity stream's mentions");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String name = getRandomString();
		String usertest = name+" "+name;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);
		nav.goToMyProfile();
		info("edit profile");
		click(pepPro.ELEMENT_EDIT_MY_PROFILE_LINK);
		info("edit info");
		pepPro.updateBasicInformation(name, name, null);
		pepPro.saveCancelUpdateInfo(true);

		/*
		- Connect to Intranet with the User A
		- Share an activity and mention the user B
		 *Expected Outcome: 
		- The username of the User B is displayed in the activity		*/
		acc.userSignIn(userType.PUBLISHER);
		mentionActivity(true,"",usertest);

		/*
		- Move the mouse over the username link
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/ 
		mouseOver(home.ELEMENT_ACTIVITY.replace("${activityText}",usertest), true);	
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", usertest));
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}",username1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",username1), DEFAULT_TIMEOUT,1,2);

		//Detele data test
		acc.signIn(username1, password1);
		home.deleteActivity(usertest, true);
	}

	/**
	 * Case ID:108036.
	 * Test Case Name: User's informations should be displayed on generic pop up of activity stream's avatars.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test07_UsersInformationsShouldBeDisplayedOnGenericPopUpOfActivityStreamsAvatars() {
		info("Test 7: User's informations should be displayed on generic pop up of activity stream's avatars");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String name = getRandomString();
		String usertest = name+" "+name;
		String activity = "activity" + getRandomNumber();
		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);
		nav.goToMyProfile();
		info("edit profile");
		click(pepPro.ELEMENT_EDIT_MY_PROFILE_LINK);
		info("edit info");
		pepPro.updateBasicInformation(name, name, null);
		pepPro.saveCancelUpdateInfo(true);

		/*
		- Connect to Intranet with the User A
		- Share an activity		
		- Move the mouse over the user's avatar
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/
		acc.signIn(username1, password1);
		addActivity(true, activity, false, "");
		Utils.pause(1000);
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_AVATAR.replace("${index}","1").replace("${author}", usertest), true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", usertest));
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}",username1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",username1), DEFAULT_TIMEOUT,1,2);

		//Delete date test
		nav.goToHomePage();
		home.deleteActivity(activity, true);
	}

	/**
	 * Case ID:108037.
	 * Test Case Name: User's informations should be displayed on generic pop up of activity stream's user names.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test08_UsersInformationsShouldBeDisplayedOnGenericPopUpOfActivityStreamsUserNames() {
		info("Test 8: User's informations should be displayed on generic pop up of activity stream's user names");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String name = getRandomString();
		String usertest = name+" "+name;
		String activity = "activity" + getRandomNumber();
		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);
		nav.goToMyProfile();
		info("edit profile");
		click(pepPro.ELEMENT_EDIT_MY_PROFILE_LINK);
		info("edit info");
		pepPro.updateBasicInformation(name, name, null);
		pepPro.saveCancelUpdateInfo(true);

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);
		/*
		- Connect to Intranet with the User A
		- Share an activity
		- Move the mouse over the username link
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity message		*/
		acc.signIn(username1, password1);
		nav.goToHomePage();
		addActivity(true, activity, false, "");

		acc.userSignIn(userType.PUBLISHER);
		selectFileter("Connections");
		waitForAndGetElement(home.ELEMENT_ACTIVITY_AUTHOR_NAME.replace("${index}","1").replace("${author}", usertest));
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_NAME.replace("${index}","1").replace("${author}", usertest), true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", usertest));
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}",username1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",username1), DEFAULT_TIMEOUT,1,2);
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY.replace("${activity}",activity));
		info("Last activity of user displayes true");
	}

	/**
	 * Case ID:108042.
	 * Test Case Name: Generic popup should be displayed as status type for activity stream's likes.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test09_GenericPopupShouldBeDisplayedAsStatusTypeForActivityStreamsLikes() {
		info("Test 9: Generic popup should be displayed as status type for activity stream's likes");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String activity = "Activity"+getRandomString();
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);

		/*
		- Connect to Intranet
		- Share an activity: input a text in the sharebox
		 *Expected Outcome: 
		- Activity: Status is shared		*/
		acc.signIn(username1, password1);
		nav.goToHomePage();
		addActivity(true, activity, false, "");

		/*
		- Like the activity by the current user
		- Hover on the user's avatar
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: Status		*/ 
		home.likeOrUnlikeActivity(activity);

		acc.userSignIn(userType.PUBLISHER);
		mouseOver(ELEMENT_AVATAR_LIST_LIKER_INDEX.replace("${activityText}", activity).replace("${index}", "1"),true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", usertest));
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}",username1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",username1), DEFAULT_TIMEOUT,1,2);
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY.replace("${activity}",activity));
		info("Last activity of user displayes true");

	}

	/**
	 * Case ID:108043.
	 * Test Case Name: Generic popup should be displayed as status type for activity stream's mentions.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test10_GenericPopupShouldBeDisplayedAsStatusTypeForActivityStreamsMentions() {
		info("Test 10 Generic popup should be displayed as status type for activity stream's mentions");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String activity = "Activity"+getRandomString();
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);
		nav.goToHomePage();
		addActivity(true, activity, false, "");

		/*
		- Connect to Intranet
		- Share an activity: add a mention (current user) with the shared text
		 *Expected Outcome: 
		- Activity with mention is shared		*/
		acc.signIn(username1, password1);
		mentionActivity(true,"",user2);
		Utils.pause(1000);

		/*
		- Hover on the current user's mention link
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: text (status)+mention		*/ 
		mouseOver(home.ELEMENT_ACTIVITY.replace("${activityText}",user2), true);		
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", user2));
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}",DATA_USER2), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2), DEFAULT_TIMEOUT,1,2);
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY.replace("${activity}",activity));
		info("Last activity of user displayes true");

		//Detele data test
		home.deleteActivity(user2, true);
		acc.userSignIn(userType.PUBLISHER);
		home.deleteActivity(activity,true);
	}

	/**
	 * Case ID:108044.
	 * Test Case Name: Generic popup should be displayed as status type for activity stream's avatar.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test11_GenericPopupShouldBeDisplayedAsStatusTypeForActivityStreamsAvatar() {
		info("Test 11 Generic popup should be displayed as status type for activity stream's avatar");
		String activity = "Activity"+getRandomString();
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);
		
		/*
		- Connect to Intranet
		- Share an activity
		 *Expected Outcome: 
		- Activity with status is shared		*/
		acc.signIn(username1, password1);
		addActivity(true, activity, false, "");
		Utils.pause(1000);

		/*
		- Hover on the current user's avatar in the timeline
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: Status		*/ 
		acc.userSignIn(userType.PUBLISHER);
		selectFileter("Connections");
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_AVATAR.replace("${index}","1").replace("${author}", usertest), true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", usertest));
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY.replace("${activity}",activity));
		info("Last activity of user displayes true");
	}

	/**
	 * Case ID:108045.
	 * Test Case Name: Generic popup should be displayed as status type for activity stream's username.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test12_GenericPopupShouldBeDisplayedAsStatusTypeForActivityStreamsUsername() {
		info("Test 12 Generic popup should be displayed as status type for activity stream's username");
		String activity = "Activity 108045";
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);
		
		/*
		- Connect to Intranet
		- Share an activity
		 *Expected Outcome: 
		- Activity with status is shared		*/
		acc.signIn(username1, password1);
		addActivity(true, activity, false, "");
		Utils.pause(1000);

		/*
		- Hover on the current username link
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: Status		*/ 
		acc.userSignIn(userType.PUBLISHER);
		selectFileter("Connections");
		waitForAndGetElement(home.ELEMENT_ACTIVITY_AUTHOR_NAME.replace("${index}","1").replace("${author}", usertest));
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_NAME.replace("${index}","1").replace("${author}", usertest), true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", usertest));
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY.replace("${activity}",activity));
		info("Last activity of user displayes true");
	}

	/**
	 * Case ID:108048.
	 * Test Case Name: Generic popup should be displayed as File Sharing type for activity stream's avatar.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test 
	public  void test13_GenericPopupShouldBeDisplayedAsFileSharingTypeForActivityStreamsAvatar() {
		info("Test 13 Generic popup should be displayed as File Sharing type for activity stream's avatar");
		String uploadFileName = "French.docx";
		String folder = "folder108048";
		String driverName = "Personal Drives";
		String folderPath = "Personal Documents";
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);
		
		/*
		- Connect to Intranet
		- Input a text in the shared box
		- Attach a file
		- Click on button "Share"
		 *Expected Outcome: 
		- The File is shared in the activity stream		*/
		acc.signIn(username1, password1);
		nav.goToHomePage();
		selectFile(driverName,true,folderPath,"",uploadFileName,folder);

		/*
		- Hover on the current user's avatar in the timeline
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: FileName		*/ 
		acc.userSignIn(userType.PUBLISHER);
		selectFileter("Connections");
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_AVATAR.replace("${index}","1").replace("${author}", usertest), true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", usertest));
		info("Last activity of user displayes true");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY.replace("${activity}",uploadFileName));
	}	

	/**
	 * Case ID:108049.
	 * Test Case Name: Generic popup should be displayed as File sharing type for activity stream's likes.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 * Bug: https://jira.exoplatform.org/browse/PLF-6024
	 */
	@Test 
	public  void test14_GenericPopupShouldBeDisplayedAsFileSharingTypeForActivityStreamsLikes() {
		info("Test 14 Generic popup should be displayed as File sharing type for activity stream's likes");
		String uploadFileName = "French.docx";
		String folder = "folder108049";
		String driverName = "Personal Drives";
		String folderPath = "Personal Documents";
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);
		
		/*
		- Connect to Intranet
		- Attach a file
		- Click on the button "Share"
		 *Expected Outcome: 
		- Activity: File is shared		*/
		acc.signIn(username1, password1);
		nav.goToHomePage();
		selectFile(driverName,true,folderPath,"",uploadFileName,folder);

		/*
		- Like the activity by the current user
		- Hover on the user's avatar
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: File		*/ 
		home.likeOrUnlikeActivity(uploadFileName);
		
		acc.userSignIn(userType.PUBLISHER);
		selectFileter("Connections");
		String elem = "//*[@href='/portal/intranet/profile/"+username1+"']//*[@alt='"+usertest+"']";
		mouseOver(elem, true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", usertest));
		info("Last activity of user displayes true");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY.replace("${activity}",uploadFileName));

		//Delete date test
		nav.goToHomePage();
		home.deleteActivity(uploadFileName, true);
		nav.goToSiteExplorer();
		act.chooseDrive(ecms.ELEMENT_PERSONAL_DRIVE);
		act.actionsOnElement(folder, actionType.DELETE,true,true);
	}

	/**
	 * Case ID:108050.
	 * Test Case Name: Generic popup should be displayed as File sharing type for activity stream's mentions.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 * Bug: https://jira.exoplatform.org/browse/PLF-5844
	 */
	@Test 
	public  void test15_GenericPopupShouldBeDisplayedAsFileSharingTypeForActivityStreamsMentions() {
		info("Test 15 Generic popup should be displayed as File sharing type for activity stream's mentions");
		String uploadFileName = "French.docx";
		String folder = "folder108050";
		String driverName = "Personal Drives";
		String folderPath = "Personal Documents";
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);
		
		/*
		- Connect to Intranet
		- Attach a file + mention
		- Click "Share"
		 *Expected Outcome: 
		- Activity with File is shared		*/
		acc.signIn(username1, password1);
		info ("-- Adding a mention activity --");	
		WebElement inputText = waitForAndGetElement(home.ELEMENT_ACTIVITY_TEXTBOX, DEFAULT_TIMEOUT, 1, 2);
		((JavascriptExecutor)driver).executeScript("arguments[0].style.display = 'block'; arguments[0].style.visibility = 'visible'", inputText);
		Utils.pause(1000);
		click(ELEMENT_MENTION_USER_BUTTON);
		inputText.sendKeys(usertest);
		click(ELEMENT_MENTION_USER_AVATAR.replace("${userName}", usertest));
		Utils.pause(1000);
		click(home.ELEMENT_ACTIVITY_TEXTBOX);
		Utils.pause(1000);	
		selectFile(driverName,true,folderPath,"",uploadFileName,folder);

		/*
		- Hover on the current user's mention link
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: File sharing+mention		*/ 
		acc.userSignIn(userType.PUBLISHER);
		selectFileter("Connections");
		mouseOver(home.ELEMENT_ACTIVITY.replace("${activityText}",usertest), true);		
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", usertest));
		info("Last activity of user displayes true");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY.replace("${activity}",usertest));
	}

	/**
	 * Case ID:108051.
	 * Test Case Name: Generic popup should be displayed as File sharing type for activity stream's username.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 * Bug: https://jira.exoplatform.org/browse/COMMONS-278
	 */
	@Test 
	public  void test16_GenericPopupShouldBeDisplayedAsFileSharingTypeForActivityStreamsUsername() {
		info("Test 16 Generic popup should be displayed as File sharing type for activity stream's username");
		String uploadFileName = "French.docx";
		String folder = "folder108051";
		String driverName = "Personal Drives";
		String folderPath = "Personal Documents";
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);
		
		/*
		- Connect to Intranet
		- Share a File
		 *Expected Outcome: 
		- Activity with File is shared		*/
		acc.signIn(username1, password1);
		nav.goToHomePage();
		selectFile(driverName,true,folderPath,"",uploadFileName,folder);

		/*
		- Hover on the current username link
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: File		*/ 
		acc.userSignIn(userType.PUBLISHER);
		selectFileter("Connections");
		String elem = "//*[@href='/portal/intranet/profile/"+username1+"']//*[@alt='"+usertest+"']";
		mouseOver(elem, true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", usertest));
		info("Last activity of user displayes true");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY.replace("${activity}",uploadFileName));
	}

	/**
	 * Case ID:108052.
	 * Test Case Name: Generic popup should be displayed as Link Sharing type for activity stream's avatar.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test17_GenericPopupShouldBeDisplayedAsLinkSharingTypeForActivityStreamsAvatar() {
		info("Test 17 Generic popup should be displayed as Link Sharing type for activity stream's avatar");
		String link = "http://yahoo.com";
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);
		/*
		- Connect to Intranet
		- Input a text in the shared box
		- Add a link and click "Attach"
		- Click on button "Share"
		 *Expected Outcome: 
		- The link is shared in the activity stream		*/
		acc.signIn(username1, password1);
		addActivity(false, "", true, link);		

		/*
		- Hover on the current user's avatar in the timeline
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: Link		*/
		acc.userSignIn(userType.PUBLISHER);
		selectFileter("Connections");
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_AVATAR.replace("${index}","1").replace("${author}", usertest), true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", usertest));
		info("Last activity of user displayes true");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY.replace("${activity}","Yahoo"));
	}

	/**
	 * Case ID:108053.
	 * Test Case Name: Generic popup should be displayed as Link sharing type for activity stream's likes.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test18_GenericPopupShouldBeDisplayedAsLinkSharingTypeForActivityStreamsLikes() {
		info("Test 18 Generic popup should be displayed as Link sharing type for activity stream's likes");
		String link = "http://yahoo.com";
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);
		
		/*
		- Connect to Intranet
		- Add a Link and click "Attach"
		- Click on the button "Share"
		 *Expected Outcome: 
		- Activity: Link is shared		*/
		acc.signIn(username1, password1);
		addActivity(false, "", true, link);	

		/*
		- Like the activity by the current user
		- Hover on the user's avatar
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: Link		*/ 
		home.likeOrUnlikeActivity(link);
		
		acc.userSignIn(userType.PUBLISHER);
		selectFileter("Connections");
		String elem = "//*[@href='/portal/intranet/profile/"+username1+"']//*[@alt='"+usertest+"']";
		mouseOver(elem, true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", usertest));
		info("Last activity of user displayes true");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY.replace("${activity}","Yahoo"));
	}

	/**
	 * Case ID:108054.
	 * Test Case Name: Generic popup should be displayed as Link sharing type for activity stream's mentions.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test19_GenericPopupShouldBeDisplayedAsLinkSharingTypeForActivityStreamsMentions() {
		info("Test 19 Generic popup should be displayed as Link sharing type for activity stream's mentions");
		String link = "http://yahoo.com";
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);
		
		/*
		- Connect to Intranet
		- Attach a Link + mention
		- Click "Share"
		 *Expected Outcome: 
		- Activity with Link is shared		*/
		info ("-- Adding a mention activity --");	
		WebElement inputText = waitForAndGetElement(home.ELEMENT_ACTIVITY_TEXTBOX, DEFAULT_TIMEOUT, 1, 2);
		((JavascriptExecutor)driver).executeScript("arguments[0].style.display = 'block'; arguments[0].style.visibility = 'visible'", inputText);
		Utils.pause(1000);
		click(ELEMENT_MENTION_USER_BUTTON);
		inputText.sendKeys(user2);
		click(ELEMENT_MENTION_USER_AVATAR.replace("${userName}", user2));
		Utils.pause(1000);
		click(home.ELEMENT_ACTIVITY_TEXTBOX);
		Utils.pause(1000);	
		addActivity(false, "", true, link);	

		/*
		- Hover on the current user's mention link
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: Link sharing		*/ 
		mouseOver(home.ELEMENT_ACTIVITY.replace("${activityText}",user2), true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", user2));
		info("Last activity of user displayes true");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY.replace("${activity}","Yahoo"));
		Utils.pause(1000);
	}

	/**
	 * Case ID:108055.
	 * Test Case Name: Generic popup should be displayed as Link sharing type for activity stream's username.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test20_GenericPopupShouldBeDisplayedAsLinkSharingTypeForActivityStreamsUsername() {
		info("Test 20 Generic popup should be displayed as Link sharing type for activity stream's username");
		String link = "http://yahoo.com";
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA connect userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);
		
		/*
		- Connect to Intranet
		- Share a Link
		 *Expected Outcome: 
		- Activity with Link is shared		*/
		acc.signIn(username1, password1);
		addActivity(false, "", true, link);	

		/*
		- Hover on the current username link
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic popup is displayed with the last activity posted: Link		*/ 
		acc.userSignIn(userType.PUBLISHER);
		selectFileter("Connections");
		String elem = "//*[@href='/portal/intranet/profile/"+username1+"']//*[@alt='"+usertest+"']";
		mouseOver(elem, true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", usertest));
		info("Last activity of user displayes true");	
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_LAST_ACTIVITY.replace("${activity}","Yahoo"));
	}

	/**
	 * Case ID:108060.
	 * Test Case Name: Generic pop up should be display with "Connect" button in the activity stream's mention.
	 * Pre-Condition: User A and User B are not a connectionUser B is connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test21_GenericPopUpShouldBeDisplayWithConnectButtonInTheActivityStreamsMention() {
		info("Test 21 Generic pop up should be display with Connect button in the activity stream's mention");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/

		/*
		- Connect to Intranet with the User B
		- Share an activity where User A is mentionned
		 *Input Data: 
		 *Expected Outcome: 
		- The activity is shared with Username A link		*/
		acc.userSignIn(userType.PUBLISHER);
		mentionActivity(true, "", usertest);

		/*
		- Move the mouse over the username link
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Connect" is displayed		*/
		mouseOver(home.ELEMENT_ACTIVITY.replace("${activityText}",usertest), true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", usertest));
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}",username1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",username1), DEFAULT_TIMEOUT,1,2);
		info("Button [Connect] is displayed");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Connect"));
		Utils.pause(1000);

		/*
		- Click on the button "Connect"
		 *Input Data: 
		 *Expected Outcome: Button is changed to Cancel Request		*/ 
		click(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Connect"));
		mouseOver(home.ELEMENT_ACTIVITY.replace("${activityText}",usertest), true);
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Cancel Request"));

		//Delete data test
		nav.goToHomePage();
		home.deleteActivity(usertest, true);
	}

	/**
	 * Case ID:108061.
	 * Test Case Name: Generic pop up should be display with "Connect" button in the activity stream's Like.
	 * Pre-Condition: User A and User B are member of a space, User B is connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test22_GenericPopUpShouldBeDisplayWithConnectButtonInTheActivityStreamsLike() {
		info("Test 22 Generic pop up should be display with Connect button in the activity stream's Like");
		String activity1 = "Activity 1080611A";
		String activity2 = "Activity 1080611B";
		String spaceName = "Space1080614";
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("User A & B is member of Space1");
		mSpace.goToAllSpaces();
		mSpace.addNewSpace(spaceName,"");
		addActivity(true, activity1, false, "");
		goToMembers(spaceName);
		mMember.inviteSingleUser(userType.PUBLISHER);

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/
		acc.userSignIn(userType.PUBLISHER);
		mMember.acceptInvitation(spaceName);
		mSpace.accessSpace(spaceName);
		addActivity(true, activity2, false, "");

		/*
		- Connect to Intranet with the User B 		
		- Share an activity
		- Like the activity of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- Activity is shared and Liked		*/
		acc.signIn(username1, password1);
		nav.goToHomePage();
		selectFileter("My Spaces");
		home.likeOrUnlikeActivity(activity2);

		/*
		- Open the User A's session
		- Move the mouse over the Liker Avatar (User B)
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Connect" is displayed		*/
		acc.userSignIn(userType.PUBLISHER);
		mouseOver(ELEMENT_AVATAR_LIST_LIKER_INDEX.replace("${activityText}", activity2).replace("${index}", "1"),true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", usertest));
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}",username1), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",username1), DEFAULT_TIMEOUT,1,2);
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Connect"));

		/*
		- Click on the button "Connect"
		 *Input Data: 
		 *Expected Outcome: 
		- The State of the button changes to show a connection request was sent.		*/ 
		click(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Connect"));
		Utils.pause(1000);
		mouseOver(ELEMENT_AVATAR_LIST_LIKER_INDEX.replace("${activityText}", activity2).replace("${index}", "1"),true);
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Cancel Request"));

		//Delete data test
		acc.signIn(username1, password1);
		goToAllSpaces();
		mSpace.deleteSpace(spaceName, 300000);
	}

	/**
	 * Case ID:108062.
	 * Test Case Name: Generic pop up should be display with "Connect" button in the activity stream's avatar.
	 * Pre-Condition: User A and User B are member of Space1, User B is connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test23_GenericPopUpShouldBeDisplayWithConnectButtonInTheActivityStreamsAvatar() {
		info("Test 23 Generic pop up should be display with Connect button in the activity stream's avatar");

		String spaceName = "Space108062";
		String activity = "Activity 108062";
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("User A & B is member of Space1");
		mSpace.goToAllSpaces();
		mSpace.addNewSpace(spaceName,"");
		goToMembers(spaceName);
		mMember.inviteSingleUser(userType.PUBLISHER);

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/
		acc.userSignIn(userType.PUBLISHER);
		mMember.acceptInvitation(spaceName);
		mSpace.accessSpace(spaceName);
		addActivity(true, activity, false, "");	

		/*
		- Connect to Intranet with the User B
		- Move the mouse over the Avatar (User A)
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Connect" is displayed		*/
		acc.signIn(username1, password1);
		mSpace.accessSpace(spaceName);
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_AVATAR.replace("${index}","1").replace("${author}", user2), true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", user2));
		info("Confirm user avatar");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}",DATA_USER2), DEFAULT_TIMEOUT,1,2);
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2), DEFAULT_TIMEOUT,1,2);
		info("Button [Connect] is displayed");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Connect"), DEFAULT_TIMEOUT,1,2);
		Utils.pause(1000);

		/*
		- Click on the button "Connect"
		 *Input Data: 
		 *Expected Outcome: 
		- The State of the button changes to show a connection request was sent.		*/ 
		click(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Connect"), DEFAULT_TIMEOUT,1,2);
		Utils.pause(1000);
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_AVATAR.replace("${index}","1").replace("${author}", user2), true);
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Cancel Request"), DEFAULT_TIMEOUT,1,2);

		acc.signIn(username1, password1);
		goToAllSpaces();
		mSpace.deleteSpace(spaceName, 300000);
	}

	/**
	 * Case ID:108063.
	 * Test Case Name: Generic pop up should be display with "Connect" button in the activity stream's username.
	 * Pre-Condition: User A and User B are member of Space1 User B is connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test24_GenericPopUpShouldBeDisplayWithConnectButtonInTheActivityStreamsUsername() {
		info("Test 24 Generic pop up should be display with Connect button in the activity stream's username");
		String activity = "Activity 108063";
		String spaceName = "Space108063";
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("User A & B is member of Space1");
		mSpace.goToAllSpaces();
		mSpace.addNewSpace(spaceName,"");
		goToMembers(spaceName);
		mMember.inviteSingleUser(userType.PUBLISHER);

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/
		acc.userSignIn(userType.PUBLISHER);
		mMember.acceptInvitation(spaceName);
		mSpace.accessSpace(spaceName);
		addActivity(true, activity, false, "");	

		/*
		- Connect to Intranet with the User B in other browser
		- Move the mouse over the username A
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Connect" is displayed		*/
		acc.signIn(username1, password1);
		mSpace.accessSpace(spaceName);
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_NAME.replace("${index}","1").replace("${author}", user2), true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", user2));
		info("Confirm user name");
		waitForAndGetElement(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2), DEFAULT_TIMEOUT,1,2);
		info("Button [Connect] is displayed");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Connect"), DEFAULT_TIMEOUT,1,2);
		Utils.pause(1000);

		/*
		- Click on the button "Connect"
		 *Input Data: 
		 *Expected Outcome: 
		- The State of the button changes to show a connection request was sent.		*/ 
		click(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Connect"));
		Utils.pause(1000);
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_NAME.replace("${index}","1").replace("${author}", user2), true);
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Cancel Request"));

		acc.signIn(username1, password1);
		goToAllSpaces();
		mSpace.deleteSpace(spaceName, 300000);
	}

	/**
	 * Case ID:108066.
	 * Test Case Name: Generic pop up should be display with "Confirm" button in the activity stream's avatar.
	 * Pre-Condition: User B has received an invitation from the User A User A and B are connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test25_GenericPopUpShouldBeDisplayWithConfirmButtonInTheActivityStreamsAvatar() {
		info("Test 25 Generic pop up should be display with Confirm button in the activity stream's avatar");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/
		nav.goToHomePage();
		mentionActivity(true, "", user2);	

		/*
		- Connect to Intranet with the User B 
		- Move the mouse over the Avatar (User A)
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Confirm" is displayed		*/
		acc.userSignIn(userType.PUBLISHER);
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_AVATAR.replace("${index}","1").replace("${author}", usertest), true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", usertest));
		info("Button [Connect] is displayed");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Confirm"), DEFAULT_TIMEOUT,1,2);
		Utils.pause(1000);
	}

	/**
	 * Case ID:108067.
	 * Test Case Name: Generic pop up should be display with "Confirm" button in the activity stream's Like.
	 * Pre-Condition: User B has received an invitation from the User A User B is connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test26_GenericPopUpShouldBeDisplayWithConfirmButtonInTheActivityStreamsLike() {
		info("Test 26 Generic pop up should be display with Confirm button in the activity stream's Like");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/
		acc.userSignIn(userType.PUBLISHER);
		nav.goToHomePage();
		mentionActivity(true, "", usertest);	

		/*
		- Connect to Intranet with the User B
		- Share an activity
		- Like the activity of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- Activity is shared and Liked		*/
		acc.signIn(username1, password1);
		nav.goToHomePage();
		home.likeOrUnlikeActivity(usertest);

		/*
		- Open the User A's session
		- Move the mouse over the Liker Avatar (User B)
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Confirm" is displayed		*/ 
		acc.userSignIn(userType.PUBLISHER);
		waitForAndGetElement(ELEMENT_AVATAR_LIST_LIKER_INDEX.replace("${activityText}", username1).replace("${index}", "1"));
		mouseOver(ELEMENT_AVATAR_LIST_LIKER_INDEX.replace("${activityText}", username1).replace("${index}", "1"),true);
		info("Button [Connect] is displayed");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Confirm"), DEFAULT_TIMEOUT,1,2);
		Utils.pause(1000);
	}

	/**
	 * Case ID:108068.
	 * Test Case Name: Generic pop up should be display with "Confirm" button in the activity stream's mention.
	 * Pre-Condition: User B has received an invitation from the User A User B is connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test27_GenericPopUpShouldBeDisplayWithConfirmButtonInTheActivityStreamsMention() {
		info("Test 27 Generic pop up should be display with Confirm button in the activity stream's mention");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/

		/*
		- Connect to Intranet with the User B 
		- Share an activity where User A is mentionned
		 *Input Data: 
		 *Expected Outcome: 
		- The activity is shared with Username A link		*/
		info("User A & B is member of Space1");
		acc.userSignIn(userType.PUBLISHER);
		nav.goToHomePage();
		mentionActivity(true, "", usertest);	

		/*
		- Move the mouse over the username link
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Confirm" is displayed		*/ 
		mouseOver(home.ELEMENT_ACTIVITY.replace("${activityText}",usertest), true);		
		info("Button [Connect] is displayed");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Confirm"), DEFAULT_TIMEOUT,1,2);
		Utils.pause(1000);
	}

	/**
	 * Case ID:108069.
	 * Test Case Name: Generic pop up should be display with "Confirm" button in the activity stream's username.
	 * Pre-Condition: User B has received an invitation from the User AUser B is connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test28_GenericPopUpShouldBeDisplayWithConfirmButtonInTheActivityStreamsUsername() {
		info("Test 28 Generic pop up should be display with Confirm button in the activity stream's username");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		nav.goToHomePage();
		mentionActivity(true, "", user2);	

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/

		/*
		- Connect to Intranet with the User B 
		- Move the mouse over the username A
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Confirm" is displayed		*/ 
		acc.userSignIn(userType.PUBLISHER);
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_NAME.replace("${index}","1").replace("${author}", usertest), true);
		info("Button [Connect] is displayed");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Confirm"), DEFAULT_TIMEOUT,1,2);
		Utils.pause(1000);
	}

	/**
	 * Case ID:108072.
	 * Test Case Name: Generic pop up should be display with "Cancel Request" button in the activity stream's avatar.
	 * Pre-Condition: User A has received an invitation from the User B User B is connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test29_GenericPopUpShouldBeDisplayWithCancelRequestButtonInTheActivityStreamsAvatar() {
		info("Test 29 Generic pop up should be display with Cancel Request button in the activity stream's avatar");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/
		info("User A & B is member of Space1");
		acc.userSignIn(userType.PUBLISHER);
		nav.goToHomePage();
		mentionActivity(true, "", usertest);	

		/*
		- Connect to Intranet with the User B
		- Move the mouse over the avatar of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Cancel Request" is displayed		*/ 
		acc.signIn(username1, password1);
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_AVATAR.replace("${index}","1").replace("${author}", user2), true);	
		info("Button [Connect] is displayed");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Cancel Request"), DEFAULT_TIMEOUT,1,2);
		Utils.pause(1000);
	}

	/**
	 * Case ID:108073.
	 * Test Case Name: Generic pop up should be display with "Cancel Request" button in the activity stream's Like.
	 * Pre-Condition: User A has received an invitation from the User BUser B is connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test30_GenericPopUpShouldBeDisplayWithCancelRequestButtonInTheActivityStreamsLike() {
		info("Test 30 Generic pop up should be display with Cancel Request button in the activity stream's Like");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		nav.goToHomePage();
		mentionActivity(true, "", user2);

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/

		/*
		- Connect to Intranet with the User B 
		- Share an activity
		- Like the activity of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- Activity is shared and Liked		*/	
		acc.userSignIn(userType.PUBLISHER);
		home.likeOrUnlikeActivity(user2);

		/*
		- Open the User A's session
		- Move the mouse over the Liker Avatar (User B)
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Cancel Request" is displayed		*/
		acc.signIn(username1, password1);
		waitForAndGetElement(ELEMENT_AVATAR_LIST_LIKER_INDEX.replace("${activityText}", user2.substring(user2.indexOf(" ")+1)).replace("${index}", "1"));
		mouseOver(ELEMENT_AVATAR_LIST_LIKER_INDEX.replace("${activityText}", user2.substring(user2.indexOf(" ")+1)).replace("${index}", "1"),true);
		info("Button [Connect] is displayed");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Cancel Request"), DEFAULT_TIMEOUT,1,2);
	}

	/**
	 * Case ID:108074.
	 * Test Case Name: Generic pop up should be display with "Cancel Request" button in the activity stream's mention.
	 * Pre-Condition: User A has received an invitation from the User B User B is connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test31_GenericPopUpShouldBeDisplayWithCancelRequestButtonInTheActivityStreamsMention() {
		info("Test 31 Generic pop up should be display with Cancel Request button in the activity stream's mention");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/

		/*
		- Connect to Intranet with the User B
		- Share an activity where User A is mentionned
		 *Input Data: 
		 *Expected Outcome: 
		- The activity is shared with Username A link		*/
		nav.goToHomePage();
		mentionActivity(true, "", user2);

		/*
		- Move the mouse over the username link
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Cancel Request" is displayed		*/ 
		mouseOver(home.ELEMENT_ACTIVITY.replace("${activityText}",user2), true);		
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", user2));
		info("Button [Connect] is displayed");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Cancel Request"), DEFAULT_TIMEOUT,1,2);
	}

	/**
	 * Case ID:108075.
	 * Test Case Name: Generic pop up should be display with "Cancel Request" button in the activity stream's username.
	 * Pre-Condition: User A has received an invitation from the User B User B is connected to Intranet User B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test32_GenericPopUpShouldBeDisplayWithCancelRequestButtonInTheActivityStreamsUsername() {
		info("Test 32 Generic pop up should be display with Cancel Request button in the activity stream's username");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);


		/*- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared	*/	
		acc.userSignIn(userType.PUBLISHER);
		nav.goToHomePage();
		mentionActivity(true, "", usertest);


		/*	- Connect to Intranet with the User B 
		- Move the mouse over the username A
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Cancel Request" is displayed	*/	 
		acc.signIn(username1, password1);
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_NAME.replace("${index}","1").replace("${author}", user2), true);
		info("Button [Connect] is displayed");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Cancel Request"), DEFAULT_TIMEOUT,1,2);
		Utils.pause(1000);
	}

	/**
	 * Case ID:108078.
	 * Test Case Name: Generic pop up should be display with "Remove Connection" button in the activity stream's avatar.
	 * Pre-Condition: User A and User B are already a connection User A and User B are connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test33_GenericPopUpShouldBeDisplayWithRemoveConnectionButtonInTheActivityStreamsAvatar() {
		info("Test 33 Generic pop up should be display with Remove Connection button in the activity stream's avatar");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;

		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);
		nav.goToHomePage();
		mentionActivity(true, "", usertest);

		/*
		- Connect to Intranet with the User B
		- Move the mouse over the avatar of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Remove Connection" is displayed		*/ 
		acc.signIn(username1, password1);
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_AVATAR.replace("${index}","1").replace("${author}", user2), true);	
		info("Button [Connect] is displayed");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Remove Connection"), DEFAULT_TIMEOUT,1,2);
	}

	/**
	 * Case ID:108079.
	 * Test Case Name: Generic pop up should be display with "Remove Connection" button in the activity stream's Like.
	 * Pre-Condition: User A and User B are already a connectionUser A and User B are connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test34_GenericPopUpShouldBeDisplayWithRemoveConnectionButtonInTheActivityStreamsLike() {
		info("Test 34 Generic pop up should be display with Remove Connection button in the activity stream's Like");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;
		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		but.ok();
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);

		acc.signIn(username1, password1);
		nav.goToHomePage();
		mentionActivity(true, "", user2);	

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/

		/*
		- Connect to Intranet with the User B 
		- Share an activity
		- Like the activity of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- Activity is shared and Liked		*/
		acc.userSignIn(userType.PUBLISHER);
		nav.goToHomePage();
		home.likeOrUnlikeActivity(user2);

		/*
		- Open the User A's session
		- Move the mouse over the Liker Avatar (User B)
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Remove Connection" is displayed		*/ 
		acc.signIn(username1, password1);
		waitForAndGetElement(ELEMENT_AVATAR_LIST_LIKER_INDEX.replace("${activityText}", user2.substring(user2.indexOf(" ")+1)).replace("${index}", "1"));
		mouseOver(ELEMENT_AVATAR_LIST_LIKER_INDEX.replace("${activityText}", user2.substring(user2.indexOf(" ")+1)).replace("${index}", "1"),true);
		info("Button [Connect] is displayed");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Remove Connection"), DEFAULT_TIMEOUT,1,2);

	}

	/**
	 * Case ID:108080.
	 * Test Case Name: Generic pop up should be display with "Remove Connection" button in the activity stream's mention.
	 * Pre-Condition: User A and User B are already a connectionUser A and User B are connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test35_GenericPopUpShouldBeDisplayWithRemoveConnectionButtonInTheActivityStreamsMention() {
		info("Test 35 Generic pop up should be display with Remove Connection button in the activity stream's mention");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;
		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);

		/*
		- Connect to Intranet with the User B
		- Share an activity where User A is mentionned
		 *Input Data: 
		 *Expected Outcome: 
		- The activity is shared with Username A link		*/
		nav.goToHomePage();
		mentionActivity(true, "", usertest);

		/*
		- Move the mouse over the username link
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Remove Connection" is displayed		*/ 
		mouseOver(home.ELEMENT_ACTIVITY.replace("${activityText}",usertest), true);		
		info("Button [Connect] is displayed");
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Remove Connection"), DEFAULT_TIMEOUT,1,2);
		Utils.pause(1000);
	}

	/**
	 * Case ID:108081.
	 * Test Case Name: Generic pop up should be display with "Remove Connection" button in the activity stream's username.
	 * Pre-Condition: User A and User B are already a connectionUser A and User B are connected to IntranetUser B shared an activity in her activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test36_GenericPopUpShouldBeDisplayWithRemoveConnectionButtonInTheActivityStreamsUsername() {
		info("Test 36 Generic pop up should be display with Remove Connection button in the activity stream's username");
		String username1 = getRandomString();
		String password1 = username1;
		String email1 = username1+"@gmail.com";
		String usertest = username1+" "+username1;
		info("User update profile");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, username1, username1, null, email1, null, null,false);
		acc.signIn(username1, password1);

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(usertest);

		/*
		- Connect to Intranet with the User A
		- Share an activity 
		 *Expected Outcome: 
		- The activity is shared		*/
		nav.goToHomePage();
		mentionActivity(true, "", usertest);

		/*
		- Connect to Intranet with the User B in other browser
		- Move the mouse over the username A
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed* avatar* name* title (or position in the company) if defined* last activity title* The boutton "Remove Connection" is displayed		*/ 
		acc.signIn(username1, password1);
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_NAME.replace("${index}","1").replace("${author}", user2), true);	
		waitForAndGetElement(hg.ELEMENT_USER_POPUP_STATUS_CONNECT.replace("${status}", "Remove Connection"), DEFAULT_TIMEOUT,1,2);
		Utils.pause(1000);
	}

	/**
	 * Case ID:108084.
	 * Test Case Name: User's activity should be displayed after click on the username on generic pop up of activity stream's avatars.
	 * Pre-Condition: User A and User B are a connection User A and User B are connected to Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test37_UsersActivityShouldBeDisplayedAfterClickOnTheUsernameOnGenericPopUpOfActivityStreamsAvatars() {
		info("Test 37 User's activity should be displayed after click on the username on generic pop up of activity stream's avatars");
		String activity = "Activity 108084";

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);

		/*
		- Connect to Intranet with the User A
		- Share an activity
		 *Expected Outcome: 
		- Activity of the User A is shared		*/
		nav.goToHomePage();
		addActivity(true, activity, false, "");

		/*
		- Connect to Intranet with User B
		- Mouve the mouse on the avatar of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic pop up is displayed		*/
		acc.userSignIn(userType.ADMIN);
		nav.goToHomePage();
		selectFileter("Connections");
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_AVATAR.replace("${index}","1").replace("${author}", user2), true);	
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", user2));

		/*
		- From the pop up, Click on the name of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- The User B is redirected to the User A's activity stream		*/ 
		click(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2));
		Utils.pause(1000);
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER2)), DEFAULT_TIMEOUT,1,2);

		//Delete data test
		nav.goToConnectionPage();
		pConnect.removeConnection(user2);

		acc.userSignIn(userType.PUBLISHER);
		home.deleteActivity(activity);
	}

	/**
	 * Case ID:108085.
	 * Test Case Name: User's activity should be displayed after click on the username on generic pop up of activity stream's likes.
	 * Pre-Condition: User A and User B are a connectionUser A and User B are connected to IntranetUser B share an activity
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test38_UsersActivityShouldBeDisplayedAfterClickOnTheUsernameOnGenericPopUpOfActivityStreamsLikes() {
		info("Test 38 User's activity should be displayed after click on the username on generic pop up of activity stream's likes");
		String activity1 = "Activity 108085A";
		String activity2 = "Acvitity 108085B";

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);	

		/*
		- Connect to Intranet with the User A
		- Share an activity
		 *Expected Outcome: 
		- The activity is shared		*/
		nav.goToHomePage();
		addActivity(true, activity1, false, "");

		/*
		- Connect to Intranet with the User B
		- Like the activity shared by the User A
		 *Input Data: 
		 *Expected Outcome: 
		- The activity of the User A is liked		*/
		acc.userSignIn(userType.ADMIN);
		addActivity(true, activity2, false, "");
		selectFileter("Connections");
		home.likeOrUnlikeActivity(activity1);

		/*
		- Open the User A's session
		- From the liked activity, Move the mouse over the User B's avatar 
		 *Input Data: 
		 *Expected Outcome: 
		- A Generic pop up information is displayed	*/
		acc.userSignIn(userType.PUBLISHER);
		selectFileter("My Activities");
		Utils.pause(1000);
		String avatarName = waitForAndGetElement(ELEMENT_AVATAR_LIST_LIKER_INDEX.replace("${activityText}", activity1).replace("${index}", "1")).getAttribute("alt");
		assert(avatarName.contains(user1));
		mouseOver(ELEMENT_AVATAR_LIST_LIKER_INDEX.replace("${activityText}", activity1).replace("${index}", "1"),true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", user1));

		/*
		-From the Generic pop up, click on the name of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- The User A is redirected to the activity stream of the User B		*/ 
		click(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1));
		Utils.pause(1000);
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER1)), DEFAULT_TIMEOUT,1,2);

		//Delete data test
		nav.goToHomePage();
		home.deleteActivity(activity1);
		nav.goToConnectionPage();
		pConnect.removeConnection(user1);

		acc.userSignIn(userType.ADMIN);
		selectFileter("All Activities");
		home.deleteActivity(activity2);
	}

	/**
	 * Case ID:108086.
	 * Test Case Name: User's activity should be displayed after click on the username on generic pop up of activity stream's mentions.
	 * Pre-Condition: User A and User B are a connectionUser A and User B are connected to Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test39_UsersActivityShouldBeDisplayedAfterClickOnTheUsernameOnGenericPopUpOfActivityStreamsMentions() {
		info("Test 39 User's activity should be displayed after click on the username on generic pop up of activity stream's mentions");
		String activity = "Activity 108086";

		/*
		- Connect to Intranet with the User A
		- Shared an activity
		 *Expected Outcome: 
		- The username of the User B is displayed in the activity		*/
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		nav.goToHomePage();
		addActivity(true, activity, false, "");

		/*
		- Connect to Intranet with the User B 
		- Share an activity where User A is mentionned
		 *Input Data: 
		 *Expected Outcome: 
		- The activity is shared
		- The mentionned user is displayed as a link		*/
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);	
		nav.goToHomePage();
		mentionActivity(true, "", user1);

		/*
		- Move the mouse over the username link
		 *Input Data: 
		 *Expected Outcome: 
		- A Generic pop up information is displayed	*/
		mouseOver(home.ELEMENT_ACTIVITY.replace("${activityText}",user1), true);		
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", user1));

		/*
		- From the Generic pop up, Click on the name of the user A
		 *Input Data: 
		 *Expected Outcome: 
		- The User B is redirected to the User A's activity		*/ 
		click(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER1));
		Utils.pause(1000);
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER1)), DEFAULT_TIMEOUT,1,2);

		//Delete data test
		nav.goToHomePage();
		home.deleteActivity(user1, true);
		nav.goToConnectionPage();
		pConnect.removeConnection(user1);

		acc.userSignIn(userType.ADMIN);
		home.deleteActivity(activity, true);
	}

	/**
	 * Case ID:108087.
	 * Test Case Name: User's activity should be displayed after click on the username on generic pop up of activity stream's user names.
	 * Pre-Condition: User A and User B are a connectionUser A and User B are connected to Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test40_UsersActivityShouldBeDisplayedAfterClickOnTheUsernameOnGenericPopUpOfActivityStreamsUserNames() {
		info("Test 40 User's activity should be displayed after click on the username on generic pop up of activity stream's user names");
		String activity = "Activity 108087";

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);

		/*
		- Connect to Intranet with the User A
		- Share an activity
		 *Expected Outcome: 
		- The activity of the User A is shared		*/
		nav.goToHomePage();
		addActivity(true, activity, false, "");

		/*
		- Connect to Intranet with the User B
		 *Input Data: 
		 *Expected Outcome: 
		- The activity of the User A is shared in the activity Stream		*/
		/*
		- Mouve the mouse of the username (User A) link
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed*/
		acc.userSignIn(userType.ADMIN);
		nav.goToHomePage();
		selectFileter("Connections");
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_NAME.replace("${index}","1").replace("${author}", user2), true);	
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", user2));

		/*
		- From the Generic pop up, click on the name of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- The User B is redirecred to the activity stream of the User A		*/ 
		click(hg.ELEMENT_ONLINE_USER_TITLE.replace("${acc}",DATA_USER2));
		Utils.pause(1000);
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER2)), DEFAULT_TIMEOUT,1,2);

		//Delete data test
		nav.goToConnectionPage();
		pConnect.removeConnection(user2);

		acc.userSignIn(userType.PUBLISHER);
		home.deleteActivity(activity);
	}

	/**
	 * Case ID:108092.
	 * Test Case Name: User's activity should be displayed after click on User's avatar on generic pop up of activity stream's likes.
	 * Pre-Condition: User A and User B are a connectionUser A and User B are connected to IntranetUser B share an activity
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test41_UsersActivityShouldBeDisplayedAfterClickOnUsersAvatarOnGenericPopUpOfActivityStreamsLikes() {
		info("Test 41 User's activity should be displayed after click on User's avatar on generic pop up of activity stream's likes");
		String activity1 = "Activity 108092A1";
		String activity2 = "Acvitity 108092B1";

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);

		/*
		- Connect to Intranet with the User A
		- Share an activity
		 *Expected Outcome: 
		- The activity is shared		*/
		nav.goToHomePage();
		addActivity(true, activity1, false, "");

		/*
		- Connect to Intranet with the User B
		- Like the activity shared by the User A
		 *Input Data: 
		 *Expected Outcome: 
		- The activity of the User A is liked		*/
		acc.userSignIn(userType.ADMIN);
		addActivity(true, activity2, false, "");
		selectFileter("Connections");
		home.likeOrUnlikeActivity(activity1);

		/*
		- Open the User A's session
		- From the liked activity, Move the mouse over the User B's avatar 
		 *Input Data: 
		 *Expected Outcome: 
		- A Generic pop up information is displayed*/
		acc.userSignIn(userType.PUBLISHER);
		selectFileter("My Activities");
		Utils.pause(1000);
		String avatarName = waitForAndGetElement(ELEMENT_AVATAR_LIST_LIKER_INDEX.replace("${activityText}", activity1).replace("${index}", "1")).getAttribute("alt");
		assert(avatarName.contains(user1));
		mouseOver(ELEMENT_AVATAR_LIST_LIKER_INDEX.replace("${activityText}", activity1).replace("${index}", "1"),true);
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", user1));

		/*
		-From the Generic pop up, click on the User's avatar of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- The User A is redirected to the activity stream of the User B		*/ 
		click(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}",DATA_USER1));
		Utils.pause(1000);
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER1)), DEFAULT_TIMEOUT,1,2);

		//Delete data test
		nav.goToHomePage();
		home.deleteActivity(activity1);
		nav.goToConnectionPage();
		pConnect.removeConnection(user1);

		acc.userSignIn(userType.ADMIN);
		selectFileter("All Activities");
		home.deleteActivity(activity2);
	}

	/**
	 * Case ID:108093.
	 * Test Case Name: User's activity should be displayed after click on User's avatar on generic pop up of activity stream's avatars.
	 * Pre-Condition: User A and User B are a connectionUser A and User B are connected to Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test42_UsersActivityShouldBeDisplayedAfterClickOnUsersAvatarOnGenericPopUpOfActivityStreamsAvatars() {
		info("Test 42 User's activity should be displayed after click on User's avatar on generic pop up of activity stream's avatars");
		String activity = "Activity 108093";

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);

		/*
		- Connect to Intranet with the User A
		- Share an activity
		 *Expected Outcome: 
		- Activity of the User A is shared		*/
		nav.goToHomePage();
		addActivity(true, activity, false, "");

		/*
		- Connect to Intranet with User B 
		- Mouve the mouse on the avatar of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- The Generic pop up is displayed		*/
		acc.userSignIn(userType.ADMIN);
		nav.goToHomePage();
		selectFileter("Connections");
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_AVATAR.replace("${index}","1").replace("${author}", user2), true);	
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", user2));

		/*
		- From the pop up, Click on the avatar of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- The User B is redirected to the User A's activity stream		*/ 
		click(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}",DATA_USER2));
		Utils.pause(1000);
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER2)), DEFAULT_TIMEOUT,1,2);

		//Delete data test
		nav.goToConnectionPage();
		pConnect.removeConnection(user2);

		acc.userSignIn(userType.PUBLISHER);
		home.deleteActivity(activity);
	}

	/**
	 * Case ID:108094.
	 * Test Case Name: User's activity should be displayed after click on User's avatar on generic pop up of activity stream's mentions.
	 * Pre-Condition: User A and User B are a connectionUser A and User B are connected to Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test43_UsersActivityShouldBeDisplayedAfterClickOnUsersAvatarOnGenericPopUpOfActivityStreamsMentions() {
		info("Test 43 User's activity should be displayed after click on User's avatar on generic pop up of activity stream's mentions");
		String activity = "Activity 1080941";

		/*
		- Connect to Intranet with the User A
		- Shared an activity
		 *Expected Outcome: 
		- The username of the User B is displayed in the activity		*/
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);

		nav.goToHomePage();
		addActivity(true, activity, false, "");

		/*
		- Connect to Intranet with the User B
		- Share an activity where User A is mentionned
		 *Input Data: 
		 *Expected Outcome: 
		- The activity is shared
		- The mentionned user is displayed as a link		*/
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);	
		nav.goToHomePage();
		mentionActivity(true, "", user1);

		/*
		- Move the mouse over the username link
		 *Input Data: 
		 *Expected Outcome: 
		- A Generic pop up information is displayed*/
		mouseOver(home.ELEMENT_ACTIVITY.replace("${activityText}",user1), true);		
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", user1));

		/*
		- From the Generic pop up, Click on the avatar of the user A
		 *Input Data: 
		 *Expected Outcome: 
		- The User B is redirected to the User A's activity		*/ 
		click(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}",DATA_USER1));
		Utils.pause(1000);
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER1)), DEFAULT_TIMEOUT,1,2);

		//Delete data test
		nav.goToHomePage();
		home.deleteActivity(user1, true);
		nav.goToConnectionPage();
		pConnect.removeConnection(user1);

		acc.userSignIn(userType.ADMIN);
		home.deleteActivity(activity);
	}

	/**
	 * Case ID:108095.
	 * Test Case Name: User's activity should be displayed after click on User's avatar on generic pop up of activity stream's user names.
	 * Pre-Condition: User A and User B are a connectionUser A and User B are connected to Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/19 11:19:30
	 */
	@Test
	public  void test44_UsersActivityShouldBeDisplayedAfterClickOnUsersAvatarOnGenericPopUpOfActivityStreamsUserNames() {
		info("Test 44 User's activity should be displayed after click on User's avatar on generic pop up of activity stream's user names");
		String activity = "Activity 108094";

		//Pre-Condition
		info("UserA send a request to userB");
		nav.goToConnectionPage();
		pConnect.connectPeople(user2);
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConnect.acceptInvitation(user1);

		/*
		- Connect to Intranet with the User A
		- Share an activity
		 *Expected Outcome: 
		- The activity of the User A is shared		*/
		nav.goToHomePage();
		addActivity(true, activity, false, "");

		/*
		- Connect to Intranet with the User B in other browser
		 *Input Data: 
		 *Expected Outcome: 
		- The activity of the User A is shared in the activity Stream		*/
		/*
		- Mouve the mouse of the username (User A) link
		 *Input Data: 
		 *Expected Outcome: 
		- A pop up information is displayed*/
		acc.userSignIn(userType.ADMIN);
		nav.goToHomePage();
		selectFileter("Connections");
		mouseOver(home.ELEMENT_ACTIVITY_AUTHOR_AVATAR.replace("${index}","1").replace("${author}", user2), true);	
		waitForAndGetElement(ELEMENT_USER_PROFILE_POPUP.replace("${userName}", user2));

		/*
		- From the Generic pop up, click on the avatar of the User A
		 *Input Data: 
		 *Expected Outcome: 
		- The User B is redirecred to the activity stream of the User A		*/ 
		click(hg.ELEMENT_ONLINE_USER_ACC_IMG.replace("${acc}",DATA_USER2));
		Utils.pause(1000);
		waitForAndGetElement(By.xpath(hg.ELEMENT_MY_AS_TAB.replace("${acc}",DATA_USER2)), DEFAULT_TIMEOUT,1,2);

		//Delete data test
		nav.goToConnectionPage();
		pConnect.removeConnection(user2);

		acc.userSignIn(userType.PUBLISHER);
		home.deleteActivity(activity);
	}
}