package org.exoplatform.selenium.platform.forum.functional.forum.category;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.Button;
import org.exoplatform.selenium.ManageAlert;
import org.exoplatform.selenium.Utils;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.UserGroupManagement;
import org.exoplatform.selenium.platform.ManageAccount.userType;
import org.exoplatform.selenium.platform.forum.ForumBase;
import org.exoplatform.selenium.platform.forum.ForumManageCategory;
import org.exoplatform.selenium.platform.forum.ForumManageForum;
import org.exoplatform.selenium.platform.forum.ForumManagePost;
import org.exoplatform.selenium.platform.forum.ForumManageTopic;
import org.exoplatform.selenium.platform.forum.ForumPermission;
import org.openqa.selenium.By;
import org.testng.annotations.*;

/**
 * @author khanhnt 
 * Update chinhdtt
 */
public class Forum_Forum_Category_Edit extends ForumBase{

	ManageAccount acc;
	ForumManageCategory fmCat;
	ForumManageForum forum; 
	ForumManageTopic topic; 
	ManageAlert alert; 
	ForumPermission pForum; 
	ForumManagePost post; 
	NavigationToolbar nav; 
	UserGroupManagement uGroup; 
	ForumPermission frumPer;

	@BeforeMethod
	public void setUpBeforeTest() {
		initSeleniumTest();
		driver.get(baseUrl);
		fmCat = new ForumManageCategory(driver);
		acc = new ManageAccount(driver);
		acc.signIn(DATA_USER1, DATA_PASS);
		forum = new ForumManageForum(driver);
		topic = new ForumManageTopic(driver);
		pForum = new ForumPermission(driver, this.plfVersion);
		post = new ForumManagePost(driver, this.plfVersion);
		button = new Button(driver,this.plfVersion);
		nav = new NavigationToolbar(driver, this.plfVersion);
		uGroup = new UserGroupManagement(driver, this.plfVersion);
		frumPer = new ForumPermission(driver, this.plfVersion);
	}

	@AfterMethod
	public void afterTest() {
		driver.manage().deleteAllCookies();
		driver.quit();
	}

	/**
	 * Case ID:109075.
	 * Test Case Name: Edit Category with blank entry for Restricted Audience.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/05 17:37:04
	 */
	@Test
	public  void test01_EditCategoryWithBlankEntryForRestrictedAudience() {
		info("Test 01 Edit Category with blank entry for Restricted Audience");
		String catName = "Category 72817";
		String order = "1";
		int chooseRestricted = 1;
		String[] restricted = {"mary"}; 
		String[] restrictedUpdate = {""}; 
		String description = "Description of Category";
		int setPermission = 0; 
		String[] userGroup = {""}; 
		String catNameUpdate = "Update 72817";

		/*
		- Login as administrator user.
		- Go to Forum Application, click [Add Category] button.
		- Create new category ([Restricted Audience] not blank).
		 *Expected Outcome: 
		- Category is added successfully.		*/
		goToForums();
		info("Create New Category");
		fmCat.goToAddCategory(); 
		fmCat.inputDataCategoryInForum(catName, order, chooseRestricted, restricted,
				description, setPermission, userGroup);
		button.save();

		/*
		- Go to Forum application.
		- Select Category you want to edit.
		- Click on [Mange Category] button and select [Edit] option in [Category] section. 
		 *Input Data: 
		 *Expected Outcome: 
		- All forums of selected category are listed.
		- There is a [Manage Category] button in action bar.
		- Edit Category form is shown properly.		*/
		/*
		- Change [Restricted Audience] field to blank.
		- Input valid values for other required fields
		- Click [Save] button.
		 *Input Data: 
		 *Expected Outcome: 
		- New Category is edited successfully
		- Any user can access this category by default (when'Restricted audience' is blank)		*/ 
		fmCat.editCategoryInForum(catNameUpdate, order, 1, restrictedUpdate, 
				description, setPermission, userGroup);

		info("Nomal user login to check");
		fmCat.checkRightOfViewCategory("demo", DATA_PASS, catNameUpdate, description, true);

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		goToForums();
		click(By.linkText(catNameUpdate));
		fmCat.deleteCategoryInForum(catNameUpdate, true);	
	}

	/**
	 * Case ID:109080.
	 * Test Case Name: Edit Category with invalid data entry for Restricted Audience.	 
	 * Created by khanhnt at 2013/11/21 17:20:14
	 */
	@Test
	public  void test02_EditCategoryInCaseInvalidUserEntryForRestrictedAudienceField() {
		info("Test 2: Edit Category in case invalid user entry for Restricted audience field"); 
		String catName = "Category 109080";
		String order = "0";
		int chooseRestricted = 0;
		String[] restricted = { "" };
		String description = "Description";
		int setPermission = 0;
		String[] userGroup = null;
		boolean permission = false;
		String[] invalidRestricted = {"invaliduser, /invalidGroup, invalidRole:/developers"};

		/*
		- Login as administrator user.
		- Go to Forum Application, click on [Add Category] button in toolbar.
		- Create new category that allow anyone to access ([Restricted Audience] = blank).
		 *Expected Outcome: 
		- Category is added successfully.		*/
		info("Create Category");
		goToForums();
		fmCat.addNewCategoryInForum(catName, order, chooseRestricted,
				restricted, description, setPermission, userGroup, permission);
		fmCat.goToForumHome();
		waitForAndGetElement(By.linkText(catName)).click();

		/*
		- Go to Forum application.
		- Select Category you want to edit.
		- Click on [Mange Category] button and select [Edit] option in Category section.
		 *Input Data: 
		 *Expected Outcome: 
		- All forums of selected category are shown.
		- There is a [Manage Category] button in action bar.
		- Edit Category form is shown properly.		*/
		/*
		- Enter invalid (unavailable) user(s)/role(s)/group(s) into[Restricted Audience] field.
		 *Input Data: 
		 *Expected Outcome: 
		- User(s)/role(s)/group(s) can be input into[Restricted Audience] field.		*/
		/*
		- Input valid value for other required fields.
		- Click [Save] button.
		 *Input Data: 
		 *Expected Outcome: 
		- Alert message is shown in order to notify about INCORRECT user(s)s/role(s)/group(s) at [Restricted Audience] field.
		- User should correct [Restricted Audience] field with available user(s)/role(s)/group(s); 
		Or leave this field blank then click [Save] button.		*/
		fmCat.editCategoryInForum(catName, order, 1, invalidRestricted, null, 0, null);
		waitForMessage(fmCat.MESSAGE_RESTRICTED_AUDIENCE_INVALID+invalidRestricted[0]);
		click(ELEMENT_OK_INFOR_POPUP);
		button.cancel();

		//Delete data test
		fmCat.deleteCategoryInForum(catName, true);
	}

	/**
	 * Case ID:109084.
	 * Test Case Name: Edit Category in case valid data entry for Restricted audience field.
	 * Created by khanhnt at 2013/11/21 17:20:14
	 */
	@Test
	public  void test03_EditCategoryInCaseValidDataEntryForRestrictedAudienceField() {
		info("Test 3: Edit Category in case valid data entry for Restricted audience field"); 
		String catName = "Category 109084";
		String order = "0";
		int chooseRestricted = 0;
		String[] restricted = { "" };
		String description = "Description";
		int setPermission = 0;
		String[] userGroup = null;
		boolean permission = false;
		String[] validRestricted = { "james, manager:/platform/web-contributors, /developers" };
		String username = getRandomString();
		String password = "gtngtn";
		String firstName = "Test";
		String lastName = "FFFF";
		String email1 = username+"@exoplatform.com";

		/*
		- Login as administrator user.
		- Go to Forum Application, click on [Add Category] button.
		- Create new category that allow anyone to access ([Restricted Audience] = blank).
		 *Expected Outcome: 
		- Category is added successfully.		*/
		info("Create Category");
		goToForums();
		fmCat.addNewCategoryInForum(catName, order, chooseRestricted,
				restricted, description, setPermission, userGroup, permission);
		fmCat.goToForumHome();
		waitForAndGetElement(By.linkText(catName));

		/*
		- Go to Forum application.
		- Select Category you want to edit.
		- Click on [Mange Category] button and select [Edit] option in Category section.
		 *Input Data: 
		 *Expected Outcome: 
		- All forums of selected category are shown.
		- There is a [Manage Category] button in action bar.
		- Edit Category form is shown properly 		*/
		/*
		- Input valid (available) user(s),rolep(s), group(s) for [Restricted Audience] field; Or select user(s), role(s), group(s) in list by click on [Select User]/[Select Role]/[Select Group] buttons.
		 *Input Data: 
		 *Expected Outcome: 
		- User(s), Role(s), Group(s) can be input into [Restricted Audience] field.		*/
		/*
		- Input valid data into all required fields.
		- Click [Save] button.
		 *Input Data: 
		 *Expected Outcome: 
		- Category is edited successfully.
		 */
		click(By.linkText(catName));
		fmCat.editCategoryInForum(catName, order, 1, validRestricted, null, 0, null);

		/*
		- Login as user assigned in step3.
		- Go to Forum Application.
		 *Input Data: 
		 *Expected Outcome: 
		- User can view and access category edited.		*/
		info("james login");
		fmCat.checkRightOfViewCategory("james", DATA_PASS, catName, description, true);

		info("Mary login to check Role");
		fmCat.checkRightOfViewCategory(DATA_USER2, DATA_PASS, catName, description, true);

		info("Demo login to check Group");
		fmCat.checkRightOfViewCategory("demo", DATA_PASS, catName, description, true);

		/*
		- Login as user NOT assigned in step3.
		- Go to Forum Application.
		 *Input Data: 
		 *Expected Outcome: 
		- User can NOT view the category edited.		*/ 		
		info("Create new account to check");
		acc.userSignIn(userType.ADMIN);
		nav.goToNewStaff();
		acc.addNewUserAccount(username, password, password, firstName, lastName, "", email1, null, null, true);
		fmCat.checkRightOfViewCategory(username, password, catName, description, false);

		//Delete data test	
		acc.userSignIn(userType.ADMIN);
		goToForums();
		click(By.linkText(catName));
		fmCat.deleteCategoryInForum(catName, true);
		info("Delete users test");
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username);		
	}

	/**
	 * Case ID:109091.
	 * Test Case Name: Edit Category in case invalid user entry for Moderator field.
	 * Created by chinhdtt at 2014/06/09 13:50:14
	 */
	@Test
	public  void test04_EditCategoryInCaseInvalidUserEntryForModeratorField() {
		info("Test 04 Edit Category in case invalid user entry for Moderator field");
		String catName = "Category 73007";
		String order = "1";
		int chooseRestricted = 1;
		String[] restricted = {""}; 
		String description = "Description of Category";
		int setPermission = 0; 
		String[] userGroup = {""}; 
		String[] userInvalid = {"invalidUser"};
		String[] groupInvalid = {"/invalidGroup"};
		String[] roleInvalid = {"invalidRole:/developers"};

		/*
		- Login as administrator user: [root].
		- Go to Forum Application, click on [Add Category] button in toolbar to create category.
		 *Expected Outcome: 
		- Category is created successfully.		*/
		goToForums();
		info("Create New Category");
		fmCat.goToAddCategory(); 
		fmCat.inputDataCategoryInForum(catName, order, chooseRestricted, restricted,
				description, setPermission, userGroup, false);
		button.save();

		/*
		- Select Category you want to edit by click on Category name.
		- Click on [Mange Category] button and select [Edit] option in Category section.
		 *Input Data: 
		 *Expected Outcome: 
		- All forums of selected category are shown.
		- There is a [Manage Category] button in action bar.
		- Edit Category form is shown properly.		*/
		fmCat.goToEditCategoryInForum(true);

		/*
		- Select [Permissions] tab.
		- Enter invalid (unavailable) user(s)/role(s)/group(s) for [Moderator] field.
		- Click [Add] button.
		 *Input Data: 
		 *Expected Outcome: 
		- User(s)/role(s)/group(s) is NOT displayed in [Moderator] field.
		- Alert message is shown in order to notify that invalid user entry for [Moderator] field.		*/ 	
		info("Invalid User");
		pForum.setPermissionWithOption(1, userInvalid);
		click(pForum.ELEMENT_FORUM_CATEGORY_PERMISSION_GRID);
		click(button.ELEMENT_ADD_BUTTON);
		waitForMessage('"'+userInvalid[0]+'"' +" "+ fmCat.MESSAGE_CATEGORY_MODERATOR_INVALID);
		button.ok();

		info("Invalid Group");
		pForum.setPermissionWithOption(1, groupInvalid);
		click(pForum.ELEMENT_FORUM_CATEGORY_PERMISSION_GRID);
		click(button.ELEMENT_ADD_BUTTON);
		waitForMessage('"'+groupInvalid[0]+'"' +" "+ fmCat.MESSAGE_CATEGORY_MODERATOR_INVALID);
		button.ok();

		info("Invalid Role");
		pForum.setPermissionWithOption(1, roleInvalid);
		click(pForum.ELEMENT_FORUM_CATEGORY_PERMISSION_GRID);
		click(button.ELEMENT_ADD_BUTTON);
		waitForMessage('"'+roleInvalid[0]+'"' +" "+ fmCat.MESSAGE_CATEGORY_MODERATOR_INVALID);
		button.ok();

		//Delete data test
		goToForums();
		fmCat.deleteCategoryInForum(catName, true);
	}

	/**
	 * Case ID:109094.
	 * Test Case Name: Edit Category with removing data in Moderator field.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/04 18:16:39
	 */
	@Test
	public  void test05_EditCategoryWithRemovingDataInModeratorField() {
		info("Test 05 Edit Category with removing data in Moderator field");
		String catName = "Category 109094";
		String order = "1";
		int chooseRestricted = 1;
		String[] restricted = {"john"}; 
		String description = "Description of Category";
		String[] user = {"james"};
		String[] userRole = {"manager:/platform/web-contributors"}; 
		String[] userGroup = {"/developers"}; 
		String catNameUpdate = "Update 109094";
		String[] addForum = {"Title of forum 001", "1", "Open", "Unlocked", "Description of forum 001"}; 	
		String title1 = "Title topic 001"; 
		String message1 = "Topic 001"; 
		String title2 = "Title topic 002"; 
		String message2 = "Topic 002"; 

		/*
		- Login as administrator user: [root].
		- Go to Forum Application, click on [Add Category] button.
		- Create category that allows any user can access it ([Restricted Audience] = blank). And this category has some Moderators in Permission tab.
		 *Expected Outcome: 
		- Category is added successfully.		*/
		goToForums();
		info("Create New Category");
		fmCat.goToAddCategory(); 
		fmCat.inputTitleOrderDescriptionCategory(catName, order, description);
		fmCat.selectRestricted(chooseRestricted, restricted);
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user, true);
		frumPer.configPermission4ForumCategory(1, userRole, true);
		frumPer.configPermission4ForumCategory(1, userGroup, true);
		button.save();

		info("Create New Forum");
		forum.goToAddForum(); 
		forum.inputDataInAddForumTab_addForum(catName, addForum); 
		button.save(); 		

		/*
		- Select Category you want to edit by click on Category name.
		- Click on [Mange Category] button and select [Edit] option in Category section.
		 *Input Data: 
		 *Expected Outcome: 
		- All forums of selected category are shown.
		- There is a [Manage Category] button in action bar.
		- Edit Category form is shown properly.		*/
		goToForumHome();
		click(By.linkText(catName));
		fmCat.goToEditCategoryInForum(true);

		/*
		- Select [Permissions] tab.
		- Remove user(s)/role(s)/group(s) in list of Permisssions tab.
		 *Input Data: 
		 *Expected Outcome: 
		- User(s)/role(s)/group(s) is removed from list in Permissions tab.		*/
		pForum.deletePermission4ForumCategory("james");
		Utils.pause(1000);

		/*
		- Input valid value for other required fields.
		- Click [Save] button.
		 *Input Data: 
		 *Expected Outcome: 
		- Selected category is edited successfully.
		- Only User(s), User(s) having role(s), User(s) belong group(s) remained in moderator table is moderator of this category.		*/ 
		click(fmCat.ELEMENT_CATEGORY_TAB);
		fmCat.inputTitleOrderDescriptionCategory(catNameUpdate, order, description);
		button.save();

		info("Demo login to check Group");
		acc.userSignIn(userType.DEVELOPER);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0])); 
		topic.quickStartTopic(title1, message1); 
		Utils.pause(1000);

		info("Mary login to check role");
		acc.userSignIn(userType.PUBLISHER);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0])); 
		topic.quickStartTopic(title2, message2); 
		Utils.pause(1000);

		info("James login to check");		
		acc.userSignIn(userType.AUTHOR);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0])); 
		waitForElementNotPresent(topic.ELEMENT_START_TOPIC_BUTTON);
		Utils.pause(1000);

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		goToForums();
		click(By.linkText(catNameUpdate));
		fmCat.deleteCategoryInForum(catNameUpdate, true);
	}

	/**
	 * Case ID:109097.
	 * Test Case Name: Edit category which deleted by another user.
	 * Bug ID : FORUM-310
	 * Created by khanhnt at 2013/11/21 17:20:14
	 */
	@Test(groups={"error"})
	public  void test06_EditCategoryWhichDeletedByAnotherUser() {
		info("Test 6: Edit category which deleted by another user"); 
		String catName = "Category 109097";
		String order = "0";
		int chooseRestricted = 0;
		String[] restricted = { "" };
		String description = "Description";
		int setPermission = 0;
		String[] userGroup = null;
		boolean permission = false;

		/*
		- Login as root in a web browser (Exp: Firefox).
		- Create category.
		- Click on Category name to open this category.
		 *Expected Outcome: 
		- Category is created successfully.
		- [root] is standing at Category created.		*/
		goToForums();
		fmCat.addNewCategoryInForum(catName, order, chooseRestricted,
				restricted, description, setPermission, userGroup, permission);

		/*
		- Login by other admin [john] in another web browser (Exp: Chrome).
		- Select category created by [root] at step1 to perform delete category: + Click on [Manage Category] button, select [Delete] option in Category section.
		 *Input Data: 
		 *Expected Outcome: Category is deleted by admin [john].		*/
		fmCat.loginInNewWindowToDeleteCategory(USER_ROOT, PASS_ROOT, catName);

		/*
		- Back to browser that user [root] logged-in. [root] is still standing at the category created at step1.
		- Click on [Manage Category] button, select [Edit] option in Category section.
		 *Input Data: 
		 *Expected Outcome: 
		- Home Forum is opened. 
		- Category deleted above is not shown.		*/ 	
		fmCat.goToEditCategoryInForum(false);
		waitForMessage(fmCat.MESSAGE_CATEGORY_NOT_EXISTE);
		click(ELEMENT_OK_INFOR_POPUP);		
	}

	/**
	 * Case ID:109109.
	 * Test Case Name: Edit Category with valid user entry for Restricted Audience.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/11 14:29:51
	 */
	@Test
	public  void test07_EditCategoryWithValidUserEntryForRestrictedAudience() {
		info("Test 7: Edit Category with valid user entry for Restricted Audience");
		String catName = "Category 109109";
		String order = "1";
		int chooseRestricted = 2; 
		String[] restricted = {"mary"}; 
		String description = "Description of Category";
		int setPermission = 0;
		String[] userGroup = null;
		boolean permission = false;
		String catNameUpdate = "Update 109109";

		/*
		- Login as administrator user.
		- Go to Forum Application, click on [Add Category] button.
		- Create new category that allow anyone to access ([Restricted Audience] = blank).
		 *Expected Outcome: 
		- Category is added successfully.		*/
		goToForums();
		info("Create New Category");
		fmCat.goToAddCategory(); 
		fmCat.inputDataCategoryInForum(catName, order, 5, restricted,
				description, setPermission, userGroup, permission);
		button.save();

		/*
		- Go to Forum application.
		- Select Category you want to edit.
		- Click on [Manage Category] button and select [Edit] option in Category section.
		 *Input Data: 
		 *Expected Outcome: 
		- All forums of selected category are shown.
		- There is a [Manage Category] button in action bar.
		- Edit Category form is shown properly 		*/
		/*
		- Input valid (available) user(s) for [Restricted Audience] field; Or select user(s) in list by click on [Select User button.
		 *Input Data: 
		 *Expected Outcome: 
		- User(s) can be input into [Restricted Audience] field.		*/
		/*
		- Input valid data into all required fields.
		- Click [Save] button.
		 *Input Data: 
		 *Expected Outcome: 
		- Category is edited successfully.
		- Only user(s) assigned at step 3 can see this category.		*/
		fmCat.editCategoryInForum(catNameUpdate, order, chooseRestricted, restricted, 
				description, setPermission, userGroup, permission);

		/*
		- Login as user assigned in step3.
		- Go to Forum Application.
		 *Input Data: 
		 *Expected Outcome: 
		- User can view and access category edited.		*/
		info("User Mary login to check");
		fmCat.checkRightOfViewCategory("mary", DATA_PASS, catNameUpdate, description, true);

		/*
		- Login as user NOT assigned in step3.
		- Go to Forum Application.
		 *Input Data: 
		 *Expected Outcome: 
		- User can NOT view the category edited.		*/ 
		info("User James login to check");
		fmCat.checkRightOfViewCategory("james", DATA_PASS, catNameUpdate, description, false);

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		goToForums();
		click(By.linkText(catNameUpdate));
		fmCat.deleteCategoryInForum(catNameUpdate, true);	
	}

	/**
	 * Case ID:109110.
	 * Test Case Name: Edit Category with valid role entry for Restricted Audience.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/11 14:29:51
	 */
	@Test
	public  void test08_EditCategoryWithValidRoleEntryForRestrictedAudience() {
		info("Test 8: Edit Category with valid role entry for Restricted Audience");
		String catName = "Category 109110";
		String order = "1";
		int chooseRestricted = 1; 
		String[] restricted = {"manager:/platform/web-contributors"}; 
		String description = "Description of Category";
		int setPermission = 0;
		String[] userGroup = null;
		boolean permission = false;
		String catNameUpdate = "Update 109110";

		/*
		- Login as administrator user.
		- Go to Forum Application, click on [Add Category] button.
		- Create new category that allow anyone to access ([Restricted Audience] = blank).
		 *Expected Outcome: 
		- Category is added successfully.		*/
		goToForums();
		info("Create New Category");
		fmCat.goToAddCategory(); 
		fmCat.inputDataCategoryInForum(catName, order, 5, restricted,
				description, setPermission, userGroup, permission);
		button.save();

		/*
		- Go to Forum application.
		- Select Category you want to edit.
		- Click on [Mange Category] button and select [Edit] option in Category section.
		 *Input Data: 
		 *Expected Outcome: 
		- All forums of selected category are shown.
		- There is a [Manage Category] button in action bar.
		- Edit Category form is shown properly 		*/
		/*
		- Input valid role(s) for [Restricted Audience] field; Or select role(s) in list by click on[Select Role] button.
		 *Input Data: 
		 *Expected Outcome: 
		- Role(s) can be input into [Restricted Audience] field.		*/
		/*
		- Input valid data into all required fields.
		- Click [Save] button.
		 *Input Data: 
		 *Expected Outcome: 
		- Category is edited successfully.
		- Only users have the role assigned at step 3 can see this category.		*/
		info("Edit Role");
		fmCat.editCategoryInForum(catNameUpdate, order, chooseRestricted, restricted, description, setPermission, userGroup, permission);

		/*
		- Login as user who has role assigned in step3.
		- Go to Forum Application.
		 *Input Data: 
		 *Expected Outcome: 
		- User can view and access category edited.		*/
		fmCat.checkRightOfViewCategory("mary", DATA_PASS, catNameUpdate, description, true);

		/*
		- Login as user who does NOT have the role assigned in step3.
		- Go to Forum Application.
		 *Input Data: 
		 *Expected Outcome: 
		- User can NOT view the category edited.		*/ 
		fmCat.checkRightOfViewCategory("james", DATA_PASS, catNameUpdate, description, false);

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		goToForums();
		click(By.linkText(catNameUpdate));
		fmCat.deleteCategoryInForum(catNameUpdate, true);
	}

	/**
	 * Case ID:109111.
	 * Test Case Name: Edit Category with valid group entry for Restricted Audience.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/11 14:29:51
	 */
	@Test
	public  void test09_EditCategoryWithValidGroupEntryForRestrictedAudience() {
		info("Test 9: Edit Category with valid group entry for Restricted Audience");
		String catName = "Category 109111";
		String order = "1";
		int chooseRestricted = 1; 
		String[] restricted = {"/developers"}; 
		String description = "Description of Category";
		int setPermission = 0;
		String[] userGroup = null;
		boolean permission = false;
		String catNameUpdate = "Update 109111";

		/*
		- Login as administrator user.
		- Go to Forum Application, click on [Add Category] button.
		- Create new category that allow anyone to access ([Restricted Audience] = blank).
		 *Expected Outcome: 
		- Category is added successfully.		*/
		goToForums();
		info("Create New Category");
		fmCat.goToAddCategory(); 
		fmCat.inputDataCategoryInForum(catName, order, 5, restricted,
				description, setPermission, userGroup, permission);
		button.save();

		/*
		- Go to Forum application.
		- Select Category you want to edit.
		- Click on [Mange Category] button and select [Edit] option in Category section.
		 *Input Data: 
		 *Expected Outcome: 
		- All forums of selected category are shown.
		- There is a [Manage Category] button in action bar.
		- Edit Category form is shown properly 		*/
		/*
		- Input valid group(s) for [Restricted Audience] field; Or select group(s) in list by click on [Select Group] button.
		 *Input Data: 
		 *Expected Outcome: 
		- Group(s) can be input into [Restricted Audience] field.		*/
		/*
		- Input valid data into all required fields.
		- Click [Save] button.
		 *Input Data: 
		 *Expected Outcome: 
		- Category is edited successfully.
		- Only users in group assigned at step 3 can see this category.		*/
		info("Edit Group");
		fmCat.editCategoryInForum(catNameUpdate, order, chooseRestricted, restricted, description, setPermission, userGroup, permission);

		/*
		- Login as user who is in group assigned in step3.
		- Go to Forum Application.
		 *Input Data: 
		 *Expected Outcome: 
		- User can view and access category edited.		*/
		fmCat.checkRightOfViewCategory("demo", DATA_PASS, catNameUpdate, description, true);

		/*
		- Login as userwho is NOT in group assigned in step3.
		- Go to Forum Application.
		 *Input Data: 
		 *Expected Outcome: 
		- User can NOT view the category edited.		*/ 
		fmCat.checkRightOfViewCategory("mary", DATA_PASS, catNameUpdate, description, false);

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		goToForums();
		click(By.linkText(catNameUpdate));
		fmCat.deleteCategoryInForum(catNameUpdate, true);
	}

	/**
	 * Case ID:109112.
	 * Test Case Name: Edit Category with removing data entry in Restricted Audience.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/11 14:29:51
	 */
	@Test
	public  void test10_EditCategoryWithRemovingDataEntryInRestrictedAudience() {
		info("Test 10 Edit Category with removing data entry in Restricted Audience");
		String catName = "Category 109112";
		String order = "1";
		int chooseRestricted = 1; 
		String[] restricted = {"james,manager:/platform/web-contributors,/developers"}; 
		String[] restrictedUpdate = {"james, manager:/platform/web-contributors"}; 
		String description = "Description of Category";
		int setPermission = 0;
		String[] userGroup = null;
		boolean permission = false;
		String catNameUpdate = "Update 109112";

		/*
		- Login as administrator user.
		- Go to Forum Application.
		- Create new category with valid users, roles, groups in [Restricted Audience] field.
		 *Expected Outcome: 
		- Category is added successfully.		*/
		goToForums();
		info("Create New Category");
		fmCat.goToAddCategory(); 
		fmCat.inputDataCategoryInForum(catName, order, chooseRestricted, restricted,
				description, setPermission, userGroup, permission);
		button.save();

		/*
		- Go to Forum application.
		- Select Category you want to edit.
		- Click on [Mange Category] button and select [Edit] option in Category section.
		 *Input Data: 
		 *Expected Outcome: 
		- All forums of selected category are shown.
		- There is a [Manage Category] button in action bar.
		- Edit Category form is shown properly 		*/
		/*
		- Remove user/role/group in existing list of [Restricted Audience].
		 *Input Data: 
		 *Expected Outcome: 
		- List of [Restricted Audience] field is updated following.		*/
		/*
		- Input valid data into all required fields.
		- Click [Save] button.
		 *Input Data: 
		 *Expected Outcome: 
		- Category is edited successfully.
		- Only user(s), users have the role and users in group assigned at step 3 can see this category.		*/
		info("Edit [Restricted Audience] field");
		fmCat.editCategoryInForum(catNameUpdate, order, chooseRestricted, restrictedUpdate, description, setPermission, userGroup, permission);

		/*
		- Login as user assigned in step3.
		- Go to Forum Application.
		 *Input Data: 
		 *Expected Outcome: 
		- User can view and access category edited.		*/
		info("Mary login to check Role");
		fmCat.checkRightOfViewCategory("mary", DATA_PASS, catNameUpdate, description, true);
		info("James login to check user");
		fmCat.checkRightOfViewCategory("james", DATA_PASS, catNameUpdate, description, true);

		/*
		- Login as user NOT assigned in step3.
		- Go to Forum Application.
		 *Input Data: 
		 *Expected Outcome: 
		- User can NOT view the category edited.		*/ 
		fmCat.checkRightOfViewCategory("demo", DATA_PASS, catNameUpdate, description, false);

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		goToForums();
		click(By.linkText(catNameUpdate));
		fmCat.deleteCategoryInForum(catNameUpdate, true);
	}

	/*
	 * Case ID:109113.
	 * Test Case Name: Edit Category with valid data entry in Moderator field.	 * 
	 * Created by chinhdtt at 2014/06/09 14:35:14
	 */
	@Test
	public  void test11_EditCategoryInCaseValidUserEntryForModeratorField() {
		info("Test 11: Edit Category with valid data entry in Moderator field"); 
		String catName = "Category 109113";
		String order = "1";
		int chooseRestricted = 5; 
		String[] restricted = {""}; 
		String description = "Description of Category";
		int setPermission = 0;
		String[] userGroup = null;
		String catNameUpdate = "Update 109113";
		String[] user = {"james"};
		String[] userRole = {"manager:/platform/web-contributors"}; 
		String[] userGroups = {"/developers"}; 
		String[] addForum = {"Title of forum 001", "1", "Open", "Unlocked", "Description of forum 001"}; 	
		String title1 = "Title topic 001"; 
		String message1 = "Topic 001"; 
		String title2 = "Title topic 002"; 
		String message2 = "Topic 002"; 
		String title3 = "Title topic 003"; 
		String message3 = "Topic 003"; 
		String postTitle1 = "Post 001";
		String postTitle2 = "Post 002";
		String postTitle3 = "Post 003";
		String username = getRandomString();
		String password = "gtngtn";
		String firstName = "Test";
		String lastName = "GGGG";
		String email1 = username+"@exoplatform.com";

		/*
		- Login as administrator user: [root].
		- Go to Forum Application, click on [Add Category] button.
		- Create category that allows any user can access it ([Restricted Audience] = blank).
		 *Expected Outcome: 
		- Category is added successfully.		*/
		goToForums();
		info("Create New Category");
		fmCat.goToAddCategory(); 
		fmCat.inputDataCategoryInForum(catName, order, chooseRestricted, restricted,
				description, setPermission, userGroup, false);
		button.save();

		/*
		- Select Category you want to edit by click on Category name.
		- Click on [Mange Category] button and select [Edit] option in Category section.
		 *Input Data: 
		 *Expected Outcome: 
		- All forums of selected category are shown.
		- There is a [Manage Category] button in action bar.
		- Edit Category form is shown properly.		*/
		goToForumHome();
		click(By.linkText(catName));
		fmCat.goToEditCategoryInForum(true);

		/*
		- Select [Permissions] tab.
		- Input valid (available) user(s)/role(s)/group(s) in list of Permissions tab.
		- Click [Add] button.
		 *Input Data: 
		 *Expected Outcome: 
		- User(s)/role(s)/group(s) is added to list in Permissions tab.		*/
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user, true);
		frumPer.configPermission4ForumCategory(1, userRole, true);
		frumPer.configPermission4ForumCategory(1, userGroups, true);
		Utils.pause(1000);

		/*
		- Input valid value for other required fields.
		- Click [Save] button.
		 *Input Data: 
		 *Expected Outcome: 
		- Selected category is edited successfully.
		 */ 
		click(fmCat.ELEMENT_CATEGORY_TAB);
		fmCat.inputTitleOrderDescriptionCategory(catNameUpdate, order, description);
		button.save();

		info("Create New Forum");
		forum.goToAddForum(); 
		forum.inputDataInAddForumTab_addForum(catNameUpdate, addForum); 
		button.save(); 

		//	- Only User(s), User(s) having role(s), User(s) belong group(s) in Permission table (with Moderator checkbox = TRUE) is moderator of this category.	
		info("Verify user User(s)/Role(s)/ Group(s)");
		info("James login to check");
		acc.userSignIn(userType.AUTHOR);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0])); 
		topic.quickStartTopic(title1, message1); 
		Utils.pause(1000);
		click(By.linkText(title1));
		post.postReply(postTitle1, postTitle1, "", "");
		Utils.pause(1000);

		info("Mary login to check role");
		acc.userSignIn(userType.PUBLISHER);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0])); 
		topic.quickStartTopic(title2, message2); 
		Utils.pause(1000);
		click(By.linkText(title2));
		post.postReply(postTitle2, postTitle2, "", "");
		Utils.pause(1000);

		info("Demo login to check Group");
		acc.userSignIn(userType.DEVELOPER);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0])); 
		topic.quickStartTopic(title3, message3); 
		Utils.pause(1000);
		click(By.linkText(title3));
		post.postReply(postTitle3, postTitle3, "", "");
		Utils.pause(1000);

		info("Create new account to check");
		acc.userSignIn(userType.ADMIN);
		nav.goToNewStaff();
		acc.addNewUserAccount(username, password, password, firstName, lastName, "", email1, null, null, true);
		acc.signOut();
		acc.signIn(username, password);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0]));
		waitForElementNotPresent(topic.ELEMENT_START_TOPIC_BUTTON);

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		goToForums();
		click(By.linkText(catNameUpdate));
		fmCat.deleteCategoryInForum(catNameUpdate, true);		
		info("Delete users test");
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username);
	}	

	/**
	 * Case ID:109114.
	 * Test Case Name: Assign [Permission to start topics] for valid user when editting category.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/04 18:16:39
	 */
	@Test
	public  void test12_AssignPermissionToStartTopicsForValidUserWhenEdittingCategory() {
		info("Test 12 Assign [Permission to start topics] for valid user when editting category");
		String catName = "Category 109114";
		String order = "1";
		int chooseRestricted = 5; 
		String[] restricted = {""}; 
		String description = "Description of Category";
		String[] userGroup = null;
		String[] user = {"james"};
		String[] userRole = {"manager:/platform/web-contributors"}; 
		String[] userGroups = {"/developers"}; 
		String catNameUpdate = "Update 109114";
		String[] addForum = {"Title of forum 001", "1", "Open", "Unlocked", "Description of forum 001"}; 	
		String title1 = "Title topic 001"; 
		String message1 = "Topic 001"; 
		String title2 = "Title topic 002"; 
		String message2 = "Topic 002"; 
		String title3 = "Title topic 003"; 
		String message3 = "Topic 003"; 
		String username = getRandomString();
		String password = "gtngtn";
		String firstName = "Test";
		String lastName = "KKKK";
		String email1 = username+"@exoplatform.com";

		/*
		- Login as administrator user: [root].
		- Go to Forum Application, click on [Add Category] button. Create category that allows any user can access it ([Restricted Audience] = blank). And this category has some Moderators in Permission tab.
		- Add a Forum in this category.
		 *Expected Outcome: 
		- Category is added successfully with forum inside.		*/
		goToForums();
		info("Create New Category");
		fmCat.goToAddCategory(); 
		fmCat.inputDataCategoryInForum(catName, order, chooseRestricted, restricted, 
				description, 0, userGroup, false);
		button.save();
		Utils.pause(1000);

		/*
		- Go to Forum Home, Select Category you want to edit by click on Category name.
		- Click on [Mange Category] button and select [Edit] option in Category section.
		 *Input Data: 
		 *Expected Outcome: 
		- All forums of selected category are shown.
		- There is a [Manage Category] button in action bar.
		- Edit Category form is shown properly.		*/
		goToForumHome();
		click(By.linkText(catName));
		fmCat.goToEditCategoryInForum(true);

		/*
		- Select [Permissions] tab.
		- Select a moderator in list.
		- Tick checkbox [Permission to start topics] = TRUE.
		 *Input Data: 
		 *Expected Outcome: 
		- [Permission to start topics] = TRUE for the moderator.		*/
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user, false, true, false, false);
		frumPer.configPermission4ForumCategory(1, userRole, false, true, false, false);
		frumPer.configPermission4ForumCategory(1, userGroups, false, true, false, false);
		Utils.pause(1000);

		/*
		- Input valid value for other required fields.
		- Click [Save] button.
		 *Input Data: 
		 *Expected Outcome: 
		- Selected category is edited successfully.		*/
		click(fmCat.ELEMENT_CATEGORY_TAB);
		fmCat.inputTitleOrderDescriptionCategory(catNameUpdate, order, description);
		button.save();

		info("Create New Forum");
		forum.goToAddForum(); 
		forum.inputDataInAddForumTab_addForum(catNameUpdate, addForum); 
		button.save(); 

		/*
		- Login as user assigned in step3.
		- Go to Forum Application. Access category and forum created above.
		- Click on [Start topic] button.
		 *Input Data: 
		 *Expected Outcome: 
		- User can see [Start topic] button and can create new topic.		*/ 
		info("Verify user User(s)/Role(s)/ Group(s)");
		info("James login to check");
		acc.userSignIn(userType.AUTHOR);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0])); 
		topic.quickStartTopic(title1, message1); 
		Utils.pause(1000);

		info("Mary login to check role");
		acc.userSignIn(userType.PUBLISHER);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0])); 
		topic.quickStartTopic(title2, message2); 
		Utils.pause(1000);

		info("Demo login to check Group");
		acc.userSignIn(userType.DEVELOPER);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0])); 
		topic.quickStartTopic(title3, message3); 
		Utils.pause(1000);

		info("Create new account to check");
		acc.userSignIn(userType.ADMIN);
		nav.goToNewStaff();
		acc.addNewUserAccount(username, password, password, firstName, lastName, "", email1, null, null, true);
		acc.signOut();
		acc.signIn(username, password);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0]));
		waitForElementNotPresent(topic.ELEMENT_START_TOPIC_BUTTON);

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		goToForums();
		click(By.linkText(catNameUpdate));
		fmCat.deleteCategoryInForum(catNameUpdate, true);		
		info("Delete users test");
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username);
	}

	/**
	 * Case ID:109115.
	 * Test Case Name: Assign [Permission to post replies] for valid user when editting category.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/04 18:16:39
	 */
	@Test
	public  void test13_AssignPermissionToPostRepliesForValidUserWhenEdittingCategory() {
		info("Test 13 Assign [Permission to post replies] for valid user when editting category");
		String catName = "Category 109115";
		String order = "1";
		int chooseRestricted = 5; 
		String[] restricted = {""}; 
		String description = "Description of Category";
		String[] userGroup = null;
		String[] user = {"james"};
		String[] userRole = {"manager:/platform/web-contributors"}; 
		String[] userGroups = {"/developers"}; 
		String catNameUpdate = "Update 109115";
		String[] addForum = {"Title of forum 001", "1", "Open", "Unlocked", "Description of forum 001"}; 	
		String title = "Title topic 001"; 
		String message = "Topic 001"; 
		String postTitle1 = "Post 001";
		String postTitle2 = "Post 002";
		String postTitle3 = "Post 003";
		String username = getRandomString();
		String password = "gtngtn";
		String firstName = "Test";
		String lastName = "JJJJ";
		String email1 = username+"@exoplatform.com";		

		/*
		- Login as administrator user: [root].
		- Go to Forum Application, click on [Add Category] button. Create category that allows any user can access it ([Restricted Audience] = blank). And this category has some Moderators in Permission tab.
		- Add a Forum in this category and start a topic.
		 *Expected Outcome: 
		- Category is added successfully with forum and topic inside.		*/
		goToForums();
		info("Create New Category");
		fmCat.goToAddCategory(); 
		fmCat.inputDataCategoryInForum(catName, order, chooseRestricted, restricted, 
				description, 0, userGroup, true);
		button.save();
		Utils.pause(1000);

		/*
		- Go to Forum Home, Select Category you want to edit by click on Category name.
		- Click on [Mange Category] button and select [Edit] option in Category section.
		 *Input Data: 
		 *Expected Outcome: 
		- All forums of selected category are shown.
		- There is a [Manage Category] button in action bar.
		- Edit Category form is shown properly.		*/
		goToForumHome();
		click(By.linkText(catName));
		fmCat.goToEditCategoryInForum(true);

		/*
		- Select [Permissions] tab.
		- Select a moderator in list.
		- Tick checkbox [Permission to post replies] = TRUE.
		 *Input Data: 
		 *Expected Outcome: 
		- [Permission to post replies] = TRUE for the moderator.		*/
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user, false, false, true, false);
		frumPer.configPermission4ForumCategory(1, userRole, false, false, true, false);
		frumPer.configPermission4ForumCategory(1, userGroups, false, false, true, false);
		Utils.pause(1000);

		/*
		- Input valid value for other required fields.
		- Click [Save] button.
		 *Input Data: 
		 *Expected Outcome: 
		- Selected category is edited successfully.		*/
		click(fmCat.ELEMENT_CATEGORY_TAB);
		fmCat.inputTitleOrderDescriptionCategory(catNameUpdate, order, description);
		button.save();

		info("Create New Forum");
		forum.goToAddForum(); 
		forum.inputDataInAddForumTab_addForum(catNameUpdate, addForum); 
		button.save(); 

		info("Create topic");
		topic.quickStartTopic(title, message); 
		Utils.pause(1000);

		/*
		- Login as user assigned in step3.
		- Go to Forum Application. Access category, forum and topic created above.
		- Click on [Post Reply] button.
		 *Input Data: 
		 *Expected Outcome: 
		- User can post the reply for topic above.		*/ 
		info("Verify user James");
		acc.userSignIn(userType.AUTHOR);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0])); 
		click(By.linkText(title));
		post.postReply(postTitle1, postTitle1, "", "");
		Utils.pause(1000);

		info("Mary login to check Role");
		acc.userSignIn(userType.PUBLISHER);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0])); 
		click(By.linkText(title));
		post.postReply(postTitle2, postTitle2, "", "");
		Utils.pause(1000);

		info("Verify user Group");
		acc.userSignIn(userType.DEVELOPER);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0])); 
		click(By.linkText(title));
		post.postReply(postTitle3, postTitle3, "", "");
		Utils.pause(1000);

		info("Create new account to check");
		acc.userSignIn(userType.ADMIN);
		nav.goToNewStaff();
		acc.addNewUserAccount(username, password, password, firstName, lastName, "", email1, null, null, true);
		acc.signOut();
		acc.signIn(username, password);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0]));
		click(By.linkText(title));
		Utils.pause(1000);
		waitForElementNotPresent(post.ELEMENT_POST_REPLY_BUTTON);

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		goToForums();
		click(By.linkText(catNameUpdate));
		fmCat.deleteCategoryInForum(catNameUpdate, true);		
		info("Delete users test");
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username);			
	}

	/**
	 * Case ID:109116.
	 * Test Case Name: Assign [Permission to view posts] for valid user when editting category.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/04 18:16:39
	 */
	@Test
	public  void test14_AssignPermissionToViewPostsForValidUserWhenEdittingCategory() {
		info("Test 14 Assign [Permission to view posts] for valid user when editting category");
		String catName = "Category 109116";
		String order = "1";
		int chooseRestricted = 5;
		String[] restricted = {""}; 
		String description = "Description of Category";
		String[] userGroup = null;
		String[] user = {"james"};
		String[] userRole = {"manager:/platform/web-contributors"}; 
		String[] userGroups = {"/developers"}; 
		String catNameUpdate = "Update 109116";
		String[] addForum = {"Title of forum 001", "1", "Open", "Unlocked", "Description of forum 001"}; 	
		String title = "Title topic 001"; 
		String message = "Topic 001"; 
		String postTitle = "Post 001";
		String username = getRandomString();
		String password = "gtngtn";
		String firstName = "Test";
		String lastName = "MMMM";
		String email1 = username+"@exoplatform.com";	

		/*
		- Login as administrator user: [root].
		- Go to Forum Application, click on [Add Category] button. Create category that allows any user can access it ([Restricted Audience] = blank). And this category has some Moderators in Permission tab.
		- Add a Forum in this category. Start a topic and post some replies.
		 *Expected Outcome: 
		- Category is added successfully with forum, topic and replies inside.		*/
		goToForums();
		info("Create New Category");
		fmCat.goToAddCategory(); 
		fmCat.inputDataCategoryInForum(catName, order, chooseRestricted, restricted, 
				description, 0, userGroup, false);
		button.save();
		Utils.pause(1000);

		/*
		- Go to Forum Home, Select Category you want to edit by click on Category name.
		- Click on [Mange Category] button and select [Edit] option in Category section.
		 *Input Data: 
		 *Expected Outcome: 
		- All forums of selected category are shown.
		- There is a [Manage Category] button in action bar.
		- Edit Category form is shown properly.		*/
		goToForumHome();
		click(By.linkText(catName));
		fmCat.goToEditCategoryInForum(true);

		/*
		- Select [Permissions] tab.
		- Select a moderator in list.
		- Tick checkbox [Permission to view posts] = TRUE.
		 *Input Data: 
		 *Expected Outcome: 
		- [Permission to view posts] = TRUE for the moderator.		*/
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user, false, false, false, true);
		frumPer.configPermission4ForumCategory(1, userRole, false, false, false, true);
		frumPer.configPermission4ForumCategory(1, userGroups, false, false, false, true);
		Utils.pause(1000);

		/*
		- Input valid value for other required fields.
		- Click [Save] button.
		 *Input Data: 
		 *Expected Outcome: 
		- Selected category is edited successfully.		*/
		click(fmCat.ELEMENT_CATEGORY_TAB);
		fmCat.inputTitleOrderDescriptionCategory(catNameUpdate, order, description);
		button.save();

		info("Create New Forum");
		forum.goToAddForum(); 
		forum.inputDataInAddForumTab_addForum(catNameUpdate, addForum); 
		button.save(); 

		info("Create topic");
		topic.quickStartTopic(title, message); 
		Utils.pause(1000);
		click(By.linkText(title));
		post.postReply(postTitle, postTitle, "", "");
		Utils.pause(1000);

		/*
		- Login as user assigned in step3.
		- Go to Forum Application. Access category, forum and topic created above.
		 *Input Data: 
		 *Expected Outcome: 
		- User can view topic and posts inside topic above.		*/ 
		info("User(s)/Role(s)/Group(s) login to verify");
		info("Verify user James");
		acc.userSignIn(userType.AUTHOR);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0])); 
		click(By.linkText(title));
		waitForAndGetElement(post.ELEMENT_POST_TITLE_TEXT.replace("${post}", postTitle));
		waitForAndGetElement(post.ELEMENT_POST_CONTENT_TEXT.replace("${post}", postTitle));
		Utils.pause(1000);

		info("Mary login to check role");
		acc.userSignIn(userType.PUBLISHER);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0])); 
		click(By.linkText(title));
		waitForAndGetElement(post.ELEMENT_POST_TITLE_TEXT.replace("${post}", postTitle));
		waitForAndGetElement(post.ELEMENT_POST_CONTENT_TEXT.replace("${post}", postTitle));
		Utils.pause(1000);

		info("Demo login to check group");
		acc.userSignIn(userType.DEVELOPER);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0])); 
		click(By.linkText(title));
		waitForAndGetElement(post.ELEMENT_POST_TITLE_TEXT.replace("${post}", postTitle));
		waitForAndGetElement(post.ELEMENT_POST_CONTENT_TEXT.replace("${post}", postTitle));
		Utils.pause(1000);

		info("Create new account to check");
		acc.userSignIn(userType.ADMIN);
		nav.goToNewStaff();
		acc.addNewUserAccount(username, password, password, firstName, lastName, "", email1, null, null, true);
		acc.signOut();
		acc.signIn(username, password);
		goToForums();
		click(By.linkText(catNameUpdate));
		click(By.linkText(addForum[0]));
		waitForElementNotPresent(By.linkText(title));

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		goToForums();
		click(By.linkText(catNameUpdate));
		fmCat.deleteCategoryInForum(catNameUpdate, true);		
		info("Delete users test");
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username);		
	}

}