package org.exoplatform.selenium.platform.wiki.functional.information;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.Button;
import org.exoplatform.selenium.Dialog;
import org.exoplatform.selenium.ManageAlert;
import org.exoplatform.selenium.Utils;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.social.ManageMember;
import org.exoplatform.selenium.platform.wiki.BasicAction;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebElement;
import org.testng.annotations.*;
/**
 * @author chinhdtt
 * @date 13 May 2014
 */
public class Wiki_PageInformation_RelatedPage extends BasicAction{

	ManageAccount acc;
	Dialog dialog;
	Button button;	
	ManageMember mMember;	
	NavigationToolbar nav; 

	@BeforeMethod
	public void beforeMethod(){
		initSeleniumTest();
		driver.get(baseUrl);
		driver.manage().window().maximize();
		acc = new ManageAccount(driver,this.plfVersion);
		dialog = new Dialog(driver);
		alert = new ManageAlert(driver, this.plfVersion);
		button = new Button(driver, this.plfVersion);	
		mMember = new ManageMember(driver, this.plfVersion);
		nav = new NavigationToolbar(driver, this.plfVersion);
		acc.signIn(DATA_USER1,DATA_PASS);;		
	}

	@AfterMethod
	public void afterMethod(){
		driver.manage().deleteAllCookies();
		driver.quit();
	}

	/**
	 * Case ID:99193.
	 * Test Case Name: Renaming a page from another space should correctly be updated in Page Info Layout of a related page.
	 * Pre-Condition: User is member of Space 1, Space 2, Space 3
		Wiki of "Space 1" has following pages:
		- Page 1
		- Page 2

		Wiki of "Space 2" has following pages:
		- Page A
		- Page B

		Wiki of "Space 3" has following pages:
		- Page a
		- Page b

		"Page 1 " of "Space 1" wiki has relations with:
		-- "Page A" from "Space 2"
		-- "Page a" from "Space 3"
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/13 17:34:46
	 */
	@Test
	public  void test09_RenamingAPageFromAnotherSpaceShouldCorrectlyBeUpdatedInPageInfoLayoutOfARelatedPage() {
		info("Test 9: Renaming a page from another space should correctly be updated in Page Info Layout of a related page");
		String space1 = "Space01";		
		String space2 = "Space02";
		String title1 = "Page 1";
		String title2 = "Page A";
		String title3 = "Page B";
		String titleUpdate = "Page A Renamed";
		String wikiPath = "Wiki Home";

		//Pre-Condition: 
		info("Create all space and page");
		mMember.goToAllSpaces();
		mMember.addNewSpace(space2, "");
		mMember.goToSpaceMenu("Wiki");
		addBlankWikiPage(title2, title2, 0);
		Utils.pause(1000);
		click(By.linkText("Wiki Home"));
		Utils.pause(1000);		
		addBlankWikiPage(title3, title3, 0);

		mMember.goToAllSpaces();
		mMember.addNewSpace(space1, "");
		mMember.goToSpaceMenu("Wiki");
		addBlankWikiPage(title1, title1, 0);
		Utils.pause(1000);

		info("Add Relations of page1");
		addRelatedPage(wikiPath, title2, space2, true);
		Utils.pause(500);

		/*Step 1:
		  - Go to "Page A" of "Space 2" wiki
		 *Expected Outcome: - Wiki is displaying "Page A".		*/
		mMember.accessSpace(space2);
		mMember.goToSpaceMenu("Wiki");
		click(By.linkText(title2));

		/*Step 2: 
		 *Input Data: - Rename "Page A" to "Page A renamed"
		 *Expected Outcome: - Title of the wiki page is now "Page A renamed" 		*/
		editWikiPage(titleUpdate, titleUpdate, 0);

		/*Step 3: 
		 *Input Data: - Go to "Page 1 " of "Space 1" wiki
		 *Expected Outcome: - Wiki is displaying "Page 1"	*/
		mMember.accessSpace(space1);
		mMember.goToSpaceMenu("Wiki");
		click(By.linkText(title1));

		/*Step 4: 
		 *Input Data: 
		- Open "More" Menu
		- Select "Page Info"
		 *Expected Outcome: - Page infos of Page 1 are diplayed		*/
		goToPageInfo(null, wikiPath);
		Utils.pause(1000);

		/*Step 5: 
		 *Input Data: - Check updates in Related pages
		 *Expected Outcome: - Title of "Page A" has been correctly renamed "Page A renamed"	*/ 
		waitForAndGetElement(ELEMENT_RELATED_PAGE.replace("${relatedPage}", titleUpdate));

		//Delete data test
		mMember.goToAllSpaces();
		mMember.deleteSpace(space1,300000);
		Utils.pause(3000);
		mMember.deleteSpace(space2,300000);	
	}

	/**
	 * Case ID:99194.
	 * Test Case Name: Renaming a Space should be correctly updated in Page Info Layout of a related page
	 * Pre-Condition: User is member of Space 1, Space 2, Space 3

		Wiki of "Space 1" has following pages:
		- Page 1
		- Page 2

		Wiki of "Space 2" has following pages:
		- Page A
		- Page B

		Wiki of "Space 3" has following pages:
		- Page a
		- Page b

		"Page 1 " of "Space 1" wiki has relations with:
		-- "Page A" from "Space 2"
		-- "Page a" from "Space 3"
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/13 17:34:46
	 */
	@Test
	public  void test10_RenamingASpaceShouldBeCorrectlyUpdatedInPageInfoLayoutOfARelatedPage() {
		info("Test 10: Renaming a Space should be correctly updated in Page Info Layout of a related page");
		String space1 = "Space99194A";
		String space2 = "Space99194B";
		String title1 = "Page 1";
		String title2 = "Page A";
		String wikiPath = "Wiki Home";
		String spaceUpdate = "Space Update";

		//Pre-Condition: 
		info("Create all space and page");
		mMember.goToAllSpaces();
		mMember.addNewSpace(space2, "");
		mMember.goToSpaceMenu("Wiki");
		addBlankWikiPage(title2, title2, 0);
		Utils.pause(1000);

		mMember.goToAllSpaces();
		mMember.addNewSpace(space1, "");
		mMember.goToSpaceMenu("Wiki");
		addBlankWikiPage(title1, title1, 0);
		Utils.pause(1000);

		info("Add Relations of page1");
		addRelatedPage(wikiPath, title2, space2, true);
		Utils.pause(500);

		/*Step 1:
		 *Input Data: 	- Go to "Space 3"
		 *Expected Outcome: - Activity stream of "Space 3" is displayed	*/				
		/*Step 2: 
		 *Input Data: 
		- Go to "Space Management"
		- Renamed "Space 3" to "Space 3 renamed"
		 *Expected Outcome: - Space has been renamed to "Space 3 renamed"		*/
		mMember.goToAllSpaces();
		mMember.editSpace(space2, spaceUpdate, "", false, "");

		/*Step 3: 
		 *Input Data: - Go to "Page 1 " of "Space 1" wiki
		 *Expected Outcome: - Wiki is displaying "Page 1"		*/
		mMember.accessSpace(space1);
		mMember.goToSpaceMenu("Wiki");
		click(By.linkText(title1));

		/*Step 4: 
		 *Input Data: 
		- Open "More" Menu
		- Select "Page Info"
		 *Expected Outcome: - Page infos of Page 1 are diplayed	*/
		goToPageInfo(null, wikiPath);
		Utils.pause(1000);

		/*Step 5: 
		 *Input Data: - Check updates in Related pages
		 *Expected Outcome: - Wiki of "Page a" is "Space 3 renamed"	*/ 
		waitForAndGetElement(By.xpath(ELEMENT_RELATED_PAGE_SPACE.replace("${spaceName}", spaceUpdate)));

		//Delete data test
		mMember.goToAllSpaces();
		mMember.deleteSpace(space1,300000);
		Utils.pause(3000);
		mMember.deleteSpace(spaceUpdate,300000);	
	}

	/**
	 * Case ID:99195.
	 * Test Case Name: Add 2 relations from 2 different spaces.
	 * Pre-Condition: User is member of Space 1, Space 2, Space 3

		Wiki of "Space 1" has following pages:
		- Page 1
		- Page 2

		Wiki of "Space 2" has following pages:
		- Page A
		- Page B

		Wiki of "Space 3" has following pages:
		- Page a
		- Page b
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/13 17:34:46
	 */
	@Test
	public  void test11_Add2RelationsFrom2DifferentSpaces() {
		info("Test 11: Add 2 relations from 2 different spaces");
		String space1 = "Space99195A";
		String space2 = "Space99195B";
		String space3 = "Space99195C";
		String title1 = "Page 1";
		String title2 = "Page A";
		String title3 = "Page a";
		String wikiPath = "Wiki Home";	

		//Pre-Condition: 
		info("Create all space and page");
		mMember.goToAllSpaces();
		mMember.addNewSpace(space2, "");
		mMember.goToSpaceMenu("Wiki");
		addBlankWikiPage(title2, title2, 0);
		Utils.pause(1000);

		mMember.goToAllSpaces();
		mMember.addNewSpace(space3, "");
		mMember.goToSpaceMenu("Wiki");
		addBlankWikiPage(title3, title3, 0);
		Utils.pause(1000);

		mMember.goToAllSpaces();
		mMember.addNewSpace(space1, "");
		mMember.goToSpaceMenu("Wiki");
		addBlankWikiPage(title1, title1, 0);
		Utils.pause(1000);


		/*Step 1: 
		 * - Go to "Space 1" wiki 
		 *Expected Outcome: - Wiki of "Space 1" is displayed		*/
		/*Step 2: 
		 *Input Data: - Open "Page 1"
		 *Expected Outcome: - Page 1 is displayed in the wiki		*/
		/*Step 3: 
		 *Input Data: 
		 - Open "More" Menu
		 - Select "Page Info"
		 *Expected Outcome: - Page infos of Page 1 are diplayed		*/
		/*Step 4: 
		 *Input Data: - On "Related Page Layout" click on button "Add More Relations"
		 *Expected Outcome: - The popup to select a related page is displayed		*/
		/*Step 5: 
		 *Input Data: - Open Space switcher component
		 *Expected Outcome: - The list of space swticher options is displayed	*/ 
		/*Step 6: 
		 *Input Data: - Select "Space 2"
		 *Expected Outcome: - Wiki tree of "Space 2" is displayed on the container below the space switcher	*/ 
		/*Step 7: 
		 *Input Data: 
		- Select "Page A"
		- Click on "Select" button
		 *Expected Outcome: 
		 - Popup is closed
		 - "Page A" is added as a related pages on page info layout	*/ 
		info("Add Relations with pageA");
		addRelatedPage(wikiPath, title2, space2, true);
		Utils.pause(1000);

		/*Step 8: 
		 *Input Data: - On "Related Page Layout" click on button "Add More Relations"
		 *Expected Outcome: - The popup to select a related page is displayed	*/ 
		/*Step 9: 
		 *Input Data: - Open Space switcher component
		 *Expected Outcome: - The list of space swticher options is displayed	*/ 
		/*Step 10: 
		 *Input Data: - Select "Space 3"
		 *Expected Outcome: - Wiki tree of "Space 3" is displayed on the container below the space switcher	*/ 
		/*Step 11: 
		 *Input Data: 
		- Select "Page a"
		- Click on "Select" button
		 *Expected Outcome: 
		 - Popup is closed
		 - "Page a" is added as a related pages on page info layout
         - "Page A" is still displayed as a related pages on page info layout	*/ 
		info("Add Relations with page a");
		WebElement element = waitForAndGetElement(ELEMENT_ADD_MORE_RELATION_BUTTON);
		((JavascriptExecutor)driver).executeScript("arguments[0].click();", element);
		click(ELEMENT_SELECT_SPACE);
		click(ELEMENT_SPACE_NAME_SELECTED.replace("${space}", space3.toLowerCase()));
		click(By.xpath(ELEMENT_SELECTED_PAGE.replace("${relatedPage}", title3)));
		Utils.pause(500);
		click(button.ELEMENT_SELECT_BUTTON);
		Utils.pause(1000);
		waitForAndGetElement(ELEMENT_RELATED_PAGE.replace("${relatedPage}", title3));

		//Delete data test
		mMember.goToAllSpaces();
		mMember.deleteSpace(space1,300000);
		Utils.pause(3000);
		mMember.deleteSpace(space2,300000);	
		Utils.pause(3000);
		mMember.deleteSpace(space3,300000);	
	}

	/**
	 * Case ID:99196.
	 * Test Case Name: Add related popup must display the currently browsed space by default.
	 * Pre-Condition: User is member of Space 2
		Space 2 wiki has following pages:
		- Page 1
		- Page 2
		--- Sub-Page 1
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/13 17:34:46
	 */
	@Test
	public  void test12_AddRelatedPopupMustDisplayTheCurrentlyBrowsedSpaceByDefault() {
		info("Test 12: Add related popup must display the currently browsed space by default");
		String spaceName = "Space99196";
		String title1 = "Page 1";
		String title2 = "Page 2";
		String wikiPath = "Wiki Home";

		//Pre-Condition: 
		info("Create all space and page");
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, "");
		mMember.goToSpaceMenu("Wiki");
		addBlankWikiPage(title1, title1, 0);
		Utils.pause(1000);
		addBlankWikiPage(title2, title2, 0);
		Utils.pause(1000);

		/*Step 1: - Go into "Space 2" wiki
		 *Expected Outcome: - "Space 2 " wiki is displayed		*/
		/*Step 2: 
		 *Input Data: 
		- Open "More" Menu
		- Select "Page Info"
		 *Expected Outcome: - Page Info of "Wiki Home" page are displayed.		*/
		info("Open Page Info");
		goToPageInfo(null, wikiPath);
		Utils.pause(1000);

		/*Step 3: 
		 *Input Data: - On the part dedicated to related page, click on the button "Add More Relations"
		 *Expected Outcome: 
		 - Popup to select a page is displayed
		 - Label "Select the space:" with the space switcher are displayed */
		info("Click on Add More button");
		WebElement element = waitForAndGetElement(ELEMENT_ADD_MORE_RELATION_BUTTON);
		((JavascriptExecutor)driver).executeScript("arguments[0].click();", element);
		waitForAndGetElement(ELEMENT_SELECT_SPACE);

		/*Step 4: 
		 *Input Data: - Check space switcher component
		 *Expected Outcome: - Space switcher component is displaying "Space 2"	*/
		info("Check space default");
		waitForAndGetElement(By.xpath(ELEMENT_RELATED_PAGE_SPACE_DEFAUT.replace("${spaceName}", spaceName)));

		//Delete data test
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName,300000);
	}

	/**
	 * Case ID:99197.
	 * Test Case Name: Add relation to a page from another space.
	 * Pre-Condition: User is member of Space 1 and Space 2

		Wiki of "Space 1" has following pages:
		- Page 1
		- Page 2

		Wiki of "Space 2" has following pages:
		- Page A
		- Page B
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/13 17:34:46
	 */
	@Test
	public  void test13_AddRelationToAPageFromAnotherSpace() {
		info("Test 13: Add relation to a page from another space");
		String space1 = "Space99197A";
		String space2 = "Space99197B";
		String title1 = "Page 1";
		String title2 = "Page A";
		String wikiPath = "Wiki Home";	

		//Pre-Condition: 
		info("Create all space and page");
		mMember.goToAllSpaces();
		mMember.addNewSpace(space2, "");
		mMember.goToSpaceMenu("Wiki");
		addBlankWikiPage(title2, title2, 0);
		Utils.pause(1000);

		mMember.goToAllSpaces();
		mMember.addNewSpace(space1, "");
		mMember.goToSpaceMenu("Wiki");
		addBlankWikiPage(title1, title1, 0);
		Utils.pause(1000);

		/*Step 1: 
		 - Go to "Space 1" wiki 
		 *Expected Outcome: - Wiki of "Space 1" is displayed		*/
		/*Step 2:
		 *Input Data: 
		- Open "Page 1"
		 *Expected Outcome: - Page 1 is displayed in the wiki		*/
		/*Step 3: 
		 *Input Data: 
		- Open "More" Menu
		- Select "Page Info"
		 *Expected Outcome: - Page infos of Page 1 are diplayed	*/
		/*Step 4: 
		 *Input Data: - On "Related Page Layout" click on button "Add More Relations"
		 *Expected Outcome: - The popup to select a related page is displayed	*/
		/*Step 5: 
		 *Input Data: 
		- Open Space switcher component
		 *Expected Outcome: - The list of space swticher options is displayed		*/
		/*Step 6: 
		 *Input Data: 
		- Select "Space 2"
		 *Expected Outcome: - Wiki tree of "Space 2" is displayed on the container below the space switcher		*/
		/*Step 7:
		 *Input Data: 
		- Select "Page A"
		- Click on "Select" button
		 *Expected Outcome: 
		- Popup is closed
		- "Page A" is added as a related pages on page info layout	*/ 
		info("Add Relations with pageA");
		addRelatedPage(wikiPath, title2, space2, true);
		Utils.pause(1000);

		//Delete data test
		mMember.goToAllSpaces();
		mMember.deleteSpace(space1,300000);
		Utils.pause(3000);
		mMember.deleteSpace(space2,300000);	
	}

	/**
	 * Case ID:99198.
	 * Test Case Name: Add relation to a page from the same space.
	 * Pre-Condition: 
	 * User is member of Space 1
		Wiki of "Space 1" has following pages:
		- Page 1
		- Page 2
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/13 17:34:46
	 */
	@Test
	public  void test14_AddRelationToAPageFromTheSameSpace() {
		info("Test 14 Add relation to a page from the same space");
		String spaceName = "Space99198";
		String title1 = "Page 1";
		String title2 = "Page 2";
		String wikiPath = "Wiki Home";

		//Pre-Condition: 
		info("Create all space and page");
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, "");
		mMember.goToSpaceMenu("Wiki");
		addBlankWikiPage(title1, title1, 0);
		Utils.pause(1000);
		click(By.linkText(wikiPath));
		addBlankWikiPage(title2, title2, 0);
		Utils.pause(1000);

		/*
		- Go to "Space 1" wiki 
		 *Expected Outcome: - Wiki of "Space 1" is displayed		*/
		/*
		- Open "Page 1" 
		 *Input Data: 
		 *Expected Outcome: - Page 1 is displayed in the wiki	*/
		/*- Open "More" Menu
		  - Select "Page Info"
		 *Input Data: 
		 *Expected Outcome: - Page infos of Page 1 are diplayed	*/
		/*
		- On "Related Page Layout" click on button "Add More Relations"
		 *Input Data: 
		 *Expected Outcome: - The popup to select a related page is displayed		*/
		/*
		- Select "Page 2"
		- Click on "Select" button
		 *Input Data: 
		 *Expected Outcome: 
		 - Popup is closed
		 - "Page 2" is added as a related pages on page info layout	*/ 
		info("Open Page Info");
		mouseOverAndClick(ELEMENT_MORE_LINK);
		mouseOverAndClick(ELEMENT_PAGE_INFO_LINK);
		Utils.pause(1000);
		info("Add Relations page");
		WebElement element = waitForAndGetElement(ELEMENT_ADD_MORE_RELATION_BUTTON);
		((JavascriptExecutor)driver).executeScript("arguments[0].click();", element);
		click(By.xpath(ELEMENT_SELECTED_PAGE.replace("${relatedPage}", title1)));
		Utils.pause(500);
		click(button.ELEMENT_SELECT_BUTTON);
		Utils.pause(1000);
		waitForAndGetElement(ELEMENT_RELATED_PAGE.replace("${relatedPage}", title1));

		//Delete data test
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName,300000);
	}

	/**
	 * Case ID:99199.
	 * Test Case Name: User should be able to select the currently browsed space.
	 * Pre-Condition: 
	 * User is member of Space 2		
		Wiki of "Space 2" has following pages:
		- Page 1
		- Page 2
		--- Sub-Page 1
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/13 17:34:46
	 */
	@Test
	public  void test15_UserShouldBeAbleToSelectTheCurrentlyBrowsedSpace() {
		info("Test 15: User should be able to select the currently browsed spaceView content of current version while view content of other version");
		String spaceName = "Space99199";
		String title1 = "Page 1";
		String title2 = "Page 2";
		String title3 = "Page 3";
		String wikiPath = "Wiki Home";

		//Pre-Condition: 
		info("Create all space and page");
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, "");
		mMember.goToSpaceMenu("Wiki");
		addBlankWikiPage(title1, title1, 0);
		Utils.pause(1000);
		click(By.linkText(wikiPath));
		addBlankWikiPage(title2, title2, 0);
		Utils.pause(1000);
		click(By.linkText(wikiPath));
		addBlankWikiPage(title3, title3, 0);
		Utils.pause(1000);

		/*
		- Go to "Space 2" wiki
		 *Expected Outcome: - Wiki Space 2 is displayed 	*/
		/*
		- Select "Page 2" the wiki tree
		 *Input Data: 
		 *Expected Outcome: - "Page 2" is displayed		*/
		/*- Open "More" Menu
		- Select "Page Info"
		 *Input Data: 
		 *Expected Outcome: - Page info of "Page 2" are displayed	*/
		info("Open Page Info");
		mouseOverAndClick(ELEMENT_MORE_LINK);
		mouseOverAndClick(ELEMENT_PAGE_INFO_LINK);
		Utils.pause(1000);

		/*
		- On "Related pages" part, click on the button "Add More Relations"
		 *Input Data: 
		 *Expected Outcome: - The popup to select a related page is displayed	*/
		info("Click on Add More button");
		WebElement element = waitForAndGetElement(ELEMENT_ADD_MORE_RELATION_BUTTON);
		((JavascriptExecutor)driver).executeScript("arguments[0].click();", element);
		waitForAndGetElement(ELEMENT_SELECT_SPACE);

		/*
		- Open Space switcher component
		 *Input Data: 
		 *Expected Outcome: - Space switcher component is displaying its list of options with "Space 2"		*/
		info("Check space default");
		waitForAndGetElement(By.xpath(ELEMENT_RELATED_PAGE_SPACE_DEFAUT.replace("${spaceName}", spaceName)));

		/*
		- Select "Space 2"
		 *Input Data: 
		 *Expected Outcome:- the page selection part is displaying the wiki tree of "Space 2"	*/ 
		info("The page selection part is displayed");
		click(By.xpath(ELEMENT_RELATED_PAGE_SPACE_DEFAUT.replace("${spaceName}", spaceName)));
		Utils.pause(1000);
		waitForAndGetElement(By.xpath(ELEMENT_SELECTED_PAGE.replace("${relatedPage}", title1)));
		waitForAndGetElement(By.xpath(ELEMENT_SELECTED_PAGE.replace("${relatedPage}", title2)));

		//Delete data test
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName,300000);
	}

	/**
	 * Case ID:99200.
	 * Test Case Name: Check behaviors when long space name in Page Layout.
	 * Pre-Condition: User is member of space : "Check long title for a space 1"
		Wiki of "Check long title for a space 1" has following pages:
		- Page 1
		- Page 2
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/13 17:34:46
	 */
	@Test
	public  void test16_CheckBehaviorsWhenLongSpaceNameInPageLayout() {
		info("Test 16 Check behaviors when long space name in Page Layout");
		String spaceName = "Space99200CheckLongTitle";
		String title1 = "Page 1";
		String title2 = "Page 2";
		String wikiPath = "Wiki Home";

		//Pre-Condition: 
		info("Create all space and page");
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, "");
		mMember.goToSpaceMenu("Wiki");
		addBlankWikiPage(title1, title1, 0);
		Utils.pause(1000);
		click(By.linkText(wikiPath));
		addBlankWikiPage(title2, title2, 0);

		/*Step 1: 
		 - Go to "Check long title for a space 1" wiki 
		 *Expected Outcome: - Wiki of "Check long title for a space 1" is displayed	*/
		/*Step 2: 
		 *Input Data: - Open "Page 1"
		 *Expected Outcome: - Page 1 is displayed in the wiki		*/
		/*Step 3: 
		 *Input Data: - Open "More" Menu
		- Select "Page Info"
		 *Expected Outcome: - Page infos of Page 1 are diplayed		*/
		info("Open Page Info");
		mouseOverAndClick(ELEMENT_MORE_LINK);
		mouseOverAndClick(ELEMENT_PAGE_INFO_LINK);
		Utils.pause(1000);

		/*Step 4: 
		 *Input Data: - On "Related Page Layout" click on button "Add More Relations"
		 *Expected Outcome: - the popup is closed
		- "Page 2" is added as a related page on page info layout	*/		

		/*Step 5:
		 *Input Data: 
		- Select "Page 2"
		- Click on "Select" button
		 *Expected Outcome: 
		 - the popup is closed
		 - "Page 2" is added as a related page on page info layout		*/ 
		info("Add Relations page");
		WebElement element = waitForAndGetElement(ELEMENT_ADD_MORE_RELATION_BUTTON);
		((JavascriptExecutor)driver).executeScript("arguments[0].click();", element);
		click(By.xpath(ELEMENT_SELECTED_PAGE.replace("${relatedPage}", title1)));
		Utils.pause(500);
		click(button.ELEMENT_SELECT_BUTTON);
		Utils.pause(1000);
		waitForAndGetElement(ELEMENT_RELATED_PAGE.replace("${relatedPage}", title1));

		/*Step 5: 
		 *Input Data: 
		- Check Page Info Layout, on related page part
		 *Expected Outcome: - The space named is displayed correctly		*/ 
		waitForAndGetElement(By.xpath(ELEMENT_RELATED_PAGE_SPACE.replace("${spaceName}", spaceName)));

		//Delete data test
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName,300000);
	}

	/**
	 * Case ID:99201.
	 * Test Case Name: Check behaviors when long space name in Select Page popup.
	 * Pre-Condition: User is member of space : "Check long title for a space 1"
		Wiki of "Check long title for a space 1" has following pages:
		- Page 1
		- Page 2
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/13 17:34:46
	 */
	@Test
	public  void test17_CheckBehaviorsWhenLongSpaceNameInSelectPagePopup() {
		info("Test 17 Check behaviors when long space name in Select Page popup");
		String spaceName = "Space99201CheckLongTitle";
		String title1 = "Page 1";
		String title2 = "Page 2";
		String wikiPath = "Wiki Home";

		//Pre-Condition: 
		info("Create all space and page");
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, "");
		mMember.goToSpaceMenu("Wiki");
		addBlankWikiPage(title1, title1, 0);
		Utils.pause(1000);
		click(By.linkText(wikiPath));
		addBlankWikiPage(title2, title2, 0);

		/*Step 1: 
		 * - Go to "Check long title for a space 1" wiki 
		 *Expected Outcome: - Wiki of "Check long title for a space 1" is displayed		*/
		/*Step 2: 
		 *Input Data: 
		- Open "Page 1"
		 *Expected Outcome: - Page 1 is displayed in the wiki	*/
		/*Step 3: 
		 *Input Data: - Open "More" Menu
		 - Select "Page Info"
		 *Expected Outcome: - Page infos of Page 1 are diplayed		*/
		info("Open Page Info");
		mouseOverAndClick(ELEMENT_MORE_LINK);
		mouseOverAndClick(ELEMENT_PAGE_INFO_LINK);
		Utils.pause(1000);

		/*Step 4: 
		 *Input Data: 
		- On "Related Page Layout" click on button "Add More Relations"
		 *Expected Outcome: - The popup to select a related page is displayed		*/
		info("Add Relations page");
		WebElement element = waitForAndGetElement(ELEMENT_ADD_MORE_RELATION_BUTTON);
		((JavascriptExecutor)driver).executeScript("arguments[0].click();", element);		

		/*Step 5: 
		 *Input Data: - Check Space Switcher
		 *Expected Outcome: - "Check long title for a space 1" is displayed correctly		*/		
		info("Check space name");
		waitForAndGetElement(By.xpath(ELEMENT_RELATED_PAGE_SPACE_DEFAUT.replace("${spaceName}", spaceName)));

		//Delete data test
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName,300000);
	}

	/**
	 * Case ID:99202.
	 * Test Case Name: Check changes in Add related popup layout.
	 * Pre-Condition: User is member of Space 2
		Space 2 wiki has following pages:
		- Page 1
		- Page 2
		--- Sub-Page 1
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/13 17:34:46
	 */
	@Test
	public  void test18_CheckChangesInAddRelatedPopupLayout() {
		info("Test 18 Check changes in Add related popup layout");
		String spaceName = "Space99202";
		String title1 = "Page 1";
		String title2 = "Page 2";
		String wikiPath = "Wiki Home";

		//Pre-Condition: 
		info("Create all space and page");
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, "");
		mMember.goToSpaceMenu("Wiki");
		addBlankWikiPage(title1, title1, 0);
		Utils.pause(1000);
		click(By.linkText(wikiPath));
		addBlankWikiPage(title2, title2, 0);

		/*
		- Go into "Space 2" wiki
		 *Expected Outcome: - "Space 2 " wiki is displayed		*/
		/*
		- Open "More" Menu
		- Select "Page Info"
		 *Input Data: 
		 *Expected Outcome: - Page Info of "Wiki Home" page are displayed 		*/
		info("Open Page Info");
		mouseOverAndClick(ELEMENT_MORE_LINK);
		mouseOverAndClick(ELEMENT_PAGE_INFO_LINK);
		Utils.pause(1000);

		/*
		- On the part dedicated to related page, click on the button "Add More Relations"
		 *Input Data: 
		 *Expected Outcome: - Popup to select a page is displayed
		- Label "Select the space:" with the space switcher are displayed 		*/ 
		info("Add Relations page");
		WebElement element = waitForAndGetElement(ELEMENT_ADD_MORE_RELATION_BUTTON);
		((JavascriptExecutor)driver).executeScript("arguments[0].click();", element);		
		info("Label Select the spaces");
		waitForAndGetElement(ELEMENT_SELECT_SPACE);

		//Delete data test
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName,300000);
	}

	/**
	 * Case ID:99203.
	 * Test Case Name: Check changes in Page info layout.
	 * Pre-Condition: User is member of Space 2
		Space 2 wiki has following pages:
		- Page 1
		- Page 2
		--- Sub-Page 1
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/13 17:34:46
	 */
	@Test
	public  void test19_CheckChangesInPageInfoLayout() {
		info("Test 19: Check changes in Page info layout");
		String spaceName = "Space99203";
		String title1 = "Page 1";
		String title2 = "Page 2";
		String wikiPath = "Wiki Home";

		//Pre-Condition: 
		info("Create all space and page");
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, "");
		mMember.goToSpaceMenu("Wiki");
		addBlankWikiPage(title1, title1, 0);
		Utils.pause(1000);
		click(By.linkText(wikiPath));
		addBlankWikiPage(title2, title2, 0);

		/*
		- Go to "Space 2" wiki
		 *Expected Outcome: - Wiki Space 2 is displayed 		*/
		/*
		- Select "Page 2" the wiki tree
		 *Input Data: 
		 *Expected Outcome: - "Page 2" is displayed		*/
		/*
		- Open "More" Menu
		- Select "Page Info"
		 *Input Data: 
		 *Expected Outcome: Page info of "Page 2" are displayed 		*/
		mMember.accessSpace(spaceName);
		mMember.goToSpaceMenu("Wiki");
		click(By.linkText(title2));
		info("Open Page Info");
		mouseOverAndClick(ELEMENT_MORE_LINK);
		mouseOverAndClick(ELEMENT_PAGE_INFO_LINK);
		Utils.pause(1000);

		/*
		- On "Related pages" part, click on the button "Add More Relations"
		 *Input Data: 
		 *Expected Outcome: - The popup to select a related page is displayed	*/
		/*
		- Select "Page 1"
		- Click on "Select" button
		 *Input Data: 
		 *Expected Outcome: 
		- The popup is dismissed
		- Page 1 is added in related page part		*/
		info("Add Relations page");
		WebElement element = waitForAndGetElement(ELEMENT_ADD_MORE_RELATION_BUTTON);
		((JavascriptExecutor)driver).executeScript("arguments[0].click();", element);
		click(By.xpath(ELEMENT_SELECTED_PAGE.replace("${relatedPage}", title1)));
		Utils.pause(500);
		click(button.ELEMENT_SELECT_BUTTON);
		Utils.pause(1000);
		waitForAndGetElement(ELEMENT_RELATED_PAGE.replace("${relatedPage}", title1));

		/*
		- Check Related page table layout
		 *Input Data: 
		 *Expected Outcome: 
		- First column is Wiki and displaying "Space 2"
		- Second column is Related Pages and displaying "Wiki Home > Page 1"
		- Third column is Actions and displaying a bin icon	*/
		waitForAndGetElement(By.xpath(ELEMENT_RELATED_PAGE_HEAD_INDEX.replace("${index}","1").replace("${text}", "Wiki")));
		waitForAndGetElement(By.xpath(ELEMENT_RELATED_PAGE_HEAD_INDEX.replace("${index}", "2").replace("${text}", "Related Pages")));
		waitForAndGetElement(By.xpath(ELEMENT_RELATED_PAGE_HEAD_INDEX.replace("${index}", "3").replace("${text}", "Actions")));
		waitForAndGetElement(By.xpath(ELEMENT_RELATED_PAGE_COLUMN_SPACE_INDEX.replace("${spaceName}", spaceName).replace("${index}", "1")));
		waitForAndGetElement(By.xpath(ELEMENT_RELATED_PAGE_COLUMN_WIKI_HOME.replace("${index}", "2")));
		waitForAndGetElement(By.xpath(ELEMENT_RELATED_PAGE_COLUMN_WIKI_PAGE.replace("${index}", "2").replace("${relatedPage}", title1)));
		waitForAndGetElement(By.xpath(ELEMENT_RELATED_PAGE_COLUMN_ACTION_INDEX.replace("${index}", "3")));

		//Delete data test
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName,300000);
	}
}