package org.exoplatform.selenium.platform.wiki.functional.attachment;

import org.exoplatform.selenium.Button;
import org.exoplatform.selenium.platform.ManageAccount;
import static org.exoplatform.selenium.TestLogger.info;
import org.exoplatform.selenium.platform.wiki.BasicAction;
import org.openqa.selenium.By;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

/**
 * Migrate to PLF4
 * <li> Update By @author vuna2 </li>
 *
 */
public class Wiki_Attachment_Delete extends BasicAction{
	ManageAccount magAcc;
	Button button;

	@BeforeMethod
	public void setUpBeforeTest(){
		initSeleniumTest();
		driver.get(baseUrl);
		magAcc = new ManageAccount(driver);
		button = new Button(driver);

		magAcc.signIn(DATA_USER1, DATA_PASS); 
		goToWiki();
	}

	@AfterMethod
	public void afterTest(){
		driver.manage().deleteAllCookies();
		driver.quit();
	}

	/**
	 * Qmetry ID: 69741
	 * Case 01: Delete attach file for page
	 * Create a wiki page
	 * Scroll down, click Upload, choose an image
	 * verify attachment link
	 * Delete attachment
	 * Click Cancel
	 */
	@Test
	public  void test01_DeleteAttachment(){

		String DATA_WIKI_PAGE_NAME="Blank_Wiki_Page_With_Image";
		String DATA_WIKI_PAGE_CONTENT="Blank_Wiki_Page_With_Image_Content";
		String ATTACHMENT_NAME="Winter.jpg";
		String ATTACHMENT_PATH="TestData/"+ATTACHMENT_NAME+"";
		By ATTACHMENT_FILE_LINK=By.xpath("//*[text()='"+ATTACHMENT_NAME+"']");

		info("Delete attachment at wiki page");
		goToAddBlankPage();

		info("--Add a wiki page from blank--");
		addWikiPageSourceEditor(DATA_WIKI_PAGE_NAME, DATA_WIKI_PAGE_CONTENT);

		attachFileInWiki(ATTACHMENT_PATH, 2);
		waitForAndGetElement(ATTACHMENT_FILE_LINK);

		deleteAnAttachment(ATTACHMENT_NAME);
		waitForElementNotPresent(ATTACHMENT_FILE_LINK);

		/**	click(ELEMENT_CANCEL_BUTTON_ADD_PAGE);
		//click(ELEMENT_CANCEL_BUTTON);
		waitForTextPresent(MESSAGE_CANCEL_CREATE_PAGE);
		click(button.ELEMENT_OK_BUTTON);*/
	}

	/**
	 * Case ID:113788.
	 * Test Case Name: Delete an attachment in View mode.
	 * Pre-Condition: - A wiki page is already created with more than 2 attachments
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by phuongdt at 2014/09/24 16:09:43
	 */
	@Test
	public  void test02_DeleteAnAttachmentInViewMode() {
		info("Test 2: Delete an attachment in View mode");
		String DATA_WIKI_PAGE_NAME="wiki113788";
		String DATA_WIKI_PAGE_CONTENT="content113788";
		String ATTACHMENT_NAME1="KS_Wiki_Attachment_pdffile.pdf";
		String ATTACHMENT_NAME2="ECMS_DMS_SE_Upload_xmlfile.xml";
		String ATTACHMENT_PATH1="TestData/"+ATTACHMENT_NAME1+"";
		String ATTACHMENT_PATH2="TestData/"+ATTACHMENT_NAME2+"";
		By ATTACHMENT_FILE_LINK1=By.xpath("//*[text()='"+ATTACHMENT_NAME1+"']");
		By ATTACHMENT_FILE_LINK2=By.xpath("//*[text()='"+ATTACHMENT_NAME2+"']");
		
		info("Create data test");
		goToAddBlankPage();
		addWikiPageSourceEditor(DATA_WIKI_PAGE_NAME, DATA_WIKI_PAGE_CONTENT);
		attachFileInWiki(ATTACHMENT_PATH1, 2);
		waitForAndGetElement(ATTACHMENT_FILE_LINK1);
		attachFileInWiki(ATTACHMENT_PATH2, 2);
		waitForAndGetElement(ATTACHMENT_FILE_LINK2);
		click(ELEMENT_SAVE_BUTTON_ADD_PAGE);
		waitForAndGetElement(ELEMENT_ATTACHMENT_NUMBER.replace("${No}", "2"));
		
		/*Step Number: 1
		 *Step Name: Step 1: Open Attachments pane
		 *Step Description: 
			- Open the wiki page containing more than 2 attachments
			- Click the number of attachments at Info bar
		 *Input Data: 

		 *Expected Outcome: 
			- The wiki page is shown
			- The Attachments pane is shown at the bottom*/
		click(ELEMENT_ATTACHMENT_NUMBER.replace("${No}", "2"));
		waitForAndGetElement(ELEMENT_ATTACHMENT_TITLE.replace("${fileName}", ATTACHMENT_NAME1));
		waitForAndGetElement(ELEMENT_ATTACHMENT_TITLE.replace("${fileName}", ATTACHMENT_NAME2));
		waitForAndGetElement(ELEMENT_UPLOAD_NEW_FILE_BUTTON);
		
		/*Step number: 2
		 *Step Name: Step 2: Delete an attachment
		 *Step Description: 
			Click [Delete_icon] corresponding to aattachment
		 *Input Data: 

		 *Expected Outcome: 
			- The selected attachment is removed from Attachments pane
			- The number of attachments at Info bar is updated*/ 
		deleteAnAttachment(ATTACHMENT_NAME1);
		waitForAndGetElement(ELEMENT_ATTACHMENT_NUMBER.replace("${No}", "1"));
		waitForElementNotPresent(ELEMENT_ATTACHMENT_TITLE.replace("${fileName}", ATTACHMENT_NAME1));
		waitForAndGetElement(ELEMENT_ATTACHMENT_TITLE.replace("${fileName}", ATTACHMENT_NAME2));
		info("Clear data");
		deleteCurrentWikiPage();	
	}

	/**
	 * Case ID:113789.
	 * Test Case Name: Delete an attachment in Edit mode.
	 * Pre-Condition: - A wiki page is already with more than 2 attachments
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by phuongdt at 2014/09/24 16:09:43
	 */
	@Test
	public  void test03_DeleteAnAttachmentInEditMode() {
		info("Test 3: Delete an attachment in Edit mode");
		String DATA_WIKI_PAGE_NAME="wiki113789";
		String DATA_WIKI_PAGE_CONTENT="content113789";
		String ATTACHMENT_NAME1="KS_Wiki_Attachment_pdffile.pdf";
		String ATTACHMENT_NAME2="ECMS_DMS_SE_Upload_xmlfile.xml";
		String ATTACHMENT_PATH1="TestData/"+ATTACHMENT_NAME1+"";
		String ATTACHMENT_PATH2="TestData/"+ATTACHMENT_NAME2+"";
		By ATTACHMENT_FILE_LINK1=By.xpath("//*[text()='"+ATTACHMENT_NAME1+"']");
		By ATTACHMENT_FILE_LINK2=By.xpath("//*[text()='"+ATTACHMENT_NAME2+"']");
		
		info("Create data test");
		goToAddBlankPage();
		addWikiPageSourceEditor(DATA_WIKI_PAGE_NAME, DATA_WIKI_PAGE_CONTENT);
		attachFileInWiki(ATTACHMENT_PATH1, 2);
		waitForAndGetElement(ATTACHMENT_FILE_LINK1);
		attachFileInWiki(ATTACHMENT_PATH2, 2);
		waitForAndGetElement(ATTACHMENT_FILE_LINK2);
		click(ELEMENT_SAVE_BUTTON_ADD_PAGE);
		waitForAndGetElement(ELEMENT_ATTACHMENT_NUMBER.replace("${No}", "2"));
		
		/*Step Number: 1
		 *Step Name: Step 1: Open Attachments pane
		 *Step Description: 
			- Open the wiki page.
			- Select Edit
			- Scroll down to the bottom
		 *Input Data: 

		 *Expected Outcome: 
			- The wiki page is shown
			- The Attachments pane is shown at the bottom*/
		mouseOverAndClick(ELEMENT_EDIT_PAGE_LINK);
		waitForElementNotPresent(ELEMENT_EDIT_PAGE_LINK);
		waitForAndGetElement(ELEMENT_ATTACHMENT_TITLE.replace("${fileName}", ATTACHMENT_NAME1));
		waitForAndGetElement(ELEMENT_ATTACHMENT_TITLE.replace("${fileName}", ATTACHMENT_NAME2));
		waitForAndGetElement(ELEMENT_UPLOAD_NEW_FILE_BUTTON);
		
		/*Step number: 2
		 *Step Name: Step 2: Delete an attachment
		 *Step Description: 
			Click [Delete_icon] corresponding to aattachment
		 *Input Data: 

		 *Expected Outcome: 
			- The selected attachment is removed from Attachments pane
			- The number of attachments at Info bar is updated*/ 
		deleteAnAttachment(ATTACHMENT_NAME1);
		waitForElementNotPresent(ELEMENT_ATTACHMENT_TITLE.replace("${fileName}", ATTACHMENT_NAME1));
		waitForAndGetElement(ELEMENT_ATTACHMENT_TITLE.replace("${fileName}", ATTACHMENT_NAME2));
		click(ELEMENT_SAVE_BUTTON_ADD_PAGE);
		waitForAndGetElement(ELEMENT_ATTACHMENT_NUMBER.replace("${No}", "1"));
		info("Clear data");
		deleteCurrentWikiPage();	
	}
}

