package org.exoplatform.selenium.platform.forum.functional.forum.post;
import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.Button;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.ManageAccount.userType;
import org.exoplatform.selenium.platform.forum.ForumBase;
import org.exoplatform.selenium.platform.forum.ForumManageCategory;
import org.exoplatform.selenium.platform.forum.ForumManageForum;
import org.exoplatform.selenium.platform.forum.ForumManagePost;
import org.exoplatform.selenium.platform.forum.ForumManageTopic;
import org.openqa.selenium.By;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

/**
* @author phuongdt
*
*/
public class Forum_Forum_Post_Move extends ForumBase{
	ManageAccount magAc;
	ForumManageCategory mngCat;
	ForumManageForum mngFru;
	ForumManageTopic mngTopic;
	ForumManagePost mngPost;

	@BeforeMethod
	public void setUpBeforeTest(){
		initSeleniumTest();
		magAc = new ManageAccount(driver);
		mngCat = new ForumManageCategory(driver, this.plfVersion);
		mngFru = new ForumManageForum(driver, this.plfVersion);
		mngTopic = new ForumManageTopic(driver, this.plfVersion);
		mngPost = new ForumManagePost(driver, this.plfVersion);
		button = new Button(driver);

		magAc.signIn(DATA_USER1, DATA_PASS);
		goToForums();
	}

	@AfterMethod
	public void afterTest(){
		driver.manage().deleteAllCookies();
		driver.quit();
	}
	/**
	* Case ID:107032.
	* Test Case Name: Move Post of normal users by Administrator.
	* Pre-Condition: 
	* Post-Condition: 
	* Done with OSs and browsers : 
	* Generated by phuongdt at 2014/01/22 10:24:54
	*/
	@Test
	public  void test01_MovePostOfNormalUsersByAdministrator() {
		String titleCat = "Category 107032";
		String titleForum = "Forum 107032";
		String titleTop1 = "Topic 1070321";
		String titleTop2 = "Topic 1070322";
		String post1 = "Post 107032";
		
		info("Test 01 Move Post of normal users by Administrator");
		/*Step Number: 1
		*Step Name: Step 1: Create topic
		*Step Description: 
			- Login as administrator to create a new category, forum, 2 topics"Topic A.1.1" and "To move demo's post"
		*Input Data: 
			
		*Expected Outcome: 
			- Categories, forums, topics are created*/
		mngFru.addCategoryForum(titleCat, titleForum);
		mngTopic.startTopic(titleTop1, titleTop1, "", 0, null, true, true);
		mngTopic.startTopic(titleTop2, titleTop2, "", 0, null, true, true);

		/*Step number: 2
		*Step Name: Step 2: Add post(s) by normal users
		*Step Description: 
			- Log in as demo
			- Post a reply to "Topic A.1.1"
		*Input Data: 
			
		*Expected Outcome: 
			- Post(s) is created*/
		magAc.userSignIn(userType.DEVELOPER);
		goToForums();
		click(By.linkText(titleForum));
		click(By.linkText(titleTop1));
		mngPost.postReply(post1, post1, "", "");
		
		/*Step number: 3
		*Step Name: Step 3: Move post by Admin
		*Step Description: 
			- Login as admin
			- Move demo's post from "Topic A.1.1" to "To move demo's post"
		*Input Data: 
			
		*Expected Outcome: 
			This post is removed from "Topic A.1.1" and move to "To move demo's post"*/
		magAc.userSignIn(userType.ADMIN);
		goToForums();
		click(By.linkText(titleForum));
		click(By.linkText(titleTop1));
		mngPost.movePost(post1, titleTop2);
		
		/*Step number: 4
		*Step Name: Step 4: Move to Other topic
		*Step Description: 
			- Move again demo's post from "To move demo's post" to another topic
		*Input Data: 
			
		*Expected Outcome: 
			Move successfully and no Ui error no exception in console*/ 
		click(By.linkText(titleCat));
		click(By.linkText(titleForum));
		click(By.linkText(titleTop2));
		mngPost.movePost(post1, titleTop1);
		
		//Clear data
		info("Clear data");
		click(By.linkText(titleCat));
		mngCat.deleteCategoryInForum(titleCat, true);
 	}
}
