package org.exoplatform.selenium.platform.plf.functional.homepagegadgets.suggestiongadget;

import static org.exoplatform.selenium.TestLogger.info;


import org.exoplatform.selenium.Button;
import org.exoplatform.selenium.Utils;
import org.exoplatform.selenium.platform.HomePageGadget;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.UserGroupManagement;
import org.exoplatform.selenium.platform.ManageAccount.userType;
import org.exoplatform.selenium.platform.social.Activity;
import org.exoplatform.selenium.platform.social.ManageMember;
import org.exoplatform.selenium.platform.social.PeopleConnection;
import org.exoplatform.selenium.platform.social.SpaceManagement;
import org.openqa.selenium.By;
import org.testng.annotations.*;

/**
 * @author chinhdtt
 * @date 10 Feb 2014
 */
public class PLF_HomepageGadgets_SuggestionGadget extends Activity{
	ManageAccount acc; 
	NavigationToolbar nav; 
	PeopleConnection pConn; 
	String user = "John Smith";
	String user1 = "Jack Miller";
	String user2 = "James Davis";
	String user3 = "Mary Williams";
	String user4 = "FQA VN";
	String user5 = "Root Root";
	ManageMember mMember; 
	HomePageGadget hGadget; 
	UserGroupManagement uGroup; 
	SpaceManagement mSpace;
	Button button; 

	@BeforeMethod
	public void beforeMethods(){	
		initSeleniumTest();
		driver.get(baseUrl);
		acc = new ManageAccount(driver, this.plfVersion);
		nav = new NavigationToolbar(driver, this.plfVersion);	
		pConn = new PeopleConnection(driver, this.plfVersion);
		mMember = new ManageMember(driver, this.plfVersion);	
		hGadget = new HomePageGadget(driver);
		uGroup = new UserGroupManagement(driver, this.plfVersion);
		mSpace = new SpaceManagement(driver, this.plfVersion);
		acc.signIn(DATA_USER1, DATA_PASS);		
		button = new Button(driver, this.plfVersion);
	}

	@AfterMethod
	public void afterMethods() {
		info("Logout portal");
		driver.manage().deleteAllCookies();
		driver.quit();
	}
	
	/** 
	 * Case ID: 121085.
	 * Test Case Name: Check the display of "Suggestions Porlet" when starting server with "minimal" profile
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * This case pending because can not start package with "minimal" profile activating
	 */
	@Test (groups = "pending")
	public  void test01_CheckDisplayOfSuggestionsPorletWhenStartingServerWithMinimalProfile() {
		info("Test 01: Check the display of Suggestions Porlet when starting server with minimal profile");
		/*
		- Open "setenv-customize.sh" in "bin" directory (Tomcat) 
		- Edit: EXO_PROFILES="minimal"
		- Start PLF
		 *Input Data: 
		 *Expected Outcome: 
		- PLF is start successfully.
		*/

		/*
		- Connect to intranet
		- Look at "Suggestions" gadget
		 *Input Data: 
		 *Expected Outcome: 
		- Only message "Suggestions Portlet requires the all profile. [Fix this]." is displayed 		
		*/
	}
	
	/**
	 * Case ID: 121154.
	 * Test Case Name: Display 1 People without common connections and 1 People with common connections.
	 * Pre-Condition: User A isn't connected with some users in Intranet (B, C, D)
	 * ------- User A is connected to X,Y B is connected to X, Y 
	 * ------- User A has common connections only with the user B
	 * ------- User A and User B aren't connected in Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/02/10 08:46:52
	 * BugID: https://jira.exoplatform.org/browse/PLF-5354
	 */
	@Test (priority=3)
	public  void test02_Display1PeopleWithoutCommonConnectionsAnd1PeopleWithCommonConnections() {
		info("Test 02: Display 1 People without common connections and 1 People with common connections");
		String username1 = getRandomString();
		String password1 = "gtn123";
		String firstName1 = "User";
		String lastName1 = "X";
		String email1 = username1+"@gmail.com";
		
		String username2 = getRandomString();
		String password2 = "gtn123";
		String firstName2 = "User";
		String lastName2 = "Y";
		String email2 = username2+"@gmail.com";

		info("Add 2 new users");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password1, password1, firstName1, lastName1, "", email1, null, null, false);
		Utils.pause(2000);		
		button.ok();
		acc.addNewUserAccount(username2, password2, password2, firstName2, lastName2, "", email2, null, null, false);
		Utils.pause(2000);
		button.ok();
		
		info("Demo user sent connection request to username1 and username2");
		acc.userSignIn(userType.DEVELOPER);
		nav.goToConnectionPage();
		pConn.connectPeople(username1);
		driver.navigate().refresh();
		pConn.connectPeople(username2);
		
		info("User B sent request to X, Y");
		acc.userSignIn(userType.DEVELOPER);
		nav.goToConnectionPage();
		pConn.connectPeople(user2);
		driver.navigate().refresh();
		pConn.connectPeople(user3);

		info("User X connect to A, B");
		acc.userSignIn(userType.AUTHOR);
		pConn.acceptInvitation(user);
		driver.navigate().refresh();
		pConn.acceptInvitation(user1);

		info("User Y connect to A, B");
		acc.userSignIn(userType.PUBLISHER);
		pConn.acceptInvitation(user);
		driver.navigate().refresh();
		pConn.acceptInvitation(user1);
		/*
		- Connect to Intranet
		 *Input Data: 
		 *Expected Outcome: 
		- The gadget "Suggestions" is displayed
		- A User B is displayed in the top of the list of suggestions
		- A second user who is the last registered user is displayed.		*/ 
		acc.userSignIn(userType.ADMIN);
		waitForAndGetElement(hGadget.ELEMENT_SUGGESTION_GADGET_FORM);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", user1));
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", firstName1+" "+lastName1));

		//Delete data test
		info("Delete users test");
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username1);
		pConn.removeConnection(user2);
		pConn.removeConnection(user3);
		info("User B remove connection");
		acc.userSignIn(userType.DEVELOPER);
		pConn.removeConnection(user2);
		pConn.removeConnection(user3);
	}

	/**
	 * Test case ID: 121155.
	 * Test case name: Display 1 space without members are connections and 1 space with members are connections.
	 * Pre-Condition: User A is connected with a member of space A User A isn't connected with members of space B
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/02/10 08:46:52
	 * Bug: https://jira.exoplatform.org/browse/PLF-6184
	 */
	@Test(priority=5)
	public  void test03_Display1SpaceWithoutMembersAreConnectionsAnd1SpaceWithMembersAreConnections() {
		info("Test 03: Display 1 space without members are connections and 1 space with members are connections");
		String nameSpace1 = "mySpace1"+getRandomNumber();
		String nameSpace2 = "mySpace2"+getRandomNumber();

		String username = getRandomString();
		String password = "gtn123";
		String firstName = "User";
		String lastName = "A";
		String email1 = username+"@gmail.com";
		
		info("Add new user");
		nav.goToNewStaff();
		acc.addNewUserAccount(username, password, password, firstName, lastName, "", email1, null, null, false);
		Utils.pause(2000);		
		button.ok();
		
		info("Add new space 1");
		nav.goToHomePage();
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace1,"");	
		
		info("Invite Mary to a member to space 1");
		goToMembers(nameSpace1);
		mMember.inviteSingleUser(userType.PUBLISHER);
		
		info("New user send connect request to member of space 1");
		acc.signIn(username, password);
		nav.goToConnectionPage();
		pConn.connectPeople(user3);
		acc.signOut();
		
		info("Member of space 1 accept connection request of New user");
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConn.acceptInvitation(firstName+" "+lastName);
		acc.signOut();
		
		info("Add new space2");
		acc.userSignIn(userType.ADMIN);
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace2,"");

		info("Invite Demo to a member to space 1");
		goToMembers(nameSpace1);
		mMember.inviteSingleUser(userType.DEVELOPER);
		
		/*
		- Connect to Intranet
		 *Input Data: 
		 *Expected Outcome: 
		- The gadget "Suggestions" is displayed
		- Space A is displayed in the top of the list of suggestions with "1 connections are member"
		- A second space B is displayed with "0 connections are member": is the first space alphabetically ordered from the list of spaces in Intranet 		*/ 
		//acc.userSignIn(userType.DEVELOPER);
		//pConn.acceptInvitation(user3);
		//nav.goToHomePage();
		acc.signIn(username, password);
		waitForAndGetElement(hGadget.ELEMENT_SUGGESTION_GADGET_FORM);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS_INDEX.replace("${index}","0").replace("${spaceName}", nameSpace1));
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS_INDEX.replace("${index}","1").replace("${spaceName}", nameSpace2));
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_STATUS_SPACE_SUGGESTION.replace("${spaceName}", nameSpace1));
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_STATUS_SPACE_SUGGESTION.replace("${spaceName}", nameSpace2));

		//Delete data test
		info("Remove connection");
		pConn.removeConnection(user3);
		acc.userSignIn(userType.ADMIN);
		info("Delete spaces test");
		mMember.goToAllSpaces();
		mMember.deleteSpace(nameSpace1, 300000);
		nav.driver.navigate().refresh();
		mMember.deleteSpace(nameSpace2, 300000);
	}
	
	/**
	 * Case ID: 121160.
	 * Test Case Name: Display 2 People and 2 Space suggestions.
	 * Pre-Condition: 
	 *      More than 2 peoples are members in Intranet 
	 *      More than 2 Spaces exist in Intranet 
	 *      User isn't connected to any spaces and people in the Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/02/10 08:46:52
	 * Updated by hatv at 2015/05/14
	 */
	@Test(priority=1)
	public  void test04_Display2PeopleAnd2SpaceSuggestions() {
		info("Test 04: Display 2 People and 2 Space suggestions");
		String nameSpace1 = "Space1"+getRandomNumber();
		String nameSpace2 = "Space2"+getRandomNumber();
		String nameSpace3 = "Space3"+getRandomNumber();
		
		String username1 = "aa"+getRandomString();
		String password = "gtn123";
		String firstName1 = "User";
		String lastName1 = "AAA";
		String email1 = username1+"@gmail.com";
		String username2 = "bb"+getRandomString();
		String firstName2 = "User";
		String lastName2 = "BBB";
		String email2 = username2+"@gmail.com";
		String username3 = "cc"+getRandomString();
		String firstName3 = "User";
		String lastName3 = "CCC";
		String email3 = username3+"@gmail.com";
		
		info("Add new space1");
		nav.goToHomePage();
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace1,"");	
		
		info("Add new space2");
		nav.goToHomePage();
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace2,"");

		info("Add new space3");
		nav.goToHomePage();
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace3,"");
		
		
		info("Add new 3 users");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password, password, firstName1, lastName1, "", email1, null, null, false);
		Utils.pause(2000);		
		button.ok();
		acc.addNewUserAccount(username2, password, password, firstName2, lastName2, "", email2, null, null, false);
		Utils.pause(2000);
		button.ok();
		acc.addNewUserAccount(username3, password, password, firstName3, lastName3, "", email3, null, null, false);
		Utils.pause(2000);
		button.ok();
		
		/*
		- Connect to Intranet
		 *Input Data: 
		 *Expected Outcome: 
		- The suggestion gadget is displayed in the right panel of the Intranet Homepage
		- The gadget displays 2 people suggestions and 2 Space suggestions		*/ 	
		info("View suggestion gadget");
		acc.userSignIn(userType.AUTHOR);
		waitForAndGetElement(hGadget.ELEMENT_SUGGESTION_GADGET_FORM);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", firstName3+" "+lastName3));
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", firstName2+" "+lastName2));
		waitForElementNotPresent(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", firstName1+" "+lastName1));
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace3));
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace2));
		waitForElementNotPresent(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace1));		

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		info("Delete spaces test");
		mMember.goToAllSpaces();
		mMember.deleteSpace(nameSpace1, 300000);
		nav.driver.navigate().refresh();
		mMember.deleteSpace(nameSpace2, 300000);	
		nav.driver.navigate().refresh();
		mMember.deleteSpace(nameSpace3, 300000);	
		
		acc.userSignIn(userType.ADMIN);
		info("Delete users test");
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username1);
		Utils.pause(1000);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username2);
		Utils.pause(1000);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username3);
	}

	/**
	 * Case ID: 121161.
	 * Test Case Name: Display 2 People with common connections.
	 * Pre-Condition: User A is not connected to user B or C User A has a common connection with User C
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/02/10 08:46:52
	 * Bug: https://jira.exoplatform.org/browse/PLF-6185
	 */
	@Test (groups = "errors")
	public  void test05_Display2PeopleWithCommonConnections() {
		info("Test 5: Display 2 People with common connections");
		String username1 = "aa"+getRandomString();
		String password = "gtn123";
		String firstName1 = "User";
		String lastName1 = "AAA";
		String email1 = username1+"@gmail.com";
		String username2 = "bb"+getRandomString();
		String firstName2 = "User";
		String lastName2 = "BBB";
		String email2 = username2+"@gmail.com";
		String username3 = "cc"+getRandomString();
		String firstName3 = "User";
		String lastName3 = "CCC";
		String email3 = username3+"@gmail.com";
		
		info("Add new 3 users");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password, password, firstName1, lastName1, "", email1, null, null, false);
		Utils.pause(2000);		
		button.ok();
		acc.addNewUserAccount(username2, password, password, firstName2, lastName2, "", email2, null, null, false);
		Utils.pause(2000);
		button.ok();
		acc.addNewUserAccount(username3, password, password, firstName3, lastName3, "", email3, null, null, false);
		Utils.pause(2000);
		button.ok();
				
		info("User A send connection request to User James");	
		acc.signIn(username1, password);
		nav.goToConnectionPage();
		pConn.connectPeople(user2);
		acc.signOut();
		
		info("User James accept connection request of User A");
		acc.userSignIn(userType.AUTHOR);
		nav.goToConnectionPage();
		pConn.acceptInvitation(firstName1+" "+lastName1);
		acc.signOut();
		
		info("User C send connection request to User James");	
		acc.signIn(username3, password);
		nav.goToConnectionPage();
		pConn.connectPeople(user2);
		acc.signOut();
		
		info("User James accept connection request of User C");
		acc.userSignIn(userType.AUTHOR);
		nav.goToConnectionPage();
		pConn.acceptInvitation(firstName3+" "+lastName3);
		acc.signOut();
		
		
		/*
		- Connect to Intranet with User A
		 *Input Data: 
		 *Expected Outcome: 
		- The gadget "Suggestions" is displayed
		- The User C is displayed in the top of the list of suggestions
		- The User B is displayed in the second position 		*/ 
		//acc.userSignIn(userType.ADMIN);
		acc.signIn(username1, password);
		waitForAndGetElement(hGadget.ELEMENT_SUGGESTION_GADGET_FORM);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", user3));
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", user2));
		
		//Delete data test
		info("User A remove connection");
		acc.signIn(username1, password);
		pConn.removeConnection(user2);
		
		info("User C remove connection");
		acc.signIn(username1, password);
		pConn.removeConnection(user2);

		info("Delete users test");
		acc.userSignIn(userType.ADMIN);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username1);
		Utils.pause(1000);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username2);
		Utils.pause(1000);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username3);
	}
	
	/**
	 * Case ID:121162.
	 * Test Case Name: Display 2 people without connections in common.
	 * Pre-Condition: 
	 *        More than 2 users are members in Intranet 
	 *        The User isn't connected with any member of Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/02/10 08:46:52
	 */
	@Test
	public  void test06_Display2PeopleWithoutConnectionsInCommon() {
		info("Test 06: Display 2 people without connections in common - Case ID:79608");
		String username1 = "aa"+getRandomString();
		String password = "gtn123";
		String firstName1 = "User";
		String lastName1 = "AAA"+getRandomString();
		String email1 = username1+"@gmail.com";
		String username2 = "bb"+getRandomString();
		String firstName2 = "User";
		String lastName2 = "BBB"+getRandomString();
		String email2 = username2+"@gmail.com";
		String username3 = "cc"+getRandomString();
		String firstName3 = "User";
		String lastName3 = "CCC"+getRandomString();
		String email3 = username3+"@gmail.com";

		//Pre-Condition
		info("Add new 3 users");
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password, password, firstName1, lastName1, "", email1, null, null, false);
		Utils.pause(2000);		
		button.ok();
		acc.addNewUserAccount(username2, password, password, firstName2, lastName2, "", email2, null, null, false);
		Utils.pause(2000);
		button.ok();
		acc.addNewUserAccount(username3, password, password, firstName3, lastName3, "", email3, null, null, false);
		Utils.pause(2000);
		button.ok();
		/*
		- Connect to Intranet
		 *Input Data: 
		 *Expected Outcome: 
		- The Suggestion Gadget is displayed
		- 2 People are suggested
		- People displayed are Last users that has joined the Intranet		*/ 
		info("View suggestion gadget");
		nav.goToHomePage();
		waitForAndGetElement(hGadget.ELEMENT_SUGGESTION_GADGET_FORM);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", firstName3+" "+lastName3));
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", firstName2+" "+lastName2));
		waitForElementNotPresent(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", firstName1+" "+lastName1));
		
		//Delete data test
		info("Delete users test");
		acc.userSignIn(userType.ADMIN);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username1);
		Utils.pause(1000);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username2);
		Utils.pause(1000);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username3);
	}

	/**
	 * Case ID: 121163.
	 * Test Case Name: Display 2 space without members are connections.
	 * Pre-Condition: More than 2 spaces exist in Intranet, users who are members of spaces are not connected to the user
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/02/10 08:46:52
	 */
	@Test(priority=4)
	public  void test07_Display2SpaceWithoutMembersAreConnections() {
		info("Test 07: Display 2 space without members are connections");
		String nameSpace1 = "space79611a";
		String nameSpace2 = "space79611b";
		String nameSpace3 = "space79611c";

		String username = "aa"+getRandomString();
		String password = "gtn123";
		String firstName = "User";
		String lastName = "AAA"+getRandomString();
		String email = username+"@gmail.com";
		
		info("Add a new user");
		nav.goToNewStaff();
		acc.addNewUserAccount(username, password, password, firstName, lastName, "", email, null, null, false);
		Utils.pause(2000);		
		button.ok();
		
		info("Add new space1");
		nav.goToHomePage();
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace1,"");	
		
		info("Invite Mary to a member to space 1");
		goToMembers(nameSpace1);
		mMember.inviteSingleUser(userType.PUBLISHER);
		
		info("Add new space2");
		nav.goToHomePage();
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace2,"");
		
		info("Invite James to a member to space 2");
		goToMembers(nameSpace2);
		mMember.inviteSingleUser(userType.AUTHOR);
		
		info("Add new space3");
		nav.goToHomePage();
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace3,"");
		
		info("Invite Demo to a member to space 3");
		goToMembers(nameSpace3);
		mMember.inviteSingleUser(userType.DEVELOPER);

		/*
		- Connect to Intranet
		 *Input Data: 
		 *Expected Outcome: 
		- The Suggestion Gadget is displayed
		- 2 Spaces are suggested
		- Space displayed are the two last spaces that has been created		*/ 
		info("View suggestion gadget");
		acc.signIn(username, password);
		waitForAndGetElement(hGadget.ELEMENT_SUGGESTION_GADGET_FORM);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace3),5000,1,2);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace2),5000,1,2);
		waitForElementNotPresent(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace1));

		//Delete data test
		info("Delete spaces test");
		acc.userSignIn(userType.ADMIN);
		mMember.goToAllSpaces();
		mMember.deleteSpace(nameSpace1, 300000);
		nav.driver.navigate().refresh();
		mMember.deleteSpace(nameSpace2, 300000);
		nav.driver.navigate().refresh();
		mMember.deleteSpace(nameSpace3, 300000);
		
		info("Delete user test");
		acc.userSignIn(userType.ADMIN);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username);
	}

	/**
	 * Case ID:121236.
	 * Test Case Name: Display buttons "Connect and revoke" for people suggestion.
	 * Pre-Condition: The gadget suggestions contains a people suggestion
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/02/10 08:46:52
	 */
	@Test
	public  void test08_DisplayButtonsConnectAndRevokeForPeopleSuggestion() {
		info("Test 08: Display buttons Connect and revoke for people suggestion");
		String username = "aa"+getRandomString();
		String password = "gtn123";
		String firstName = "User";
		String lastName = "AAA"+getRandomString();
		String email = username+"@gmail.com";
		
		info("Add a new user");
		nav.goToNewStaff();
		acc.addNewUserAccount(username, password, password, firstName, lastName, "", email, null, null, false);
		Utils.pause(2000);		
		button.ok();
		
		/*
		- Connect to Intranet
		- From the gadget "Suggestions", move the mouse over a People suggestion labels 
		 *Input Data: 
		 *Expected Outcome: 
		- "Connect" is displayed as a bouton
		- "Revoke" is displayed as a cross		*/ 
		acc.userSignIn(userType.DEVELOPER);
		waitForAndGetElement(hGadget.ELEMENT_SUGGESTION_GADGET_FORM);
		info("Move mouse over space suggestion");
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", firstName+" "+lastName));
		
		mouseOver(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", firstName+" "+lastName), true);
		Utils.pause(2000);
		waitForAndGetElement(hGadget.ELEMENT_CONNECT_USER_SUGGESTIONS.replace("${peopleName}", firstName+" "+lastName),2000,2);
		waitForAndGetElement(hGadget.ELEMENT_REMOVE_USER_SUGGESTIONS.replace("${peopleName}", firstName+" "+lastName),2000,2);
		
		info("Delete user test");
		acc.userSignIn(userType.ADMIN);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username);
	}

	/**
	 * Case ID: 121237.
	 * Test Case Name: Display buttons "Join and revoke" for space suggestion.
	 * Pre-Condition: The gadget suggestions contains a space suggestion
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/02/10 08:46:52
	 */
	@Test(priority=6)
	public  void test09_DisplayButtonsJoinAndRevokeForSpaceSuggestion() {
		info("Test 09: Display buttons Join and revoke for space suggestion");

		String nameSpace1 = "mySpace1"+getRandomNumber();
		String nameSpace2 = "mySpace2"+getRandomNumber();

		//Pre-Condition
		info("Add new space1");
		nav.goToHomePage();
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace1,"");	
		
		info("Add new space2");
		nav.goToHomePage();
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace2, "", "", "Open", "", "");

		/*
		- Connect to Intranet
		- From the gadget "Suggestions", move the mouse over a Space suggestion labels 
		 *Input Data: 
		 *Expected Outcome: 
		- "Join" and "Revoke" buttons are displayed for "Public" Space
		- "Connect" and "Revoke" buttons are displayed for "Private" Space		*/ 
		acc.userSignIn(userType.DEVELOPER);
		waitForAndGetElement(hGadget.ELEMENT_SUGGESTION_GADGET_FORM);
		
		info("for Public Space");
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace2));
		mouseOver(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace2), true);
		waitForAndGetElement(hGadget.ELEMENT_JOIN_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace2),2000,2);
		waitForAndGetElement(hGadget.ELEMENT_REMOVE_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace2),2000,2);

		info("for Private Space");
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace1),5000,1,2);
		mouseOver(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace1), true);
		waitForAndGetElement(hGadget.ELEMENT_REQUEST_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace1),2000,2);
		waitForAndGetElement(hGadget.ELEMENT_REMOVE_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace1),2000,2);

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		info("Delete spaces test");
		mMember.goToAllSpaces();
		mMember.deleteSpace(nameSpace1, 300000);		
		nav.driver.navigate().refresh();
		mMember.deleteSpace(nameSpace2, 300000);
	}
	
	/** 
	 * Case ID: 121335.
	 * Test Case Name: Display suggestion gadget when there are only 2 users.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/02/10 08:46:52
	 * This case pending because can not start package without extension. 
	 */
	@Test (groups = "pending")
	public  void test10_DisplaySuggestionGadgetWhenThereAreOnly2Users() {
		info("Test 10: Display suggestion gadget when there are only 2 users");
		/*
		- Start a fresh package without extension
		- Set up an account eg fqa
		 *Input Data: 
		 *Expected Outcome: 
		- Server starts successfully
		- Only 2 users exist: root and fqa		*/

		/*
		- Log in as root in a browser
		- Log in as fqa in a browser
		- Refresh both browser
		 *Input Data: 
		 *Expected Outcome: 
		- In browser with fqa, root is listed in suggestion gadget 
		- In browser with root, fqais listed in suggestion gadget 		*/


		/*
		- From root connects to fqa
		- fqa accepts
		- Stand at intranet homepage, Refresh both browsers
		 *Input Data: 
		 *Expected Outcome: 
		- Suggestion gadget is not shown.		*/ 
	}
	
	/** 
	 * Case ID: 121442.
	 * Test Case Name: Gadget "Suggestions" isn't displayed when no suggestions are available
	 * This case has to run first when running test suite because of the pre-condition:  the user is connected to everyone
	 */
	@Test
	public  void test11_SuggestionsGadgetNotDisplayWhenNoSuggestionAvailable() {
		info("Test 11: Gadget Suggestions isn't displayed when no suggestions are available");
		String username = "aa"+getRandomString();
		String password = "gtn123";
		String firstName = "User";
		String lastName = "AAA"+getRandomString();
		String email = username+"@gmail.com";
		
		info("Add a new user");
		nav.goToNewStaff();
		acc.addNewUserAccount(username, password, password, firstName, lastName, "", email, null, null, false);
		Utils.pause(2000);		
		button.ok();
		
		info("New user send connection request to all users in intranet");	
		
		info("New user send connection request to John");	
		acc.signIn(username, password);
		nav.goToConnectionPage();
		pConn.connectPeople(user);
		nav.driver.navigate().refresh();
		pConn.connectPeople(user1);
		nav.driver.navigate().refresh();
		pConn.connectPeople(user2);
		nav.driver.navigate().refresh();
		pConn.connectPeople(user3);
		nav.driver.navigate().refresh();
		pConn.connectPeople(user4);
		nav.driver.navigate().refresh();
		pConn.connectPeople(user5);
		nav.driver.navigate().refresh();
		
		info("John accept connection request of New user");
		acc.userSignIn(userType.ADMIN);
		nav.goToConnectionPage();
		pConn.acceptInvitation(firstName+" "+lastName);
		acc.signOut();
		
		info("Demo accept connection request of New user");
		acc.userSignIn(userType.DEVELOPER);
		nav.goToConnectionPage();
		pConn.acceptInvitation(firstName+" "+lastName);
		acc.signOut();
		
		info("James accept connection request of New user");
		acc.userSignIn(userType.AUTHOR);
		nav.goToConnectionPage();
		pConn.acceptInvitation(firstName+" "+lastName);
		acc.signOut();
		
		info("Mary accept connection request of New user");
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConn.acceptInvitation(firstName+" "+lastName);
		acc.signOut();
		
		info("Root accept connection request of New user");
		acc.userSignIn(userType.ROOT);
		nav.goToConnectionPage();
		pConn.acceptInvitation(firstName+" "+lastName);
		acc.signOut();
		
		info("FQA accept connection request of New user");
		acc.userSignIn(userType.MEMBER);
		nav.goToConnectionPage();
		pConn.acceptInvitation(firstName+" "+lastName);
		acc.signOut();
		
		acc.userSignIn(userType.DEVELOPER);
		waitForElementNotPresent(hGadget.ELEMENT_SUGGESTION_GADGET_FORM,2000,2);
		
		//Delete data test
		info("Delete user test");
		acc.userSignIn(userType.ADMIN);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username);
	}

	/** 
	 * Case ID: 121443.
	 * Test Case Name: Gadget "Suggestions" isn't displayed when only one user is available in the product
	 * This case pending because of the pre-condition "only one user is available in the product" 
	 */
	@Test (groups = "pending")
	public  void test12_SuggestionsGadgetNotDisplayWhenOnlyOneSuggestionAvailable() {
		info("Test 12: Gadget Suggestions isn't displayed when only one user is available in the product");
		/*
		- Start a fresh package without extension
		- Set up an account eg fqa
		 *Input Data: 
		 *Expected Outcome: 
		- Server starts successfully
		- Only 2 users exist: root and fqa		*/

		/*
		- Log in as root in a browser
		- Log in as fqa in a browser
		- Refresh both browser
		 *Input Data: 
		 *Expected Outcome: 
		- In browser with fqa, root is listed in suggestion gadget 
		- In browser with root, fqais listed in suggestion gadget 		*/


		/*
		- From root connects to fqa
		- fqa accepts
		- Stand at intranet homepage, Refresh both browsers
		 *Input Data: 
		 *Expected Outcome: 
		- Suggestion gadget is not shown.		*/ 
	}
	
	/**
	 * Case ID:121679.
	 * Test Case Name: Remove a people suggestion from the gadget.
	 * Pre-Condition: Gadget "SUGGESTION" contains "people"
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/02/10 08:46:52
	 */
	@Test
	public  void test13_RemoveAPeopleSuggestionFromTheGadget() {
		info("Test 13 Remove a people suggestion from the gadget");
		String username = "aa"+getRandomString();
		String password = "gtn123";
		String firstName = "User";
		String lastName = "AAA"+getRandomString();
		String email = username+"@gmail.com";
		
		info("Add a new user");
		nav.goToNewStaff();
		acc.addNewUserAccount(username, password, password, firstName, lastName, "", email, null, null, false);
		Utils.pause(2000);		
		button.ok();
		/*
		- Connect to Intranet
		- From the gadget "Suggestion", move the mouse over the "people suggestion" label
		 *Input Data: 
		 *Expected Outcome: The button "Connect" and "X" icon are displayed		*/
		acc.userSignIn(userType.AUTHOR);
		info("View suggestion gadget");
		waitForAndGetElement(hGadget.ELEMENT_SUGGESTION_GADGET_FORM);
		info("Move mouse over user suggestion");
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", firstName+" "+lastName),5000,1,2);
		waitForAndGetElement(hGadget.ELEMENT_CONNECT_USER_SUGGESTIONS.replace("${peopleName}", firstName+" "+lastName),5000,1,2);
		waitForAndGetElement(hGadget.ELEMENT_REMOVE_USER_SUGGESTIONS.replace("${peopleName}", firstName+" "+lastName),5000,1,2);

		/*
		- Connect or revoke a people suggestion
		 *Input Data: 
		 *Expected Outcome: the suggestion fades out and it's removed permantelly from the gadget		*/
		hGadget.removeUserSuggestionsGadget(firstName+" "+lastName);
		waitForTextNotPresent(hGadget.ELEMENT_CONNECT_USER_SUGGESTIONS.replace("${peopleName}", firstName+" "+lastName));

		/*Reload the page
		 *Input Data: 
		 *Expected Outcome: The people suggestion is not suggested again.		*/ 
		driver.navigate().refresh();
		waitForTextNotPresent(hGadget.ELEMENT_CONNECT_USER_SUGGESTIONS.replace("${peopleName}", firstName+" "+lastName));
		
		//Delete data test
		info("Delete user test");
		acc.userSignIn(userType.ADMIN);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username);
	}
	
	/**
	 * Case ID:121680.
	 * Test Case Name: Remove a space suggestion from the gadget.
	 * Pre-Condition: Gadget "SUGGESTION" contains "Spaces"
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/02/10 08:46:52
	 * Bug: https://jira.exoplatform.org/browse/PLF-4496
	 * PLF-4411
	 */
	@Test
	public  void test14_RemoveASpaceSuggestionFromTheGadget() {
		info("Test 14 Remove a space suggestion from the gadget");
		String nameSpace = getRandomString();

		//Pre-Condition
		info("Add new space1");
		nav.goToHomePage();
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace,"");	

		/*- Connect to Intranet
		- From the gadget "Suggestion", move the mouse over the "space suggestion" label
		 *Input Data: 
		 *Expected Outcome: The button "Join" and "X" icon are displayed	*/	
		acc.userSignIn(userType.DEVELOPER);
		waitForAndGetElement(hGadget.ELEMENT_SUGGESTION_GADGET_FORM);
		info("Move mouse over space suggestion");
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace),5000,1,2);
		mouseOver(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace), true);
		waitForAndGetElement(hGadget.ELEMENT_REQUEST_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace),5000,1,2);
		waitForAndGetElement(hGadget.ELEMENT_REMOVE_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace),5000,1,2);

		/*
		- Join or revoke a space
		 *Input Data: 
		 *Expected Outcome: the suggestion fades out and it's removed permantelly from the gadget		*/
		hGadget.connectSpaceSuggestionsGadget(nameSpace);
		waitForElementNotPresent(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace),5000,1,2);

		/*Reload the page
		 *Input Data: 
		 *Expected Outcome: The space suggestion is not suggested again.		*/ 
		nav.driver.navigate().refresh();
		waitForElementNotPresent(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace),5000,1,2);

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		info("Delete spaces test");
		mMember.goToAllSpaces();
		mMember.deleteSpace(nameSpace, 300000);		
	}

	/**
	 * Case ID:121682.
	 * Test Case Name: Remove all suggestions from the gadget Suggestions.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/02/10 08:46:52
	 */
	@Test(priority=0)
	public  void test15_RemoveAllSuggestionsFromTheGadgetSuggestions() {
		info("Test 15 Remove all suggestions from the gadget Suggestions");
		
		/*
		- Connect to Intranet
		- Accept/refuse all suggestions from the gagdet SUGGESTIONS
		 *Input Data: 
		 *Expected Outcome: 
		- All suggestions disappears
		- The Gadget "Suggestions" disappears from the Intranet Homepage		*/ 
		acc.userSignIn(userType.DEVELOPER);
		waitForAndGetElement((hGadget.ELEMENT_SUGGESTION_GADGET_FORM),5000,1,2);
		
		while( isDisplay(By.xpath("//*[@id='suggestions']/li[1]")) == true)
		{
			mouseOver(By.xpath("//*[@id='suggestions']/li[1]"), true, 1);
			click(By.xpath("//*[@id='suggestions']/li[1]//*[@class='uiIconClose']"));
			Utils.pause(2000);
		}
		
		while( isDisplay(By.xpath("//*[@id='suggestionsspace']/li[1]")) == true)
		{
			mouseOver(By.xpath("//*[@id='suggestionsspace']/li[1]"), true, 1);
			click(By.xpath("//*[@id='suggestionsspace']/li[1]//*[@class='uiIconClose']"));
			Utils.pause(2000);
		} 
		
		waitForElementNotPresent(hGadget.ELEMENT_SUGGESTION_GADGET_FORM);
	}

	/**
	 * Case ID:121694.
	 * Test Case Name: Replace the removed people suggestion by other.
	 * Pre-Condition: The people is displayed following the rule (The 2 people suggestions are people with the most common connections with the users. (then we use alphabetical order to display them)
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/02/10 08:46:52
	 * BugID: https://jira.exoplatform.org/browse/PLF-5354
	 */
	@Test
	public  void test16_ReplaceTheRemovedPeopleSuggestionByOther() {
		info("Test 16 Replace the removed people suggestion by other");

		String[] username = {getRandomString(),getRandomString(),getRandomString()};
		String[] fullName = new String[3];
		String password = "gtngtn";

		nav.goToNewStaff();
		for(int i=0; i < 3; i++){
			acc.addNewUserAccount(username[i], password, password, username[i], username[i], "", username[i] + "@gmail.com", null, null, false);
			Utils.pause(2000);		
			button.ok();
			fullName[i] = username[i] + " " + username[i];
		}
		
		/*- Connect to Intranet
		- Remove a people suggestion from the gadget suggestion
		 *Input Data: 
		 *Expected Outcome: 
		- The people suggestion is removed from the gagdet
		- A new people suggestion is displayed to replace the removed one
		- if not, one less people suggestion is displayed	*/	 

		acc.signOut();
		acc.signIn("demo", DATA_PASS);
		info("View suggestion gadget");
		waitForAndGetElement((hGadget.ELEMENT_SUGGESTION_GADGET_FORM),5000,1,2);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS_INDEX.replace("${index}", "1").replace("${peopleName}", fullName[2]),5000,1,2);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS_INDEX.replace("${index}", "2").replace("${peopleName}", fullName[1]),5000,1,2);
		waitForElementNotPresent(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", fullName[0]));

		hGadget.connectUserSuggestionsGadget(fullName[2]);
		waitForElementNotPresent(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", fullName[2]));
		waitForAndGetElement((hGadget.ELEMENT_SUGGESTION_GADGET_FORM),5000,1,2);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS_INDEX.replace("${index}", "1").replace("${peopleName}", fullName[1]),5000,1,2);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS_INDEX.replace("${index}", "2").replace("${peopleName}", fullName[0]),5000,1,2);

		acc.userSignIn(userType.ADMIN);
		//Delete data test
		info("Delete users test");
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username[0]);
		uGroup.deleteUser(username[1]);
		uGroup.deleteUser(username[2]);
	}
	
	/**
	 * Case ID:121695.
	 * Test Case Name: Replace the removed space suggestion by other.
	 * Pre-Condition: The space is displayed following the rule (The 2 space suggestions are spaces that have the most members who are user's connections. (then we use alphabetical order to display them)
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/02/10 08:46:52
	 */
	@Test(priority=7)
	public  void test17_ReplaceTheRemovedSpaceSuggestionByOther() {
		info("Test 17 Replace the removed space suggestion by other");
		String nameSpace1 = "space79618a";
		String nameSpace2 = "space79618b";
		String nameSpace3 = "space79618c";

		//Pre-Condition
		info("Add new space1");
		nav.goToHomePage();
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace1,"");	
		info("Add new space2");
		nav.goToHomePage();
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace2,"");	
		info("Add new space3");
		nav.goToHomePage();
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace3,"");	

		/*
		- Connect to Intranet
		- Remove a space suggestion from the gadget suggestion
		 *Input Data: 
		 *Expected Outcome: 
		- The space suggestion is removed from the gagdet
		- A new space suggestion is displayed to replace the removed one
		- if not, one less space suggestion is displayed		*/ 
		acc.userSignIn(userType.DEVELOPER);
		waitForAndGetElement((hGadget.ELEMENT_SUGGESTION_GADGET_FORM),5000,1,2);
		info("Space suggestion");
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS_INDEX.replace("${index}","1").replace("${spaceName}", nameSpace3),5000,1,2);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS_INDEX.replace("${index}","2").replace("${spaceName}", nameSpace2),5000,1,2);
		waitForElementNotPresent(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace1));
		hGadget.connectSpaceSuggestionsGadget(nameSpace3);
		waitForElementNotPresent(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace3));
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS_INDEX.replace("${index}","1").replace("${spaceName}", nameSpace2),5000,1,2);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS_INDEX.replace("${index}","1").replace("${spaceName}", nameSpace1),5000,1,2);

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		info("Delete spaces test");
		mMember.goToAllSpaces();
		mMember.deleteSpace(nameSpace1, 300000);		
		nav.driver.navigate().refresh();
		mMember.deleteSpace(nameSpace2, 300000);
		nav.driver.navigate().refresh();
		mMember.deleteSpace(nameSpace3, 300000);				
	}

	/**
	 * Case ID:121736.
	 * Test Case Name: Should suggest last created space or last registered user when there is no sggestion based on network.
	 * Pre-Condition: User A is already connected with all users of his network ( = none of his connections has a connection that he does not have) 
	 * User A is already member of all the spaces where his network is member of ( = none of his connections is member of a space where he is not)
	 * User X, Y, Z have registered in that order but a they are not connected with User A
	 * Space X, Y, Z have been created in that order but User A is not member of them
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/02/10 08:46:52
	 * 
	 * BugID: https://jira.exoplatform.org/browse/PLF-5354
	 */
	@Test (groups="pending")
	public  void test18_ShouldSuggestLastCreatedSpaceOrLastRegisteredUserWhenThereIsNoSggestionBasedOnNetwork() {
		info("Test 18: Should suggest last created space or last registered user when there is no sggestion based on network");
		String username1 = getRandomString();
		String password = "gtn123";
		String firstName1 = "User";
		String lastName1 = "AAA"+getRandomString();
		String email1 = username1+"@gmail.com";
		String username2 = getRandomString();
		String firstName2 = "User";
		String lastName2 = "BBB"+getRandomString();
		String email2 = username2+"@gmail.com";
		String username3 = getRandomString();
		String firstName3 = "User";
		String lastName3 = "CCC"+getRandomString();
		String email3 = username3+"@gmail.com";
		String username4 = getRandomString();
		String firstName4 = "User";
		String lastName4 = "DDD"+getRandomString();
		String email4 = username4+"@gmail.com";
		String nameSpace1 = "nameSpace1"+getRandomString();
		String nameSpace2 = "nameSpace2"+getRandomString();
		String nameSpace3 = "nameSpace3"+getRandomString();

		info("Create User 1");		
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password, password, firstName1, lastName1, "", email1, null, null, false);
		Utils.pause(2000);		
		button.ok();
				
		//Pre-Condition
		info("User 1 send connection request to all default user");
		acc.signIn(username1, password);
		nav.goToConnectionPage();
		pConn.connectPeople(user);
		Utils.pause(500);
		pConn.connectPeople(user1);
		Utils.pause(500);
		pConn.connectPeople(user2);
		Utils.pause(500);
		pConn.connectPeople(user3);		
		Utils.pause(500);
		pConn.connectPeople(user4);
		Utils.pause(500);
		pConn.connectPeople(user5);

		info("Default users accept connection request of User 1");
		acc.userSignIn(userType.ROOT);
		nav.goToConnectionPage();
		pConn.acceptInvitation(firstName1+" "+lastName1);
		Utils.pause(500);
		
		acc.userSignIn(userType.ADMIN);
		nav.goToConnectionPage();
		pConn.acceptInvitation(firstName1+" "+lastName1);
		Utils.pause(500);
		
		acc.userSignIn(userType.PUBLISHER);
		nav.goToConnectionPage();
		pConn.acceptInvitation(firstName1+" "+lastName1);
		Utils.pause(500);
		
		acc.userSignIn(userType.DEVELOPER);
		nav.goToConnectionPage();
		pConn.acceptInvitation(firstName1+" "+lastName1);
		Utils.pause(500);
		
		acc.userSignIn(userType.AUTHOR);
		nav.goToConnectionPage();
		pConn.acceptInvitation(firstName1+" "+lastName1);
		Utils.pause(500);
		
		acc.userSignIn(userType.MEMBER);
		nav.goToConnectionPage();
		pConn.acceptInvitation(firstName1+" "+lastName1);
		Utils.pause(500);

		info("Create User 2, User 3, User 4");	
		acc.userSignIn(userType.ADMIN);
		nav.goToNewStaff();
		acc.addNewUserAccount(username2, password, password, firstName2, lastName2, "", email2, null, null, false);
		Utils.pause(2000);
		button.ok();
		acc.addNewUserAccount(username3, password, password, firstName3, lastName3, "", email3, null, null, false);
		Utils.pause(2000);
		button.ok();
		acc.addNewUserAccount(username4, password, password, firstName4, lastName4, "", email4, null, null, false);
		Utils.pause(2000);
		button.ok();

		info("User 2 create spaceX");
		acc.signIn(username2, password);
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace1,"");
		acc.signOut();

		info("User 3 create spaceY");
		acc.signIn(username3, password);
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace2,"");
		acc.signOut();

		info("User 4 create spaceZ");
		acc.signIn(username4, password);
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace3,"");
		acc.signOut();

		/*With User 1, go to homepage
		 *Input Data: 
		 *Expected Outcome: User 3 and 4 are suggested Space Y and Z are suggested		*/
		acc.signIn(username1, password);
		
		waitForAndGetElement(hGadget.ELEMENT_SUGGESTION_GADGET_FORM);
		
		info("Users suggestion");
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", firstName3+" "+lastName3),5000,1,2);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", firstName4+" "+lastName4),5000,1,2);
		waitForElementNotPresent(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", firstName2+" "+lastName2));

		info("Space suggestion");
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS_INDEX.replace("${index}","1").replace("${spaceName}", nameSpace3),5000,1,2);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS_INDEX.replace("${index}","2").replace("${spaceName}", nameSpace2),5000,1,2);
		waitForElementNotPresent(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace1));

		/*Accept User Z and Join Space Z
		 *Input Data: 
		 *Expected Outcome: User X is suggestedSpace X is suggested		*/ 
		info("Accept user Z");
		hGadget.connectUserSuggestionsGadget(firstName4+" "+lastName4);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", firstName3+" "+lastName3),5000,1,2);
		waitForElementNotPresent(hGadget.ELEMENT_VERIFY_USER_SUGGESTIONS.replace("${peopleName}", firstName4+" "+lastName4));
		
		info("Join Space Z");
		hGadget.connectSpaceSuggestionsGadget(nameSpace3);
		waitForElementNotPresent(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace3));
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS.replace("${spaceName}", nameSpace1),5000,1,2);

		//Delete data test
		info("Delete spaces test");
		acc.signIn(username2, password);
		mMember.goToAllSpaces();
		mMember.deleteSpace(nameSpace1, 300000);		
		//nav.driver.navigate().refresh();
		
		acc.signIn(username3, password);
		mMember.goToAllSpaces();
		mMember.deleteSpace(nameSpace2, 300000);
		//nav.driver.navigate().refresh();
		
		acc.signIn(username4, password);
		mMember.goToAllSpaces();
		mMember.deleteSpace(nameSpace3, 300000);
		
		info("Delete users test");
		acc.userSignIn(userType.ADMIN);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username1);
		Utils.pause(1000);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username2);
		Utils.pause(1000);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username3);
		Utils.pause(1000);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username4);
	}

	/**
	 * Case ID:121792.
	 * Test Case Name: Suggestion spaces with the most connections as members.
	 * Pre-Condition: Space A has the most members who are user's connections
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/02/10 08:46:52
	 */
	@Test
	public  void test19_SuggestionSpacesWithTheMostConnectionsAsMembers() {
		info("Test 19: Suggestion spaces with the most connections as members");
		String username1 = getRandomString();
		String password = "gtn123";
		String firstName1 = username1;
		String lastName1 = username1;
		String email1 = username1+"@gmail.com";
		String username2 = getRandomString();
		String firstName2 = username2;
		String lastName2 = username2;
		String email2 = username2+"@gmail.com";
		
		String nameSpace1 = getRandomString();
		String nameSpace2 = getRandomString();

		info("Create two new users");	
		nav.goToNewStaff();
		acc.addNewUserAccount(username1, password, password, firstName1, lastName1, "", email1, null, null, false);
		Utils.pause(2000);
		button.ok();
		acc.addNewUserAccount(username2, password, password, firstName2, lastName2, "", email2, null, null, false);
		Utils.pause(2000);
		button.ok();
		
		info("Add new space1");
		nav.goToHomePage();
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace1,"");	
		
		info("Invite user 1 to the member of space");
		goToMembers(nameSpace1);
		mMember.inviteSingleUser(username1);
		Utils.pause(500);
		
		info("Add new space2");
		nav.goToHomePage();
		mMember.goToMySpacePage();
		mMember.addNewSpace(nameSpace2,"");
		
		info("John send connection request to user 1 and user 2");
		nav.goToHomePage();
		nav.goToConnectionPage();
		pConn.connectPeople(firstName1+" "+lastName1);
		nav.driver.navigate().refresh();
		pConn.connectPeople(firstName2+" "+lastName2);

		info("User 1 accept space invitation");
		acc.signIn(username1, password);
		mMember.acceptInvitation(nameSpace1);
		
		info("User 1 accept connection request of John");
		nav.goToHomePage();
		nav.goToConnectionPage();
		pConn.acceptInvitation(user);
		
		info("User 1 send connection request to User 2");
		nav.goToHomePage();
		nav.goToConnectionPage();
		pConn.connectPeople(firstName2+" "+lastName2);

		/*
		- Connect to Intranet
		 *Input Data: 
		 *Expected Outcome: 
		- The gadget "Suggestions" is displayed
		- TheSpace A is displayed in the top of the list of suggestions
		- The Space B is displayed in the second position 		*/ 
		acc.signIn(username2, password);
		nav.goToConnectionPage();
		pConn.acceptInvitation(user);
		driver.navigate().refresh();
		pConn.acceptInvitation(firstName1+" "+lastName1);
		nav.goToHomePage();
		waitForAndGetElement(hGadget.ELEMENT_SUGGESTION_GADGET_FORM);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS_INDEX.replace("${index}","1").replace("${spaceName}", nameSpace1),5000,1,2);
		waitForAndGetElement(hGadget.ELEMENT_VERIFY_SPACE_SUGGESTIONS_INDEX.replace("${index}","2").replace("${spaceName}", nameSpace2),5000,1,2);

		//Delete data test
		info("Delete users test");
		acc.userSignIn(userType.ADMIN);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username1);
		Utils.pause(1000);
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username2);
		
		info("Delete spaces test");
		mMember.goToAllSpaces();
		mMember.deleteSpace(nameSpace1, 300000);
		nav.driver.navigate().refresh();
		mMember.deleteSpace(nameSpace2, 300000);
	}
}