package org.exoplatform.selenium.platform.plf.functional.navigation.topnavigation;

import static org.exoplatform.selenium.TestLogger.info;

import java.util.HashMap;
import java.util.Map;

import org.exoplatform.selenium.Utils;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.PageManagement;
import org.exoplatform.selenium.platform.PlatformBase;
import org.exoplatform.selenium.platform.forum.ForumManageCategory;
import org.exoplatform.selenium.platform.social.ManageMember;
import org.openqa.selenium.By;
import org.testng.annotations.*;

/**
 * @author chinhdtt
 * @date 19 May 2014
 */
public class PLF_Navigation_TopNavigation_Help extends PlatformBase{
	ManageAccount acc;
	NavigationToolbar nav;
	ManageMember mMember;
	ForumManageCategory catMag;
	PageManagement mPage; 

	@BeforeMethod
	public void beforeMethods(){	
		initSeleniumTest();
		driver.get(baseUrl);
		acc = new ManageAccount(driver, this.plfVersion);
		nav = new NavigationToolbar(driver, this.plfVersion);				
		acc.signIn(DATA_USER1, DATA_PASS);		
		mMember = new ManageMember(driver, this.plfVersion);
		catMag = new ForumManageCategory(driver, this.plfVersion);
		mPage = new PageManagement(driver, this.plfVersion);
	}

	@AfterMethod
	public void afterMethods() {
		info("Logout portal");
		driver.manage().deleteAllCookies();
		driver.quit();
	}
	/**
	 * Case ID:76659.
	 * Test Case Name: Edit links of documentation.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 * Pending this case because can't auto edit configuration file. 
	 */
	@Test (groups = "pending")
	public  void test01_EditLinksOfDocumentation() {
		info("Test 1: Edit links of documentation");
		/*
		- From Configuration file of binary, edit a link of document
		- Save
		- Launch a server
		 *Expected Outcome: The application is ready		*/

		/*
		- Connect to application and open the module of the edited link
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab is displayed in the browser
		- The user guide is displayed in the correspond link		*/ 

	}

	/**
	 * Case ID:76660.
	 * Test Case Name: Open user guide in a new tab.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test02_OpenUserGuideInANewTab() {
		info("Test 2: Open user guide in a new tab");	
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.GettingStarted.SocialIntranetHomepage.html";
		/*
		- Connect to Intranet
		 *Expected Outcome: 
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		info("Help button is displayed");
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened to displayed the online user guide		*/ 
		info("Click on Help button");
		click(ELEMENT_HELP_ICON);
		info("Open new window");
		Utils.pause(5000);	
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());
	}

	/**
	 * Case ID:76661.
	 * Test Case Name: Open user guide when user is in "My Connections" screen.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test03_OpenUserGuideWhenUserIsInMyConnectionsScreen() {
		info("Test 3: Open user guide when user is in My Connections screen");
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.ManagingYourPersonalApplications.ManagingYourConnections.html";
		/*
		- Connect to Intranet
		- Open "My Connections" screen
		 *Expected Outcome: 
		- The"My Connections" page is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		mouseOverAndClick(ELEMENT_ACCOUNT_NAME_LINK);
		mouseOverAndClick(ELEMENT_MY_CONNECTIONS);
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		info("Help button is displayed");
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on: http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.ManagingYourPersonalApplications.ManagingYourConnections.html		*/ 
		info("Click on Help button");
		click(ELEMENT_HELP_ICON);
		info("Open new window");
		Utils.pause(5000);	
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());
	}

	/**
	 * Case ID:76662.
	 * Test Case Name: Open user guide when user is in "My Dashboard" screen.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test04_OpenUserGuideWhenUserIsInMyDashboardScreen() {
		info("Test 4: Open user guide when user is in My Dashboard screen");
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.ManagingYourPersonalApplications.ManagingYourDashboard.html";
		/*
		- Connect to Intranet
		- Open "My Dashboard" screen
		 *Expected Outcome: 
		- The "My Dashboard" page is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		nav.goToDashboard();
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		info("Help button is displayed");
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on: http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.ManagingYourPersonalApplications.ManagingYourDashboard.html		*/ 
		click(ELEMENT_HELP_ICON);
		info("Open new window");
		Utils.pause(5000);	
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		//		driver.navigate().to(URL);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());
	}

	/**
	 * Case ID:76663.
	 * Test Case Name: Open user guide when user is in "My Profile" screen.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test05_OpenUserGuideWhenUserIsInMyProfileScreen() {
		info("Test 5: Open user guide when user is in My Profile screen");
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.ManagingYourPersonalApplications.ManagingYourProfile.html";
		/*
		- Connect to Intranet
		- Open "My Profile" screen
		 *Expected Outcome: 
		- The"My Profile" page is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		nav.goToMyProfile();
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		info("Help button is displayed");
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on: http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.ManagingYourPersonalApplications.ManagingYourProfile.html		*/ 
		click(ELEMENT_HELP_ICON);
		info("Check URL is shown");
		Utils.pause(5000);	
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());	
	}

	/**
	 * Case ID:76664.
	 * Test Case Name: Open user guide when user is in "My Wiki" screen.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test06_OpenUserGuideWhenUserIsInMyWikiScreen() {
		info("Test 6: Open user guide when user is in My Wiki screen");
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.ManagingYourPersonalApplications.WorkingWithYourWiki.html";

		/*
		- Connect to Intranet
		- Open "My Wiki" screen
		 *Expected Outcome: 
		- The"My Wiki" page is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		mouseOverAndClick(ELEMENT_ACCOUNT_NAME_LINK);
		mouseOverAndClick(ELEMENT_MY_WIKI_LINK);
		Utils.pause(1000);
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		info("Help button is shown");
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on:http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.ManagingYourPersonalApplications.WorkingWithYourWiki.html		*/ 
		click(ELEMENT_HELP_ICON);
		Utils.pause(5000);	
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		//		driver.navigate().to(URL);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());
	}

	/**
	 * Case ID:76665.
	 * Test Case Name: Open user guide when user is in other places.
	 * Pre-Condition: user is not in:Homepage, Wiki,Forum, Calendar, Answers or FAQ, Documents, Spaces, "My Connections", "My Profile", "My Wiki", "My Dashboard", inside a Space, on the Activity Stream,Space Management,Wiki,Forum, Calendar, Answers or FAQ, Documents
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test07_OpenUserGuideWhenUserIsInOtherPlaces() {
		info("Test 7: Open user guide when user is in other places");
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.html";
		/*
		- Connect to Intranet
		 *Expected Outcome: 
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		info("User in other places");
		mouseOverAndClick(ELEMENT_ACCOUNT_NAME_LINK);
		mouseOverAndClick(ELEMENT_NOTIFICATION_LINK);
		Utils.pause(1000);
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		info("Help button is shown");
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on: http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.html		*/ 
		click(ELEMENT_HELP_ICON);
		info("Check URL is shown");
		Utils.pause(5000);	
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		//		driver.navigate().to(URL);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());
	}

	/**
	 * Case ID:76666.
	 * Test Case Name: Open user guide when user is inside a space, in activity stream.
	 * Pre-Condition: User is a member of a space
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test08_OpenUserGuideWhenUserIsInsideASpaceInActivityStream() {
		info("Test 8: Open user guide when user is inside a space, in activity stream");
		String spaceName = "Space76666";
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.WorkingWithSpaces.html";

		/*
		- Connect to Intranet
		- Open a space, go to activity stream of space
		 *Expected Outcome: 
		- The Activity stream of the space is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, spaceName);
		Utils.pause(1000);
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		info("Help button is shown");
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on: http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.WorkingWithSpaces.html		*/ 
		click(ELEMENT_HELP_ICON);
		info("Check URL is shown");
		Utils.pause(5000);	
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());

		//Delete data test		
		switchToParentWindow();
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName, 300000);
	}

	/**
	 * Case ID:76667.
	 * Test Case Name: Open user guide when user is inside a space, on Answers.
	 * Pre-Condition: The current user is a member of a space with Answers application
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test09_OpenUserGuideWhenUserIsInsideASpaceOnAnswers() {
		info("Test 9: Open user guide when user is inside a space, on Answers");
		String spaceName = "Space76667";
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.BuildingYourAnswers.html";

		//Pre-condition
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, spaceName);
		Utils.pause(1000);

		/*
		- Connect to Intranet
		- Open a space, go to Answers
		 *Expected Outcome: 
		- The Answers screen is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		mMember.goToSpaceMenu("Answer");
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on: http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.BuildingYourAnswers.html		*/ 
		click(ELEMENT_HELP_ICON);
		info("Check URL is shown");
		Utils.pause(5000);	
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());

		//Delete data test		
		switchToParentWindow();
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName, 300000);
	}

	/**
	 * Case ID:76668.
	 * Test Case Name: Open user guide when user is inside a space, on Calendar.
	 * Pre-Condition: The user is a member of a space with calendar application
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test10_OpenUserGuideWhenUserIsInsideASpaceOnCalendar() {
		info("Test 10 Open user guide when user is inside a space, on Calendar");
		String spaceName = "Space76668";
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.ManagingYourCalendars.html";

		//Pre-condition 
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, spaceName);
		Utils.pause(1000);

		/*
		- Connect to Intranet
		- Open a space, go to Calendar
		 *Expected Outcome: 
		- The Calendar screen is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		info("Calendar application");
		mMember.goToSpaceMenu("Agenda");
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on: http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.ManagingYourCalendars.html		*/ 
		click(ELEMENT_HELP_ICON);
		info("Check URL is shown");
		Utils.pause(5000);	
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());

		//Delete data test		
		switchToParentWindow();
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName, 300000);
	}

	/**
	 * Case ID:76669.
	 * Test Case Name: Open user guide when user is inside a space, on Documents.
	 * Pre-Condition: The current user is a member of a space with Document application
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test11_OpenUserGuideWhenUserIsInsideASpaceOnDocuments() {
		info("Test 11 Open user guide when user is inside a space, on Documents");
		String spaceName = "Space76669";
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.ManagingYourDocuments.html";

		//Pre-Condition 
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, spaceName);
		Utils.pause(1000);

		/*
		- Connect to Intranet
		- Open a space, go to Documents
		 *Expected Outcome: 
		- The Documents screen is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		info("Documents application");
		mMember.goToSpaceMenu("Documents");
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on:http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.ManagingYourDocuments.html		*/ 
		click(ELEMENT_HELP_ICON);
		Utils.pause(5000);	
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());

		//Delete data test		
		switchToParentWindow();
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName, 300000);
	}

	/**
	 * Case ID:76670.
	 * Test Case Name: Open user guide when user is inside a space, on FAQ.
	 * Pre-Condition: The current user is a member of a space with FAQ application
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test12_OpenUserGuideWhenUserIsInsideASpaceOnFAQ() {
		info("Test 12 Open user guide when user is inside a space, on FAQ");
		String spaceName = "Space76670";
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.BuildingYourAnswers.html";

		//Pre-Condition 
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, spaceName);
		Utils.pause(1000);

		/*
		- Connect to Intranet
		- Open a space, go to FAQ
		 *Expected Outcome: 
		- The FAQ screen is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		mMember.goToSpaceMenu("FAQ");
		Utils.pause(1000);
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on: http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.BuildingYourAnswers.html		*/ 
		click(ELEMENT_HELP_ICON);
		Utils.pause(5000);	
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());

		//Delete data test		
		switchToParentWindow();
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName, 300000);
	}

	/**
	 * Case ID:76671.
	 * Test Case Name: Open user guide when user is inside a space, on Forum.
	 * Pre-Condition: The current user is a member of a space with Forum application
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test13_OpenUserGuideWhenUserIsInsideASpaceOnForum() {
		info("Test 13 Open user guide when user is inside a space, on Forum");
		String spaceName = "Space76671";
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.BuildingYourForum.html";

		//Pre-condition 
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, spaceName);
		Utils.pause(1000);

		/*
		- Connect to Intranet
		- Open a space, go to forum
		 *Expected Outcome: 
		- The forum screen is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		mMember.goToSpaceMenu("Forums");
		Utils.pause(1000);
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on: http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.BuildingYourForum.html		*/ 
		click(ELEMENT_HELP_ICON);
		Utils.pause(5000);
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());

		//Delete data test		
		switchToParentWindow();
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName, 300000);
	}

	/**
	 * Case ID:76672.
	 * Test Case Name: Open user guide when user is inside a space, on Space Management.
	 * Pre-Condition: user is administrator of the space
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test14_OpenUserGuideWhenUserIsInsideASpaceOnSpaceManagement() {
		info("Test 14 Open user guide when user is inside a space, on Space Management");
		String spaceName = "Space76672";
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.WorkingWithSpaces.html";

		//Pre-Condition
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, spaceName);
		Utils.pause(1000);

		/*
		- Connect to Intranet
		- Open a space, go to Space management screen
		 *Expected Outcome: 
		- The Space management screen is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		mMember.goToSpaceMenu("Space Settings");
		Utils.pause(1000);
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on:http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.WorkingWithSpaces.html		*/ 
		click(ELEMENT_HELP_ICON);
		Utils.pause(5000);
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());

		//Delete data test		
		switchToParentWindow();
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName, 300000);
	}

	/**
	 * Case ID:76673.
	 * Test Case Name: Open user guide when user is inside a space, on Wiki.
	 * Pre-Condition: The current user is a member of a space with wiki application
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test15_OpenUserGuideWhenUserIsInsideASpaceOnWiki() {
		info("Test 15 Open user guide when user is inside a space, on Wiki");
		String spaceName = "Space76673";
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.WorkingWithWikis.html";

		//Pre-Condition 
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, spaceName);
		Utils.pause(1000);

		/*
		- Connect to Intranet
		- Open a space, go to wiki
		 *Expected Outcome: 
		- The wiki screen is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		mMember.goToSpaceMenu("Wiki");
		Utils.pause(1000);
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on: http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.WorkingWithWikis.html		*/ 
		click(ELEMENT_HELP_ICON);
		Utils.pause(5000);
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());

		//Delete data test		
		switchToParentWindow();
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName, 300000);
	}

	/**
	 * Case ID:76674.
	 * Test Case Name: Open user guide when user is on Answers.
	 * Pre-Condition: Create a page containing answer portlet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 * Bug: https://jira.exoplatform.org/browse/PLF-4516
	 */
	@Test (groups = "errors")
	public  void test16_OpenUserGuideWhenUserIsOnAnswers() {
		info("Test 16 Open user guide when user is on Answers");
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.BuildingYourAnswers.html";
		String nodeName = "Node76674"+getRandomString();
		String displayName = "Node76674"+getRandomString();
		String title = "Collaboration";
		Map<String, String> portletIds= new HashMap<String, String>();
		portletIds.put("Collaboration/AnswersPortlet", "");

		//Pre-condition
		nav.goToPageCreationWizard();
		Utils.pause(5000);
		click(ELEMENT_UP_LEVEL);
		info("Create page");
		mPage.addNewPageEditor(nodeName, displayName,"",title, portletIds, false, false);
		Utils.pause(5000);	

		/*
		- Connect to Intranet
		- Open Answers application
		 *Expected Outcome: 
		- TheAnswers page is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		info("Check top navigation bar");
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on: http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.BuildingYourAnswers.html		*/ 
		click(ELEMENT_HELP_ICON);
		Utils.pause(5000);
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());

		//Delete data test
		info("Delete page");
		mPage.deletePageAtManagePageAndPortalNavigation(nodeName, true, "intranet", false, null,displayName);
	}

	/**
	 * Case ID:76675.
	 * Test Case Name: Open user guide when user is on Calendar.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test17_OpenUserGuideWhenUserIsOnCalendar() {
		info("Test 17 Open user guide when user is on Calendar");
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.ManagingYourCalendars.html";
		/*
		- Connect to Intranet
		- OpenCalendar application
		 *Expected Outcome: 
		- TheCalendar page is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		info("Click on Calendar");
		click(ELEMENT_CALENDAR_PAGE);
		Utils.pause(500);
		waitForAndGetElement(ELEMENT_CALENDAR_PANEL);
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on:http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.ManagingYourCalendars.html		*/ 
		click(ELEMENT_HELP_ICON);
		Utils.pause(5000);
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());
	}

	/**
	 * Case ID:76676.
	 * Test Case Name: Open user guide when user is on Documents.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test18_OpenUserGuideWhenUserIsOnDocuments() {
		info("Test 18 Open user guide when user is on Documents");
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.ManagingYourDocuments.html";

		/*
		- Connect to Intranet
		- Open Documents application
		 *Expected Outcome: 
		- TheDocuments page is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		info("Click on Documments");
		click(ELEMENT_PERSONAL_DOCUMENTS);
		Utils.pause(500);
		waitForAndGetElement(By.id("UIFileViewCheckBox"), 3000, 1, 2);
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on: http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.ManagingYourDocuments.html		*/ 
		click(ELEMENT_HELP_ICON);
		Utils.pause(5000);
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());
	}

	/**
	 * Case ID:76677.
	 * Test Case Name: Open user guide when user is on FAQ.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 * Bug: https://jira.exoplatform.org/browse/PLF-4516
	 */
	@Test (groups = "errors")
	public  void test19_OpenUserGuideWhenUserIsOnFAQ() {
		info("Test 19 Open user guide when user is on FAQ");
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.html";
		String nodeName = "Node76677"+getRandomString();
		String displayName = "Node76677"+getRandomString();
		String title = "Collaboration";
		Map<String, String> portletIds= new HashMap<String, String>();
		portletIds.put("Collaboration/FAQPortlet", "");

		//Pre-condition
		nav.goToPageCreationWizard();
		Utils.pause(5000);
		click(ELEMENT_UP_LEVEL);
		info("Create page");
		mPage.addNewPageEditor(nodeName, displayName,"",title, portletIds, false, false);
		Utils.pause(5000);	

		/*
		- Connect to Intranet
		- OpenFAQ application
		 *Expected Outcome: 
		- TheFAQ page is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on: http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.BuildingYourAnswers.html		*/ 
		click(ELEMENT_HELP_ICON);
		Utils.pause(5000);
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		driver.navigate().to(URL);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());

		//Delete data test
		info("Delete page");
		mPage.deletePageAtManagePageAndPortalNavigation(nodeName, true, "intranet", false, null,displayName);
	}

	/**
	 * Case ID:76678.
	 * Test Case Name: Open user guide when user is on Forum.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test20_OpenUserGuideWhenUserIsOnForum() {
		info("Test 20 Open user guide when user is on Forum");
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.BuildingYourForum.html";
		/*
		- Connect to Intranet
		- Open Forum application
		 *Expected Outcome: 
		- The Forum page is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		info("Click on Forum");
		click(ELEMENT_FORUM_PAGE);
		Utils.pause(500);
		waitForAndGetElement(catMag.ELEMENT_FORUM_STATE);
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on: http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.BuildingYourForum.html		*/ 
		click(ELEMENT_HELP_ICON);
		Utils.pause(5000);
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());
	}

	/**
	 * Case ID:76679.
	 * Test Case Name: Open user guide when user is on Homepage.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test21_OpenUserGuideWhenUserIsOnHomepage() {
		info("Test 21 Open user guide when user is on Homepage");
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.GettingStarted.SocialIntranetHomepage.html";
		/*
		- Connect to Intranet
		 *Expected Outcome: 
		- The Homepage is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on: http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.GettingStarted.SocialIntranetHomepage.html		*/ 
		click(ELEMENT_HELP_ICON);
		Utils.pause(5000);
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());
	}

	/**
	 * Case ID:76680.
	 * Test Case Name: Open user guide when user is on Spaces.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test22_OpenUserGuideWhenUserIsOnSpaces() {
		info("Test 22 Open user guide when user is on Spaces");
		String spaceName = "Space76680";
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.WorkingWithSpaces.html";

		/*
		- Connect to Intranet
		- Open Spaces application
		 *Expected Outcome: 
		- TheSpaces list page is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, spaceName);
		Utils.pause(1000);
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on: http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.WorkingWithSpaces.html		*/ 
		click(ELEMENT_HELP_ICON);
		Utils.pause(5000);
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());
	}

	/**
	 * Case ID:76681.
	 * Test Case Name: Open user guide when user is on Wiki.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/05/19 12:12:55
	 */
	@Test
	public  void test23_OpenUserGuideWhenUserIsOnWiki() {
		info("Test 23 Open user guide when user is on Wiki");
		String URL = "http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.WorkingWithWikis.html";

		/*
		- Connect to Intranet
		- Open Wiki application
		 *Expected Outcome: 
		- The Wiki page is displayed
		- The Top navigation bar is displayed
		- The Help button is displayed in the right of the bar		*/
		info("Click on Wiki");
		click(ELEMENT_WIKI_PAGE);
		waitForAndGetElement(ELEMENT_TITLE_WIKI_HOME_LINK);	
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_HELP_ICON);

		/*
		- Click on the button "?"
		 *Input Data: 
		 *Expected Outcome: 
		- A new tab in the internet browser is opened
		- The user guide is opened on: http://docs.exoplatform.com/public/index.jsp?topic=/PLF40/PLFUserGuide.WorkingWithWikis.html		*/ 
		click(ELEMENT_HELP_ICON);
		Utils.pause(5000);
		for(String winHandle : driver.getWindowHandles()){
			driver.switchTo().window(winHandle);
		}
		Utils.pause(1000);
		assert driver.getCurrentUrl().equalsIgnoreCase(URL);		
		info("URL "+driver.getCurrentUrl());
	}
}