package org.exoplatform.selenium.platform.plf.functional.navigation.topnavigation;

import static org.exoplatform.selenium.TestLogger.info;

import java.util.HashMap;
import java.util.Map;

import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.PageEditor;
import org.exoplatform.selenium.platform.PageManagement;
import org.exoplatform.selenium.platform.PlatformBase;
import org.exoplatform.selenium.platform.ecms.EcmsBase;
import org.exoplatform.selenium.platform.ecms.contentexplorer.ActionBar;
import org.exoplatform.selenium.platform.ecms.contentexplorer.ContextMenu.actionType;
import org.openqa.selenium.By;
import org.testng.annotations.*;
import org.exoplatform.selenium.Button;
import org.exoplatform.selenium.Utils;

/**
 * @author chinhdtt
 * @date 19 Mar 2014
 */
public class PLF_Navigation_TopNavigation_Edit extends PlatformBase{
	ManageAccount acc;
	NavigationToolbar nav;
	ActionBar act;
	EcmsBase ecms;
	PageManagement mPage; 
	PageEditor pEdit;
	Button button; 

	@BeforeMethod
	public void beforeMethods(){	
		initSeleniumTest();
		driver.get(baseUrl);
		acc = new ManageAccount(driver, this.plfVersion);
		nav = new NavigationToolbar(driver, this.plfVersion);	
		act = new ActionBar(driver, this.plfVersion);
		mPage = new PageManagement(driver, this.plfVersion);
		ecms = new EcmsBase(driver, this.plfVersion);
		pEdit = new PageEditor(driver, this.plfVersion);
		button = new Button(driver, this.plfVersion);
		acc.signIn(DATA_USER1, DATA_PASS);		
	}

	@AfterMethod
	public void afterMethods() {
		info("Logout portal");
		driver.manage().deleteAllCookies();
		driver.quit();
	}

	/**
	 * Case ID:76640.
	 * Test Case Name: Display checkbox in the "Content" entry.
	 * Pre-Condition: The current user is an editor.
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/19 17:25:04
	 */
	@Test
	public  void test01_DisplayCheckboxInTheContentEntry() {
		info("Test 1: Display checkbox in the Content entry");
		/*
		- Connect to Intranet
		 *Input Data: 
		 *Expected Outcome: 
		- The top navigation bar is displayed
		- The button "Edit" is displayed		*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_MENU_EDIT_LINK);

		/*
		- Mouse over on the button "Edit"
		 *Input Data: 
		 *Expected Outcome: 
		- The Edit menu is displayed
		- The checkbox in the content entry is displayed* if crossed: the user is on edit mode* if decrossed: the user is not in edit mode		*/ 
		mouseOverAndClick(ELEMENT_MENU_EDIT_LINK);
		waitForAndGetElement(ELEMENT_MENU_EDIT_CONTENT_TEXT);
		waitForAndGetElement(nav.ELEMENT_MENU_EDIT_CONTENT_UNCHECK);
		click(nav.ELEMENT_MENU_EDIT_CONTENT_UNCHECK);
		Utils.pause(500);
		mouseOverAndClick(ELEMENT_MENU_EDIT_LINK);
		Utils.pause(500);
		waitForAndGetElement(nav.ELEMENT_MENU_EDIT_CONTENT);
	}

	/**
	 * Case ID:76639.
	 * Test Case Name: Display items of "Page" entry.
	 * Pre-Condition: The current user is an editor.
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/19 17:25:04
	 */
	@Test
	public  void test02_DisplayItemsOfPageEntry() {
		info("Test 2: Display items of Page entry");
		/*
		- Connect to Intranet
		 *Input Data: 
		 *Expected Outcome: 
		- The top navigation bar is displayed
		- The button "Edit" is displayed		*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_MENU_EDIT_LINK);

		/*
		- Mouse over on the button "Edit"
		- Go to "Page" entry
		 *Input Data: 
		 *Expected Outcome: 
		- A submenu is displayed with the following items in this order:* Edit Layout* SEO* Add Page		*/ 
		mouseOverAndClick(ELEMENT_MENU_EDIT_LINK);
		waitForAndGetElement(ELEMENT_MENU_PAGE_LINK);
		mouseOver(ELEMENT_MENU_PAGE_LINK, true);
		waitForAndGetElement(ELEMENT_MENU_EDIT_LAYOUT);
		waitForAndGetElement(ELEMENT_MENU_SEO_LINK);
		waitForAndGetElement(ELEMENT_MENU_ADD_PAGE_LINK);
	}

	/**
	 * Case ID:76638.
	 * Test Case Name: Display items of "Site" entry.
	 * Pre-Condition: The current user is an editor
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/19 17:25:04
	 */
	@Test
	public  void test03_DisplayItemsOfSiteEntry() {
		info("Test 3: Display items of Site entry");
		/*
		- Connect to Intranet
		 *Input Data: 
		 *Expected Outcome: 
		- The top navigation bar is displayed
		- The button "Edit" is displayed		*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_MENU_EDIT_LINK);

		/*
		- Mouse over on the button "Edit"
		- Go to "Site" entry
		 *Input Data: 
		 *Expected Outcome: 
		- A submenu is displayed with the following items in this order:* Layout* Navigation* Add Site		*/ 
		mouseOverAndClick(ELEMENT_MENU_EDIT_LINK);
		waitForAndGetElement(ELEMENT_MENU_EDIT_SITES);
		mouseOver( ELEMENT_MENU_EDIT_SITES, true);
		waitForAndGetElement(ELEMENT_MENU_EDIT_SITE_LAYOUT);
		waitForAndGetElement(ELEMENT_MENU_EDIT_SITES_NAV);
		waitForAndGetElement(ELEMENT_MENU_EDIT_ADDSITE);
	}

	/**
	 * Case ID:76637.
	 * Test Case Name: Display items on Edit button.
	 * Pre-Condition: The current user is an editor of platform/admin
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/19 17:25:04
	 */
	@Test
	public  void test04_DisplayItemsOnEditButton() {
		info("Test 4: Display items on Edit button");
		/*
		- Connect to Intranet
		 *Input Data: 
		 *Expected Outcome: 
		- The top navigation bar is displayed
		- The button "Edit" is displayed		*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_MENU_EDIT_LINK);

		/*
		- Mouse over on the button "Edit"
		 *Input Data: 
		 *Expected Outcome: 
		- The Edit menu is displayed
		- The following entries are displayed in this order:* Content* Page* Site		*/ 
		mouseOverAndClick(ELEMENT_MENU_EDIT_LINK);
		waitForAndGetElement(ELEMENT_MENU_EDIT_CONTENT_TEXT);
		waitForAndGetElement(ELEMENT_MENU_PAGE_LINK);
		waitForAndGetElement(ELEMENT_MENU_EDIT_SITES);
	}

	/**
	 * Case ID:76636.
	 * Test Case Name: Put the user in edit mode.
	 * Pre-Condition: The current user is an editor
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/19 17:25:04
	 * Bug: https://jira.exoplatform.org/browse/ECMS-6122
	 */
	@Test(groups="error")
	public  void test05_PutTheUserInEditMode() {
		info("Test 5: Put the user in edit mode");
		String uploadFileName = "ECMS_CSS_File_After.txt";
		String driverName = "Personal Drives";
		String folderPath = "Personal Documents";
		String folder = "Add2folder76636";
		String nodeName = "Node76636";
		String displayName = "Node76636Test2";
		String title = "Content";
		Map<String, String> portletIds= new HashMap<String, String>();
		portletIds.put("Content/SingleContentViewer", "");

		//Pre-Condition: 
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		nav.goToUploadFile();
		uploadFileFromTopNavigation(driverName,true,folderPath,"",uploadFileName, folder);
		Utils.pause(500);
		info("Add new content page");
		nav.goToPageCreationWizard();
		Utils.pause(5000);
		click(ELEMENT_UP_LEVEL);
		info("Create page");
		mPage.addNewPageEditor(nodeName, displayName,"",title, portletIds, false, true);
		Utils.pause(5000);
		info("Edit portlet");
		pEdit.goToEditPortlet(ELEMENT_FRAME_CONTAIN_PORTLET);
		click(pEdit.ELEMENT_CONTENT_ADD_PATH);
		click(pEdit.ELEMENT_CONTENT_BROWSER_NODE.replace("${node}", driverName));
		click(pEdit.ELEMENT_CONTENT_BROWSER_NODE.replace("${node}", folderPath));
		click(pEdit.ELEMENT_CONTENT_BROWSER_NODE.replace("${node}", folder));
		click(By.linkText(uploadFileName));
		button.save();
		button.close();
		pEdit.finishEditLayout();
		Utils.pause(3000);
		driver.navigate().refresh();

		/*
		- Connect to Intranet
		 *Input Data: 
		 *Expected Outcome: 
		- The top navigation bar is displayed
		- The button "Edit" is displayed		*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		waitForAndGetElement(ELEMENT_MENU_EDIT_LINK);

		/*
		- Mouse over on the button "Edit"
		- Check the box in the entry "Content"
		 *Input Data: 
		 *Expected Outcome: The page is displayed in Edit mode		*/ 
		mouseOverAndClick(ELEMENT_MENU_EDIT_LINK);
		waitForAndGetElement(ELEMENT_MENU_EDIT_CONTENT_TEXT);
		waitForAndGetElement(nav.ELEMENT_MENU_EDIT_CONTENT_UNCHECK);
		click(nav.ELEMENT_MENU_EDIT_CONTENT_UNCHECK);
		Utils.pause(500);
		mouseOverAndClick(ELEMENT_MENU_EDIT_LINK);
		Utils.pause(500);
		waitForAndGetElement(nav.ELEMENT_MENU_EDIT_CONTENT);
		info("The page is displayed in Edit mode");
		mouseOver(ELEMENT_EDIT_PAGE_PAGE, true);
		waitForAndGetElement(By.xpath(ELEMENT_EDIT_PAGE_PAGE));
		waitForAndGetElement(ELEMENT_EDIT_MODE_PAGE);

		//Delete data test
		info("-- Clear data --");
		nav.goToSiteExplorer();
		info("Delete folder");
		act.chooseDrive(ecms.ELEMENT_PERSONAL_DRIVE);
		act.actionsOnElement(folder, actionType.DELETE,true,true);		
		info("Delete page node");
		mPage.deletePageAtManagePageAndPortalNavigation(nodeName, true, "intranet", false, null,displayName);
	}
}