package org.exoplatform.selenium.platform.plf.functional.navigation.topnavigation.create;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.Button;
import org.exoplatform.selenium.ManageAlert;
import org.exoplatform.selenium.Utils;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.ManageAccount.userType;
import org.exoplatform.selenium.platform.calendar.CalendarBase;
import org.exoplatform.selenium.platform.forum.ForumManageCategory;
import org.exoplatform.selenium.platform.forum.ForumManageForum;
import org.exoplatform.selenium.platform.forum.ForumManagePoll;
import org.exoplatform.selenium.platform.forum.ForumManageTopic;
import org.exoplatform.selenium.platform.forum.ForumPermission;
import org.exoplatform.selenium.platform.social.ManageMember;
import org.exoplatform.selenium.platform.social.SpaceManagement;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.testng.annotations.*;


/**
 * @author phuongdt
 *
 */
public class PLF_Navigation_TopNavigation_Create_TopicPoll2 extends CalendarBase{
	ManageAccount acc;
	NavigationToolbar nav;
	Button button;
	ManageAlert alert;
	//Forum
	ForumManageTopic mngTopic;
	ForumManagePoll mngPoll;
	ForumManageCategory mngCat;
	ForumManageForum mngFru;
	ForumPermission frumPer;

	//Space
	SpaceManagement spaceMag;
	ManageMember magMember;

	@BeforeMethod
	public void beforeMethods(){	
		initSeleniumTest();
		driver.get(baseUrl);
		acc = new ManageAccount(driver, this.plfVersion);
		nav = new NavigationToolbar(driver, this.plfVersion);				
		acc.signIn(DATA_USER1, DATA_PASS);	
		button = new Button(driver, this.plfVersion);
		alert = new ManageAlert(driver);
		mngTopic = new ForumManageTopic(driver, this.plfVersion);
		mngPoll = new ForumManagePoll(driver, this.plfVersion);
		mngCat = new ForumManageCategory(driver, this.plfVersion);
		mngFru = new ForumManageForum(driver, this.plfVersion);
		magMember = new ManageMember(driver,this.plfVersion);
		spaceMag = new SpaceManagement(driver,this.plfVersion);
		frumPer=new ForumPermission(driver,this.plfVersion);
	}

	@AfterMethod
	public void afterMethods() {
		info("Logout portal");
		driver.manage().deleteAllCookies();
		driver.quit();
	}

	/**
	 *Case ID:104053.
	 *Test Case Name: Display scrollbar in Space switcher in Topic menu.
	 *Case ID:104054.
	 *Test Case Name: Display Space switcher in "Create a new Poll" menu.
	 *Pre-Condition: More than 12 spaces are accessible to the user from the space switcher
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test18_19_DisplayScrollbarInSpaceSwitcherInTopicPollMenu() {
		info("Test 18 Display scrollbar in Space switcher in Topic menu");
		String spaceName = "space104053";

		//- Create new space
		for(int i =1;i<14;i++){
			magMember.goToMySpacePage();
			magMember.addNewSpace(spaceName+String.valueOf(i), "");
		}
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*Step number: 2
		 *Step Name: Show scrollbar in "In location" field
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
			- Click on the right arrow from the field "In location"
		 *Input Data: 

		 *Expected Outcome: 
			- The space switcher is displayed
			- Only 12 spaces are displayed and others are scrollable*/ 
		nav.goToCreateMenu();
		click(ELEMENT_ADD_TOPIC_ICON);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);
		click(ELEMENT_LOCATION_CARET);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_POLL_SCROLL_MENU);
		for(int i =1;i<14;i++){
			waitForAndGetElement(ELEMENT_LOCATION_OPTION.replace("${itemName}", spaceName+String.valueOf(i)));
		}
		button.cancel();

		info("Test 19 Display Space switcher in Create a new Poll menu");
		/*Step number: 2
		 *Step Name: Open Poll dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
		 *Input Data: 

		 *Expected Outcome: 
			- The menu is updated to "Create a new Poll:"
			- The field "In location" is displayed*/

		/*Step number: 3
		 *Step Name: Show "In location"
		 *Step Description: 
			- Click on the right arrow from the field "In location"
		 *Input Data: 

		 *Expected Outcome: 
			- The space switcher is displayed* Intranet* All spaces where Forum application is added and where the user is a member*/
		nav.goToCreateMenu();
		click(ELEMENT_ADD_POLL_ICON);
		click(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_POLL_SCROLL_MENU);
		for(int i =1;i<14;i++){
			waitForAndGetElement(ELEMENT_LOCATION_OPTION.replace("${itemName}", spaceName+String.valueOf(i)));
		}
		click(button.ELEMENT_CANCEL_BUTTON);
		//clear data
		for(int i =1;i<14;i++){
			magMember.goToAllSpaces();
			magMember.deleteSpace(spaceName+String.valueOf(i),300000);
		}
	}

	/**
	 *Case ID:104055.
	 *Test Case Name: Display Space switcher in "Create a new Topic" menu.
	 *Pre-Condition: 
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test20_DisplaySpaceSwitcherInCreateANewTopicMenu() {
		info("Test 20 Display Space switcher in Create a new Topic menu");
		//Declare variable
		String spaceName = "space 104055";
		//- Create new space
		magMember.goToMySpacePage();
		magMember.addNewSpace(spaceName, "");
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*Step number: 2
		 *Step Name: Show Topic dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
		 *Input Data: 

		 *Expected Outcome: 
			- The menu is updated to "Create a new Topic:"
			- The field "In location" is displayed*/
		nav.goToCreateMenu();
		click(ELEMENT_ADD_TOPIC_ICON);

		/*Step number: 3
		 *Step Name: Show "In location"
		 *Step Description: 
			- click on the right arrow from the field "In location"
		 *Input Data: 

		 *Expected Outcome: 
			- The space switcher is displayed* Intranet* All spaces where Forum application is added and where the user is a member*/
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);
		click(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		waitForAndGetElement(ELEMENT_LOCATION_OPTION.replace("${itemName}", spaceName));
		click(button.ELEMENT_CANCEL_BUTTON);
	}

	/**
	 *Case ID:104085.
	 *Test Case Name: Show "Select a Forum" in "And Forum" field for Poll menu.
	 *Case ID:104083.
	 *Test Case Name: Show "Intranet" as a default field in Poll menu.
	 *Case ID:104056.
	 *Test Case Name: Display the field "And Forum" in the Poll menu.
	 *Case ID:104081.
	 *Test Case Name: Select a forum from the list in "Create a new Poll" menu.
	 *Pre-Condition: 2 forums exist under Intranet
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test21_44_46_48_DisplayTheFieldAndForumInThePollMenu() {
		info("Test 21 Display the field And Forum in the Poll menu - Case ID:104056");
		String titleCat1 = "Category 1040561";
		String titleForum1 = "Forum 1040561";
		String titleTop1 = "Topic 1040561";

		String titleCat2 = "Category 1040562";
		String titleForum2 = "Forum 1040562";
		String titleTop2 = "Topic 1040562";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		info("Test 46 Show Intranet as a default field in Poll menu - Case ID:104083");
		/*Step number: 2
		 *Step Name: Open Poll dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Choose "Poll"
		 *Input Data: 

		 *Expected Outcome: 
			- The Create menu is updated to "Create a new Poll"
			- The field "In Location" is displayed with Intranet as default space switcher
			- Buttons "Cancel" and "Next" are displayed*/
		nav.goToCreateMenu();
		click(ELEMENT_ADD_POLL_ICON);
		waitForAndGetElement(ELEMENT_ADD_POLL_FORM);
		waitForAndGetElement(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);
		waitForAndGetElement(ELEMENT_POLL_TOPIC_SELECTED_LOCATION.replace("${itemName}", "intranet"));

		info("Test 48 Show Select a Forum in And Forum field for Poll menu - Case ID:104085");
		/*Step number: 3
		 *Step Name: Show "And forum" field
		 *Step Description: 
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			- A new select component "And Forum" is displayed
			- "Select a Forum" is displayed as a placeholder value
			- The button "Next" is disable*/ 
		button.next();
		waitForAndGetElement(ELEMENT_NEXT_BUTTON_DISABLE);
		waitForAndGetElement(nav.ELEMENT_SELECT_FORUM);

		info("Test 44 Select a forum from the list in Create a new Poll menu - Case ID:104081");
		/*Step number: 3
		 *Step Name: Select a forum
		 *Step Description: 
			- Click on the arrow in the field "And Forum"
			- Select a forum from the list
		 *Input Data: 

		 *Expected Outcome: 
			- The forum is selected
			- The button "Next" is clickable again*/
		click(nav.ELEMENT_SELECT_FORUM);
		click(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		button.next();
		button.cancel();

		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104086.
	 *Test Case Name: Show "Select a Forum" in "And Forum" field for Topic menu.
	 *Case ID:104084.
	 *Test Case Name: Show "Intranet" as a default field in Topic menu.
	 *Case ID:104057.
	 *Test Case Name: Display the field "And Forum" in the Topic menu.
	 *Case ID:104082.
	 *Test Case Name: Select a forum from the list in "Create a new Topic" menu.
	 *Pre-Condition: 2 forums exist under Intranet
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test22_45_47_49_DisplayTheFieldAndForumInTheTopicMenu() {
		info("Test 22 Display the field And Forum in the Topic menu - Case ID:104057");
		String titleCat1 = "Category 1040571";
		String titleForum1 = "Forum 1040571";
		String titleTop1 = "Topic 1040571";

		String titleCat2 = "Category 1040572";
		String titleForum2 = "Forum 1040572";
		String titleTop2 = "Topic 1040572";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			The Top Navigation bar is displayed*/

		info("Test 47 Show Intranet as a default field in Topic menu - Case ID:104084");
		/*Step number: 2
		 *Step Name: Open Topic dropdown menu
		 *Step Description: 
			-Mouse over on the button "Create" (+)
			- Choose "Topic"
		 *Input Data: 

		 *Expected Outcome: 
			- The Create menu is updated to "Create a new Topic"
			- The field "In Location" is displayed with Intranet as default space switcher
			- Buttons "Cancel" and "Next" are displayed*/
		nav.goToCreateMenu();
		click(ELEMENT_ADD_TOPIC_ICON);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);
		waitForAndGetElement(ELEMENT_POLL_TOPIC_SELECTED_LOCATION.replace("${itemName}", "intranet"));

		info("Test 49 Show Select a Forum in And Forum field for Topic menu - Case ID:104086");
		/*Step number: 3
		 *Step Name: Show "And Forum" field
		 *Step Description: 
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			- A new select component "And Forum" is displayed
			- "Select a Forum" is displayed as a placeholder value
			- The button "Next" is disable*/ 
		button.next();
		Utils.pause(5000);
		waitForAndGetElement(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_NEXT_BUTTON_DISABLE);

		/*Step number: 3
		 *Step Name: Select a forum
		 *Step Description: 
			- Click on the arrow in the field "And Forum"
			- Select a forum from the list
		 *Input Data: 

		 *Expected Outcome: 
			- The forum is selected
			- The button "Next" is clickable again*/ 
		info("Test 45 Select a forum from the list in Create a new Topic menu - Case ID:104082.");
		click(nav.ELEMENT_SELECT_FORUM);
		click(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		button.next();
		button.cancel();

		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104059.
	 *Test Case Name: Not Display a closed Forum in "Create a new Poll" menu.
	 *Pre-Condition: the user has permissions to start a poll in a Forum
	 *Forum is closed
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test23_NotDisplayAClosedForumInCreateANewPollMenu() {
		info("Test 23 Not Display a closed Forum in Create a new Poll menu");
		String titleCat1 = "Category 1040591";
		String titleForum1 = "Forum 1040591";
		String titleTop1 = "Topic 1040591";

		String titleCat2 = "Category 1040592";
		String titleForum2 = "Forum 1040592";
		String titleTop2 = "Topic 1040592";

		String titleCat3 = "Category 1040593";
		String titleForum3 = "Forum 1040593";
		String titleTop3 = "Topic 1040593";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		mngTopic.addCategoryForumTopic(titleCat3, titleForum3, titleTop3,titleTop3);
		//Close forum 3
		mngFru.actionOnForum(3);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Polldropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/
		nav.goToPoll();

		/*Step number: 3
		 *Step Name: Not Show closed forums
		 *Step Description: 
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- The forum closed is not displayed*/ 
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));
		click(button.ELEMENT_CANCEL_BUTTON);

		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat3));
		mngCat.deleteCategoryInForum(titleCat3, true);
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104060.
	 *Test Case Name: Not Display a closed Forum in "Create a new Topic" menu.
	 *Pre-Condition: the user has permissions to start a poll in a ForumForum is closed
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test24_NotDisplayAClosedForumInCreateANewTopicMenu() {
		info("Test 24 Not Display a closed Forum in Create a new Topic menu");
		String titleCat1 = "Category 1040601";
		String titleForum1 = "Forum 1040601";
		String titleTop1 = "Topic 1040601";

		String titleCat2 = "Category 1040602";
		String titleForum2 = "Forum 1040592";
		String titleTop2 = "Topic 1040592";

		String titleCat3 = "Category 1040603";
		String titleForum3 = "Forum 1040603";
		String titleTop3 = "Topic 1040603";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		mngTopic.addCategoryForumTopic(titleCat3, titleForum3, titleTop3,titleTop3);
		//Close forum 3
		mngFru.actionOnForum(3);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Topic dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/
		nav.goToTopic();
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);

		/*Step number: 3
		 *Step Name: Not Show closed forums
		 *Step Description: 
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- The forum closed is not displayed*/ 
		click(ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));
		click(button.ELEMENT_CANCEL_BUTTON);

		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat3));
		mngCat.deleteCategoryInForum(titleCat3, true);
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104061.
	 *Test Case Name: Not Display a locked Forum in "Create a new Poll" menu.
	 *Pre-Condition: the user has permissions to start a poll in a ForumSome 
	 *Forum is locked
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test25_NotDisplayALockedForumInCreateANewPollMenu() {
		info("Test 25 Not Display a locked Forum in Create a new Poll menu");
		String titleCat1 = "Category 1040611";
		String titleForum1 = "Forum 1040611";
		String titleTop1 = "Topic 1040611";

		String titleCat2 = "Category 1040612";
		String titleForum2 = "Forum 1040612";
		String titleTop2 = "Topic 1040612";

		String titleCat3 = "Category 1040613";
		String titleForum3 = "Forum 1040613";
		String titleTop3 = "Topic 1040613";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		mngTopic.addCategoryForumTopic(titleCat3, titleForum3, titleTop3,titleTop3);
		//Lock forum 3
		mngFru.actionOnForum(1);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Poll dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/
		nav.goToPoll();

		/*Step number: 3
		 *Step Name: Not show locked forums
		 *Step Description: 
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- The forum locked is not displayed*/ 
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));
		click(button.ELEMENT_CANCEL_BUTTON);

		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat3));
		mngCat.deleteCategoryInForum(titleCat3, true);
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104062.
	 *Test Case Name: Not Display a locked Forum in "Create a new Topic" menu.
	 *Pre-Condition: the user has permissions to start a topic in a ForumForum is locked
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test26_NotDisplayALockedForumInCreateANewTopicMenu() {
		info("Test 26 Not Display a locked Forum in Create a new Topic menu");
		String titleCat1 = "Category 1040621";
		String titleForum1 = "Forum 1040621";
		String titleTop1 = "Topic 1040621";

		String titleCat2 = "Category 1040622";
		String titleForum2 = "Forum 1040622";
		String titleTop2 = "Topic 1040622";

		String titleCat3 = "Category 1040623";
		String titleForum3 = "Forum 1040623";
		String titleTop3 = "Topic 1040623";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		mngTopic.addCategoryForumTopic(titleCat3, titleForum3, titleTop3,titleTop3);
		//Lock forum 3
		mngFru.actionOnForum(2);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Topic dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/
		nav.goToTopic();
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);

		/*Step number: 3
		 *Step Name: Not show locked forums
		 *Step Description: 
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- The forum locked is not displayed*/ 
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));
		click(button.ELEMENT_CANCEL_BUTTON);

		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat3));
		mngCat.deleteCategoryInForum(titleCat3, true);
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104063.
	 *Test Case Name: Not display category when forum aren't searched in "Create a new Poll" menu.
	 *Pre-Condition: Forums in a category are not matched to the search
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test27_NotDisplayCategoryWhenForumArentSearchedInCreateANewPollMenu() {
		info("Test 27 Not display category when forum aren't searched in Create a new Poll menu");
		String titleCat1 = "Category 1040631";
		String titleForum1 = "Forum 1040631";
		String titleTop1 = "Topic 1040631";

		String titleCat2 = "Category 1040632";
		String titleForum2 = "Forum 1040632";
		String titleTop2 = "Topic 1040632";

		String titleCat3 = "Category 1040633";
		String titleForum3 = "Forum 1040633";
		String titleTop3 = "Topic 1040633";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		mngTopic.addCategoryForumTopic(titleCat3, titleForum3, titleTop3,titleTop3);

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Poll dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
			- Click on the button "Next"
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- The list of categories and forums of each category is displayed
			- A textfield in the top of the list is displayed*/
		nav.goToPoll();

		/*Step number: 3
		 *Step Name: Not show categories only containing forums that are not matched to search
		 *Step Description: 
			- Input a valid search key in the textfield
		 *Input Data: 

		 *Expected Outcome: 
			- forumsstarting or having a characters are displayed 
			- category of which forums aren't searched are not displayed*/ 
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_FILTER_FORUM);
		type(ELEMENT_FILTER_FORUM,titleForum3,true);
		type(ELEMENT_FILTER_FORUM, Keys.ENTER.toString(), false);
		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));
		click(button.ELEMENT_CANCEL_BUTTON);

		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat3));
		mngCat.deleteCategoryInForum(titleCat3, true);
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104064.
	 *Test Case Name: Not display category when forum aren't searched in "Create a new Topic" menu.
	 *Pre-Condition: Forums in a category are not matched to the search
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test28_NotDisplayCategoryWhenForumArentSearchedInCreateANewTopicMenu() {
		info("Test 28 Not display category when forum aren't searched in Create a new Topic menu");
		String titleCat1 = "Category 1040641";
		String titleForum1 = "Forum 1040641";
		String titleTop1 = "Topic 1040641";

		String titleCat2 = "Category 1040642";
		String titleForum2 = "Forum 1040642";
		String titleTop2 = "Topic 1040642";

		String titleCat3 = "Category 1040643";
		String titleForum3 = "Forum 1040643";
		String titleTop3 = "Topic 1040643";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		mngTopic.addCategoryForumTopic(titleCat3, titleForum3, titleTop3,titleTop3);

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Topic dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
			- Click on the button "Next"
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- The list of categories and forums of each category is displayed
			- A textfield in the top of the list is displayed*/
		nav.goToTopic();
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);

		/*Step number: 3
		 *Step Name: Not show category of which forums are not matched
		 *Step Description: 
			- Input a valid search key in the textfield
		 *Input Data: 

		 *Expected Outcome: 
			- forumsstarting or having a characters are displayed 
			- category of which forums aren't searched are not displayed*/ 
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_FILTER_FORUM);
		type(ELEMENT_FILTER_FORUM,titleForum3,true);
		type(ELEMENT_FILTER_FORUM, Keys.ENTER.toString(), false);
		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));
		click(button.ELEMENT_CANCEL_BUTTON);

		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat3));
		mngCat.deleteCategoryInForum(titleCat3, true);
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);

	}

	/**
	 *Case ID:104065.
	 *Test Case Name: Not Display category where forums cannot be displayed in "Create a new Poll" menu.
	 *Pre-Condition: Add a category contains:
	 ** A user without permissions to start a poll in a Forum* 
	 *Forum is closed or locked
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test29_NotDisplayCategoryWhereForumsCannotBeDisplayedInCreateANewPollMenu() {
		info("Test 29 Not Display category where forums cannot be displayed in Create a new Poll menu");
		String titleCat1 = "Category 1040651";
		String titleForum1 = "Forum 1040651";
		String[] addForum1 = {titleForum1, "1", "Open", "Unlocked", titleForum1}; 
		String titleTop1 = "Topic 1040651";

		String titleCat2 = "Category 1040652";
		String titleForum2 = "Forum 1040652";
		String[] addForum2 = {titleForum2, "1", "Open", "Unlocked", titleForum2};
		String titleTop2 = "Topic 1040652";

		String titleCat3 = "Category 1040653";
		String titleForum3 = "Forum 1040653";
		String[] addForum3 = {titleForum3, "1", "Open", "Unlocked", titleForum3};
		String titleTop3 = "Topic 1040653";

		String titleCat4 = "Category 1040654";
		String titleForum4 = "Forum 1040654";
		String[] addForum4 = {titleForum4, "1", "Open", "Unlocked", titleForum4};
		String titleTop4 = "Topic 1040654";

		String[] user1 = {"james"};
		String[] user2 = {"mary"};

		mngTopic.goToForums(); 
		info("Create New Category 1");
		mngCat.goToAddCategory(); 
		mngCat.inputTitleOrderDescriptionCategory(titleCat1, "1", titleCat1);
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user1, true, true, true, true);
		frumPer.configPermission4ForumCategory(1, user2, true, true, true, true);
		button.save();

		info("Create New Forum 1");
		mngFru.goToAddForum(); 
		mngFru.inputDataInAddForumTab_addForum(titleCat1, addForum1); 
		button.save(); 
		info("Create topic");
		mngTopic.quickStartTopic(titleTop1, titleTop1); 

		info("Create New Category 2");
		mngCat.goToAddCategory(); 
		mngCat.inputTitleOrderDescriptionCategory(titleCat2, "1", titleCat2);
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user1, true, true, true, true);
		frumPer.configPermission4ForumCategory(1, user2, true, true, true, true);
		button.save();

		info("Create New Forum 2");
		mngFru.goToAddForum(); 
		mngFru.inputDataInAddForumTab_addForum(titleCat2, addForum2); 
		button.save(); 
		info("Create topic");
		mngTopic.quickStartTopic(titleTop2, titleTop2); 

		info("Create New Category 3");
		mngCat.goToAddCategory(); 
		mngCat.inputTitleOrderDescriptionCategory(titleCat3, "1", titleCat3);
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user1, false, false, false, true);
		frumPer.configPermission4ForumCategory(1, user2, true, true, true, true);
		button.save();

		info("Create New Forum 3");
		mngFru.goToAddForum(); 
		mngFru.inputDataInAddForumTab_addForum(titleCat3, addForum3); 
		button.save(); 
		info("Create topic");
		mngTopic.quickStartTopic(titleTop3, titleTop3); 

		info("Create New Category 4");
		mngCat.goToAddCategory(); 
		mngCat.inputTitleOrderDescriptionCategory(titleCat4, "1", titleCat4);
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user1, false, false, false, true);
		frumPer.configPermission4ForumCategory(1, user2, true, true, true, true);
		button.save();

		info("Create New Forum 4");
		mngFru.goToAddForum(); 
		mngFru.inputDataInAddForumTab_addForum(titleCat4, addForum4); 
		button.save(); 
		info("Create topic");
		mngTopic.quickStartTopic(titleTop4, titleTop4); 

		//Close forum 4
		click(mngCat.ELEMENT_HOME_CATEGORY);
		click(By.linkText(titleCat4));
		click(By.linkText(titleForum4));
		mngFru.actionOnForum(3);
		//Lock forum 3
		click(mngCat.ELEMENT_HOME_CATEGORY);
		click(By.linkText(titleCat3));
		click(By.linkText(titleForum3));
		mngFru.actionOnForum(1);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Poll dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/
		acc.userSignIn(userType.AUTHOR);
		nav.goToPoll();

		/*Step number: 3
		 *Step Name: Not show a category only containing locked, closed, or unaccessible forums
		 *Step Description: 
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			-A category only containing locked, closed, or unaccessible forums is not displayed in the list*/
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));
		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum4));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat4));
		click(button.ELEMENT_CANCEL_BUTTON);

		//Login with user have all right permission
		acc.userSignIn(userType.PUBLISHER);
		nav.goToPoll();
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));
		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum4));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat4));
		click(button.ELEMENT_CANCEL_BUTTON);

		/*Clear data*/
		acc.userSignIn(userType.ADMIN);
		mngTopic.goToForums();
		click(By.linkText(titleCat4));
		mngCat.deleteCategoryInForum(titleCat4, true);
		click(By.linkText(titleCat3));
		mngCat.deleteCategoryInForum(titleCat3, true);
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104066.
	 *Test Case Name: Not Display category where forums cannot be displayed in "Create a new Topic" menu.
	 *Pre-Condition: Add a category contains:* A user without permissions to start a topic in a Forum* 
	 *Forum is closed or locked
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test30_NotDisplayCategoryWhereForumsCannotBeDisplayedInCreateANewTopicMenu() {
		info("Test 30 Not Display category where forums cannot be displayed in Create a new Topic menu");
		String titleCat1 = "Category 1040661";
		String titleForum1 = "Forum 1040661";
		String[] addForum1 = {titleForum1, "1", "Open", "Unlocked", titleForum1}; 
		String titleTop1 = "Topic 1040661";

		String titleCat2 = "Category 1040662";
		String titleForum2 = "Forum 1040662";
		String[] addForum2 = {titleForum2, "1", "Open", "Unlocked", titleForum2};
		String titleTop2 = "Topic 1040662";

		String titleCat3 = "Category 1040663";
		String titleForum3 = "Forum 1040663";
		String[] addForum3 = {titleForum3, "1", "Open", "Unlocked", titleForum3};
		String titleTop3 = "Topic 1040663";

		String titleCat4 = "Category 1040664";
		String titleForum4 = "Forum 1040664";
		String[] addForum4 = {titleForum4, "1", "Open", "Unlocked", titleForum4};
		String titleTop4 = "Topic 1040664";

		String[] user1 = {"james"};
		String[] user2 = {"mary"};

		mngTopic.goToForums(); 
		info("Create New Category 1");
		mngCat.goToAddCategory(); 
		mngCat.inputTitleOrderDescriptionCategory(titleCat1, "1", titleCat1);
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user1, true, true, true, true);
		frumPer.configPermission4ForumCategory(1, user2, true, true, true, true);
		button.save();

		info("Create New Forum 1");
		mngFru.goToAddForum(); 
		mngFru.inputDataInAddForumTab_addForum(titleCat1, addForum1); 
		button.save(); 
		info("Create topic");
		mngTopic.quickStartTopic(titleTop1, titleTop1); 

		info("Create New Category 2");
		mngCat.goToAddCategory(); 
		mngCat.inputTitleOrderDescriptionCategory(titleCat2, "1", titleCat2);
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user1, true, true, true, true);
		frumPer.configPermission4ForumCategory(1, user2, true, true, true, true);
		button.save();

		info("Create New Forum 2");
		mngFru.goToAddForum(); 
		mngFru.inputDataInAddForumTab_addForum(titleCat2, addForum2); 
		button.save(); 
		info("Create topic");
		mngTopic.quickStartTopic(titleTop2, titleTop2); 

		info("Create New Category 3");
		mngCat.goToAddCategory(); 
		mngCat.inputTitleOrderDescriptionCategory(titleCat3, "1", titleCat3);
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user1, false, false, false, true);
		frumPer.configPermission4ForumCategory(1, user2, true, true, true, true);
		button.save();

		info("Create New Forum 3");
		mngFru.goToAddForum(); 
		mngFru.inputDataInAddForumTab_addForum(titleCat3, addForum3); 
		button.save(); 
		info("Create topic");
		mngTopic.quickStartTopic(titleTop3, titleTop3); 

		info("Create New Category 4");
		mngCat.goToAddCategory(); 
		mngCat.inputTitleOrderDescriptionCategory(titleCat4, "1", titleCat4);
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user1, false, false, false, true);
		frumPer.configPermission4ForumCategory(1, user2, true, true, true, true);
		button.save();

		info("Create New Forum 4");
		mngFru.goToAddForum(); 
		mngFru.inputDataInAddForumTab_addForum(titleCat4, addForum4); 
		button.save(); 
		info("Create topic");
		mngTopic.quickStartTopic(titleTop4, titleTop4); 

		//Close forum 4
		click(mngCat.ELEMENT_HOME_CATEGORY);
		click(By.linkText(titleCat4));
		click(By.linkText(titleForum4));
		mngFru.actionOnForum(3);
		//Lock forum 3
		click(mngCat.ELEMENT_HOME_CATEGORY);
		click(By.linkText(titleCat3));
		click(By.linkText(titleForum3));
		mngFru.actionOnForum(1);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Topic dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/
		acc.userSignIn(userType.AUTHOR);
		nav.goToTopic();
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);
		/*Step number: 3
		 *Step Name: Not show a category only containing locked, closed, or unaccessible forums
		 *Step Description: 
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- A category only containing locked, closed, or unaccessible forums is not displayed in the list*/
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));
		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum4));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat4));
		click(button.ELEMENT_CANCEL_BUTTON);

		//Login with user have all right permission
		acc.userSignIn(userType.PUBLISHER);
		nav.goToTopic();
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));
		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum4));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat4));
		click(button.ELEMENT_CANCEL_BUTTON);

		/*Clear data*/
		acc.userSignIn(userType.ADMIN);
		mngTopic.goToForums();
		click(By.linkText(titleCat4));
		mngCat.deleteCategoryInForum(titleCat4, true);
		click(By.linkText(titleCat3));
		mngCat.deleteCategoryInForum(titleCat3, true);
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);

	}

	/**
	 *Case ID:104067.
	 *Test Case Name: Not Display Forum added by an admin user in category space in "Create a new Topic" menu.
	 *Pre-Condition: the user has permissions to start a Topic in a Forum
	 *Forums are not closed and not locked
	 *the forum is added in category "space" by admin 
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test31_NotDisplayForumAddedByAnAdminUserInCategorySpaceInCreateANewTopicMenu() {
		info("Test 31 Not Display Forum added by an admin user in category space in Create a new Topic menu");
		String titleCat1 = "Category 1040671";
		String titleForum1 = "Forum 1040671";
		String titleTop1 = "Topic 1040671";

		String titleCat2 = "Category 1040672";
		String titleForum2 = "Forum 1040672";
		String titleTop2 = "Topic 1040672";

		String spaceName = "space 104067";
		String spaceCat = "space";

		//- Create new space
		magMember.goToMySpacePage();
		magMember.addNewSpace(spaceName, "");
		nav.goToHomePage();

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);

		/*Step Number: 1
		 *Step Name: Connect to intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Topic dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/
		nav.goToTopic();
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);

		/*Step number: 3
		 *Step Name: Not show forum added to "space" category
		 *Step Description: 
			- Click on the right arrow from the field "And Forum"
		 *Input Data: 

		 *Expected Outcome: 
			- The forum which added in the category "space" is not displayed*/ 
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_FILTER_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));
		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", spaceName));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${spaceCat}", spaceCat));
		click(button.ELEMENT_CANCEL_BUTTON);
		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);

		magMember.goToAllSpaces();
		magMember.deleteSpace(spaceName,300000);
	}

	/**
	 *Case ID:104068.
	 *Test Case Name: Not Display Forum for user without permission to start a Poll.
	 *Pre-Condition: the user has not permissions to start a poll in a Forum
	 *Forums are not closed and not locked
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test32_NotDisplayForumForUserWithoutPermissionToStartAPoll() {
		info("Test 32 Not Display Forum for user without permission to start a Poll");
		String titleCat1 = "Category 1040681";
		String titleForum1 = "Forum 1040681";
		String[] addForum1 = {titleForum1, "1", "Open", "Unlocked", titleForum1}; 
		String titleTop1 = "Topic 1040681";

		String titleCat2 = "Category 1040682";
		String titleForum2 = "Forum 1040682";
		String[] addForum2 = {titleForum2, "1", "Open", "Unlocked", titleForum2};
		String titleTop2 = "Topic 1040682";

		String titleCat3 = "Category 1040683";
		String titleForum3 = "Forum 1040683";
		String[] addForum3 = {titleForum3, "1", "Open", "Unlocked", titleForum3};
		String titleTop3 = "Topic 1040683";

		String titleCat4 = "Category 1040684";
		String titleForum4 = "Forum 1040684";
		String[] addForum4 = {titleForum4, "1", "Open", "Unlocked", titleForum4};
		String titleTop4 = "Topic 1040684";

		String[] user1 = {"james"};
		String[] user2 = {"mary"};

		mngTopic.goToForums(); 
		info("Create New Category 1");
		mngCat.goToAddCategory(); 
		mngCat.inputTitleOrderDescriptionCategory(titleCat1, "1", titleCat1);
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user1, true, true, true, true);
		frumPer.configPermission4ForumCategory(1, user2, true, true, true, true);
		button.save();

		info("Create New Forum 1");
		mngFru.goToAddForum(); 
		mngFru.inputDataInAddForumTab_addForum(titleCat1, addForum1); 
		button.save(); 
		info("Create topic");
		mngTopic.quickStartTopic(titleTop1, titleTop1); 

		info("Create New Category 2");
		mngCat.goToAddCategory(); 
		mngCat.inputTitleOrderDescriptionCategory(titleCat2, "1", titleCat2);
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user1, true, true, true, true);
		frumPer.configPermission4ForumCategory(1, user2, true, true, true, true);
		button.save();

		info("Create New Forum 2");
		mngFru.goToAddForum(); 
		mngFru.inputDataInAddForumTab_addForum(titleCat2, addForum2); 
		button.save(); 
		info("Create topic");
		mngTopic.quickStartTopic(titleTop2, titleTop2); 

		info("Create New Category 3");
		mngCat.goToAddCategory(); 
		mngCat.inputTitleOrderDescriptionCategory(titleCat3, "1", titleCat3);
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user1, false, false, false, true);
		frumPer.configPermission4ForumCategory(1, user2, true, true, true, true);
		button.save();

		info("Create New Forum 3");
		mngFru.goToAddForum(); 
		mngFru.inputDataInAddForumTab_addForum(titleCat3, addForum3); 
		button.save(); 
		info("Create topic");
		mngTopic.quickStartTopic(titleTop3, titleTop3); 

		info("Create New Category 4");
		mngCat.goToAddCategory(); 
		mngCat.inputTitleOrderDescriptionCategory(titleCat4, "1", titleCat4);
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user1, false, false, false, true);
		frumPer.configPermission4ForumCategory(1, user2, true, true, true, true);
		button.save();

		info("Create New Forum 4");
		mngFru.goToAddForum(); 
		mngFru.inputDataInAddForumTab_addForum(titleCat4, addForum4); 
		button.save(); 
		info("Create topic");
		mngTopic.quickStartTopic(titleTop4, titleTop4); 

		/*Step Number: 1
		 *Step Name: Connect to intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Poll dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/
		acc.userSignIn(userType.AUTHOR);
		nav.goToPoll();

		/*Step number: 3
		 *Step Name: Not show forum which user has not permission
		 *Step Description: 
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- The forum where user has not permission to create a new poll is not displayed*/
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));
		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum4));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat4));
		click(button.ELEMENT_CANCEL_BUTTON);

		//Login with user have all right permission
		acc.userSignIn(userType.PUBLISHER);
		nav.goToPoll();
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum4));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat4));
		click(button.ELEMENT_CANCEL_BUTTON);

		/*Clear data*/
		acc.userSignIn(userType.ADMIN);
		mngTopic.goToForums();
		click(By.linkText(titleCat4));
		mngCat.deleteCategoryInForum(titleCat4, true);
		click(By.linkText(titleCat3));
		mngCat.deleteCategoryInForum(titleCat3, true);
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104069.
	 *Test Case Name: Not Display Forum for user without permission to start a Topic.
	 *Pre-Condition: the user has not permissions to start a Topic in a ForumForums are not closed and not locked
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test33_NotDisplayForumForUserWithoutPermissionToStartATopic() {
		info("Test 33 Not Display Forum for user without permission to start a Topic");
		String titleCat1 = "Category 1040691";
		String titleForum1 = "Forum 1040691";
		String[] addForum1 = {titleForum1, "1", "Open", "Unlocked", titleForum1}; 
		String titleTop1 = "Topic 1040691";

		String titleCat2 = "Category 1040692";
		String titleForum2 = "Forum 1040692";
		String[] addForum2 = {titleForum2, "1", "Open", "Unlocked", titleForum2};
		String titleTop2 = "Topic 1040692";

		String titleCat3 = "Category 1040693";
		String titleForum3 = "Forum 1040693";
		String[] addForum3 = {titleForum3, "1", "Open", "Unlocked", titleForum3};
		String titleTop3 = "Topic 1040693";

		String titleCat4 = "Category 1040694";
		String titleForum4 = "Forum 1040694";
		String[] addForum4 = {titleForum4, "1", "Open", "Unlocked", titleForum4};
		String titleTop4 = "Topic 1040694";

		String[] user1 = {"james"};
		String[] user2 = {"mary"};

		mngTopic.goToForums(); 
		info("Create New Category 1");
		mngCat.goToAddCategory(); 
		mngCat.inputTitleOrderDescriptionCategory(titleCat1, "1", titleCat1);
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user1, true, true, true, true);
		frumPer.configPermission4ForumCategory(1, user2, true, true, true, true);
		button.save();

		info("Create New Forum 1");
		mngFru.goToAddForum(); 
		mngFru.inputDataInAddForumTab_addForum(titleCat1, addForum1); 
		button.save(); 
		info("Create topic");
		mngTopic.quickStartTopic(titleTop1, titleTop1); 

		info("Create New Category 2");
		mngCat.goToAddCategory(); 
		mngCat.inputTitleOrderDescriptionCategory(titleCat2, "1", titleCat2);
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user1, true, true, true, true);
		frumPer.configPermission4ForumCategory(1, user2, true, true, true, true);
		button.save();

		info("Create New Forum 2");
		mngFru.goToAddForum(); 
		mngFru.inputDataInAddForumTab_addForum(titleCat2, addForum2); 
		button.save(); 
		info("Create topic");
		mngTopic.quickStartTopic(titleTop2, titleTop2); 

		info("Create New Category 3");
		mngCat.goToAddCategory(); 
		mngCat.inputTitleOrderDescriptionCategory(titleCat3, "1", titleCat3);
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user1, false, false, false, true);
		frumPer.configPermission4ForumCategory(1, user2, true, true, true, true);
		button.save();

		info("Create New Forum 3");
		mngFru.goToAddForum(); 
		mngFru.inputDataInAddForumTab_addForum(titleCat3, addForum3); 
		button.save(); 
		info("Create topic");
		mngTopic.quickStartTopic(titleTop3, titleTop3); 

		info("Create New Category 4");
		mngCat.goToAddCategory(); 
		mngCat.inputTitleOrderDescriptionCategory(titleCat4, "1", titleCat4);
		info("Set permission for category");
		frumPer.configPermission4ForumCategory(2, user1, false, false, false, true);
		frumPer.configPermission4ForumCategory(1, user2, true, true, true, true);
		button.save();

		info("Create New Forum 4");
		mngFru.goToAddForum(); 
		mngFru.inputDataInAddForumTab_addForum(titleCat4, addForum4); 
		button.save(); 
		info("Create topic");
		mngTopic.quickStartTopic(titleTop4, titleTop4); 

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Poll dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/
		acc.userSignIn(userType.AUTHOR);
		nav.goToTopic();
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);

		/*Step number: 3
		 *Step Name: Not show forum which user has not permission
		 *Step Description: 
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- The forum where user has not permission to create a new Topic is not displayed*/ 
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));
		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum4));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat4));
		click(button.ELEMENT_CANCEL_BUTTON);

		//Login with user have all right permission
		acc.userSignIn(userType.PUBLISHER);
		nav.goToTopic();
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum4));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat4));
		click(button.ELEMENT_CANCEL_BUTTON);

		/*Clear data*/
		acc.userSignIn(userType.ADMIN);
		mngTopic.goToForums();
		click(By.linkText(titleCat4));
		mngCat.deleteCategoryInForum(titleCat4, true);
		click(By.linkText(titleCat3));
		mngCat.deleteCategoryInForum(titleCat3, true);
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104071.
	 *Test Case Name: Not Display forums in space's category in "Create a new Poll" menu.
	 *Pre-Condition: add forum to space where* user is member in the space* 
	 *the user has permissions to start a poll * 
	 *Forums are not closed and not locked
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test34_NotDisplayForumsInSpacesCategoryInCreateANewPollMenu() {
		info("Test 34 Not Display forums in space's category in Create a new Poll menu");
		String titleCat1 = "Category 1040711";
		String titleForum1 = "Forum 1040711";
		String titleTop1 = "Topic 1040711";

		String titleCat2 = "Category 1040712";
		String titleForum2 = "Forum 1040712";
		String titleTop2 = "Topic 1040712";

		String spaceName = "space 104071";
		String spaceCat = "space";

		//- Create new space
		magMember.goToMySpacePage();
		magMember.addNewSpace(spaceName, "");
		nav.goToHomePage();

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Poll dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/
		nav.goToPoll();
		click(nav.ELEMENT_SELECT_FORUM);

		/*Step number: 3
		 *Step Name: Not show forum added "Space" category
		 *Step Description: 
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- forums in space's category are not displayed
			- The category space type is not displayed*/ 
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_FILTER_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));
		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", spaceName));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${spaceCat}", spaceCat));
		click(button.ELEMENT_CANCEL_BUTTON);
		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);

		magMember.goToAllSpaces();
		magMember.deleteSpace(spaceName,300000);
	}

	/**
	 *Case ID:104072.
	 *Test Case Name: Not Display forums in space's category in "Create a new Topic" menu.
	 *Pre-Condition: add forum to space where* user is member in the space* the user has permissions to start a Topic* Forums are not closed and not locked
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test35_NotDisplayForumsInSpacesCategoryInCreateANewTopicMenu() {
		info("Test 35 Not Display forums in space's category in Create a new Topic menu");
		String titleCat1 = "Category 1040721";
		String titleForum1 = "Forum 1040721";
		String titleTop1 = "Topic 1040721";

		String titleCat2 = "Category 1040722";
		String titleForum2 = "Forum 1040722";
		String titleTop2 = "Topic 1040722";

		String spaceName = "space 104072";
		String spaceCat = "space";

		//- Create new space
		magMember.goToMySpacePage();
		magMember.addNewSpace(spaceName, "");
		nav.goToHomePage();

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		/*Step Number: 1
		 *Step Name: Connect to intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Topic dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/
		nav.goToTopic();
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);

		/*Step number: 3
		 *Step Name: Not show forum added to "Space" category
		 *Step Description: 
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- forums in space's category are not displayed
			- The category space type is not displayed*/ 
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_FILTER_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));
		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", spaceName));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${spaceCat}", spaceCat));
		click(button.ELEMENT_CANCEL_BUTTON);
		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);

		magMember.goToAllSpaces();
		magMember.deleteSpace(spaceName,300000);
	}

	/**
	 *Case ID:104073.
	 *Test Case Name: Open Poll application from "In location: Intranet" field.
	 *Pre-Condition: only one forum exists in Intranet
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test36_OpenPollApplicationFromInLocationIntranetField() {
		info("Test 36 Open Poll application from In location: Intranet field");

		String titleCat1 = "Category 104073";
		String titleForum1 = "Forum 104073";
		String titleTop1 = "Topic 104073";
		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);

		/*Step Number: 1
		 *Step Name: Connect to intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Poll dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
		 *Input Data: 

		 *Expected Outcome: 
			- The menu is updated to "Create a new Topic:"
			- "Intranet" is displayed in the field "In location"
			- Buttons "Cancel" and "Next" are displayed*/
		nav.goToCreateMenu();
		click(ELEMENT_ADD_POLL_ICON);
		waitForAndGetElement(ELEMENT_ADD_POLL_FORM);
		waitForAndGetElement(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);

		/*Step number: 3
		 *Step Name: Open a post editor
		 *Step Description: 
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			- The forum application is displayed under Intranet
			- A new Post editor is opened ready to create a new poll*/ 
		click(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(ELEMENT_HOME_PAGE);
		waitForAndGetElement(mngPoll.ELEMENT_POLL_QUESTION);
		waitForAndGetElement(mngPoll.ELEMENT_POLL_OPTION.replace("${index}", "1"));
		waitForAndGetElement(mngPoll.ELEMENT_POLL_CLOSE);
		waitForAndGetElement(mngPoll.ELEMENT_POLL_VOTE_AGAIN,5000,1,2);
		waitForAndGetElement(mngPoll.ELEMENT_POLL_MULTI_VOTE,5000,1,2);
		click(button.ELEMENT_CANCEL_BUTTON);
		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104074.
	 *Test Case Name: Open Poll application from "In location: Space" field.
	 *Pre-Condition: onlyoneforumexists inSpace
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test37_OpenPollApplicationFromInLocationSpaceField() {
		info("Test 37 Open Poll application from In location: Space field");
		String spaceName = "space 104074";

		//- Create new space
		magMember.goToMySpacePage();
		magMember.addNewSpace(spaceName, "");
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Poll dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
		 *Input Data: 

		 *Expected Outcome: 
			- The menu is updated to "Create a new Poll:"
			- The Space Forum is displayed in "In location" field
			- Buttons "Cancel" and "Next" are displayed*/
		nav.goToCreateMenu();
		click(ELEMENT_ADD_POLL_ICON);
		waitForAndGetElement(ELEMENT_ADD_POLL_FORM);
		waitForAndGetElement(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);

		/*Step number: 3
		 *Step Name: Open a post editor
		 *Step Description: 
			- Select a space in "In location" field
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			- The forum application is displayed in space
			- A new Post editor is opened ready to create a new poll*/ 
		click(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		click(ELEMENT_LOCATION_OPTION.replace("${itemName}", spaceName));
		button.next();
		waitForAndGetElement(spaceMag.ELEMENT_SPACE_CURRENT_NAME.replace("${spaceName}", spaceName));
		waitForAndGetElement(mngPoll.ELEMENT_POLL_QUESTION);
		waitForAndGetElement(mngPoll.ELEMENT_POLL_OPTION.replace("${index}", "1"));
		waitForAndGetElement(mngPoll.ELEMENT_POLL_CLOSE);
		waitForAndGetElement(mngPoll.ELEMENT_POLL_VOTE_AGAIN,5000,1,2);
		waitForAndGetElement(mngPoll.ELEMENT_POLL_MULTI_VOTE,5000,1,2);
		click(button.ELEMENT_CANCEL_BUTTON);
		/*Clear data*/		
		magMember.goToAllSpaces();
		magMember.deleteSpace(spaceName,300000);

	}

	/**
	 *Case ID:104075.
	 *Test Case Name: Open Poll application in a selected space.
	 *Pre-Condition: a space contain forum application
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test38_OpenPollApplicationInASelectedSpace() {
		info("Test 38 Open Poll application in a selected space");
		String spaceName1 = "space 1040751";
		String spaceName2 = "space 1040752";

		//- Create new space
		magMember.goToMySpacePage();
		magMember.addNewSpace(spaceName1, "");
		magMember.goToMySpacePage();
		magMember.addNewSpace(spaceName2, "");
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Poll dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
		 *Input Data: 

		 *Expected Outcome: 
			- The menu is updated to "Create a new Topic:"
			- The field "In location" is displayed 
			- Buttons "Cancel" and "Next" are displayed*/
		nav.goToCreateMenu();
		click(ELEMENT_ADD_POLL_ICON);
		waitForAndGetElement(ELEMENT_ADD_POLL_FORM);
		waitForAndGetElement(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);

		/*Step number: 3
		 *Step Name: Open a post editor
		 *Step Description: 
			- From the field "In location", choose a space from the list
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			- The forum application is displayed in the chosen space
			- A new Post editor is opened ready to create a new poll*/
		click(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		click(ELEMENT_LOCATION_OPTION.replace("${itemName}", spaceName2));
		button.next();
		waitForAndGetElement(spaceMag.ELEMENT_SPACE_CURRENT_NAME.replace("${spaceName}", spaceName2));
		waitForAndGetElement(mngPoll.ELEMENT_POLL_QUESTION);
		waitForAndGetElement(mngPoll.ELEMENT_POLL_OPTION.replace("${index}", "1"));
		waitForAndGetElement(mngPoll.ELEMENT_POLL_CLOSE);
		waitForAndGetElement(mngPoll.ELEMENT_POLL_VOTE_AGAIN,5000,1,2);
		waitForAndGetElement(mngPoll.ELEMENT_POLL_MULTI_VOTE,5000,1,2);
		click(button.ELEMENT_CANCEL_BUTTON);
		/*Clear data*/		
		magMember.goToAllSpaces();
		magMember.deleteSpace(spaceName1,300000);
		magMember.deleteSpace(spaceName2,300000);

	}
}