package org.exoplatform.selenium.platform.plf.functional.navigation.topnavigation.create;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.Button;
import org.exoplatform.selenium.ManageAlert;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.ManageAccount.userType;
import org.exoplatform.selenium.platform.calendar.CalendarBase;
import org.exoplatform.selenium.platform.forum.ForumManageCategory;
import org.exoplatform.selenium.platform.forum.ForumManageForum;
import org.exoplatform.selenium.platform.forum.ForumManagePoll;
import org.exoplatform.selenium.platform.forum.ForumManageTopic;
import org.exoplatform.selenium.platform.forum.ForumPermission;
import org.exoplatform.selenium.platform.social.ManageMember;
import org.exoplatform.selenium.platform.social.SpaceManagement;
import org.openqa.selenium.By;
import org.testng.annotations.*;


/**
 * @author phuongdt
 *
 */
public class PLF_Navigation_TopNavigation_Create_TopicPoll3 extends CalendarBase{
	ManageAccount acc;
	NavigationToolbar nav;
	Button button;
	ManageAlert alert;
	//Forum
	ForumManageTopic mngTopic;
	ForumManagePoll mngPoll;
	ForumManageCategory mngCat;
	ForumManageForum mngFru;
	ForumPermission frumPer;

	//Space
	SpaceManagement spaceMag;
	ManageMember magMember;

	@BeforeMethod
	public void beforeMethods(){	
		initSeleniumTest();
		driver.get(baseUrl);
		acc = new ManageAccount(driver, this.plfVersion);
		nav = new NavigationToolbar(driver, this.plfVersion);				
		acc.signIn(DATA_USER1, DATA_PASS);	
		button = new Button(driver, this.plfVersion);
		alert = new ManageAlert(driver);
		mngTopic = new ForumManageTopic(driver, this.plfVersion);
		mngPoll = new ForumManagePoll(driver, this.plfVersion);
		mngCat = new ForumManageCategory(driver, this.plfVersion);
		mngFru = new ForumManageForum(driver, this.plfVersion);
		magMember = new ManageMember(driver,this.plfVersion);
		spaceMag = new SpaceManagement(driver,this.plfVersion);
		frumPer=new ForumPermission(driver,this.plfVersion);
	}

	@AfterMethod
	public void afterMethods() {
		info("Logout portal");
		driver.manage().deleteAllCookies();
		driver.quit();
	}
	
	/**
	 *Case ID:104076.
	 *Test Case Name: Open Topic application from "In location: Intranet "field.
	 *Pre-Condition: onlyoneforumexists inIntranet
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test39_OpenTopicApplicationFromInLocationIntranetField() {
		info("Test 39 Open Topic application from In location: Intranet field");
		String titleCat1 = "Category 104076";
		String titleForum1 = "Forum 104076";
		String titleTop1 = "Topic 104076";
		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Topic dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
		 *Input Data: 

		 *Expected Outcome: 
			- The menu is updated to "Create a new Topic:"
			- "Intranet" is displayed in the field "In location"
			- Buttons "Cancel" and "Next" are displayed*/
		nav.goToCreateMenu();
		click(ELEMENT_ADD_TOPIC_ICON);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);
		waitForAndGetElement(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);

		/*Step number: 3
		 *Step Name: Open a new post editor
		 *Step Description: 
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			- The forum application is displayed under Intranet
			- A new Post editor is opened*/ 
		click(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(ELEMENT_HOME_PAGE);
		waitForAndGetElement(mngTopic.ELEMENT_POPUP_START_TOPIC);
		waitForAndGetElement(mngTopic.ELEMENT_TOPIC_TITLE);
		click(button.ELEMENT_CANCEL_BUTTON);
		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);

	}

	/**
	 *Case ID:104077.
	 *Test Case Name: Open Topic application from "In location: Space" field.
	 *Pre-Condition: onlyoneforumexists inSpace
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test40_OpenTopicApplicationFromInLocationSpaceField() {
		info("Test 40 Open Topic application from In location: Space field");
		String spaceName = "space 104074";

		//- Create new space
		magMember.goToMySpacePage();
		magMember.addNewSpace(spaceName, "");
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Topic dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
		 *Input Data: 

		 *Expected Outcome: 
			- The menu is updated to "Create a new Topic:"
			- The Space Forum is displayed in "In location" field
			- Buttons "Cancel" and "Next" are displayed*/
		nav.goToCreateMenu();
		click(ELEMENT_ADD_TOPIC_ICON);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);
		waitForAndGetElement(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);

		/*Step number: 3
		 *Step Name: Open a new post editor
		 *Step Description: 
			- Select a space in "In location" field
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			- The forum application is displayed in space
			- A new Post editor is opened*/ 
		click(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		click(ELEMENT_LOCATION_OPTION.replace("${itemName}", spaceName));
		button.next();
		waitForAndGetElement(spaceMag.ELEMENT_SPACE_CURRENT_NAME.replace("${spaceName}", spaceName));
		waitForAndGetElement(mngTopic.ELEMENT_POPUP_START_TOPIC);
		waitForAndGetElement(mngTopic.ELEMENT_TOPIC_TITLE);
		click(button.ELEMENT_CANCEL_BUTTON);
		/*Clear data*/		
		magMember.goToAllSpaces();
		magMember.deleteSpace(spaceName,300000);

	}

	/**
	 *Case ID:104078.
	 *Test Case Name: Open Topic application in a selected space.
	 *Pre-Condition: a space contain forum application
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test41_OpenTopicApplicationInASelectedSpace() {
		info("Test 41 Open Topic application in a selected space");
		String spaceName1 = "space 1040781";
		String spaceName2 = "space 1040782";

		//- Create new space
		magMember.goToMySpacePage();
		magMember.addNewSpace(spaceName1, "");
		magMember.goToMySpacePage();
		magMember.addNewSpace(spaceName2, "");
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Topic dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
		 *Input Data: 

		 *Expected Outcome: 
			- The menu is updated to "Create a new Topic:"
			- The field "In location" is displayed 
			- Buttons "Cancel" and "Next" are displayed*/
		nav.goToCreateMenu();
		click(ELEMENT_ADD_TOPIC_ICON);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);
		waitForAndGetElement(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);

		/*Step number: 3
		 *Step Name: Open a new post editor in a space
		 *Step Description: 
			- From the field "In location", choose a space from the list
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			- The forum application is displayed in the chosen space
			- A new Post editor is opened*/ 
		click(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		click(ELEMENT_LOCATION_OPTION.replace("${itemName}", spaceName2));
		button.next();
		waitForAndGetElement(spaceMag.ELEMENT_SPACE_CURRENT_NAME.replace("${spaceName}", spaceName2));
		waitForAndGetElement(mngTopic.ELEMENT_POPUP_START_TOPIC);
		waitForAndGetElement(mngTopic.ELEMENT_TOPIC_TITLE);
		click(button.ELEMENT_CANCEL_BUTTON);
		/*Clear data*/		
		magMember.goToAllSpaces();
		magMember.deleteSpace(spaceName1,300000);
		magMember.deleteSpace(spaceName2,300000);
	}

	/**
	 *Case ID:104079.
	 *Test Case Name: Search by the textfield in "Create a new Poll" menu.
	 *Pre-Condition: There are some forums in intranet
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test42_SearchByTheTextfieldInCreateANewPollMenu() {
		info("Test 42 Search by the textfield in Create a new Poll menu");
		String titleCat1 = "Category 1040791";
		String titleForum1 = "1040791 Forum";
		String titleTop1 = "Topic 1040791";

		String titleCat2 = "Category 1040792";
		String titleForum2 = "Forum 1040792";
		String titleTop2 = "Topic 1040792";

		String titleCat3 = "Category 1040793";
		String titleForum3 = "Forum 1040793";
		String titleTop3 = "Topic 1040793";

		String titleCat4 = "titleCat4";
		String titleForum4 = "titleF4";
		String titleTop4 = "titleTop4";

		String searchInput = "Forum";
		String searchCat = "Cat";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		mngTopic.addCategoryForumTopic(titleCat3, titleForum3, titleTop3,titleTop3);
		mngTopic.addCategoryForumTopic(titleCat4, titleForum4, titleTop4,titleTop4);

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Poll dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
			- Click on the button "Next"
			- Click on the right arrow from the field "And Forum"
		 *Input Data: 

		 *Expected Outcome: 
			- The list of categories and forums of each category is displayed
			- A textfield in the top of the list is displayed*/
		nav.goToPoll();

		/*Step number: 3
		 *Step Name: Filter forum
		 *Step Description: 
			- Input a characters in the textfield
		 *Input Data: 

		 *Expected Outcome: 
			- The  filter  is  working  only  into  forums,  not  on  categories.
			- The filter is displayed once the character has been inputted
			- forums starting or having a characters are displayed 
			- categories containing the characters aren't displayed*/
		//Filter forum
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_FILTER_FORUM);
		type(ELEMENT_FILTER_FORUM,searchInput,true);
//		type(ELEMENT_FILTER_FORUM, Keys.ENTER.toString(), false);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));

		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum4));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat4));

		//Filter category
		click(nav.ELEMENT_SELECT_FORUM);
		type(ELEMENT_FILTER_FORUM,searchCat,true);
//		type(ELEMENT_FILTER_FORUM, Keys.ENTER.toString(), false);
		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));

		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum4));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat4));
		click(button.ELEMENT_CANCEL_BUTTON);

		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat4));
		mngCat.deleteCategoryInForum(titleCat4, true);
		click(By.linkText(titleCat3));
		mngCat.deleteCategoryInForum(titleCat3, true);
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104080.
	 *Test Case Name: Search by the textfield in "Create a new Topic" menu.
	 *Pre-Condition: There are some forums in intranet
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test43_SearchByTheTextfieldInCreateANewTopicMenu() {
		info("Test 43 Search by the textfield in Create a new Topic menu");
		String titleCat1 = "Category 1040801";
		String titleForum1 = "1040801 Forum";
		String titleTop1 = "Topic 1040801";

		String titleCat2 = "Category 1040802";
		String titleForum2 = "Forum 1040802";
		String titleTop2 = "Topic 1040802";

		String titleCat3 = "Category 1040803";
		String titleForum3 = "Forum 1040803";
		String titleTop3 = "Topic 1040803";

		String titleCat4 = "titleCat1040804";
		String titleForum4 = "titleF1040804";
		String titleTop4 = "titleTop1040804";

		String searchInput = "Forum";
		String searchCat = "Cat";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		mngTopic.addCategoryForumTopic(titleCat3, titleForum3, titleTop3,titleTop3);
		mngTopic.addCategoryForumTopic(titleCat4, titleForum4, titleTop4,titleTop4);

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Topic dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
			- Click on the button "Next"
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- The list of categories and forums of each category is displayed
			- A textfield in the top of the list is displayed*/
		nav.goToTopic();
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);

		/*Step number: 3
		 *Step Name: Filter forums
		 *Step Description: 
			- Input a characters in the textfield
		 *Input Data: 

		 *Expected Outcome: 
			- Thefilterisstarting once the first character has been inputted
			- forumsstartinng or having a characters are displayed 
			- categories containing the characters aren't displayed*/ 
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_FILTER_FORUM);
		type(ELEMENT_FILTER_FORUM,searchInput,true);
//		type(ELEMENT_FILTER_FORUM, Keys.ENTER.toString(), false);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));

		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum4));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat4));

		//Filter category
		type(ELEMENT_FILTER_FORUM,searchCat,true);
//		type(ELEMENT_FILTER_FORUM, Keys.ENTER.toString(), false);
		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));
		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));

		waitForElementNotPresent(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum4));
		waitForElementNotPresent(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat4));
		click(button.ELEMENT_CANCEL_BUTTON);

		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat4));
		mngCat.deleteCategoryInForum(titleCat4, true);
		click(By.linkText(titleCat3));
		mngCat.deleteCategoryInForum(titleCat3, true);
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}


	/**
	 *Case ID:104087.
	 *Test Case Name: Show categories sorted alphabetically in "Create a new Poll" menu.
	 *Case ID:104090.
	 *Test Case Name: Show forums sorted alphabetically in "Create a new Poll" menu.
	 *Pre-Condition: There are many categories with forums in intranet
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test50_52_ShowCategoriesSortedAlphabeticallyInCreateANewPollMenu() {
		info("Test 50 Show categories sorted alphabetically in Create a new Poll menu - Case ID:104087");
		String titleCat1 = "Category 1040871";
		String titleForum1 = "Forum 1040871";
		String titleTop1 = "Topic 1040871";

		String titleCat2 = "Category 1040872";
		String titleForum21 = "aForum 1040872";
		String titleTop2 = "Topic 1040872";
		String titleForum22 = "bForum 1040872";
		String titleForum23 = "cForum 1040872";

		String titleCat3 = "Category 1040873";
		String titleForum3 = "Forum 1040873";
		String titleTop3 = "Topic 1040873";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat2, titleForum21, titleTop2,titleTop2);
		mngFru.quickAddForum(titleForum23);
		mngFru.quickAddForum(titleForum22);
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat3, titleForum3, titleTop3,titleTop3);
		mngTopic.goToForums();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Poll dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/
		nav.goToPoll();

		/*Step number: 3
		 *Step Name: Show categories in the list in "And forum" field
		 *Step Description: 
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- categories are displayed and sorted alphabetically*/ 
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_FILTER_FORUM);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_POLL_CATEGORY_INDEX.replace("${index}", "2").replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_ADD_TOPIC_POLL_CATEGORY_INDEX.replace("${index}", "4").replace("${catName}", titleCat2));
		waitForAndGetElement(ELEMENT_ADD_TOPIC_POLL_CATEGORY_INDEX.replace("${index}", "6").replace("${catName}", titleCat3));

		info("Test 52 Show forums sorted alphabetically in Create a new Poll menu - Case ID:104090.");
		/*Step number: 3
		 *Step Name: Show forums in "And forum"
		 *Step Description: 
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- forums are displayed and sorted alphabetically*/ 
		waitForAndGetElement(ELEMENT_ADD_TOPIC_POLL_CATEGORY_FORUM_INDEX.replace("${indexCat}", "5").replace("${indexFor}", "1").replace("${forName}", titleForum21));
		waitForAndGetElement(ELEMENT_ADD_TOPIC_POLL_CATEGORY_FORUM_INDEX.replace("${indexCat}", "5").replace("${indexFor}", "2").replace("${forName}", titleForum22));
		waitForAndGetElement(ELEMENT_ADD_TOPIC_POLL_CATEGORY_FORUM_INDEX.replace("${indexCat}", "5").replace("${indexFor}", "3").replace("${forName}", titleForum23));
		click(button.ELEMENT_CANCEL_BUTTON);
		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat3));
		mngCat.deleteCategoryInForum(titleCat3, true);
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat1, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat2, true);
	}

	/**
	 *Case ID:104088.
	 *Test Case Name: Show categories sorted alphabetically in "Create a new Topic" menu.
	 *Case ID:104091.
	 *Test Case Name: Show forums sorted alphabetically in "Create a new Topic" menu.
	 *Pre-Condition: There are many categories with forums in intranet
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test51_53_ShowCategoriesSortedAlphabeticallyInCreateANewTopicMenu() {
		info("Test 51 Show categories sorted alphabetically in Create a new Topic menu - Case ID:104088");
		String titleCat1 = "Category 1040881";
		String titleForum1 = "Forum 1040881";
		String titleTop1 = "Topic 1040881";

		String titleCat2 = "Category 1040882";
		String titleForum21 = "aForum 1040882";
		String titleTop2 = "Topic 1040882";
		String titleForum22 = "bForum 1040882";
		String titleForum23 = "cForum 1040882";

		String titleCat3 = "Category 1040883";
		String titleForum3 = "Forum 1040883";
		String titleTop3 = "Topic 1040883";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat2, titleForum21, titleTop2,titleTop2);
		mngFru.quickAddForum(titleForum23);
		mngFru.quickAddForum(titleForum22);
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat3, titleForum3, titleTop3,titleTop3);
		mngTopic.goToForums();
		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Topic dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/
		nav.goToTopic();
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);

		/*Step number: 3
		 *Step Name: Show categories in "And forum" field
		 *Step Description: 
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- categories are displayed and sorted alphabetically*/ 
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_FILTER_FORUM);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_POLL_CATEGORY_INDEX.replace("${index}", "2").replace("${catName}", titleCat1));
		waitForAndGetElement(ELEMENT_ADD_TOPIC_POLL_CATEGORY_INDEX.replace("${index}", "4").replace("${catName}", titleCat2));
		waitForAndGetElement(ELEMENT_ADD_TOPIC_POLL_CATEGORY_INDEX.replace("${index}", "6").replace("${catName}", titleCat3));

		info("Test 53 Show forums sorted alphabetically in Create a new Topic menu -Case ID:104091");
		/*Step number: 3
		 *Step Name: Show forums in "And forum"
		 *Step Description: 
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- forums are displayed and sorted alphabetically*/ 
		waitForAndGetElement(ELEMENT_ADD_TOPIC_POLL_CATEGORY_FORUM_INDEX.replace("${indexCat}", "5").replace("${indexFor}", "1").replace("${forName}", titleForum21));
		waitForAndGetElement(ELEMENT_ADD_TOPIC_POLL_CATEGORY_FORUM_INDEX.replace("${indexCat}", "5").replace("${indexFor}", "2").replace("${forName}", titleForum22));
		waitForAndGetElement(ELEMENT_ADD_TOPIC_POLL_CATEGORY_FORUM_INDEX.replace("${indexCat}", "5").replace("${indexFor}", "3").replace("${forName}", titleForum23));
		click(button.ELEMENT_CANCEL_BUTTON);
		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat3));
		mngCat.deleteCategoryInForum(titleCat3, true);
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat1, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat2, true);

	}

	/**
	 *Case ID:104100.
	 *Test Case Name: Update "Create" menu to "Create a new Poll" menu.
	 *Pre-Condition: 
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test54_UpdateCreateMenuToCreateANewPollMenu() {
		info("Test 54 Update Create menu to Create a new Poll menu");
		/*Declare variables*/
		String titleCat1 = "Category 1041001";
		String titleForum1 = "Forum 1041001";
		String titleTop1 = "Topic 1041001";

		String titleCat2 = "Category 1041002";
		String titleForum2 = "Forum 1041002";
		String titleTop2 = "Topic 1041002";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		nav.goToHomePage();
		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Create menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
		 *Input Data: 

		 *Expected Outcome: 
			The list of items is displayed:* Event/Task* Poll* Topic* Upload Document* Wiki*/

		/*Step number: 3
		 *Step Name: Show Poll dropdown menu
		 *Step Description: 
			- Select the item "Poll"
		 *Input Data: 

		 *Expected Outcome: 
			- The menu is updatedto display "Create a new Poll:"
			- Fields "In location" is displayed
			- Buttons "Cancel" and "Next" are displayed*/ 
		nav.goToCreateMenu();
		click(ELEMENT_ADD_POLL_ICON);
		waitForAndGetElement(ELEMENT_ADD_POLL_FORM);
		waitForAndGetElement(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);
		waitForAndGetElement(ELEMENT_POLL_FORM_LABEL);
		click(button.ELEMENT_CANCEL_BUTTON);

		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat1, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat2, true);

	}

	/**
	 *Case ID:104101.
	 *Test Case Name: Update "Create" menu to "Create a new Topic" menu.
	 *Pre-Condition: 
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test55_UpdateCreateMenuToCreateANewTopicMenu() {
		info("Test 55 Update Create menu to Create a new Topic menu");
		/*Declare variables*/
		String titleCat1 = "Category 1041011";
		String titleForum1 = "Forum 1041011";
		String titleTop1 = "Topic 1041011";

		String titleCat2 = "Category 1041012";
		String titleForum2 = "Forum 1041012";
		String titleTop2 = "Topic 1041012";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Create menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
		 *Input Data: 

		 *Expected Outcome: 
			The list of items is displayed:* Event/Task* Poll* Topic* Upload Document* Wiki*/

		/*Step number: 3
		 *Step Name: Show Topic dropdown menu
		 *Step Description: 
			- Select the item "Topic"
		 *Input Data: 

		 *Expected Outcome: 
			- The menu is updatedto display "Create a new Topic:"
			- Fields "In location" is displayed
			- Buttons "Cancel" and "Next" are displayed*/ 
		nav.goToCreateMenu();
		click(ELEMENT_ADD_TOPIC_ICON);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);
		waitForAndGetElement(ELEMENT_TOPIC_FORM_LABEL);
		click(button.ELEMENT_CANCEL_BUTTON);
		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat1, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat2, true);
	}

	/**
	 *Case ID:104114.
	 *Test Case Name: Display scrollbar in Space switcher in Poll menu.
	 *Pre-Condition: More than 12 spaces are accessible to the user from the space switcher
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test56_DisplayScrollbarInSpaceSwitcherInPollMenu() {
		info("Test 56 Display scrollbar in Space switcher in Poll menu");
		String spaceName = "space104114";

		//- Create new space
		for(int i =1;i<14;i++){
			magMember.goToMySpacePage();
			magMember.addNewSpace(spaceName+String.valueOf(i), "");
		}
		nav.goToHomePage();
		
		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Show scrollbar in "In location" field
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
			- Click on the right arrow from the field "In location"
		 *Input Data: 

		 *Expected Outcome: 
			- The space switcher is displayed
			- Only 12 spaces are displayed and others are scrollable*/ 
		nav.goToCreateMenu();
		click(ELEMENT_ADD_POLL_ICON);
		click(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_POLL_SCROLL_MENU);
		for(int i =1;i<14;i++){
			waitForAndGetElement(ELEMENT_LOCATION_OPTION.replace("${itemName}", spaceName+String.valueOf(i)));
		}
		
		//clear data
		for(int i =1;i<14;i++){
			magMember.goToAllSpaces();
			magMember.deleteSpace(spaceName+String.valueOf(i),300000);
		}

	}

	/**
	 *Case ID:104115.
	 *Test Case Name: Not Display Forum added by an admin user in category space in "Create a new Poll" menu.
	 *Pre-Condition: the user has permissions to start a Topic in a Forum
	 *Forums are not closed and not locked
	 *the forum is added in category "space" by admin
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test57_NotDisplayForumAddedByAnAdminUserInCategorySpaceInCreateANewPollMenu() {
		info("Test 57 Not Display Forum added by an admin user in category space in Create a new Poll menu");
		//Declare variable
		String spaceName = "space104115";

		//- Create new space
		magMember.goToMySpacePage();
		magMember.addNewSpace(spaceName, "");
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/

		/*Step number: 2
		 *Step Name: Open Topic dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/
		
		/*Step number: 3
		 *Step Name: Not show forum added to "space" category
		 *Step Description: 
			- Click on the right arrow from the field "And Forum"
		 *Input Data: 

		 *Expected Outcome: 
			- The forum which added in the category "space" is not displayed*/
		acc.userSignIn(userType.AUTHOR);
		nav.goToCreateMenu();
		click(ELEMENT_ADD_POLL_ICON);
		click(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		waitForElementNotPresent(ELEMENT_LOCATION_OPTION.replace("${itemName}", spaceName));
		
		//clear data
		acc.userSignIn(userType.ADMIN);
		mngTopic.goToForums();
		magMember.goToAllSpaces();
		magMember.deleteSpace(spaceName,300000);
	}
}