package org.exoplatform.selenium.platform.plf.functional.navigation.topnavigation.create;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.Button;
import org.exoplatform.selenium.ManageAlert;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.calendar.CalendarBase;
import org.exoplatform.selenium.platform.forum.ForumManageCategory;
import org.exoplatform.selenium.platform.forum.ForumManageForum;
import org.exoplatform.selenium.platform.forum.ForumManagePoll;
import org.exoplatform.selenium.platform.forum.ForumManageTopic;
import org.exoplatform.selenium.platform.forum.ForumPermission;
import org.exoplatform.selenium.platform.social.ManageMember;
import org.exoplatform.selenium.platform.social.SpaceManagement;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.testng.annotations.*;


/**
 * @author phuongdt
 *
 */
public class PLF_Navigation_TopNavigation_Create_TopicPoll1 extends CalendarBase{
	ManageAccount acc;
	NavigationToolbar nav;
	Button button;
	ManageAlert alert;
	//Forum
	ForumManageTopic mngTopic;
	ForumManagePoll mngPoll;
	ForumManageCategory mngCat;
	ForumManageForum mngFru;
	ForumPermission frumPer;

	//Space
	SpaceManagement spaceMag;
	ManageMember magMember;

	@BeforeMethod
	public void beforeMethods(){	
		initSeleniumTest();
		driver.get(baseUrl);
		acc = new ManageAccount(driver, this.plfVersion);
		nav = new NavigationToolbar(driver, this.plfVersion);				
		acc.signIn(DATA_USER1, DATA_PASS);	
		button = new Button(driver, this.plfVersion);
		alert = new ManageAlert(driver);
		mngTopic = new ForumManageTopic(driver, this.plfVersion);
		mngPoll = new ForumManagePoll(driver, this.plfVersion);
		mngCat = new ForumManageCategory(driver, this.plfVersion);
		mngFru = new ForumManageForum(driver, this.plfVersion);
		magMember = new ManageMember(driver,this.plfVersion);
		spaceMag = new SpaceManagement(driver,this.plfVersion);
		frumPer=new ForumPermission(driver,this.plfVersion);
	}

	@AfterMethod
	public void afterMethods() {
		info("Logout portal");
		driver.manage().deleteAllCookies();
		driver.quit();
	}

	/**
	 *Case ID:104036.
	 *Test Case Name: Dismiss the "Create a new Poll" menu after a list display.
	 *Pre-Condition: 
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test01_DismissTheCreateANewPollMenuAfterAListDisplay() {
		info("Test 1: Dismiss the Create a new Poll menu after a list display");
		/*Declare variables*/
		String titleCat1 = "Category 1040361";
		String titleForum1 = "Forum 1040361";
		String titleTop1 = "Topic 1040361";

		String titleCat2 = "Category 1040362";
		String titleForum2 = "Forum 1040362";
		String titleTop2 = "Topic 1040362";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		/*Step number: 2
		 *Step Name: Open Poll dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Chosse "Poll"
		 *Input Data: 

		 *Expected Outcome: 
			- The Create menu is displayed
			- The field "In Location" is displayed
			- Buttons "Cancel" and "Next" are displayed*/
		nav.goToCreateMenu();
		click(ELEMENT_ADD_POLL_ICON);
		waitForAndGetElement(ELEMENT_ADD_POLL_FORM);
		waitForAndGetElement(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);
		/*Step number: 3
		 *Step Name: Dismiss menu
		 *Step Description: 
			- Click on the button "Cancel"
		 *Input Data: 

		 *Expected Outcome: 
			The menu "Create" is dismissed*/
		click(button.ELEMENT_CANCEL_BUTTON);
		waitForElementNotPresent(ELEMENT_ADD_POLL_FORM);

		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104037.
	 *Test Case Name: Dismiss the "Create a new Topic" menu after a list display.
	 *Pre-Condition: 
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test02_DismissTheCreateANewTopicMenuAfterAListDisplay() {
		info("Test 2: Dismiss the Create a new Topic menu after a list display");
		/*Declare variables*/
		String titleCat1 = "Category 1040371";
		String titleForum1 = "Forum 1040371";
		String titleTop1 = "Topic 1040371";

		String titleCat2 = "Category 1040372";
		String titleForum2 = "Forum 1040372";
		String titleTop2 = "Topic 1040372";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		nav.goToHomePage();
		/*Step Number: 1
		 *Step Name: Connect to intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		/*Step number: 2
		 *Step Name: Open Topic dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Choose "Topic"
		 *Input Data: 

		 *Expected Outcome: 
			- The" Create a new Topic" menu is displayed
			- Buttons "Cancel" and "Next" are displayed*/
		nav.goToCreateMenu();
		click(ELEMENT_ADD_TOPIC_ICON);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);

		/*Step number: 3
		 *Step Name: Dismiss menu
		 *Step Description: 
			- Click on the button "Cancel"
		 *Input Data: 

		 *Expected Outcome: 
			The menu "Create" is dismissed*/ 
		click(button.ELEMENT_CANCEL_BUTTON);
		waitForElementNotPresent(ELEMENT_ADD_TOPIC_FORM);

		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104038.
	 *Test Case Name: Display "And Forum" list in "Create a new Poll" menu.
	 *Pre-Condition: The user has permissions to start a topic/poll Forums are not closed and not locked2 forums exist under Intranet
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test03_DisplayAndForumListInCreateANewPollMenu() {
		info("Test 3: Display And Forum list in Create a new Poll menu");
		/*Declare variables*/
		String titleCat1 = "Category 1040381";
		String titleForum1 = "Forum 1040381";
		String titleTop1 = "Topic 1040381";

		String titleCat2 = "Category 1040382";
		String titleForum2 = "Forum 1040382";
		String titleTop2 = "Topic 1040382";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		/*Step number: 2
		 *Step Name: Open Poll dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/
		nav.goToPoll();
		/*Step number: 3
		 *Step Name: Input into "And forum" field
		 *Step Description: 
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- The list of categories and forum of each category is displayed*/ 
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		click(button.ELEMENT_CANCEL_BUTTON);
		waitForElementNotPresent(ELEMENT_ADD_POLL_FORM);

		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);

	}

	/**
	 *Case ID:104039.
	 *Test Case Name: Display "And Forum" list in "Create a new Topic" menu.
	 *Pre-Condition: The user has permissions to start a topicForums are not closed and not locked2 forums exist under Intranet
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test04_DisplayAndForumListInCreateANewTopicMenu() {
		info("Test 4: Display And Forum list in Create a new Topic menu");
		/*Declare variables*/
		/*Declare variables*/
		String titleCat1 = "Category 1040391";
		String titleForum1 = "Forum 1040391";
		String titleTop1 = "Topic 1040391";

		String titleCat2 = "Category 1040392";
		String titleForum2 = "Forum 1040392";
		String titleTop2 = "Topic 1040392";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		/*Step number: 2
		 *Step Name: Open Topic dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/
		nav.goToTopic();
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);
		/*Step number: 3
		 *Step Name: Input into "And forum" field
		 *Step Description: 
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- The list of categories and forum of each category is displayed*/ 
		click(ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		click(button.ELEMENT_CANCEL_BUTTON);
		waitForElementNotPresent(ELEMENT_ADD_POLL_FORM);

		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);

	}

	/**
	 *Case ID:104040.
	 *Test Case Name: Display a category with a long name in "Create new Poll" menu.
	 *Pre-Condition: add a category with a long name
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 *PENDING: can't automate to revrify: The category with a long name is truncated and appended "...." 
	 *--> check this case manually
	 */
	@Test (groups="pending")
	public  void test05_DisplayACategoryWithALongNameInCreateNewPollMenu() {
		info("Test 5: Display a category with a long name in Create new Poll menu");
		String titleCat1 = "Long Category 1040401 Long Category 1040401 Long Category 1040401";
		String titleForum1 = "Forum 1040401";
		String titleTop1 = "Topic 1040401";

		String titleCat2 = "Long Category 1040402 Long Category 1040402 Long Category 1040402";
		String titleForum2 = "Forum 1040402";
		String titleTop2 = "Topic 1040402";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		/*Step number: 2
		 *Step Name: Check long name of a category
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
			- Click on the right arrow from the field "And Forum"
		 *Input Data: 

		 *Expected Outcome: 
			- The list of categories is displayed
			- The category with a long name is truncated and appended "...."*/ 
		nav.goToPoll();
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		click(button.ELEMENT_CANCEL_BUTTON);
		waitForElementNotPresent(ELEMENT_ADD_POLL_FORM);
		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104041.
	 *Test Case Name: Display a category with a long name in "Create new Topic" menu.
	 *Pre-Condition: add a category with a long name
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 *PENDING: can't automate to revrify: The category with a long name is truncated and appended "...." 
	 *--> check this case manually
	 */
	@Test (groups="pending")
	public  void test06_DisplayACategoryWithALongNameInCreateNewTopicMenu() {
		info("Test 6: Display a category with a long name in Create new Topic menu");
		String titleCat1 = "Long Category 1040411 Long Category 1040411 Long Category 1040411";
		String titleForum1 = "Forum 1040411";
		String titleTop1 = "Topic 1040411";

		String titleCat2 = "Long Category 1040412 Long Category 1040412 Long Category 1040412";
		String titleForum2 = "Forum 1040412";
		String titleTop2 = "Topic 1040412";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		/*Step number: 2
		 *Step Name: Show a category with a long name
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- The list of categories is displayed
			- The category with a long name is truncated and appended "...."*/ 
		nav.goToTopic();
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		click(button.ELEMENT_CANCEL_BUTTON);
		waitForElementNotPresent(ELEMENT_ADD_POLL_FORM);
		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);

	}

	/**
	 *Case ID:104042.
	 *Test Case Name: Display a forum with a long name in "Create new Poll" menu.
	 *Pre-Condition: add a forum with a long name
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 *PENDING: can't automate to revrify: The forum with a long name is truncated and appended "...."
	 *--> check this case manually
	 */
	@Test (groups="pending")
	public  void test07_DisplayAForumWithALongNameInCreateNewPollMenu() {
		info("Test 7: Display a forum with a long name in Create new Poll menu");
		String titleCat1 = "Category 1040421";
		String titleForum1 = "Long  Forum 1040421 Long Forum 1040421 Long Forum 1040421 Long Forum 1040421";
		String titleTop1 = "Topic 1040421";

		String titleCat2 = "Category 1040422";
		String titleForum2 = "Long  Forum 1040422 Long Forum 1040422 Long Forum 1040422 Long Forum 1040421";
		String titleTop2 = "Topic 1040422";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*Step number: 2
		 *Step Name: Show a forum with long name
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
			- Click on the right arrow from the field "And Forum"
		 *Input Data: 

		 *Expected Outcome: 
			- The list of forums is displayed
			- The forum with a long name is truncated and appended "...."*/ 
		nav.goToPoll();
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		click(button.ELEMENT_CANCEL_BUTTON);
		waitForElementNotPresent(ELEMENT_ADD_POLL_FORM);
		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);

	}

	/**
	 *Case ID:104043.
	 *Test Case Name: Display a forum with a long name in "Create new Topic" menu.
	 *Pre-Condition: add a forum with a long name
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 *PENDING: can't automate to revrify: The forum with a long name is truncated and appended "...."
	 *--> check this case manually
	 */
	@Test (groups="pending")
	public  void test08_DisplayAForumWithALongNameInCreateNewTopicMenu() {
		info("Test 8: Display a forum with a long name in Create new Topic menu");
		String titleCat1 = "Category 1040431";
		String titleForum1 = "Long  Forum 1040421 Long Forum 1040421 Long Forum 1040421 Long Forum 1040421";
		String titleTop1 = "Topic 1040421";

		String titleCat2 = "Category 1040422";
		String titleForum2 = "Long  Forum 1040422 Long Forum 1040422 Long Forum 1040422 Long Forum 1040421";
		String titleTop2 = "Topic 1040422";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*Step number: 2
		 *Step Name: Show a forum with a long name
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
			- Click on the right arrow from the field "And Fourm"
		 *Input Data: 

		 *Expected Outcome: 
			- The list of forums is displayed
			- The forum with a long name is truncated and appended "...."*/ 
		nav.goToTopic();
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		click(button.ELEMENT_CANCEL_BUTTON);
		waitForElementNotPresent(ELEMENT_ADD_POLL_FORM);
		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104044.
	 *Test Case Name: Display a space with a long name in Space switcher.
	 *Pre-Condition: add a space with a long name
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 *PENDING: can't automate to revrify: TThe space with a long name is truncated and appended "...."
	 *--> check this case manually
	 */
	@Test (groups="pending")
	public  void test09_DisplayASpaceWithALongNameInSpaceSwitcher() {
		info("Test 9: Display a space with a long name in Space switcher");
		//Declare variable
		String spaceName = "space 104044 space 104044 space 104044 space 104044";
		//- Create new space
		magMember.goToMySpacePage();
		magMember.addNewSpace(spaceName, "");
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*Step number: 2
		 *Step Name: Show a space with long name
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
			- Click on the right arrow from the field "In location"
		 *Input Data: 

		 *Expected Outcome: 
			- The space switcher is displayed
			- Space level is displayed
			- The space with a long name is truncated and appended "...."*/
		nav.goToCreateMenu();
		click(ELEMENT_ADD_TOPIC_ICON);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);
		click(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		waitForAndGetElement(ELEMENT_LOCATION_OPTION.replace("${itemName}", spaceName));

		click(button.ELEMENT_CANCEL_BUTTON);
		waitForElementNotPresent(ELEMENT_ADD_POLL_FORM);
		//clear data
		magMember.goToAllSpaces();
		magMember.deleteSpace(spaceName,300000);
	}

	/**
	 *Case ID:104045.
	 *Test Case Name: Display a "Filter forum" textfield in "Create a new Poll" menu.
	 *Pre-Condition: the user has permissions to start a poll Forums are not closed and not locked
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test10_DisplayAFilterForumTextfieldInCreateANewPollMenu() {
		info("Test 10 Display a Filter forum textfield in Create a new Poll menu");
		String titleCat1 = "Category 1040451";
		String titleForum1 = "Forum 1040451";
		String titleTop1 = "Topic 1040451";

		String titleCat2 = "Category 1040452";
		String titleForum2 = "Forum 1040452";
		String titleTop2 = "Topic 1040452";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*Step number: 2
		 *Step Name: Open Poll dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/

		/*Step number: 3
		 *Step Name: Show textfield at the top of a list of forums
		 *Step Description: 
			- Click on the right arrow at the field "And Forum"
		 *Input Data: 

		 *Expected Outcome: 
			- The list of categories and forums of each category is displayed
			- A "Filter forum" textfield in the top of the list is displayed, the text "Filter forum" is shown on this field*/
		nav.goToPoll();
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_FILTER_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		click(button.ELEMENT_CANCEL_BUTTON);
		waitForElementNotPresent(ELEMENT_ADD_POLL_FORM);
		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104046.
	 *Test Case Name: Display a "Filter forum" textfield in "Create a new Topic" menu.
	 *Pre-Condition: the user has permissions to start a TopicForums are not closed and not locked
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test11_DisplayAFilterForumTextfieldInCreateANewTopicMenu() {
		info("Test 11 Display a Filter forum textfield in Create a new Topic menu");
		String titleCat1 = "Category 1040461";
		String titleForum1 = "Forum 1040461";
		String titleTop1 = "Topic 1040461";

		String titleCat2 = "Category 1040462";
		String titleForum2 = "Forum 1040462";
		String titleTop2 = "Topic 1040462";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		nav.goToHomePage();


		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*Step number: 2
		 *Step Name: Open Topic dropdown menu
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
			- Click on the button "Next"
		 *Input Data: 

		 *Expected Outcome: 
			The field "And Fourm" is displayed*/

		/*Step number: 3
		 *Step Name: Show textfield at the top of a list of forums
		 *Step Description: 
			- Click on the right arrow from the field "And Forum"
		 *Input Data: 

		 *Expected Outcome: 
			- The list of categories and forums of each category is displayed
			- A textfield in the top of the list is displayed, and the text "Filter forum" is shown on this field*/ 
		nav.goToCreateMenu();
		click(ELEMENT_ADD_TOPIC_ICON);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);
		button.next();
		click(ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_FILTER_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		click(button.ELEMENT_CANCEL_BUTTON);
		waitForElementNotPresent(ELEMENT_ADD_POLL_FORM);
		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104047.
	 *Test Case Name: Display a warning message when no forums exists in "Create a new Poll".
	 *Pre-Condition: no forum exist
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test12_DisplayAWarningMessageWhenNoForumsExistsInCreateANewPoll() {
		info("Test 12 Display a warning message when no forums exists in Create a new Poll");
		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*Step number: 2
		 *Step Name: Open Poll dropdown menu
		 *Step Description: 
			- Mouse over on "Create" (+)
			- Choose "Poll"
		 *Input Data: 

		 *Expected Outcome: 
			-A warning message with the label "Sorry, no forum available yet to create a poll. Start by creating your own space" is displayed
			- Button cancel is displayed*/ 
		nav.goToCreateMenu();
		click(ELEMENT_ADD_POLL_ICON);
		waitForAndGetElement(ELEMENT_NO_FORUM);
		assert waitForAndGetElement(ELEMENT_NO_FORUM).getText().contains(ELEMENT_NO_FORUM_MESSAGE);
		button.cancel();

	}

	/**
	 *Case ID:104048.
	 *Test Case Name: Display a warning message when no forums exists in "Create a new Topic".
	 *Pre-Condition: no forum exist
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test13_DisplayAWarningMessageWhenNoForumsExistsInCreateANewTopic() {
		info("Test 13 Display a warning message when no forums exists in Create a new Topic");
		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*Step number: 2
		 *Step Name: Open Topic dropdown menu
		 *Step Description: 
			- Mouse over on "Create" (+)
			- Choose "Topic"
		 *Input Data: 

		 *Expected Outcome: 
			-A warning message with the label "Sorry, no forum available yet to create a topic. Start by creating your own space" is displayed
			- Button cancel is displayed*/
		nav.goToCreateMenu();
		click(ELEMENT_ADD_TOPIC_ICON);
		waitForAndGetElement(ELEMENT_NO_FORUM);
		assert waitForAndGetElement(ELEMENT_NO_FORUM).getText().contains(ELEMENT_NO_FORUM_MESSAGE_TO_CREATE_TOPIC);
		button.cancel();

		/*Step number: 3
		 *Step Name: Show a message
		 *Step Description: 
			- Create a forum
			- Mouse over Create (+) menu
			- Click topic
		 *Input Data: 

		 *Expected Outcome: 
			- The Create menu is displayed
			- The label "In Location"and a drop down menu that displays "intranet" are displayed
			- Buttons "Cancel" and "Next" are displayed*/ 
		String titleCat1 = "Category 1040481";
		String titleForum1 = "Forum 1040481";
		String titleTop1 = "Topic 1040481";

		String titleCat2 = "Category 1040482";
		String titleForum2 = "Forum 1040482";
		String titleTop2 = "Topic 1040482";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		nav.goToHomePage();

		nav.goToCreateMenu();
		click(ELEMENT_ADD_TOPIC_ICON);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);
		waitForAndGetElement(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);

		click(button.ELEMENT_CANCEL_BUTTON);
		waitForElementNotPresent(ELEMENT_ADD_POLL_FORM);
		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);	
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}

	/**
	 *Case ID:104049.
	 *Test Case Name: Display only Space's list in "Create a new Poll" menu.
	 *Pre-Condition: the user has permissions to start a topic/poll 
	 *Forums are not closed and not locked
	 *no forum defined on the intranet
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test14_DisplayOnlySpacesListInCreateANewPollMenu() {
		info("Test 14 Display only Space's list in Create a new Poll menu");
		//Declare variable
		String spaceName = "space1040491";

		//- Create new space
		magMember.goToMySpacePage();
		magMember.addNewSpace(spaceName, "");
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*Step number: 2
		 *Step Name: Show only spaces in the selectbox
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
			- Open the field "In location"
		 *Input Data: 

		 *Expected Outcome: 
			In the field "In location", only the list of spaces on the user is displayed*/
		nav.goToCreateMenu();
		click(ELEMENT_ADD_POLL_ICON);
		click(ELEMENT_ADD_POLL_TOPIC_LOCATION);
		waitForAndGetElement(ELEMENT_LOCATION_OPTION.replace("${itemName}", spaceName));

		click(button.ELEMENT_CANCEL_BUTTON);
		waitForElementNotPresent(ELEMENT_ADD_POLL_FORM);
		//clear data
		magMember.goToAllSpaces();
		magMember.deleteSpace(spaceName,300000);
	}

	/**
	 *Case ID:104050.
	 *Test Case Name: Display only Space's list in "Create a new Topic" menu.
	 *Pre-Condition: the user has permissions to start a topic/poll Forums are not closed and not lockedno forum defined on the intranet
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test15_DisplayOnlySpacesListInCreateANewTopicMenu() {
		info("Test 15 Display only Space's list in Create a new Topic menu");
		String spaceName = "space104050";

		//- Create new space
		magMember.goToMySpacePage();
		magMember.addNewSpace(spaceName, "");
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);
		/*Step number: 2
		 *Step Name: Show only spaces in the selectbox
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
			- Open the field "In location"
		 *Input Data: 

		 *Expected Outcome: 
			In the field "In location", only the list of spaces on the user is displayed*/ 
		nav.goToCreateMenu();
		click(ELEMENT_ADD_TOPIC_ICON);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);
		click(ELEMENT_LOCATION_CARET);
		waitForAndGetElement(ELEMENT_LOCATION_OPTION.replace("${itemName}", spaceName));
		click(button.ELEMENT_CANCEL_BUTTON);
		waitForElementNotPresent(ELEMENT_ADD_POLL_FORM);
		//clear data
		magMember.goToAllSpaces();
		magMember.deleteSpace(spaceName,300000);
	}

	/**
	 *Case ID:104051.
	 *Test Case Name: Display scrollbar in list of "And Forum" in "Create a new Poll" menu.
	 *Case ID:104052.
	 *Test Case Name: Display scrollbar in list of "And Forum" in "Create a new Topic" menu.
	 *Pre-Condition: More than 12 forums in intranet are accessible to the user from the list
	 *Post-Condition: 
	 *Done with OSs and browsers : 
	 *Generated by phuongdt at 2014/06/30 10:11:57
	 */
	@Test
	public  void test16_17_DisplayScrollbarInListOfAndForumInCreateANewPollTopicMenu() {
		info("Test 16 Display scrollbar in list of And Forum in Create a new Poll menu");
		String titleCat1 = "Category 1040511";
		String titleForum1 = "Forum 1040511";
		String titleTop1 = "Topic 1040511";

		String titleCat2 = "Category 1040512";
		String titleForum2 = "Forum 1040512";
		String titleTop2 = "Topic 1040512";

		String titleCat3 = "Category 1040513";
		String titleForum3 = "Forum 1040513";
		String titleTop3 = "Topic 1040513";

		String titleCat4 = "Category 1040514";
		String titleForum4 = "Forum 1040514";
		String titleTop4 = "Topic 1040514";

		String titleCat5 = "Category 1040515";
		String titleForum5 = "Forum 1040515";
		String titleTop5 = "Topic 1040515";

		String titleCat6 = "Category 1040516";
		String titleForum6 = "Forum 1040516";
		String titleTop6 = "Topic 1040516";

		String titleCat7 = "Category 1040517";
		String titleForum7 = "Forum 1040517";
		String titleTop7 = "Topic 1040517";

		String titleCat8 = "Category 1040518";
		String titleForum8 = "Forum 1040518";
		String titleTop8 = "Topic 1040518";

		String titleCat9 = "Category 1040519";
		String titleForum9 = "Forum 1040519";
		String titleTop9 = "Topic 1040519";

		String titleCat10 = "Category 10405190";
		String titleForum10 = "Forum 10405190";
		String titleTop10 = "Topic 10405190";

		String titleCat11 = "Category 10405191";
		String titleForum11 = "Forum 10405191";
		String titleTop11 = "Topic 10405191";

		String titleCat12 = "Category 10405192";
		String titleForum12 = "Forum 10405192";
		String titleTop12 = "Topic 10405192";

		String titleCat13 = "Category 10405193";
		String titleForum13 = "Forum 10405193";
		String titleTop13 = "Topic 10405193";

		mngTopic.goToForums();
		mngTopic.addCategoryForumTopic(titleCat1, titleForum1, titleTop1,titleTop1);
		mngTopic.addCategoryForumTopic(titleCat2, titleForum2, titleTop2,titleTop2);
		mngTopic.addCategoryForumTopic(titleCat3, titleForum3, titleTop3,titleTop3);
		mngTopic.addCategoryForumTopic(titleCat4, titleForum4, titleTop4,titleTop4);
		mngTopic.addCategoryForumTopic(titleCat5, titleForum5, titleTop5,titleTop5);
		mngTopic.addCategoryForumTopic(titleCat6, titleForum6, titleTop6,titleTop6);
		mngTopic.addCategoryForumTopic(titleCat7, titleForum7, titleTop7,titleTop7);
		mngTopic.addCategoryForumTopic(titleCat8, titleForum8, titleTop8,titleTop8);
		mngTopic.addCategoryForumTopic(titleCat9, titleForum9, titleTop9,titleTop9);
		mngTopic.addCategoryForumTopic(titleCat10, titleForum10, titleTop10,titleTop10);
		mngTopic.addCategoryForumTopic(titleCat11, titleForum11, titleTop11,titleTop11);
		mngTopic.addCategoryForumTopic(titleCat12, titleForum12, titleTop12,titleTop12);
		mngTopic.addCategoryForumTopic(titleCat13, titleForum13, titleTop13,titleTop13);
		nav.goToHomePage();

		/*Step Number: 1
		 *Step Name: Connect to Intranet
		 *Step Description: 
			- Connect to Intranet
		 *Input Data: 

		 *Expected Outcome: 
			- The Top Navigation bar is displayed*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*Step number: 2
		 *Step Name: Show a scrollbar in the field "And Forum"
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Poll"
			- Click on Next
			- Click on the right arrow from the field "And Forum"
		 *Input Data: 

		 *Expected Outcome: 
			- The space switcher is displayed
			- Only 12 items are displayed and others are scrollable*/ 
		nav.goToPoll();
		click(nav.ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_FILTER_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum4));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat4));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum5));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat5));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum6));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat6));

		((JavascriptExecutor) driver).executeScript("arguments[0].scrollTop = arguments[0].scrollHeight;", 
				waitForAndGetElement(ELEMENT_FORUM_FILTER_AREA));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum7));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat7));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum8));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat8));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum9));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat9));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum10));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat10));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum11));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat11));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum12));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat12));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum13));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat13));

		button.cancel();

		info("Test 17 Display scrollbar in list of And Forum in Create a new Topic menu");
		/*Step number: 2
		 *Step Name: Show a scrollbar in the field "And Forum"
		 *Step Description: 
			- Mouse over on the button "Create" (+)
			- Select "Topic"
			- Click on Next
			- Click on the right arrow from the field "And Forum"
		 *Input Data: 

		 *Expected Outcome: 
			- The space switcher is displayed
			- Only 12 items are displayed and others are scrollable*/ 
		nav.goToCreateMenu();
		click(ELEMENT_ADD_TOPIC_ICON);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_FORM);
		button.next();
		click(ELEMENT_SELECT_FORUM);
		waitForAndGetElement(ELEMENT_FILTER_FORUM);
		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum1));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat1));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum2));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat2));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum3));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat3));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum4));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat4));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum5));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat5));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum6));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat6));

		((JavascriptExecutor) driver).executeScript("arguments[0].scrollTop = arguments[0].scrollHeight;", 
				waitForAndGetElement(ELEMENT_FORUM_FILTER_AREA));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum7));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat7));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum8));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat8));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum9));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat9));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum10));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat10));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum11));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat11));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum12));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat12));

		waitForAndGetElement(ELEMENT_SELECT_FORUM_ITEM.replace("${forumName}", titleForum13));
		waitForAndGetElement(ELEMENT_SELECT_CATEGORY_ITEM.replace("${catName}", titleCat13));
		click(button.ELEMENT_CANCEL_BUTTON);
		/*Clear data*/
		mngTopic.goToForums();
		click(By.linkText(titleCat13));
		mngCat.deleteCategoryInForum(titleCat13, true);
		click(By.linkText(titleCat12));
		mngCat.deleteCategoryInForum(titleCat12, true);
		click(By.linkText(titleCat11));
		mngCat.deleteCategoryInForum(titleCat11, true);
		click(By.linkText(titleCat10));
		mngCat.deleteCategoryInForum(titleCat10, true);
		click(By.linkText(titleCat9));
		mngCat.deleteCategoryInForum(titleCat9, true);
		click(By.linkText(titleCat8));
		mngCat.deleteCategoryInForum(titleCat8, true);
		click(By.linkText(titleCat7));
		mngCat.deleteCategoryInForum(titleCat7, true);
		click(By.linkText(titleCat6));
		mngCat.deleteCategoryInForum(titleCat6, true);
		click(By.linkText(titleCat5));
		mngCat.deleteCategoryInForum(titleCat5, true);
		click(By.linkText(titleCat4));
		mngCat.deleteCategoryInForum(titleCat4, true);
		click(By.linkText(titleCat3));
		mngCat.deleteCategoryInForum(titleCat3, true);
		click(By.linkText(titleCat2));
		mngCat.deleteCategoryInForum(titleCat2, true);
		click(By.linkText(titleCat1));
		mngCat.deleteCategoryInForum(titleCat1, true);
	}
}