package org.exoplatform.selenium.platform.plf.functional.navigation.topnavigation.create;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.Utils;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.PageManagement;
import org.exoplatform.selenium.platform.ManageAccount.userType;
import org.exoplatform.selenium.platform.UserGroupManagement;
import org.exoplatform.selenium.platform.social.ApplicationManagement;
import org.exoplatform.selenium.platform.social.ManageMember;
import org.exoplatform.selenium.platform.social.SocialBase;
import org.exoplatform.selenium.platform.wiki.Permission;
import org.openqa.selenium.By;
import org.testng.annotations.*;
/**
 * @author chinhdtt
 * @date 03 Jun 2014
 */
public class PLF_Navigation_TopNavigation_Create_WikiPage extends Permission{
	ManageAccount acc;
	NavigationToolbar nav;
	ManageMember mMember;
	PageManagement mPage; 
	ApplicationManagement mApplication; 
	UserGroupManagement uGroup; 
	SocialBase social; 

	@BeforeMethod
	public void beforeMethods(){	
		initSeleniumTest();
		driver.get(baseUrl);
		acc = new ManageAccount(driver, this.plfVersion);
		nav = new NavigationToolbar(driver, this.plfVersion);				
		acc.signIn(DATA_USER1, DATA_PASS);		
		mMember = new ManageMember(driver, this.plfVersion);
		mPage = new PageManagement(driver, this.plfVersion);
		mApplication = new ApplicationManagement(driver);
		uGroup = new UserGroupManagement(driver, this.plfVersion);
		social = new SocialBase(driver, this.plfVersion);
	}

	@AfterMethod
	public void afterMethods() {
		info("Logout portal");
		driver.manage().deleteAllCookies();
		driver.quit();
	}

	/**
	 * Case ID:76775.
	 * Test Case Name: Dismiss the "Create a new Wiki page" menu after a space switcher display.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/03 12:15:59
	 */
	@Test
	public  void test01_DismissTheCreateANewWikiPageMenuAfterASpaceSwitcherDisplay() {
		info("Test 1: Dismiss the Create a new Wiki page menu after a space switcher display");
		/*
		- Connect to Intranet
		 *Expected Outcome: The Top Navigation bar is displayed		*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*
		- Mouse over on the button "Create" (+)
		- Choose "Wiki Page"
		 *Input Data: 
		 *Expected Outcome: 
		- The "Create a new wiki page" menu is displayed
		- The field "In Location" is displayed
		- Buttons "Cancel" and "Next" are displayed		*/
		info("Go to Wiki page");
		nav.goToCreateMenu();
		click(ELEMENT_ADD_WIKI_ICON);
		waitForAndGetElement(ELEMENT_ADD_WIKI_FORM);
		waitForAndGetElement(ELEMENT_CREATE_WIKI_LABEL);
		waitForAndGetElement(ELEMENT_SPACE_SWITCHER_BREADCRUMB);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);

		/*
		- Click on the arrow in the field "In location"
		- Click on the button "Cancel"
		 *Input Data: 
		 *Expected Outcome: 
		- The space switcher is displayed
		- The menu "Create" is dismissed		*/ 
		click(ELEMENT_SPACE_SWITCHER_BREADCRUMB);
		info("Spaces field is shown");
		waitForAndGetElement(ELEMENT_LOCATION_WIKI);
		info("Close space switcher");
		click(ELEMENT_SPACE_SWITCHER_CLOSE);
		info("Cancel wiki form");
		button.cancel();
	}

	/**
	 * Case ID:76776.
	 * Test Case Name: Display Personal wiki in Space switcher.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/03 12:15:59
	 */
	@Test
	public  void test02_DisplayPersonalWikiInSpaceSwitcher() {
		info("Test 2: Display Personal wiki in Space switcher");
		/*
		- Connect to Intranet
		 *Expected Outcome: 
		- The Top Navigation bar is displayed 		*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*
		- Mouse over on the button "Create" (+)
		- Select "Wiki Page"
		 *Input Data: 
		 *Expected Outcome: 
		- The menu is updated to "Create a new Wiki Page:"
		- The field "In location" is displayed 		*/
		info("Go to Wiki page");
		nav.goToCreateMenu();
		click(ELEMENT_ADD_WIKI_ICON);
		waitForAndGetElement(ELEMENT_ADD_WIKI_FORM);
		waitForAndGetElement(ELEMENT_CREATE_WIKI_LABEL);
		waitForAndGetElement(ELEMENT_SPACE_SWITCHER_BREADCRUMB);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);

		/*
		- click on the right arrow from the field "In location"
		 *Input Data: 
		 *Expected Outcome: 
		-Personal wiki is shown on The space switcher * Personal wiki (of the connected user)		*/ 
		click(ELEMENT_SPACE_SWITCHER_BREADCRUMB);
		info("MyWiki");
		waitForAndGetElement(ELEMENT_SPACE_SWITCHER_MYWIKI);
	}

	/**
	 * Case ID:76777.
	 * Test Case Name: Display Space in Space switcher.
	 * Pre-Condition: User is member in a spaceApplication wiki exists in the spaceUser has permissions to edit page in the wiki
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/03 12:15:59
	 */
	@Test
	public  void test03_DisplaySpaceInSpaceSwitcher() {
		info("Test 3: Display Space in Space switcher");
		String spaceName = "Space76777";

		//Pre-Condition
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, spaceName);

		/*
		- Connect to Intranet
		 *Expected Outcome: 
		- The Top Navigation bar is displayed 		*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*
		- Mouse over on the button "Create" (+)
		- Select "Wiki Page"
		 *Input Data: 
		 *Expected Outcome: 
		- The menu is updated to "Create a new Wiki Page:"
		- The field "In location" is displayed 		*/
		info("Go to Wiki page");
		nav.goToCreateMenu();
		click(ELEMENT_ADD_WIKI_ICON);
		waitForAndGetElement(ELEMENT_ADD_WIKI_FORM);
		waitForAndGetElement(ELEMENT_CREATE_WIKI_LABEL);
		waitForAndGetElement(ELEMENT_SPACE_SWITCHER_BREADCRUMB);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);

		/*
		- click on the right arrow from the field "In location"
		 *Input Data: 
		 *Expected Outcome: 
		- The space switcher include: space wiki
		- Space level is displayed		*/ 
		click(ELEMENT_SPACE_SWITCHER_BREADCRUMB);
		info("Title of space switcher");
		waitForAndGetElement(ELEMENT_SPACE_SWITCHER_LOCATION);
		info("Space is displayed");
		waitForAndGetElement(ELEMENT_SPACE_SWITCHER_SELECT.replace("${spaceName}", spaceName));

		//Delete data test
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName, 300000);
	}

	/**
	 * Case ID:76779.
	 * Test Case Name: Not Display Space in Space switcher when application wiki doesn't exist.
	 * Pre-Condition: User is a member in a spaceApplication wiki doesn't exists in the space
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/03 12:15:59
	 */
	@Test
	public  void test04_NotDisplaySpaceInSpaceSwitcherWhenApplicationWikiDoesntExist() {
		info("Test 4: Not Display Space in Space switcher when application wiki doesn't exist");
		String spaceName = "Space 76779";

		//Pre-Condition
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, spaceName);
		info("Remove Wiki application");
		mMember.goToSpaceMenu("Space Settings");
		mApplication.removeApplication("Wiki");

		/*
		- Connect to Intranet
		 *Expected Outcome: 
		- The Top Navigation bar is displayed 		*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*
		- Mouse over on the button "Create" (+)
		- Select "Wiki Page"
		 *Input Data: 
		 *Expected Outcome: 
		- The menu is updated to "Create a new Wiki Page:"
		- The field "In location" is displayed 		*/
		info("Go to Wiki page");
		nav.goToCreateMenu();
		click(ELEMENT_ADD_WIKI_ICON);
		waitForAndGetElement(ELEMENT_ADD_WIKI_FORM);
		waitForAndGetElement(ELEMENT_CREATE_WIKI_LABEL);
		waitForAndGetElement(ELEMENT_SPACE_SWITCHER_BREADCRUMB);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);

		/*
		- click on the right arrow from the field "In location"
		 *Input Data: 
		 *Expected Outcome: 
		- The space switcher is displayed
		- Space without wiki application isn't displayed		*/ 
		click(ELEMENT_SPACE_SWITCHER_BREADCRUMB);
		info("Title of space switcher");
		waitForAndGetElement(ELEMENT_SPACE_SWITCHER_LOCATION);
		info("Space is displayed");
		waitForElementNotPresent(ELEMENT_SPACE_SWITCHER_SELECT.replace("${spaceName}", spaceName));

		//Delete data test
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName, 300000);
	}

	/**
	 * Case ID:76780.
	 * Test Case Name: Not Display Space in Space switcher when user has not edit permission.
	 * Pre-Condition: User is a member in a spaceApplication wiki exists in the spaceUser has not permissions to edit page in the wiki
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/03 12:15:59
	 * Bug link: https://jira.exoplatform.org/browse/PLF-4389
	 */
	@Test (groups ="errors")
	public  void test05_NotDisplaySpaceInSpaceSwitcherWhenUserHasNotEditPermission() {
		info("Test 5: Not Display Space in Space switcher when user has not edit permission");
		String username = getRandomString();
		String password = "gtn123";
		String firstName = "User";
		String lastName = "AAA";
		String email = username+"@gmail.com";
		String spaceName = "space76780";
		String userGroup = "*:/spaces/"+spaceName;

		//Pre-Condition
		info("Create new user");
		nav.goToNewStaff();
		acc.addNewUserAccount(username, password, password, firstName, lastName, "", email, null, null, false);

		info("Add new space");
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, spaceName);
		info("Delete permission of all members");
		mMember.goToSpaceMenu("Wiki");
		deleteSpacePermission(userGroup);

		info("Invite user");
		mMember.goToAllSpaces();
		waitForAndGetElement(ELEMENT_MY_SPACES_LINK);
		click(ELEMENT_MY_SPACES_LINK);
		Utils.pause(500);
		By actionLink = By.xpath(social.ELEMENT_ACTION_USER_ON_SPACE.replace("${spaceName}", spaceName).replace("${action}", "Edit"));
		waitForAndGetElement(actionLink, DEFAULT_TIMEOUT,1);
		click(actionLink);
		Utils.pause(1000);
		click(mMember.ELEMENT_MEMBER_TAB);
		waitForAndGetElement(By.id("user"));
		mMember.inviteSingleUser(username, firstName+" "+lastName);

		acc.signOut();
		acc.signIn(username, password);
		mMember.acceptInvitation(spaceName);

		/*
		- Connect to Intranet
		 *Expected Outcome: 
		- The Top Navigation bar is displayed 		*/
		nav.goToHomePage();
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*
		- Mouse over on the button "Create" (+)
		- Select "Wiki Page"
		 *Input Data: 
		 *Expected Outcome: 
		- The menu is updated to "Create a new Wiki Page:"
		- The field "In location" is displayed 		*/
		info("Go to Wiki page");
		nav.goToCreateMenu();
		click(ELEMENT_ADD_WIKI_ICON);
		waitForAndGetElement(ELEMENT_ADD_WIKI_FORM);
		waitForAndGetElement(ELEMENT_CREATE_WIKI_LABEL);
		waitForAndGetElement(ELEMENT_SPACE_SWITCHER_BREADCRUMB);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);

		/*
		- click on the right arrow from the field "In location"
		 *Input Data: 
		 *Expected Outcome: 
		- The space switcher is displayed
		- Not show space which this user has not "Edit permission" on its wiki		*/ 
		click(ELEMENT_SPACE_SWITCHER_BREADCRUMB);
		info("Title of space switcher");
		waitForAndGetElement(ELEMENT_SPACE_SWITCHER_LOCATION);
		info("Space is not displayed");
		waitForElementNotPresent(ELEMENT_SPACE_SWITCHER_SELECT.replace("${spaceName}", spaceName));

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName, 300000);	
		info("Delete users test");
		nav.goToUsersAndGroupsManagement();
		uGroup.deleteUser(username);
		Utils.pause(1000);
	}

	/**
	 * Case ID:76781.
	 * Test Case Name: Not Display Space in Space switcher when user is not a member.
	 * Pre-Condition: User is not member in a spaceApplication wiki exists in the space
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/03 12:15:59
	 */
	@Test
	public  void test06_NotDisplaySpaceInSpaceSwitcherWhenUserIsNotAMember() {
		info("Test 6: Not Display Space in Space switcher when user is not a member");
		String spaceName = "Space76781";

		//Pre-Condition
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, spaceName);

		/*
		- Connect to Intranet
		 *Expected Outcome: 
		- The Top Navigation bar is displayed 		*/
		acc.userSignIn(userType.PUBLISHER);
		Utils.pause(1000);
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*
		- Mouse over on the button "Create" (+)
		- Select "Wiki Page"
		 *Input Data: 
		 *Expected Outcome: 
		- The menu is updated to "Create a new Wiki Page:"
		- The field "In location" is displayed 		*/
		info("Go to Wiki page");
		nav.goToCreateMenu();
		click(ELEMENT_ADD_WIKI_ICON);
		waitForAndGetElement(ELEMENT_ADD_WIKI_FORM);
		waitForAndGetElement(ELEMENT_CREATE_WIKI_LABEL);
		waitForAndGetElement(ELEMENT_SPACE_SWITCHER_BREADCRUMB);
		waitForAndGetElement(button.ELEMENT_NEXT_BUTTON);
		waitForAndGetElement(button.ELEMENT_CANCEL_BUTTON);

		/*
		- click on the right arrow from the field "In location"
		 *Input Data: 
		 *Expected Outcome: 
		- The space switcher is displayed
		- Space where this user isn't member isn't displayed		*/ 
		click(ELEMENT_SPACE_SWITCHER_BREADCRUMB);
		info("Title of space switcher");
		waitForAndGetElement(ELEMENT_SPACE_SWITCHER_LOCATION);
		info("Space is not displayed");
		waitForElementNotPresent(ELEMENT_SPACE_SWITCHER_SELECT.replace("${spaceName}", spaceName));

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName, 300000);	
	}

	/**
	 * Case ID:76782.
	 * Test Case Name: Open wiki application from create menu.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/03 12:15:59
	 * Bug: https://jira.exoplatform.org/browse/PLF-6008
	 */
	@Test(groups="error")
	public  void test07_OpenWikiApplicationFromCreateMenu() {
		info("Test 7: Open wiki application from create menu");
		/*
		- Connect to Intranet
		 *Expected Outcome: 
		- The Top Navigation bar is displayed 		*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*
		- Mouse over on the button "Create" (+)
		- Select "Wiki Page"
		 *Input Data: 
		 *Expected Outcome: 
		- The menu is updated to "Create a new Wiki Page:"
		- The field "In location" is displayed 
		- Buttons "Cancel" and "Next" are displayed		*/
		/*
		- Choose a location to add a new wiki page from the space switcher
		- Click on the button "Next"
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki application is opened with the New Page editor opened		*/ 
		nav.goToWiki();
		info("Wiki is opened");
		waitForAndGetElement(ELEMENT_TITLE_WIKI_HOME_LINK);	
	}

	/**
	 * Case ID:76783.
	 * Test Case Name: Show "Intranet" as a default space switcher.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/03 12:15:59
	 * Bug: https://jira.exoplatform.org/browse/PLF-6008
	 */
	@Test(groups="error")
	public  void test08_ShowIntranetAsADefaultSpaceSwitcher() {
		info("Test 8: Show Intranet as a default space switcher");
		/*
		- Connect to Intranet
		 *Expected Outcome: 
		- The Top Navigation bar is displayed 		*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*
		- Mouse over on the button "Create" (+)
		- Select the item "Wiki Page"
		 *Input Data: 
		 *Expected Outcome: 
		- The menu is updated to "Create a new Wiki page:"
		- The field "In location" is displayed with "Intranet" as a default space switcher		*/ 
		info("Go to Wiki page");
		nav.goToCreateMenu();
		click(ELEMENT_ADD_WIKI_ICON);
		waitForAndGetElement(ELEMENT_ADD_WIKI_FORM);
		waitForAndGetElement(ELEMENT_CREATE_WIKI_LABEL);
		waitForAndGetElement(ELEMENT_SPACE_SWITCHER_BREADCRUMB);
		waitForAndGetElement(ELEMENT_CREATE_WIKI_INTRANET.replace("${name}", "intranet"));
	}

	/**
	 * Case ID:76778.
	 * Test Case Name: Show Company wiki on the Space switcher.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/03 12:15:59
	 */
	@Test
	public  void test09_ShowCompanyWikiOnTheSpaceSwitcher() {
		info("Test 9: Show Company wiki on the Space switcher");
		/*
		- Connect to Intranet
		 *Expected Outcome: 
		- The Top Navigation bar is displayed 		*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*
		- Mouse over on the button "Create" (+)
		- Select "Wiki Page"
		 *Input Data: 
		 *Expected Outcome: 
		- The menu is updated to "Create a new Wiki Page:"
		- The field "In location" is displayed 		*/
		info("Go to Wiki page");
		nav.goToCreateMenu();
		click(ELEMENT_ADD_WIKI_ICON);
		waitForAndGetElement(ELEMENT_ADD_WIKI_FORM);
		waitForAndGetElement(ELEMENT_CREATE_WIKI_LABEL);
		waitForAndGetElement(ELEMENT_SPACE_SWITCHER_BREADCRUMB);		

		/*
		- Click on the right arrow from the field "In location"
		 *Input Data: 
		 *Expected Outcome: 
		- The space switcher include:* Company wiki (Intranet)		*/ 
		info("Open location field");
		click(ELEMENT_SPACE_SWITCHER_BREADCRUMB);
		waitForAndGetElement(ELEMENT_SPACE_SWITCHER_INTRANET.replace("${spaceName}", "Intranet"));
	}

	/**
	 * Case ID:76784.
	 * Test Case Name: Update "Create" menu to "Create a nex wiki page" menu.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/06/03 12:15:59
	 */
	@Test
	public  void test10_UpdateCreateMenuToCreateANexWikiPageMenu() {
		info("Test 10 Update Create menu to Create a nex wiki page menu");
		/*
		- Connect to Intranet
		 *Expected Outcome: 
		- The Top Navigation bar is displayed 		*/
		waitForAndGetElement(ELEMENT_NAVIGATION_TOOLBAR_HOMEPAGE);

		/*
		- Mouse over on the button "Create" (+)
		 *Input Data: 
		 *Expected Outcome: The list of items is displayed:* Event/Task* Poll* Topic* Upload Document* Wiki		*/
		nav.goToCreateMenu();
		info("Item menu of Create");
		waitForAndGetElement(ELEMENT_ADD_EVENT_TASK_ICON);
		waitForAndGetElement(ELEMENT_ADD_POLL_ICON);
		waitForAndGetElement(ELEMENT_ADD_TOPIC_ICON);
		waitForAndGetElement(ELEMENT_ADD_UPLOAD_FILE_ICON);
		waitForAndGetElement(ELEMENT_ADD_WIKI_ICON);

		/*
		- Select the item "Wiki"
		 *Input Data: 
		 *Expected Outcome: 
		- The menu is updatedto display "Create a new Wiki page:"
		- The field "In location" is displayed 		*/ 
		click(ELEMENT_ADD_WIKI_ICON);
		waitForAndGetElement(ELEMENT_ADD_WIKI_FORM);
		waitForAndGetElement(ELEMENT_CREATE_WIKI_LABEL);
		waitForAndGetElement(ELEMENT_SPACE_SWITCHER_BREADCRUMB);		
	}
}