package  org.exoplatform.selenium.platform.plf.functional.homepageactivitystream.activitystream.activityordering;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.Utils;
import org.exoplatform.selenium.platform.HomePageActivity;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.ecms.contentexplorer.ActionBar;
import org.exoplatform.selenium.platform.social.Activity;
import org.exoplatform.selenium.platform.social.ManageMember;
import org.testng.annotations.*;
/**
 * @author chinhdtt
 *
 */
public class PLF_HomepageActivityStream_ActivityStream_ActivityOrdering extends Activity{
	ManageAccount acc; 
	HomePageActivity home; 
	NavigationToolbar nav; 
	ActionBar actBar;
	ManageMember mMember; 

	@BeforeMethod
	public void setUpBeforeTest(){
		initSeleniumTest();
		driver.get(baseUrl);
		acc = new ManageAccount(driver, this.plfVersion);
		home = new HomePageActivity(driver, this.plfVersion); 
		acc.signIn(DATA_USER1, DATA_PASS);
		nav = new NavigationToolbar(driver, this.plfVersion);
		mMember = new ManageMember(driver,this.plfVersion);
	}

	@AfterMethod
	public void afterTest(){
		driver.manage().deleteAllCookies();		
		driver.quit();
	}

	/**
	 * Case ID:77650.
	 * Test Case Name: Add activity from a space.
	 * Pre-Condition: A space is createdThere are some activities of space
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2013/12/26 17:47:53
	 */
	@Test
	public  void test01_AddActivityFromASpace() {
		info("Test 1: Add activity from a space");
		/*
		- Connect to Intranet
		- Open a Space
		- Add an activity
		 *Input Data: 
		 *Expected Outcome: The activity is added in the top of the stream		*/
		String spaceName = "Space 77650";
		String text1 = "Activity 1";
		String text2 = "Activity 2"; 
		mMember.goToMySpacePage();
		mMember.addNewSpace(spaceName, ""); 
		addActivity(true, text1, false,"");
		Utils.pause(500);
		addActivity(true, text2, false,"");
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","1").replace("${activityText}", text2));
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","2").replace("${activityText}", text1));
		/*
		- Go to Intranet Homepage
		- Open the stream "My space"
		 *Input Data: 
		 *Expected Outcome: The activity is added on top of the activity stream		*/ 
		nav.goToHomePage();
		selectFileter("My Spaces");
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","1").replace("${activityText}", text2));
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","2").replace("${activityText}", text1));

		//delete data
		goToAllSpaces();
		mMember.deleteSpace(spaceName, 300000);
	}

	/**
	 * Case ID:77651.
	 * Test Case Name: Add an activity in Intranet Home.
	 * Pre-Condition: There are some activities on "All Activities"
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2013/12/26 17:47:53
	 */
	@Test
	public  void test02_AddAnActivityInIntranetHome() {
		info("Test 2: Add an activity in Intranet Home");
		String text1 = "Activity 1 in 77651";
		String text2 = "Activity 2 in 77651";
		/*
		- Connect to Intranet
		- Input text into activity text box and click Share
		 *Input Data: 
		 *Expected Outcome: The activity is added at the top of the stream		*/ 
		nav.goToHomePage();
		selectFileter("All Activities");
		addActivity(true, text1, false,"");
		Utils.pause(500);
		addActivity(true, text2, false,"");
		nav.goToHomePage();
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","1").replace("${activityText}", text2));
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","2").replace("${activityText}", text1));

		//delete data
		home.deleteActivity(text2);
		home.deleteActivity(text1);
	}

	/**
	 * Case ID:77652.
	 * Test Case Name: Add a comment to an older activity from Home.
	 * Pre-Condition: There are some activities on Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2013/12/26 17:47:53
	 */
	@Test
	public  void test03_AddACommentToAnOlderActivityFromHome() {
		info("Test 3: Add a comment to an older activity from Home");
		String text1 = "Activity 1 in 77652";
		String text2 = "Activity 2 in 77652";
		String comment = "Comment 77652";
		/*
		- Connect to Intranet
		- Display the stream "All activities"
		 *Input Data: 
		 *Expected Outcome: Activities are sorted by the last action date		*/
		nav.goToHomePage();
		selectFileter("All Activities");
		addActivity(true, text1, false,"");
		Utils.pause(500);
		addActivity(true, text2, false,"");
		nav.goToHomePage();
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","1").replace("${activityText}", text2));
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","2").replace("${activityText}", text1));
		/*
		- Add a comment to an old activity
		- Refresh the page or change the stream
		 *Input Data: 
		 *Expected Outcome: 
		- The activity is placed at the top of the stream "All activities"		*/ 
		addComment(text1, comment);
		nav.goToHomePage();
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","1").replace("${activityText}", text1));
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","2").replace("${activityText}", text2));

		//delete data
		home.deleteActivity(text2);
		home.deleteActivity(text1);
	}

	/**
	 * Case ID:77653.
	 * Test Case Name: Add a Like to an older activity from the Home.
	 * Pre-Condition: There are some activities on Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2013/12/26 17:47:53
	 */
	@Test
	public  void test04_AddALikeToAnOlderActivityFromTheHome() {
		info("Test 4: Add a Like to an older activity from the Home");
		String text1 = "Activity 1 in 77653";
		String text2 = "Activity 2 in 77653";
		/*
		- Connect to Intranet
		- Display the stream "All activities"
		 *Input Data: 
		 *Expected Outcome: Activities are sorted by the last action date		*/
		nav.goToHomePage();
		selectFileter("All Activities");
		addActivity(true, text1, false,"");
		addActivity(true, text2, false,"");
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","1").replace("${activityText}", text2));
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","2").replace("${activityText}", text1));
		/*
		- Add a like to an old activity
		- Refresh the page or change the stream
		 *Input Data: 
		 *Expected Outcome: 
		- The activity keep the same place in the stream "All activities"		*/ 
		home.likeOrUnlikeActivity(text1);
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","1").replace("${activityText}", text2));
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","2").replace("${activityText}", text1));

		//delete data
		home.deleteActivity(text2);
		home.deleteActivity(text1);
	}

	/**
	 * Case ID:77654.
	 * Test Case Name: Add a comment to an older activity from a space.
	 * Pre-Condition: A space is createdThere are some activities of space
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2013/12/26 17:47:53
	 */
	@Test
	public  void test05_AddACommentToAnOlderActivityFromASpace() {
		info("Test 5: Add a comment to an older activity from a space");
		String spaceName = "Space 77654";
		String text1 = "Activity 1";
		String text2 = "Activity 2"; 
		String comment = "Comment 77654";
		/*
		- Connect to Intranet
		- Open a space
		 *Input Data: 
		 *Expected Outcome: Activities of the space are sorted by the last action date		*/
		mMember.goToMySpacePage();
		mMember.addNewSpace(spaceName, ""); 
		addActivity(true, text1, false,"");
		Utils.pause(500);
		addActivity(true, text2, false,"");
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","1").replace("${activityText}", text2));
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","2").replace("${activityText}", text1));
		/*
		- Add a comment to an old activity
		- Refresh the page or change the stream
		 *Input Data: 
		 *Expected Outcome: 
		- The activity is placed at the top of the stream of the space */ 
		addComment(text1, comment);
		Utils.pause(500);
		driver.navigate().refresh();
		Utils.pause(1000);
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","1").replace("${activityText}", text1));
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","2").replace("${activityText}", text2));
		//delete data
		goToAllSpaces();
		mMember.deleteSpace(spaceName, 300000);
	}

	/**
	 * Case ID:77655.
	 * Test Case Name: Add a Like to an older activity from a space.
	 * Pre-Condition: A space is createdThere are some activities of space
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2013/12/26 17:47:53
	 */
	@Test
	public  void test06_AddALikeToAnOlderActivityFromASpace() {
		info("Test 6: Add a Like to an older activity from a space");
		String spaceName = "Space 77655";
		String text1 = "Activity 1";
		String text2 = "Activity 2";
		/*
		- Connect to Intranet
		- Open a space
		 *Input Data: 
		 *Expected Outcome: Activities of the space are sorted by the last action date		*/
		mMember.goToMySpacePage();
		mMember.addNewSpace(spaceName, ""); 
		addActivity(true, text1, false,"");
		Utils.pause(500);
		addActivity(true, text2, false,"");
		Utils.pause(500);
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","1").replace("${activityText}", text2));
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","2").replace("${activityText}", text1));
		/*
		- Like an old activity
		- Refresh the page or change the stream
		 *Input Data: 
		 *Expected Outcome: 
		- The activity keep the same place in the stream of the space		*/ 
		home.likeOrUnlikeActivity(text1);
		Utils.pause(500);
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","1").replace("${activityText}", text2));
		waitForAndGetElement(home.ELEMENT_ACTIVITY_ORDER.replace("${index}","2").replace("${activityText}", text1));
		//delete data
		goToAllSpaces();
		mMember.deleteSpace(spaceName, 300000);
	}


}