package org.exoplatform.selenium.platform.wiki.functional.activities;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.Dialog;
import org.exoplatform.selenium.platform.HomePageActivity;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.ManageAccount.userType;
import org.exoplatform.selenium.platform.social.ManageMember;
import org.exoplatform.selenium.platform.wiki.BasicAction;
import org.exoplatform.selenium.platform.wiki.Permalink;
import org.openqa.selenium.By;
import org.testng.annotations.*;

/**
 * @author chinhdtt
 * @date 6 Mar 2014
 */
public class Wiki_Activities extends Permalink{

	ManageAccount acc;
	HomePageActivity home;
	NavigationToolbar nav;
	BasicAction bAct; 
	Permalink per; 
	Dialog dialog; 
	ManageMember mMember; 

	@BeforeMethod
	public void beforeMethod(){
		initSeleniumTest();
		driver.get(baseUrl);
		driver.manage().window().maximize();
		bAct = new BasicAction();
		per = new Permalink();
		mMember = new ManageMember(driver, this.plfVersion);
		home = new HomePageActivity(driver,this.plfVersion);
		nav = new NavigationToolbar(driver,this.plfVersion);
		acc = new ManageAccount(driver,this.plfVersion);
		acc.signIn(DATA_USER1, DATA_PASS);
	}

	@AfterMethod
	public void afterMethod(){
		driver.manage().deleteAllCookies();
		driver.quit();
	}

	/**
	 * Case ID:77113.
	 * Test Case Name: Add a wiki's activity after create a wiki page in portal.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test01_AddAWikisActivityAfterCreateAWikiPageInPortal(){
		info("Test 1: Add a wiki's activity after create a wiki page in portal");
		String title = "Case 77113";
		String content = "Add Content case 77113";

		/*
		- Connect to Intranet
		- Create a wiki page
		 *Input Data: 
		 *Expected Outcome: 
		- Wiki page is created		*/
		goToWiki();
		addBlankWikiPage(title, content, 0);

		/*
		- Back to the Hompage
		 *Input Data: 
		 *Expected Outcome: 
		- An activity of wikis added to the activity stream
		- The content of the activity is displayed		*/ 
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, content, "1");

		//Delete data test
		click(By.linkText(title));
		deleteCurrentWikiPage();
	}

	/**
	 * Case ID:77117.
	 * Test Case Name: Display "View Changes" page from wiki's activity.
	 * Pre-Condition: the wiki page is not "version 1"
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test02_DisplayViewChangesPageFromWikisActivity() {
		info("Test 2: Display View Changes page from wiki's activity");
		String title = "Case 77117";
		String titleUpdate = "Update_title 77117";
		String content = "Content case 77117";
		String contentUpdate = "Display view changes page from activity of wiki";

		/*
		- Connect to Intranet
		- Go to the Homepage
		- Go to wiki 
		- Add new page
		 *Input Data: 
		 *Expected Outcome: 
		- A wiki activity is displayed 		*/
		goToWiki();
		addBlankWikiPage(title, content, 0);
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, content, "1");

		/*
		- Click edit page
		- Change content for page
		- Click [Save]
		 *Input Data: 
		 *Expected Outcome: 
		- Edit page successfully
		- Wiki page's version "View change" is displayed		*/
		click(By.linkText(title));
		editWikiPage(titleUpdate, contentUpdate, 0);
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(titleUpdate, contentUpdate, "2");
		waitForAndGetElement(home.ELEMENT_CONTENT_WIKI_VIEW_CHANGE);

		/*
		- Click on the link "View changes"
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki application is opened in the view to compare Version N
		- 1 and Version N		*/ 
		click(home.ELEMENT_CONTENT_WIKI_VIEW_CHANGE);
		waitForAndGetElement(ELEMENT_EDIT_COMPARE_CHANGE);
		waitForAndGetElement(ELEMENT_EDIT_COMPARE_VERSION.replace("${version}","Version 1"));
		waitForAndGetElement(ELEMENT_EDIT_COMPARE_VERSION.replace("${version}","Current version"));

		//Delete data test
		click(By.linkText(titleUpdate));
		deleteCurrentWikiPage();
	}

	/**
	 * Case ID:77118.
	 * Test Case Name: Update wiki's activity after edit wiki page title with active notification.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test03_UpdateWikisActivityAfterEditWikiPageTitleWithActiveNotification() {
		info("Test 3: Update wiki's activity after edit wiki page title with active notification");
		String title = "Case 77118";
		String titleUpdate = "Update Case 77118";
		String content = "Content case 77118";

		/*
		- Connect to Intranet
		- Open wiki application
		- Add new page
		 *Input Data: 
		 *Expected Outcome: 
		- A wiki page is added successfully		*/
		goToWiki();
		addBlankWikiPage(title, content, 0);		

		/*
		- Edit a title of a wiki page
		- Check [Publish Activity]
		- Click [Save]
		 *Input Data: 
		 *Expected Outcome: 
		- Title of page is updated with new title		*/
		editPageWithCheckPublicActivity(titleUpdate, content);

		/*
		- Go to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki activity is updated
		- A comment is added in the activity: Page's title has been updated to: $value.		*/
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(titleUpdate, content, "2");
		waitForAndGetElement(home.ELEMENT_WIKI_COMMENT_EDIT_TITLE.replace("${title}", titleUpdate));

		//Delete data test
		click(By.linkText(titleUpdate));
		deleteCurrentWikiPage();
	}

	/**
	 * Case ID:77119.
	 * Test Case Name: Update wiki's activity after edit wiki page title with inactive notification.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test04_UpdateWikisActivityAfterEditWikiPageTitleWithInactiveNotification() {
		info("Test 4: Update wiki's activity after edit wiki page title with inactive notification"); 
		String title = "Case 77119";
		String titleUpdate = "Update title 77119";
		String content = "Content case 77119";

		/*
		- Connect to Intranet
		- Open wiki application
		- Add new page
		 *Input Data: 
		 *Expected Outcome: 
		- Add new page successfully		*/
		goToWiki();
		addBlankWikiPage(title, content, 0);		

		/*
		- Edit a title of a wiki page
		- Un-check [Publish Activity]
		- Click Save
		 *Input Data: 
		 *Expected Outcome: 
		- Title's page is updated with new value		*/
		click(By.linkText(title));
		editWikiPage(titleUpdate, content, 0);

		/*
		- Go to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki activity content is updated with the new page title		*/ 
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(titleUpdate, content, "2");
		waitForElementNotPresent(home.ELEMENT_WIKI_COMMENT_EDIT_TITLE.replace("${title}", titleUpdate));
		//Delete data test
		click(By.linkText(titleUpdate));
		deleteCurrentWikiPage();
	}

	/**
	 * Case ID:77120.
	 * Test Case Name: Update wiki's activity after edit wiki page without comment.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test05_UpdateWikisActivityAfterEditWikiPageWithoutComment() {
		info("Test 5: Update wiki's activity after edit wiki page without comment");
		String title = "Case 77120";
		String content = "Content case 77120";
		String contentUpdate = "Update content 77120";

		/*
		- Connect to Intranet
		- Open wiki application
		- Add new wiki page
		 *Input Data: 
		 *Expected Outcome: 
		- New page is added successfully		*/
		goToWiki();
		addBlankWikiPage(title, content, 0);		

		/*
		- Edit a content of wiki page without any comment associated
		- Click [Publish Activity]
		- Click [Save]
		 *Input Data: 
		 *Expected Outcome: 
		- Content of page is updated		*/
		editPageWithCheckPublicActivity(title, contentUpdate);

		/*
		- Go to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki activity is updated
		- A comment is added in the activity: Page's content has been edited.		*/ 
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, contentUpdate, "2");
		waitForAndGetElement(home.ELEMENT_WIKI_COMMENT_EDIT_CONTENT.replace("${title}", title));

		//Delete data test
		click(By.linkText(title));
		deleteCurrentWikiPage();
	}

	/**
	 * Case ID:77121.
	 * Test Case Name: Update wiki's activity after edit wiki page with comment.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test06_UpdateWikisActivityAfterEditWikiPageWithComment() {
		info("Test 6: Update wiki's activity after edit wiki page with comment");
		String title = "Case 77121";
		String content = "Content case 77121";
		String contentUpdate = "Update content case 77121";
		String comment = "Add Comment 77121";
		/*
		- Connect to Intranet
		- Open wiki application
		- Add new page 
		 *Input Data: 
		 *Expected Outcome: 
		- New page is added successfully		*/
		goToWiki();
		addBlankWikiPage(title, content, 0);

		/*
		- Click [Edit] page
		- Change content for page
		- Add comment
		- Click [Publish Activity]
		- Click [Save]
		 *Input Data: 
		 *Expected Outcome: Content of page is updated		*/
		editPageWithCheckPublicActivity(title, contentUpdate, comment);

		/*
		- Go to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki activity is updated
		- A comment is added to the activity, containing the associated comment value		*/ 
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, contentUpdate,"2");
		waitForAndGetElement(home.ELEMENT_ACTIVITY_COMMENT_CONTENT.replace("${title}",title).replace("${comment}", comment));

		//Delete data test
		click(By.linkText(title));
		deleteCurrentWikiPage();
	}

	/**
	 * Case ID:77122.
	 * Test Case Name: Update wiki's activity after edit wiki page with inactive notification.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test07_UpdateWikisActivityAfterEditWikiPageWithInactiveNotification() {
		info("Test 7: Update wiki's activity after edit wiki page with inactive notification");
		String title = "wikititle77122";
		String content = "wikicontent771122";
		String contentUpdate = "Line1/Line2/Line3/Line 4/Line5";

		/*
		- Connect to Intranet
		- Open wiki application
		- Add new page
		 *Input Data: 
		 *Expected Outcome: 
		- A new page is added successfully		*/
		goToWiki();
		addWikiPageWithContentMultiLine(title, content);

		/*
		- Edit a content of wiki page
		- Un-check [Publish Activity]
		- Click save
		 *Input Data: 
		 *Expected Outcome: 
		- Content of page is updated		*/
		click(By.linkText(title));
		editWikiPage(title, contentUpdate,0,true);

		/*
		- Go to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki activity is updated:* Version * potentialy first 4 lines
		- No comment is added into activity		*/ 
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, contentUpdate,"2");
		waitForAndGetElement(home.ELEMENT_ICON_COMMENT.replace("${title}",title)).getText().equalsIgnoreCase("0");

		//Delete data test
		click(By.linkText(title));
		deleteCurrentWikiPage();
	}

	/**
	 * Case ID:77123.
	 * Test Case Name: Update wiki's activity after move of wiki page.
	 * Pre-Condition: the wiki activity is already shared in the activity stream
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test08_UpdateWikisActivityAfterMoveOfWikiPage() {
		info("Test 8: Update wiki's activity after move of wiki page");
		String title1 = "Wiki_activity_title_77123_1";
		String content1 = "Wiki_activity_content_77123_1";
		String title2 = "Wiki_activity_title_77123_2";
		String content2 = "Wiki_activity_content_77123_2";
		/*
		- Connect to Intranet
		- Open wiki application
		- Add new page
		 *Input Data: 
		 *Expected Outcome: 
		- A page is added successful		*/
		goToWiki();
		addBlankWikiPage(title1, content1, 0);
		goToWikiHome();
		addBlankWikiPage(title2, content2, 0);

		/*
		- Click [More] choose [Move Page]
		- Select [Destination] and click [Move]
		 *Input Data: 
		 *Expected Outcome: Page has been moved to new place		*/
		info("Move page 2 to Intranet");
		movePage(title2, title1);

		/*
		- Go to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki activity isn't updated
		- A comment is added in the activity: Page has been moved to : $value. where $value is :SpaceName>WikiRootPage>WikiRootPage2>..		*/ 
		nav.goToHomePage();
		home.checkCommentAfterMoveWikiPage(title2, "Wiki Home > " + title1 + " > " + title2);

		//Delete data test
		click(By.linkText(title2));
		click(By.linkText(title1));
		deleteCurrentWikiPage();
	}

	/**
	 * Case ID:77127.
	 * Test Case Name: Delete a Wiki activity from activity stream by owner.
	 * Pre-Condition: Create a space and make it's wiki public ( Click Restricted link at the top then click Make public)
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test 
	public  void test09_DeleteAWikiActivityFromActivityStreamByOwner() {
		info("Test 9: Delete a Wiki activity from activity stream by owner");
		String spaceName = "Space 77127";
		String title = "Title 77127";
		String content = "Content 77127";
		String newcontent = "Content case 77127";
		//Pre-Condition 
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, "");

		/*
		- Connect to Intranet
		- Add a Wiki activity for space 
		 *Input Data: 
		 *Expected Outcome: 
		- The Wiki activity for space displayed in the activity stream		*/
		goToWikiFromSpace(spaceName);
		addBlankWikiPage(title, content, 0);
		makePublicPage();
		editPageWithCheckPublicActivity(title, newcontent);
		/*
		- Back to activity stream 
		- Move the mouse over the Wiki activity for space 
		 *Input Data: 
		 *Expected Outcome: A (X) icon is displayed in the top right panel of the activity		*/
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, newcontent, "2");

		/*
		- Click on the (X) icon
		- Click on [OK] button of confirmation message
		 *Input Data: 
		 *Expected Outcome: The Wiki activity for space removed from the activity stream		*/ 
		mouseOver(By.xpath(home.ELEMENT_ACTIVITY_WIKI_TITLE.replace("${title}", title)), true);
		waitForAndGetElement(By.xpath(home.ELEMENT_ACTIVITY_DELETE.replace("${activityText}", title)), DEFAULT_TIMEOUT,1,2);
		info("Click on X icon");
		home.deleteActivity(title);	
		waitForElementNotPresent(By.xpath(home.ELEMENT_ACTIVITY_WIKI_TITLE.replace("${title}", title)));

		//Delete data test
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName,300000);
	}

	/**
	 * Case ID:77128.
	 * Test Case Name: Dislike a Wiki activity from like icon.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test10_DislikeAWikiActivityFromLikeIcon() {
		info("Test 10 Dislike a Wiki activity from like icon");
		String title = "Title case 77128";
		String content = "Content case 77128";
		/*
		- Connect to Intranet 
		- Add a Wiki activity
		 *Input Data: 
		 *Expected Outcome: A wiki page is created		*/
		goToWiki();
		addBlankWikiPage(title, content, 0);

		/*
		- Back to Homepage
		- Click like icon
		 *Input Data: 
		 *Expected Outcome: 
		- The Wiki activity is displayed in the activity stream*like icon + number of likes to 1		*/
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, content,"1");
		home.likeOrUnlikeActivity(title);

		/*
		- Click on like icon again
		 *Input Data: 
		 *Expected Outcome: 
		- The Wiki activity is disliked by the user, the number of like is updated to -1		*/ 
		home.likeOrUnlikeActivity(title);

		//Delete data test
		click(By.linkText(title));
		deleteCurrentWikiPage();
	}

	/**
	 * Case ID:77129.
	 * Test Case Name: Add a wiki's activity after create a wiki page in space.
	 * Pre-Condition: To show wiki activity of space, make wiki page public:
	- Go to Space -> Wiki
	- Click Browse -> Wiki settings
	- Add permission: Any with View page right
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test 
	public  void test11_AddAWikisActivityAfterCreateAWikiPageInSpace() {
		info("Test 11 Add a wiki's activity after create a wiki page in space");
		String spaceName = "space771291";
		String title = "Title771291";
		String content = "Content 77129";
		String url = baseUrl+"/intranet/wiki/group/spaces/"+spaceName+"/"+title;
		String newcontent = "Content case 77129";
		/*
		- Connect to Intranet
		- Click [Join a space]
		- Add new space
		 *Input Data: 
		 *Expected Outcome: Add new space successfully		*/
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, "");

		/*
		- Go to space
		- Click Wiki link
		- Create a wiki page
		 *Input Data: 
		 *Expected Outcome: 
		- Wiki page is created for space		*/
		goToWikiFromSpace(spaceName);
		addBlankWikiPage(title, content, 0);
		makePublicPage(true);
		editPageWithCheckPublicActivity(title, newcontent);
		/*
		- Back to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- An activity of wikiis added to the activity stream
		- The content of the activity is displayed		*/
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, newcontent, "2");		

		/*
		- Login by user is not member of space
		- Access wiki page created at step 2 via URL: http://192.168.3.45:8080/portal/intranet/wiki/group/spaces/[space_name]/[wiki_name]
		 *Input Data: 
		 *Expected Outcome: 
		- User who is not member of space can see wiki page normally		*/ 
		acc.userSignIn(userType.DEVELOPER);
		driver.get(url);
		waitForAndGetElement(ELEMENT_WIKI_TITLE_PREVIEW);
		driver.navigate().back();

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName,300000);
	}

	/**
	 * Case ID:77525.
	 * Test Case Name: Check wiki's activity after create a wiki page for user.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test12_CheckWikisActivityAfterCreateAWikiPageForUser() {
		info("Test 12 Check wiki's activity after create a wiki page for user");
		String title = "Case 77525";
		String content = "Content case 77525";

		/*
		- Connect to Intranet
		- Choose [My Wiki] 
		- Add new page for user
		 *Input Data: 
		 *Expected Outcome: 
		- Wiki page is created		*/
		goToWiki();
		click(ELEMENT_WIKI_LOCATION_DROPDOWN);
		click(By.linkText("My Wiki"));
		addBlankWikiPage(title, content, 0);

		/*
		- Back to the Hompage
		 *Input Data: 
		 *Expected Outcome: No activity is added when create user wiki		*/ 
		nav.goToHomePage();
		waitForElementNotPresent(home.ELEMENT_ACTIVITY_WIKI_TITLE.replace("${title}", title));

		//Delete data test
		goToWiki();
		click(ELEMENT_WIKI_LOCATION_DROPDOWN);
		click(By.linkText("My Wiki"));
		click(By.linkText(title));
		deleteCurrentWikiPage();
	}

	/**
	 * Case ID:77615.
	 * Test Case Name: Remove wiki's page of space.
	 * Pre-Condition: Create a space and make it's wiki public ( Click Restricted link at the top then click Make public)
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test13_RemoveWikisPageOfSpace() {
		info("Test 13 Remove wiki's page of space");
		String spaceName = "Space 77615";
		String title = "Title 77615";
		String content = "Content 77615";
		String newcontent = "Content case 77615";

		//Pre-Condition 
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, "");

		/*
		- Connect to Intranet
		- Add a Wiki activity for space 
		 *Input Data: 
		 *Expected Outcome: 
		- The Wiki activity for space displayed in the activity stream		*/
		goToWikiFromSpace(spaceName);
		addBlankWikiPage(title, content, 0);
		makePublicPage(true);
		editPageWithCheckPublicActivity(title, newcontent);
		
		info("Check homepage");
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, newcontent, "2");

		/*
		- Go to Space -> Wiki 
		- Select created page
		- Click More 
		- Delete page
		 *Input Data: 
		 *Expected Outcome: 
		- Wiki page is deleted successfully		*/
		click(By.linkText(title));
		deleteCurrentWikiPage();

		/*
		- Back to activity stream
		 *Input Data: 
		 *Expected Outcome: The Wiki activity for spaceis removed from the activity stream		*/ 
		nav.goToHomePage();
		waitForElementNotPresent(By.xpath(home.ELEMENT_ACTIVITY_WIKI_TITLE.replace("${title}", title)));

		//Delete date test
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName,300000);		
	}

	/**
	 * Case ID:77616.
	 * Test Case Name: Update wiki's activity after edit wiki page content with active notification.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test14_UpdateWikisActivityAfterEditWikiPageContentWithActiveNotification() {
		info("Test 14 Update wiki's activity after edit wiki page content with active notification");
		String title = "Case 77616";
		String content = "Content case 77616";
		String contentUpdate = "Update content 77616";

		/*
		- Connect to Intranet
		- Open wiki application
		- Add new page
		 *Input Data: 
		 *Expected Outcome: 
		- A wiki page is added successfully		*/
		goToWiki();
		addBlankWikiPage(title, content, 0);

		/*
		- Edit content of a wiki page
		- Check [Publish Activity]
		- Click [Save]
		 *Input Data: 
		 *Expected Outcome: 
		- Content of page is updated with new title		*/
		editPageWithCheckPublicActivity(title, contentUpdate);

		/*
		- Go to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki activity is updated
		- A comment is added in the activity: Page's content has been edited. 		*/
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, contentUpdate, "2");
		waitForAndGetElement(home.ELEMENT_WIKI_COMMENT_EDIT_CONTENT.replace("${title}", title));

		//Delete data test
		click(By.linkText(title));
		deleteCurrentWikiPage();

	}

	/**
	 * Case ID:77617.
	 * Test Case Name: Update wiki's activity after edit wiki page content with inactive notification.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test15_UpdateWikisActivityAfterEditWikiPageContentWithInactiveNotification() {
		info("Test 15 Update wiki's activity after edit wiki page content with inactive notification");
		String title = "Case 77617";
		String content = "Content case 77617";
		String contentUpdate = "Update content 77617";
		/*
		- Connect to Intranet
		- Open wiki application
		- Add new page
		 *Input Data: 
		 *Expected Outcome: 
		- Add new page successfully		*/
		goToWiki();
		addBlankWikiPage(title, content, 0);

		/*
		- Edit a content of a wiki page
		- Un-check [Publish Activity]
		- Click Save
		 *Input Data: 
		 *Expected Outcome: 
		- Content page is updated with new value		*/
		editWikiPage(title, contentUpdate,0);

		/*
		- Go to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki activity content is updated with the new content
		- No comment is added into activity		*/ 
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, contentUpdate, "2");
		waitForAndGetElement(home.ELEMENT_ICON_COMMENT.replace("${title}",title)).getText().contains("0");
		
		//Delete data test
		click(By.linkText(title));
		deleteCurrentWikiPage();
	}
}