package org.exoplatform.selenium.platform.wiki.functional.activities;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.Dialog;
import org.exoplatform.selenium.platform.HomePageActivity;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.social.ManageMember;
import org.exoplatform.selenium.platform.wiki.Permalink;
import org.openqa.selenium.By;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

/**
 * 
 * @author havtt
 * @date 05-Nov-2013
 *
 */

public class Wiki_Activity_Delete extends Permalink{
	
	ManageAccount acc;
	HomePageActivity home;
	NavigationToolbar nav;
	Permalink per; 
	Dialog dialog; 
	ManageMember mMember; 

	@BeforeMethod
	public void beforeMethod(){
		initSeleniumTest();
		driver.get(baseUrl);
		driver.manage().window().maximize();
		per = new Permalink();
		mMember = new ManageMember(driver, this.plfVersion);
		home = new HomePageActivity(driver,this.plfVersion);
		nav = new NavigationToolbar(driver,this.plfVersion);
		acc = new ManageAccount(driver,this.plfVersion);
		acc.signIn(DATA_USER1, DATA_PASS);
	}

	@AfterMethod
	public void afterMethod(){
		driver.manage().deleteAllCookies();
		driver.quit();
	}

	/**
	 * Case ID:77127.
	 * Test Case Name: Delete a Wiki activity from activity stream by owner.
	 * Pre-Condition: Create a space and make it's wiki public ( Click Restricted link at the top then click Make public)
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test 
	public  void test01_DeleteAWikiActivityFromActivityStreamByOwner() {
		info("Test 1: Delete a Wiki activity from activity stream by owner");
		String spaceName = "Space77127";
		String title = "Title 77127";
		String content = "Content 77127";
		String newcontent = "Content case 77127";
		//Pre-Condition 
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, "");

		/*
		- Connect to Intranet
		- Add a Wiki activity for space 
		 *Input Data: 
		 *Expected Outcome: 
		- The Wiki activity for space displayed in the activity stream		*/
		goToWikiFromSpace(spaceName);
		addBlankWikiPage(title, content, 0);
		makePublicPage();
		editPageWithCheckPublicActivity(title, newcontent);
		/*
		- Back to activity stream 
		- Move the mouse over the Wiki activity for space 
		 *Input Data: 
		 *Expected Outcome: A (X) icon is displayed in the top right panel of the activity		*/
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, newcontent, "2");

		/*
		- Click on the (X) icon
		- Click on [OK] button of confirmation message
		 *Input Data: 
		 *Expected Outcome: The Wiki activity for space removed from the activity stream		*/ 
		mouseOver(By.xpath(home.ELEMENT_ACTIVITY_WIKI_TITLE.replace("${title}", title)), true);
		waitForAndGetElement(By.xpath(home.ELEMENT_ACTIVITY_DELETE.replace("${activityText}", title)), DEFAULT_TIMEOUT,1,2);
		info("Click on X icon");
		home.deleteActivity(title);	
		waitForElementNotPresent(By.xpath(home.ELEMENT_ACTIVITY_WIKI_TITLE.replace("${title}", title)));

		//Delete data test
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName,300000);
	}
	

	/**
	 * Case ID:77615.
	 * Test Case Name: Remove wiki's page of space.
	 * Pre-Condition: Create a space and make it's wiki public ( Click Restricted link at the top then click Make public)
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test02_RemoveWikisPageOfSpace() {
		info("Test 2 Remove wiki's page of space");
		String spaceName = "Space77615";
		String title = "Title 77615";
		String content = "Content 77615";
		String newcontent = "Content case 77615";

		//Pre-Condition 
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName, "");

		/*
		- Connect to Intranet
		- Add a Wiki activity for space 
		 *Input Data: 
		 *Expected Outcome: 
		- The Wiki activity for space displayed in the activity stream		*/
		goToWikiFromSpace(spaceName);
		addBlankWikiPage(title, content, 0);
		makePublicPage(true);
		editPageWithCheckPublicActivity(title, newcontent);
		
		info("Check homepage");
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, newcontent, "2");

		/*
		- Go to Space -> Wiki 
		- Select created page
		- Click More 
		- Delete page
		 *Input Data: 
		 *Expected Outcome: 
		- Wiki page is deleted successfully		*/
		click(By.linkText(title));
		deleteCurrentWikiPage();

		/*
		- Back to activity stream
		 *Input Data: 
		 *Expected Outcome: The Wiki activity for spaceis removed from the activity stream		*/ 
		nav.goToHomePage();
		waitForElementNotPresent(By.xpath(home.ELEMENT_ACTIVITY_WIKI_TITLE.replace("${title}", title)));

		//Delete date test
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName,300000);		
	}
}
