package org.exoplatform.selenium.platform.wiki.functional.activities;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.Dialog;
import org.exoplatform.selenium.Utils;
import org.exoplatform.selenium.platform.HomePageActivity;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.ManageAccount.userType;
import org.exoplatform.selenium.platform.social.ManageMember;
import org.exoplatform.selenium.platform.wiki.Permalink;
import org.openqa.selenium.By;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

/**
 * 
 * @author havtt
 * @date 05-Nov-2013
 *
 */

public class Wiki_Activity_Add extends Permalink{
	
	ManageAccount acc;
	HomePageActivity home;
	NavigationToolbar nav;
	Permalink per; 
	Dialog dialog; 
	ManageMember mMember; 

	@BeforeMethod
	public void beforeMethod(){
		initSeleniumTest();
		driver.get(baseUrl);
		driver.manage().window().maximize();
		per = new Permalink();
		mMember = new ManageMember(driver, this.plfVersion);
		home = new HomePageActivity(driver,this.plfVersion);
		nav = new NavigationToolbar(driver,this.plfVersion);
		acc = new ManageAccount(driver,this.plfVersion);
		acc.signIn(DATA_USER1, DATA_PASS);
	}

	@AfterMethod
	public void afterMethod(){
		driver.manage().deleteAllCookies();
		driver.quit();
	}
	
	/**
	 * Case ID:118067.
	 * Test Case Name: Add a wiki's activity after create a wiki page in portal.
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test01_AddAWikisActivityAfterCreateAWikiPageInPortal(){
		info("Test 1: Add a wiki's activity after create a wiki page in portal");
		String random =getRandomNumber();
		String title = "Case"+random;
		String content = "Add Content case"+random;

		/*
		- Connect to Intranet
		- Create a wiki page
		 *Input Data: 
		 *Expected Outcome: 
		- Wiki page is created		*/
		goToWiki();
		addBlankWikiPage(title, content, 0);

		/*
		- Back to the Hompage
		 *Input Data: 
		 *Expected Outcome: 
		- An activity of wikis added to the activity stream
		- The content of the activity is displayed		*/ 
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, content, "1");

		//Delete data test
		click(By.linkText(title));
		Utils.pause(2000);
		deleteCurrentWikiPage();
	}
	
	/**
	 * Case ID:118082.
	 * Test Case Name: Add a wiki's activity after create a wiki page in space.
	 * Pre-Condition: To show wiki activity of space, make wiki page public:
	- Go to Space -> Wiki
	- Click Browse -> Wiki settings
	- Add permission: Any with View page right
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test 
	public  void test02_AddAWikisActivityAfterCreateAWikiPageInSpace() {
		info("Test 02 Add a wiki's activity after create a wiki page in space");
		String random =getRandomNumber();
		String spaceName = "space"+random;
		String title = "Title"+random;
		String content = "Content"+random;
		String url = baseUrl+"/intranet/wiki/group/spaces/"+spaceName+"/"+title;
		String newcontent = "Content case"+random;
		/*
		- Connect to Intranet
		- Click [Join a space]
		- Add new space
		 *Input Data: 
		 *Expected Outcome: Add new space successfully		*/
		mMember.goToAllSpaces();
		mMember.addNewSpace(spaceName,spaceName);

		/*
		- Go to space
		- Click Wiki link
		- Create a wiki page
		 *Input Data: 
		 *Expected Outcome: 
		- Wiki page is created for space		*/
		goToWikiFromSpace(spaceName);
		addBlankWikiPage(title, content, 0);
		makePublicPage(true);
		editPageWithCheckPublicActivity(title, newcontent);
		/*
		- Back to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- An activity of wikiis added to the activity stream
		- The content of the activity is displayed		*/
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, newcontent, "2");		

		/*
		- Login by user is not member of space
		- Access wiki page created at step 2 via URL: http://192.168.3.45:8080/portal/intranet/wiki/group/spaces/[space_name]/[wiki_name]
		 *Input Data: 
		 *Expected Outcome: 
		- User who is not member of space can see wiki page normally		*/ 
		acc.userSignIn(userType.DEVELOPER);
		driver.get(url);
		waitForAndGetElement(ELEMENT_WIKI_TITLE_PREVIEW);
		driver.navigate().back();
		Utils.pause(2000);

		//Delete data test
		acc.userSignIn(userType.ADMIN);
		mMember.goToAllSpaces();
		mMember.deleteSpace(spaceName,600000);
	}
	
	/**
	 * Case ID:118083.
	 * Test Case Name: Check wiki's activity after create a wiki page for user.
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test03_CheckWikisActivityAfterCreateAWikiPageForUser() {
		info("Test 03 Check wiki's activity after create a wiki page for user");
		String random =getRandomNumber();
		String title = "Case"+random;
		String content = "Content case"+random;

		/*
		- Connect to Intranet
		- Choose [My Wiki] 
		- Add new page for user
		 *Input Data: 
		 *Expected Outcome: 
		- Wiki page is created		*/
		goToWiki();
		click(ELEMENT_WIKI_LOCATION_DROPDOWN);
		Utils.pause(2000);
		click(By.linkText("My Wiki"));
		Utils.pause(2000);
		addBlankWikiPage(title, content, 0);

		/*
		- Back to the Hompage
		 *Input Data: 
		 *Expected Outcome: No activity is added when create user wiki		*/ 
		nav.goToHomePage();
		waitForElementNotPresent(home.ELEMENT_ACTIVITY_WIKI_TITLE.replace("${title}", title));

		//Delete data test
		goToWiki();
		click(ELEMENT_WIKI_LOCATION_DROPDOWN);
		Utils.pause(2000);
		click(By.linkText("My Wiki"));
		Utils.pause(2000);
		click(By.linkText(title));
		Utils.pause(2000);
		deleteCurrentWikiPage();
	}

}
