package org.exoplatform.selenium.platform.wiki.functional.activities;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.Dialog;
import org.exoplatform.selenium.Utils;
import org.exoplatform.selenium.platform.HomePageActivity;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.social.ManageMember;
import org.exoplatform.selenium.platform.wiki.Permalink;
import org.openqa.selenium.By;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

/**
 * 
 * @author havtt
 * @date 05-Nov-2013
 *
 */

public class Wiki_Activity_Update extends Permalink{

	ManageAccount acc;
	HomePageActivity home;
	NavigationToolbar nav;
	Permalink per; 
	Dialog dialog; 
	ManageMember mMember; 

	@BeforeMethod
	public void beforeMethod(){
		initSeleniumTest();
		driver.get(baseUrl);
		driver.manage().window().maximize();
		per = new Permalink();
		mMember = new ManageMember(driver, this.plfVersion);
		home = new HomePageActivity(driver,this.plfVersion);
		nav = new NavigationToolbar(driver,this.plfVersion);
		acc = new ManageAccount(driver,this.plfVersion);
		acc.signIn(DATA_USER1, DATA_PASS);
	}

	@AfterMethod
	public void afterMethod(){
		driver.manage().deleteAllCookies();
		driver.quit();
	}

	/**
	 * Case ID:118071.
	 * Test Case Name: Update wiki's activity after edit wiki page title with active notification.
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test01_UpdateWikisActivityAfterEditWikiPageTitleWithActiveNotification() {
		info("Test 1: Update wiki's activity after edit wiki page title with active notification");
		String random =getRandomNumber();
		String title = "Case"+random;
		String titleUpdate = "Update Case"+random;
		String content = "Content case"+random;

		/*
		- Connect to Intranet
		- Open wiki application
		- Add new page
		 *Input Data: 
		 *Expected Outcome: 
		- A wiki page is added successfully		*/
		goToWiki();
		addBlankWikiPage(title, content, 0);		

		/*
		- Edit a title of a wiki page
		- Check [Publish Activity]
		- Click [Save]
		 *Input Data: 
		 *Expected Outcome: 
		- Title of page is updated with new title		*/
		editPageWithCheckPublicActivity(titleUpdate, content);

		/*
		- Go to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki activity is updated
		- A comment is added in the activity: Page's title has been updated to: $value.		*/
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(titleUpdate, content, "2");
		waitForAndGetElement(home.ELEMENT_WIKI_COMMENT_EDIT_TITLE.replace("${title}", titleUpdate));

		//Delete data test
		click(By.linkText(titleUpdate));
		Utils.pause(2000);
		deleteCurrentWikiPage();
	}

	/**
	 * Case ID: 118072.
	 * Test Case Name: Update wiki's activity after edit wiki page title with inactive notification.
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test02_UpdateWikisActivityAfterEditWikiPageTitleWithInactiveNotification() {
		info("Test 2: Update wiki's activity after edit wiki page title with inactive notification"); 
		String random =getRandomNumber();
		String title = "Case"+random;
		String titleUpdate = "Update title"+random;
		String content = "Content case"+random;

		/*
		- Connect to Intranet
		- Open wiki application
		- Add new page
		 *Input Data: 
		 *Expected Outcome: 
		- Add new page successfully		*/
		goToWiki();
		addBlankWikiPage(title, content, 0);		

		/*
		- Edit a title of a wiki page
		- Un-check [Publish Activity]
		- Click Save
		 *Input Data: 
		 *Expected Outcome: 
		- Title's page is updated with new value		*/
		click(By.linkText(title));
		editWikiPage(titleUpdate, content, 0);

		/*
		- Go to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki activity content is updated with the new page title		*/ 
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(titleUpdate, content, "2");
		waitForElementNotPresent(home.ELEMENT_WIKI_COMMENT_EDIT_TITLE.replace("${title}", titleUpdate));
		//Delete data test
		click(By.linkText(titleUpdate));
		Utils.pause(2000);
		deleteCurrentWikiPage();
	}

	/**
	 * Case ID:118073.
	 * Test Case Name: Update wiki's activity after edit wiki page without comment.
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test03_UpdateWikisActivityAfterEditWikiPageWithoutComment() {
		info("Test 3: Update wiki's activity after edit wiki page without comment");
		String random =getRandomNumber();
		String title = "Case"+random;
		String content = "Content case"+random;
		String contentUpdate = "Update content"+random;

		/*
		- Connect to Intranet
		- Open wiki application
		- Add new wiki page
		 *Input Data: 
		 *Expected Outcome: 
		- New page is added successfully		*/
		goToWiki();
		addBlankWikiPage(title, content, 0);		

		/*
		- Edit a content of wiki page without any comment associated
		- Click [Publish Activity]
		- Click [Save]
		 *Input Data: 
		 *Expected Outcome: 
		- Content of page is updated		*/
		editPageWithCheckPublicActivity(title, contentUpdate);

		/*
		- Go to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki activity is updated
		- A comment is added in the activity: Page's content has been edited.		*/ 
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, contentUpdate, "2");
		waitForAndGetElement(home.ELEMENT_WIKI_COMMENT_EDIT_CONTENT.replace("${title}", title));

		//Delete data test
		click(By.linkText(title));
		Utils.pause(2000);
		deleteCurrentWikiPage();
	}

	/**
	 * Case ID: 118074.
	 * Test Case Name: Update wiki's activity after edit wiki page with comment.
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test04_UpdateWikisActivityAfterEditWikiPageWithComment() {
		info("Test 4: Update wiki's activity after edit wiki page with comment");
		String random =getRandomNumber();
		String title = "Case"+random;
		String content = "Content case"+random;
		String contentUpdate = "Update content case"+random;
		String comment = "Add Comment"+random;
		/*
		- Connect to Intranet
		- Open wiki application
		- Add new page 
		 *Input Data: 
		 *Expected Outcome: 
		- New page is added successfully		*/
		goToWiki();
		addBlankWikiPage(title, content, 0);

		/*
		- Click [Edit] page
		- Change content for page
		- Add comment
		- Click [Publish Activity]
		- Click [Save]
		 *Input Data: 
		 *Expected Outcome: Content of page is updated		*/
		editPageWithCheckPublicActivity(title, contentUpdate, comment);

		/*
		- Go to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki activity is updated
		- A comment is added to the activity, containing the associated comment value		*/ 
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, contentUpdate,"2");
		waitForAndGetElement(home.ELEMENT_ACTIVITY_COMMENT_CONTENT.replace("${title}",title).replace("${comment}", comment));

		//Delete data test
		click(By.linkText(title));
		Utils.pause(2000);
		deleteCurrentWikiPage();
	}

	/**
	 * Case ID: 118076.
	 * Test Case Name: Update wiki's activity after move of wiki page.
	 * Pre-Condition: the wiki activity is already shared in the activity stream
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test05_UpdateWikisActivityAfterMoveOfWikiPage() {
		info("Test 5: Update wiki's activity after move of wiki page");
		String random1 =getRandomNumber();
		String random2 =getRandomNumber();
		String title1 = "Wiki_activity_title_"+random1;
		String content1 = "Wiki_activity_content_"+random1;
		String title2 = "Wiki_activity_title_"+random2;
		String content2 = "Wiki_activity_content_"+random2;
		/*
		- Connect to Intranet
		- Open wiki application
		- Add new page
		 *Input Data: 
		 *Expected Outcome: 
		- A page is added successful		*/
		goToWiki();
		addBlankWikiPage(title1, content1, 0);
		goToWikiHome();
		addBlankWikiPage(title2, content2, 0);

		/*
		- Click [More] choose [Move Page]
		- Select [Destination] and click [Move]
		 *Input Data: 
		 *Expected Outcome: Page has been moved to new place		*/
		info("Move page 2 to Intranet");
		movePage(title2, title1);

		/*
		- Go to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki activity isn't updated
		- A comment is added in the activity: Page has been moved to : $value. where $value is :SpaceName>WikiRootPage>WikiRootPage2>..		*/ 
		nav.goToHomePage();
		home.checkCommentAfterMoveWikiPage(title2, "Wiki Home > " + title1 + " > " + title2);

		//Delete data test
		click(By.linkText(title2));
		Utils.pause(2000);
		deleteCurrentWikiPage();
		click(By.linkText(title1));
		Utils.pause(2000);
		deleteCurrentWikiPage();
	}
	
	/**
	 * Case ID: 118085.
	 * Test Case Name: Update wiki's activity after edit wiki page content with active notification.
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test06_UpdateWikisActivityAfterEditWikiPageContentWithActiveNotification() {
		info("Test 6: Update wiki's activity after edit wiki page content with active notification");
		String random =getRandomNumber();
		String title = "Case"+random;
		String content = "Content case"+random;
		String contentUpdate = "Update content"+random;

		/*
		- Connect to Intranet
		- Open wiki application
		- Add new page
		 *Input Data: 
		 *Expected Outcome: 
		- A wiki page is added successfully		*/
		goToWiki();
		addBlankWikiPage(title, content, 0);

		/*
		- Edit content of a wiki page
		- Check [Publish Activity]
		- Click [Save]
		 *Input Data: 
		 *Expected Outcome: 
		- Content of page is updated with new title		*/
		editPageWithCheckPublicActivity(title, contentUpdate);

		/*
		- Go to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki activity is updated
		- A comment is added in the activity: Page's content has been edited. 		*/
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, contentUpdate, "2");
		waitForAndGetElement(home.ELEMENT_WIKI_COMMENT_EDIT_CONTENT.replace("${title}", title));

		//Delete data test
		click(By.linkText(title));
		Utils.pause(2000);
		deleteCurrentWikiPage();

	}
	
	/**
	 * Case ID: 118086.
	 * Test Case Name: Update wiki's activity after edit wiki page with inactive notification. 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test07_UpdateWikisActivityAfterEditWikiPageWithInactiveNotification() {
		info("Test 7: Update wiki's activity after edit wiki page with inactive notification");
		String random =getRandomNumber();
		String title = "wikititle"+random;
		String content = "wikiconten"+random;
		String contentUpdate = "Line1/Line2/Line3/Line 4/Line5";

		/*
		- Connect to Intranet
		- Open wiki application
		- Add new page
		 *Input Data: 
		 *Expected Outcome: 
		- A new page is added successfully		*/
		goToWiki();
		addWikiPageWithContentMultiLine(title, content);

		/*
		- Edit a content of wiki page
		- Un-check [Publish Activity]
		- Click save
		 *Input Data: 
		 *Expected Outcome: 
		- Content of page is updated		*/
		click(By.linkText(title));
		editWikiPage(title, contentUpdate,0,true);

		/*
		- Go to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki activity is updated:* Version * potentialy first 4 lines
		- No comment is added into activity		*/ 
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, contentUpdate,"2");
		waitForAndGetElement(home.ELEMENT_ICON_COMMENT.replace("${title}",title)).getText().equalsIgnoreCase("0");

		//Delete data test
		click(By.linkText(title));
		Utils.pause(2000);
		deleteCurrentWikiPage();
	}	
	
	

	/**
	 * Case ID:118086.
	 * Test Case Name: Update wiki's activity after edit wiki page content with inactive notification.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test08_UpdateWikisActivityAfterEditWikiPageContentWithInactiveNotification() {
		info("Test 8 Update wiki's activity after edit wiki page content with inactive notification");
		String random =getRandomNumber();
		String title = "Case"+random;
		String content = "Content case"+random;
		String contentUpdate = "Update content"+random;
		/*
		- Connect to Intranet
		- Open wiki application
		- Add new page
		 *Input Data: 
		 *Expected Outcome: 
		- Add new page successfully		*/
		goToWiki();
		addBlankWikiPage(title, content, 0);

		/*
		- Edit a content of a wiki page
		- Un-check [Publish Activity]
		- Click Save
		 *Input Data: 
		 *Expected Outcome: 
		- Content page is updated with new value		*/
		editWikiPage(title, contentUpdate,0);

		/*
		- Go to the Homepage
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki activity content is updated with the new content
		- No comment is added into activity		*/ 
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, contentUpdate, "2");
		waitForAndGetElement(home.ELEMENT_ICON_COMMENT.replace("${title}",title)).getText().contains("0");
		
		//Delete data test
		click(By.linkText(title));
		Utils.pause(2000);
		deleteCurrentWikiPage();
	}

}