package org.exoplatform.selenium.platform.wiki.functional.activities;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.Dialog;
import org.exoplatform.selenium.platform.HomePageActivity;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.social.ManageMember;
import org.exoplatform.selenium.platform.wiki.Permalink;
import org.openqa.selenium.By;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class Wiki_Activity_Display extends Permalink{
	
	ManageAccount acc;
	HomePageActivity home;
	NavigationToolbar nav;
	Permalink per; 
	Dialog dialog; 
	ManageMember mMember; 

	@BeforeMethod
	public void beforeMethod(){
		initSeleniumTest();
		driver.get(baseUrl);
		driver.manage().window().maximize();
		per = new Permalink();
		mMember = new ManageMember(driver, this.plfVersion);
		home = new HomePageActivity(driver,this.plfVersion);
		nav = new NavigationToolbar(driver,this.plfVersion);
		acc = new ManageAccount(driver,this.plfVersion);
		acc.signIn(DATA_USER1, DATA_PASS);
	}

	@AfterMethod
	public void afterMethod(){
		driver.manage().deleteAllCookies();
		driver.quit();
	}
	/**
	 * Case ID:77117.
	 * Test Case Name: Display "View Changes" page from wiki's activity.
	 * Pre-Condition: the wiki page is not "version 1"
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/03/06 10:33:45
	 */
	@Test
	public  void test02_DisplayViewChangesPageFromWikisActivity() {
		info("Test 2: Display View Changes page from wiki's activity");
		String title = "Case 77117";
		String titleUpdate = "Update_title 77117";
		String content = "Content case 77117";
		String contentUpdate = "Display view changes page from activity of wiki";

		/*
		- Connect to Intranet
		- Go to the Homepage
		- Go to wiki 
		- Add new page
		 *Input Data: 
		 *Expected Outcome: 
		- A wiki activity is displayed 		*/
		goToWiki();
		addBlankWikiPage(title, content, 0);
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(title, content, "1");

		/*
		- Click edit page
		- Change content for page
		- Click [Save]
		 *Input Data: 
		 *Expected Outcome: 
		- Edit page successfully
		- Wiki page's version "View change" is displayed		*/
		click(By.linkText(title));
		editWikiPage(titleUpdate, contentUpdate, 0);
		nav.goToHomePage();
		home.checkActivityInfoOfWiki(titleUpdate, contentUpdate, "2");
		waitForAndGetElement(home.ELEMENT_CONTENT_WIKI_VIEW_CHANGE);

		/*
		- Click on the link "View changes"
		 *Input Data: 
		 *Expected Outcome: 
		- The wiki application is opened in the view to compare Version N
		- 1 and Version N		*/ 
		click(home.ELEMENT_CONTENT_WIKI_VIEW_CHANGE);
		waitForAndGetElement(ELEMENT_EDIT_COMPARE_CHANGE);
		waitForAndGetElement(ELEMENT_EDIT_COMPARE_VERSION.replace("${version}","Version 1"));
		waitForAndGetElement(ELEMENT_EDIT_COMPARE_VERSION.replace("${version}","Current version"));

		//Delete data test
		click(By.linkText(titleUpdate));
		deleteCurrentWikiPage();
	}
}
